### ISSUE TITLE
Define name for the performance plugin

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#1]
As outlined in the original proposal doc, the performance plugin doesn't have a name yet. Some ideas were previously discussed in the doc and on Slack, but we can follow up here.

Once a name (and slug!) have been decided for, we need to replace the following in the scaffolded codebase:
* `TODO-SLUG` with plugin slug/textdomain
* `TODO-NAME` with (human-friendly) plugin name
* `todo_snakecaseslug` with snake_case version of the plugin slug (e.g. prefix for functions, options, etc.)
* `TODO_CONSTANTSLUG` with CONSTANT_CASE version of the plugin slug (e.g. prefix for constants)

**Comment by ecotechie** [comment]
Name: Core Performance Tests

**Comment by Otto42** [comment]
Probably best to reflect somewhat on the test or experimental nature of it, because you probably don't want people installing it on sites that are meant to be 100% stable. 

Perf-experiments, or something like that? I suck at naming, but something that reflects that it's for testing only.

**Comment by tillkruss** [comment]
`Performance Experiments` was suggested in the Google doc as well. Maybe this `perf-experiments` for the wp.org slug?

**Comment by JustinyAhin** [comment]
> Probably best to reflect somewhat on the test or experimental nature of it, because you probably don't want people installing it on sites that are meant to be 100% stable.

We should also mention this in the repo README/docs. The experimental nature of the plugin, and the fact that it shouldn't be used as a permanent solution on sites.

**Comment by szepeviktor** [comment]
There are two very-very [separate parts](https://github.com/szepeviktor/tiny-cache/blob/master/README.md#wordpress-performance) of WordPress performance.

1. WordPress core generating HTML code
2. Browser loading HTML and linked resources, rendering page.

Please take this into consideration.

**Comment by ThierryA** [comment]
Just throwing some ideas, `Performance Lab`,`Performance Labs`, `Perf Lab`, `Perf Labs`.

While some modules will be for testing, it is also important to keep in mind that it should be developed in a reliable way and not only deployed on throw away sites (like any feature plugins would, and so is Gutenberg). For that reason it would be preferable not to over index on the _experimental_ nature (IMO) which could lead to not getting the minimal user base adoption we are looking for.

**Comment by felixarntz** [comment]
`Performance Lab` (slug `performance-lab`) would sound good to me. It still indicates that these are of somewhat experimental nature, but it sounds more catchy IMO. What do y'all think?

**Comment by ecotechie** [comment]
I'd like to see a more specific name, I still like my suggestion `Core Performance Tests` since that's what they are. Performance lab seems a bit broad.

**Comment by adamsilverstein** [comment]
@ecotechie - I like the `Core Performance` part because it indicates this is a core based and targeted effort. I like `Tests` less because it would feel more risky for users to install.

How about `Core Performance Lab`?

**Comment by jdevalk** [comment]
Core says nothing to "average" users, who should be installing this too. I like just `Performance Lab` too.

**Comment by tillkruss** [comment]
I like `Performance Lab` as well, maybe with a short slug like `perflab`.

**Comment by aristath** [comment]
+1 for `Performance Lab` (`performace-lab`)

**Comment by JustinyAhin** [comment]
+1 for `Performance Lab`

**Comment by jonoalderson** [comment]
+1 for `Performance Lab` (`performace-lab`)

**Comment by ecotechie** [comment]
So we do expect/hope production sites install this plugin? And "average" users will install this on their live sites. I thought it was for testing purposes only. I then assume there will be a warning that it may break things?

**Comment by aristath** [comment]
The concept of this plugin is similar to that of Gutenberg. So no, I don't think we should have warnings etc. All plugins "may break things", nothing is ever 100% feature-complete and bug-free.

**Comment by ecotechie** [comment]
Not trying to be a pain, but if this plugin is meant as a lab or for tests, it will break "things". Same with the Gutenberg plugin. I help maintain over 600 sites and if we ever see Gutenberg installed, we recommend removing it. Since it can be unstable and features can be removed. I know the nature of plugins is such that the code will sometimes cause unintended effects. However, a plugin dev that makes a well intentioned mistake and an essentially beta testing plugin are very different. I'll leave it at that and sorry to drag this out, but I feel users should be made aware when plugins are not meant for production sites.
