### ISSUE TITLE
Add a build process for the `plugins` directory plugin.

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1006]
Follow-up: https://github.com/WordPress/performance/pull/1000#discussion_r1496680295

Currently, for the deploy process, we added plugin versions per https://github.com/WordPress/performance/issues/935#issuecomment-1952027981. However, as per @westonruter's feedback in https://github.com/WordPress/performance/pull/1000#discussion_r1496680295, we should avoid defining the version in three places (plugin main file, readme file, and plugins.json file). We need to think of a better workflow to manage their version in a single place to avoid updating in multiple places.

**Comment by thelovekesh** [comment]
@mukeshpanchal27 @westonruter I will be picking up this as we are doing something similar at https://github.com/WordPress/performance/issues/893

**Comment by felixarntz** [comment]
@mukeshpanchal27 Just spotting this, I believe this is addressing the same concern I just voiced in https://github.com/WordPress/performance/issues/935#issuecomment-1965535471?

**Comment by mukeshpanchal27** [comment]
Yes. Closing this now.
