### ISSUE TITLE
Settings link is missing from WebP Uploads plugin action links

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1016]
## Feature Description

The WebP Uploads plugin exposes [one admin setting](https://github.com/WordPress/performance/blob/28fced3ac10fb4fdb82f12cc5ca42631743a9e7c/modules/images/webp-uploads/settings.php#L54-L68) on the Media > Uploading Files setting section:

![image](https://github.com/WordPress/performance/assets/134745/a3b4917f-3dcb-44f3-986f-66e376ca2324)

However, there is no **Settings** link pointing to `/wp-admin/options-media.php#perflab_generate_webp_and_jpeg` in the plugin action links for WebP Uploads:

![image](https://github.com/WordPress/performance/assets/134745/fe9c6b39-7c2c-4685-bd85-7201facbc69d)

Compare with a plugin like Web Stories (added via the `plugin_action_links` filter):

![image](https://github.com/WordPress/performance/assets/134745/8a5066bc-7815-4b68-a85f-f6e228090844)

This would help with discovery and address a complaint we've seen about an installed plugin not having any settings. Otherwise, the user has to read the plugin description for this information:

<blockquote><p>This plugin adds WebP support for media uploads within the WordPress application. WebP images will be generated only for new uploads, pre-existing imagery will not be converted to WebP format. By default, WebP images will only be generated for JPEG uploads, only the original uploaded file will still exist as a JPEG image. All generated image sizes will exist as WebP only. If you wish to change this behaviour, there is a checkbox in <code>Settings &gt; Media</code> that – when checked – will alter the behaviour of this plugin to generate both JPEG and WebP images for every sub-size (noting again that this will only affect newly uploaded images, i.e. after making said change).</p></blockquote>

**Comment by ValeriiVasyliev** [comment]
I'm in
