### ISSUE TITLE
Improve fatal detection in php-test-standalone-plugins with E2E test rather than using PHPUnit

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1051]
Currently, php-test-standalone-plugins workflow (via the [test-plugins](https://github.com/WordPress/performance/blob/trunk/bin/plugin/commands/test-plugins.js) command) is just checking to see if each standalone plugin causes a fatal when it is active in isolation from the other plugins:

https://github.com/WordPress/performance/blob/06d6ffeb05fb5c7d3bb67253b21b924b62fe2a9e/plugin-tests/tests/test-standalone.php#L13-L15

This seems like using the wrong tool, PHPUnit, for the job. Indeed, PHPStan flags this assertion as an error:

> phpstan: Call to method PHPUnit\Framework\Assert::assertTrue() with true will always evaluate to true.

It seems better to not use PHPUnit here, but rather to use `curl` to fetch the homepage and make sure it returns a 200 status code and includes `</html>` in the response body. Even better would be to start using Playwright to do actual E2E tests.

I also think the test-plugins command should also be renamed to reduce confusion with test-php-plugins and test-php, for example, test-e2e.

Originally discussed in https://github.com/WordPress/performance/pull/1044#issuecomment-1989679007 and https://github.com/WordPress/performance/pull/1044#issuecomment-1991866728.

**Comment by swissspidy** [comment]
My previous comment:

> I think that test is just a dummy so that we have at least 1 test there. It's not really trying to detect fatal errors or anything.

What I mean with that:

This test is not supposed to detect fatal errors. It's just a dummy so that PHPUnit doesn't complain that there is no simple test.

We don't need any e2e tests here IMHO, we simply need to write some actual PHPUnit tests testing plugin functionality. Then we can remove this particular test here.

**Comment by westonruter** [comment]
> Even better would be to start using Playwright to do actual E2E tests.

See https://github.com/WordPress/performance/issues/1096
