### ISSUE TITLE
Bump minimum required WP version to 6.4

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1056]
For context on why I'm opening this issue, please see https://make.wordpress.org/performance/handbook/performance-lab/version-support-policy/. Specifically, the following:

"The Performance Lab plugin commits to supporting the latest stable version of WordPress core."

Since we use some WP 6.4 functions see https://github.com/WordPress/performance/pull/1048#discussion_r1524550877, I propose changing the minimum WP version set to 6.4. This way, we won't need to handle safeguard or old version compatibility code.

**Comment by westonruter** [comment]
As part of this, we can eliminate any wrappers for `wp_trigger_error()` since it was introduced in 6.4.

**Comment by felixarntz** [comment]
+1 to bumping the minimum requirement. Let's do it for 3.0, which is a good time to do it anyway.
