### ISSUE TITLE
Use `term_exists()` should use `get_terms()` internally

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#107]
Extracted from #34.

`term_exists()` should use `get_terms()` internally.

- https://core.trac.wordpress.org/ticket/36949
- https://github.com/WordPress/wordpress-develop/pull/2161

**Comment by tillkruss** [comment]
PR opened: https://github.com/WordPress/wordpress-develop/pull/2318

**Comment by spacedmonkey** [comment]
Merged into core - https://github.com/WordPress/wordpress-develop/commit/34d46cd5013c6433bb0e4d2b447abe162e6521d1
