### ISSUE TITLE
Add AVIF support

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#11]
Trac ticket: https://core.trac.wordpress.org/ticket/51228

**Comment by jb510** [comment]
I noticed WebP checks are in Site Health.  Seems like AVIF checks should be too.

**Comment by adamsilverstein** [comment]
> I noticed WebP checks are in Site Health. Seems like AVIF checks should be too.

Great suggestion @jb510 - lets open a separate issue for that.

**Comment by Zodiac1978** [comment]
Came here to say the same as @jb510 - but I can't find any ticket for adding AVIF status checks to Site Health or is this opened in Trac and not here?

**Comment by phanduynam** [comment]
WordPress 6.5 currently supports the Avif image format, so please update the Performance Lab plugin to support this image format.

**Comment by benoitfouc** [comment]
Yes i think that we need to tag the [[Plugin] Modern Image Formants] on this ticket, in order to make it compatible with AVIF

**Comment by benoitfouc** [comment]
@adamsilverstein created a plugin that can be a good starting point for this implementation into the Modern Image Formats plugin.

![image](https://github.com/WordPress/performance/assets/10956350/db6ae8c4-963d-4179-bbb4-52945594eaae)
![image](https://github.com/WordPress/performance/assets/10956350/6e1cc329-b306-4cd4-bfcf-d5a5f7cf3d04)
https://wordpress.org/plugins/modern-images-wp/

**Comment by adamsilverstein** [comment]
> I noticed WebP checks are in Site Health. Seems like AVIF checks should be too.

@jb510 - I created this issue to add a health check for AVIF: https://github.com/WordPress/performance/issues/1152

@benoitfouc - thanks for the call out to the plugin, I'm sure I need to update it!

I created a separate issue to add AVIF support to the Modern Image Formats plugin - https://github.com/WordPress/performance/issues/1151 since this ticket was originally about adding AVIF upload support - which we now landed in core!

Speaking of which, since we landed AVIF support in core and we have follow up issues for everything discussed in this ticket, I'm going to close this issue as **resolved**.

**Comment by adamsilverstein** [comment]
reopening on second thought, we can leave this open as a tracking issue, it is an Epic after all. Once the other issues are closed we can close this one.

**Comment by adamsilverstein** [comment]
Closing this out, AVIF has been added to the modern image formats plugin and we are working on `<picture>` element support as well.

see https://github.com/WordPress/performance/issues/1151
