### ISSUE TITLE
Bump the minimum PHP version to 7.2

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1129]
As WordPress bumps the [minimum required PHP version to 7.2](https://core.trac.wordpress.org/ticket/58719) for 6.6 version, we should do the same for Performance lab and all standalone plugins.

**Comment by westonruter** [comment]
As discussed in https://github.com/WordPress/performance/pull/1130#issuecomment-2052231860, let's target this for the next plugin release.
