### ISSUE TITLE
Speculation Rules not showing up in the frontend

### ISSUE THREAD

**Issue by tibor** [WordPress/performance#1132]
## Bug Description
I use the speculation rules plugin as standalone version. The plugin is activated and published information to the generator tag:
```
<meta name="generator" content="Performance Lab 2.9.0; modules: images/webp-support; plugins: webp-uploads, dominant-color-images, speculation-rules">
<meta name="generator" content="speculation-rules 1.1.0">
```

However, the actual speculation rules are not inserted when I hover over any link. I tried both with the console `document.querySelector('script[type="speculationrules"]')` and the network tab. There is no script and there are no requests when I hover over a link.

My theme is custom made. Are there any dependencies I need to implement?

## Additional Context

 - PHP Version: 8.1
 - OS: macOS
 - Browser: Chrome
 - Plugin Version: 1.1.0
 - Device: MacBook Air

**Comment by westonruter** [comment]
Hello! Does your theme include `wp_footer()`? This is where the speculation rules are printed:

https://github.com/WordPress/performance/blob/c2bb4a71fbead8151bfc84a7d91f1da1a4b2e660/plugins/speculation-rules/hooks.php#L47

The `script` should be printed in the HTML returned by the server without having to hover over anything.

**Comment by tibor** [comment]
I see, I got this wrong.
And thanks for the help with `wp_footer();` that helped!
