### ISSUE TITLE
Plugin Proposal: AVIF converter

### ISSUE THREAD

**Issue by benoitfouc** [WordPress/performance#1133]
## Overview

- Proposed plugin name: AVIF converter
- Proposed plugin slug: avif-converter
- Proposed plugin owner GitHub username(s): 

### Purpose
Since WordPress 6.5, the core includes support for the AVIF image format. We can create a plugin that automatically converts newly uploaded files (JPEG, PNG, and WEBP) into AVIF format. This plugin could serve as the successor to WebP Uploads, which is now outdated due to the integration of AVIF. AVIF offers greater efficiency compared to JPEG, PNG, and WebP formats.

### Scope
-Automatically convert new JPEG files into AVIF.
-Automatically convert new PNG files into AVIF.
-Automatically convert new WebP files into AVIF.

### Rationale
The WordPress Core Performance team has done an excellent job with WebP Uploads. This proposed plugin is essentially an “evolution” of WebP Uploads, aligning with the new official AVIF support included in WordPress Code 6.5.

**Comment by swissspidy** [comment]
Instead of creating yet another image plugin, the plan is to turn the existing WebP Uploads plugin into one that supports multiple formats (WebP, AVIF, etc.)

**Comment by adamsilverstein** [comment]
Hey @benoitfouc - thanks for opening this issue! 

We definitely want to add AVIF support to Performance Lab, however as @swissspidy points out we have decided to consolidate all modern image features into a single plugin.  That way, users will have a seamless experience choosing the image format(s) they want, and we will avoid deploying duplicate code.

I have opened a [separate issue](https://github.com/WordPress/performance/issues/1151) specifically to propose adding AVIF support to the Modern Image Formats plugin. Please follow along and contribute to the effort there!

I'm going to close this issue in favor of the other one.
