### ISSUE TITLE
Setting screen tooltip should go away after visiting the settings page

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#1135]
## Bug Description

The tool tip guiding users to the settings page shows even after they visit it. Instead, it should go away as if "Dismiss" was clicked.

This tooltip pops up when the user installs the plugin so they can more easily find the settings screen:

![image](https://github.com/WordPress/performance/assets/2676022/a9e2aef6-72d3-4680-b5ac-8dfc09633dae)

Once the user clicks the "Settings > Performance" link in the tooltip, or otherwise visits the settings page, we should no longer show the tooltip.

## Steps to reproduce

1. Install the plugin
2. Click "Settings > Performance" in the tooltip to visit the settings page
3. Go back and visit the Dashboard

Expected results: the tooltip should no longer show
Actual results: the tooltip is still showing

**Comment by Ellusu** [comment]
I'll work on it

**Comment by adamsilverstein** [comment]
Thanks @Ellusu!

**Comment by Ellusu** [comment]
I created: https://github.com/WordPress/performance/pull/1147 Grazie

**Comment by mukeshpanchal27** [comment]
Closed in #1147
