### ISSUE TITLE
Update standalone plugin assets

### ISSUE THREAD

**Issue by joemcgill** [WordPress/performance#1136]
## Bug Description

Following #1101, the icon and banner for some feature plugins no longer match the names. Specifically, "WebP Uploads" was renamed "Modern Image Formats" and "Dominant Color Images" was renamed "Image Placeholders".

## For Discussion
We could create new assets using the previous practice of using the first two letters of the plugin name, but this also could be a good time to rethink the design strategy for these assets. To consider:

- Should we use icons that are not "alpha" based at all, so that changing a feature name doesn't require new assets?
- Should we keep using the current "alpha" strategy, but make them based on feature initials, rather than first two letters (e.g., Auto-Sizes becomes "AS" instead of "AU"?
- Should we use a generic icon that can be applied to all features so we don't have to create assets each time we want to create a new feature plugin?

## Steps to reproduce

Visit the WP.org plugin pages:
- https://wordpress.org/plugins/dominant-color-images/
- https://wordpress.org/plugins/webp-uploads/

## Screenshots

<img width="953" alt="image" src="https://github.com/WordPress/performance/assets/801097/1e3dee7c-6a0b-4c58-8042-f64d3c7f881d">

<img width="951" alt="image" src="https://github.com/WordPress/performance/assets/801097/a15da18a-66cc-4e97-a46e-7ad9848e0ba1">

**Comment by westonruter** [comment]
> * Should we use a generic icon that can be applied to all features so we don't have to create assets each time we want to create a new feature plugin?

+1 Yes, I think this makes the most sense. And then the banner image can include this same icon, and instead of repeating the 2-letter abbreviation of the standalone plugin, it can instead mention "Performance Lab". This will enhance the connection between the standalone plugin and the Performance Lab plugin.

**Comment by ThierryA** [comment]
> Should we use a generic icon that can be applied to all features so we don't have to create assets each time we want to create a new feature plugin?

+1 to something generic (could be a simple recognisable shape for example). Do you have something in mind?

**Comment by westonruter** [comment]
Could we re-use relevant icons from Dashicons or Genericons?

**Comment by joemcgill** [comment]
> Do you have something in mind?

@ThierryA — one option would just be to use the Performance Lab (P) for all plugins that we publish under the Performance Lab program. What do you think?

**Comment by westonruter** [comment]
The banner images also don't work in all contexts. For example, when sharing the URL to Speculation Rules in Google Chat, the "SP" in the Speculative Loading plugin's banner is cropped so you just see a part of the "P":

> ![image](https://github.com/WordPress/performance/assets/134745/e8df4b53-78b2-4a60-ba41-866ed733eddc)

Slack doesn't have this problem though:

> ![image](https://github.com/WordPress/performance/assets/134745/6ee78fca-c16d-458a-b552-1f65791aff99)

Perhaps safer to center any significant design element in the banner. (Also omit the small abbreviation in the corner.) If we go with "P" as the icon, then the banner could have centered "Performance Lab".

**Comment by ThierryA** [comment]
Do we want unique for every plugin or one for all? I would refrain from using just the P of PL as it may be confusing, what about using and AI generates for simple flat white shapes (kinda QR but only with a combination of 2 -  5 shapes) which we can use to add to the blue BG. This way it is still unique, easy to create and feature/plugin name agnostic.

**Comment by joemcgill** [comment]
> Do we want unique for every plugin or one for all?

I think using the same icon for all of our plugins would be fine and removes the need to come up with new assets for each plugin and makes it obvious that all of these plugins are part of the same collection, but I don't feel strongly about it. If we have a good strategy for easily creating custom assets for each plugin that is unique, I think that would be fine too, we should just refrain from tying the icon to the name of the plugin.

**Comment by westonruter** [comment]
Also, since the Performance features screen now no longer shows the icons, there is less of a concern that they are going to be redundant. The only place they'll see the icon is on the WordPress plugin directory when looking at an individual plugin. 

Instead of just "P" what about "PL" for the icon? And then the banner can just have "Performance Lab" centered on the blue background, without the additional "PL" in the bottom right corner.

**Comment by ThierryA** [comment]
> Instead of just "P" what about "PL" for the icon? And then the banner can just have "Performance Lab" centered on the blue background, without the additional "PL" in the bottom right corner.

I think this solution would be the least convenient and appropriate given that the initial purpose of decoupling the PL into standalone plugin and the potential confusion between the main PL plugin and the standalone plugins. Using the branding colors is good though, no confusion but a good reference to the project overall.
My vote would be either for a single re-usable abstract shapes (ala QR code) or unique to each plugins.

**Comment by joemcgill** [comment]
I think a single, reusable abstract would essentially become a new "logo" for the performance team, and I don't think going through a whole branding exercise is necessary as a first step to updating the current plugin assets. However, as a next step we could try to source a few options to evaluate based on our current assets. 

Personally, I still think that the standalone `P` (representing "Performance") or a the `P` paired with an appropriate icon that relates to each feature would work. Here's a very rough example of what that might look like.

![image](https://github.com/WordPress/performance/assets/801097/f987850b-bb74-4daa-a569-d9b6f7a17fdb)

Alternately, I'd propose we stick with the same lettering style we already have and use "WPP" to represent WordPress Performance. This could also either be a standalone mark used on all plugins or a mark that gets paired with an icon for each feature.

Jetpack is doing something similar with their suite of plugins to add a small JP login to each plugin icon.

<img width="956" alt="image" src="https://github.com/WordPress/performance/assets/801097/8c03b662-d5c0-44a3-bf2b-8c3c3cde2bbf">

**Comment by westonruter** [comment]
> My vote would be either for a single re-usable abstract shapes (ala QR code) or unique to each plugins.

@ThierryA So like core does with a commenter's avatar when no Gravatar is available? 

![image](https://github.com/WordPress/performance/assets/134745/6aa802b0-f83a-4a91-95c7-e8875131ab4f)

IMO, while these are visually distinctive (normally) they have no semantic value. I think i9t would be better to have at least _something_ identifiable about the plugin in the icon.

> Personally, I still think that the standalone `P` (representing "Performance") or a the `P` paired with an appropriate icon that relates to each feature would work. Here's a very rough example of what that might look like.

@joemcgill I really like that idea. Also nice precedence with Jetpack.

**Comment by adamsilverstein** [comment]
The Jetpack example is great, thanks @joemcgill! I like that direction, either with the P in a small circle like the Jetpack logo example or large like your mock.

Summarizing, I feel we agreed on:

* Some common branding: eg color or the "P" for Performance across all the plugins
* A unique icon for each plugin
* Abstract icons so names can change and icon doesn't need to change

**Comment by westonruter** [comment]
And for the banner, to reuse the same "Performance Lab" banner consistently across all the plugins? In this way, the icon and name would be distinct, but the banner would remain the same. Or should the banner be custom for each plugin as it is now? Just to [reiterate](https://github.com/WordPress/performance/issues/1136#issuecomment-2061858438) that the current banners don't work in all cases. Apparently the WordPress.org banner is being used as the "social preview" in Google Chat and also Twitter:

> ![image](https://github.com/WordPress/performance/assets/134745/89ba839c-cb29-4967-b1f4-483568f467dc)

And also Facebook:

> ![share_7283814777406191051](https://github.com/WordPress/performance/assets/134745/d794486e-11c7-4c4c-8eb3-4876fac45707)

Compare with the actual banner:

> ![image](https://github.com/WordPress/performance/assets/134745/f34b7b21-b74b-4575-935e-e6f32ca05469)

So the "S" in the "SP" of Speculative Loading is getting cut off. So in practice the banner is already "P" for many. It seems the WordPress.org banner should be designed with a "safe region" that is centered with 2:1 aspect ratio, the same as GitHub's social preview template:

> ![image](https://github.com/WordPress/performance/assets/134745/108e13ce-67fb-493b-8aa3-1d0cd27ad643)

**Comment by joemcgill** [comment]
Today during our weekly Performance Team chat, I asked @eclarke1 if we could get some mockups of some of these ideas created to make a decision a bit easier ([link](https://wordpress.slack.com/archives/C02KGN5K076/p1713887265719239)). She thinks the designer who has helped with our other logos may be able to help with this next week. I say we follow up on this once Em has had the chance to check in with them.

**Comment by ThierryA** [comment]
> @ThierryA So like core does with a commenter's avatar when no Gravatar is available?

That was the idea, yes. However the path that you are all exploring sounds great, it is definitely going towards a good solution IMO 👍 

Looking forward to seeing the options the designer comes back with.

**Comment by sstopfer** [comment]
I'll meet the designer this week to brief her and get this going. One question for the group; considering this will get published on social media and the banner will show each time, I think this is an opportunity to "sell" it better. 

Having the same banner for all plugins is okay, but we should probably add a tagline; something applicable to Performance lab in general. 

That way, if a user encounters it the first time around, the messaging isn't the ONLY think that is supposed to attract the user. For those who are familiar, it will be more easily recognizable. 

The simple blue background looks a bit like a placeholder image. What do you think about adding a tagline? And does the Performance Lab already have one?

**Comment by joemcgill** [comment]
Good question, @sstopfer.

> Having the same banner for all plugins is okay, but we should probably add a tagline; something applicable to Performance lab in general.

Primarily, these assets are used on the Plugin pages themselves, (e.g., https://wordpress.org/plugins/performance-lab/) and inside the WordPress plugins screen as folks are searching for plugins. And will be shown along with the short description for the plugin, so creating taglines are probably unnecessary.

<img width="550" alt="image" src="https://github.com/WordPress/performance/assets/801097/8ea1e47e-4158-4e74-998e-ca3bb643afa2">

The primary goals for new assets, in my opinion, are summarized by Adam above:

> - Some common branding: eg color or the "P" for Performance across all the plugins
> - A unique icon for each plugin
> - Abstract icons so names can change and icon doesn't need to change

In addition, it would be great if we were able to easily generate assets for new plugins based on this system.

**Comment by westonruter** [comment]
The banner image is shown:

1. On the WordPress Plugin Directory page.
2. In the lightbox for getting more details for a plugin in the admin.
3. On social media when a plugin's directory URL is shared.

Directory Page | Lightbox in Admin | Social Media
--|--|--
![image](https://github.com/WordPress/performance/assets/134745/31e2b524-c41b-448d-92df-3085fb43abb0) | ![image](https://github.com/WordPress/performance/assets/134745/09787d66-af79-41a0-b218-5f58916e893e) | ![image](https://github.com/WordPress/performance/assets/134745/74f478c0-b89d-45a5-b96d-c3c86072c725)

Given the banner is used consistently in all three scenarios, I think it should have _some_ meaningful content ([again centered in the safe region](https://github.com/WordPress/performance/issues/1136#issuecomment-2072969793)). If we use the same for each plugin, which will make it easier for us in the future, it could just say "Performance Lab".

**Comment by westonruter** [comment]
Punting from 3.1.0 to n.e.x.t (3.2.0). Normally this would be on June 17th, but given that WCEU is immediately prior to this, I think it makes sense to do a mid-cycle release, perhaps June 10th (or even the week prior).

**Comment by sstopfer** [comment]
We're happy to share the first concept for our plugin assets update. This includes a couple of icons options for different plugins as you will be able to see below. 

The mockups are based on the idea that the icon should represent the plugin, and the "P" (as the Performance Lab logo) should be smaller and strategically placed in a top corner to inform the users the plugin is a part of the Performance Lab brand. 

While we are waiting on the second concept/proposal, let us know what you think. Do you like the style? Should the be position of the icon and the logo be inverse? Curious about your feedback.  

![Performance branding letters](https://github.com/WordPress/performance/assets/140073502/a4470930-f10f-4383-9a1f-02eeabee1bf2)

**Comment by westonruter** [comment]
This is great! I think this is the correct positioning.

**Comment by joemcgill** [comment]
These are looking really good. @sstopfer could you find out if these icons are from some specific set that we should standardize on or if each are custom? It might be worth considering using [the WordPress icon set](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library) for consistency and ease of use.

**Comment by sstopfer** [comment]
@joemcgill Good point, I'll check and let you know.

**Comment by westonruter** [comment]
Please make sure that "Image Prioritizer" (#1088) is included as one of the created icons.

**Comment by westonruter** [comment]
Reminder that these assets are needed in the next couple weeks for WCEU.

**Comment by sstopfer** [comment]
Here is the second concept for our plugin assets update. The idea is still the same, referenced throughout the thread above, where the icon should represent the plugin, and the "P" (as the Performance Lab logo) should be smaller and strategically placed in a top corner to inform the users the plugin is a part of the Performance Lab brand.

The main difference is that, this time around, the icons used to describe the plugins are not based on the Performance Lab logo style, but give a more recognizable UI feeling. 

Which one do you prefer? 

![version-two](https://github.com/WordPress/performance/assets/140073502/0089ce70-c3e2-4592-87a2-28847aaaf9c1)

**Comment by westonruter** [comment]
@sstopfer I like the second set more. Are these using the [the WordPress icon set](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library)? Whatever can reuse assets so they don't have to be created from scratch for each new plugin.

**Comment by sstopfer** [comment]
@westonruter Not exactly. We’re creating branding for these plugins, which are more logos than UI icons. This library doesn’t include every possible icon, and in order to communicate the difference between the plugins, we are creating our own unique icons. However, this second concept is incorporating already familiar WP UI icons as elements of the logo, where possible. For example, the second set (which would be used for the Performant Translations) uses the language icon, which is a WP UI icon, inside a bubble (which is the custom part of the logo).

**Comment by adamsilverstein** [comment]
+1 to style 2 from me, looks good!

**Comment by joemcgill** [comment]
I prefer style 2 as well—particularly that they incorporate already familiar iconography from WP.

**Comment by westonruter** [comment]
@sstopfer Any update on the new banner design? And any update on how the design of the icons is progressing?

**Comment by sstopfer** [comment]
Here is the preview of the icons for all standalone plugins. 
![Auto-sizes for Lazy-loaded Images](https://github.com/WordPress/performance/assets/140073502/e5b87e00-3b89-46a3-9f6c-192dd6788b57)
![Embed Optimizer](https://github.com/WordPress/performance/assets/140073502/d24e253b-a13e-4888-b8ff-3c9d9cdd2dca)
![Fetchpriority](https://github.com/WordPress/performance/assets/140073502/cfe9ca13-7684-480f-998b-52e6bda80690)
![Image Placeholders](https://github.com/WordPress/performance/assets/140073502/b8f77af1-87e2-4e7d-8e1c-63d7559e8cbb)
![Modern Image Formats](https://github.com/WordPress/performance/assets/140073502/27da305b-03e5-4ed5-8c5e-fb565f34586a)
![New plugin - Javascript](https://github.com/WordPress/performance/assets/140073502/347f6f25-1554-4854-a86a-e586d25a61f0)
![Optimization Detective](https://github.com/WordPress/performance/assets/140073502/7c5289a7-9bb6-4189-95fe-22fccee54a1d)
![Performant Translations](https://github.com/WordPress/performance/assets/140073502/d9200f36-b30f-4d88-b789-3151645cf18d)
![Speculative Loading](https://github.com/WordPress/performance/assets/140073502/cba8ab97-3b3e-4378-b5b0-2e10e7932f49)

We also have the banner design. There were a couple of ideas for the tagline, but we can also do without it, dependent on what you think works best. If we go without the tagline, the PL logo will be centered. 
Tagline ideas: 

1. “Unlock Peak Performance for Your WordPress Site”
2. “Supercharge Your WordPress Site’s Speed and Efficiency”
3. “Boost Your WordPress Site’s Performance to New Heights”
4. “Empower Your WordPress Site with Lightning-Fast Performance”

![Frame 409](https://github.com/WordPress/performance/assets/140073502/9f42a583-7967-4a59-b81a-d38329ac1084)

Let me know what you think.

**Comment by swissspidy** [comment]
The second to last one is probably for Performant Translations?


> We also have the banner design. There were a couple of ideas for the tagline, but we can also do without it

For translation reasons I'd suggest not adding a tagline for now

**Comment by westonruter** [comment]
Looking good! As mentioned in https://github.com/WordPress/performance/issues/1136#issuecomment-2125876004 we also need one for Image Prioritizer.

For the tagline, either we could do nothing or just use the "Performance Lab" name.

**Comment by adamsilverstein** [comment]
The new icons looks great, one small piece of feedback: the white icon part seems small in comparison to the overall blue box. Could the icon part be a bit large, I'm concerned it will be hard to make them out if shown at a small size.

I'm fine with no tagline, if we do add one it should mention that this plugin lets users test the latest performance features being tested for core.

**Comment by westonruter** [comment]
@sstopfer Could we also see how the banner would look cropped to a 2:1 aspect ratio per https://github.com/WordPress/performance/issues/1136#issuecomment-2072969793?

**Comment by westonruter** [comment]
> For the tagline, either we could do nothing or just use the "Performance Lab" name.

What if we have two versions, one with just the P which is used for the Performance Lab plugin, and then another which includes **Performance Lab** as the "tagline" which we use for the feature plugins (in which case it would not be redundant).

**Comment by joemcgill** [comment]
> What if we have two versions...

I don't think we need to complicate things. One version that is applicable to any plugin should be fine. We can always iterate in the future.

**Comment by westonruter** [comment]
The thing is that for the feature plugins it may not be clear what the P refers to.

**Comment by joemcgill** [comment]
It's worth remembering that the 'P' is used as the icon that represents the Performance Team, and not just the Performance Lab plugin. The same icon is used in the badge that members of the team get on their profile, as well as the icon used on our [team site](https://make.wordpress.org/performance/):

**Profile screenshot**
<img width="944" alt="image" src="https://github.com/WordPress/performance/assets/801097/da27ccb0-bd7c-4d02-b2f2-a14b730b9c5f">

**Profile team site screenshot**
<img width="297" alt="image" src="https://github.com/WordPress/performance/assets/801097/5dbb14da-8392-4f77-a8dc-4866c7aa6edc">
