### ISSUE TITLE
Progress indicator is missing when activating a feature

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1139]
## Feature Description

When activating a feature on the Performance screen, there can be quite a bit of delay between the initial click and the page reloading with the success admin notice:

[Screen recording 2024-04-15 10.18.42.webm](https://github.com/WordPress/performance/assets/134745/eea5a8f6-17af-4792-9123-4a297f1c72f0)

This is because activating a feature may involve installing a plugin first before activating the plugin. There should be some spinner that appears with the Activate button that was clicked. Also, the other features' Activate buttons should also be disabled while this reload process is happening.

Perhaps better would be to use an Ajax process to activate the plugin rather than to do a full page reload. This would allow a user to click to activate multiple features without having to wait for a page reload (e.g. shiny updates).

**Comment by mukeshpanchal27** [comment]
In #1091, I initially used the AJAX approach for installation and activation. However, based on the feedback https://github.com/WordPress/performance/pull/1091#discussion_r1539743622, I changed it to reload. In the AJAX approach, I added a loading button. If we agree to use AJAX, then I'm happy to open a PR that uses that approach.

**Comment by westonruter** [comment]
See video in https://github.com/WordPress/performance/pull/1184 (for features with plugin dependencies) which shows further need for a spinner.

**Comment by westonruter** [comment]
@mukeshpanchal27 Let's start with just the spinner as the quick fix, and then we can go with Ajax next.
