### ISSUE TITLE
Site Speed Report Against CrUX

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#114]
When it comes to measuring Performance data, users should understand how their performance metrics weigh in against the greater internet. This is where the CrUX (Chrome User Experience Report) can provide valuable insight.

Interesting article for reference / more detail:
https://www.brainlabsdigital.com/blog/how-to-create-a-site-speed-report-on-data-studio-based-on-chrome-user-experience/

The object here would be to give the user an up to date idea how their site metrics perform against the rest of the internet. This is ideally where Google wants to see your site excel. If you can know that your site is in the top 3% of sites across the internet, that not only makes users feel good about their site but also increases sentiment. 

This idea is also motivated by Google: https://web.dev/vitals-tools/ for large sites that would be indexed by CrUX, so it may not apply to your average little old blog, but for more seasoned WordPress sites with lots of traffic this could be very valuable.

I'd envision this in some kind of Dashboard Widget, but thought I'd just echo the idea out here and get some feedback.

**Comment by swissspidy** [comment]
Closing in favor of #1324 where similar but broader ideas are shared
