### ISSUE TITLE
Server-Timing: Add in REST API

### ISSUE THREAD

**Issue by swissspidy** [WordPress/performance#1149]
## Feature Description

Related: #770 

Here's how I did it manually by filtering `rest_post_dispatch`:

https://github.com/swissspidy/media-experiments/blob/c3b9d0c76734b215e1ac7015c0bc7a9dd96381ab/inc/functions.php#L1019-L1046

Related: https://core.trac.wordpress.org/ticket/49634

**Comment by adamsilverstein** [comment]
Great idea and seems like you have the code we need already!
