### ISSUE TITLE
Add a Performance Checklist to Plugin

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#115]
Often end users are not aware of every aspect of performance. Hence we should help them determine what is critically missing from their site. Lighthouse may be a bit too much for them or made up of details that aren't obvious.

Similar to an SEO or Security setup which checks certain items are in order, this could look something like:

- ✅  Site runs on HTTPS?
- ✅  Uses a CDN for Images?
- ✅  Uses WebP for Images?
- ❌  JS bundle sizes are low
- ❌  No resources are render blocking
- ❌  Preloads important assets

Something along those lines, present in the wp-toolbar or a dashboard widget / overall plugin status could be very useful in mitigating performance issues, especially considering the open source nature of WordPress themes / plugins.

**Comment by tillkruss** [comment]
Response time may be nice to measure too and suggest page/object caching.

**Comment by mitogh** [comment]
I like this idea, as well I think having an API or a mechanism as well so developers can set custom measurements for specific areas of a theme like:

- how long does it take to load the main image of my products?
- how long does it take the main featured image to be displayed?

This can be a place where we can use the API [`performance.measure`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure) as a place to allow developers to measure specific areas of a site.

**Comment by dainemawer** [comment]
@mitogh agreed - I think this could be seriously useful, if well thought out and purposeful. I think to scope things, we should (for now) only be concerned with what is absolutely critical for loading a good user experience above the fold. That may involve a number of areas, but if we can ensure that pixels get to the browser early enough then we're doing our job :)

**Comment by adamsilverstein** [comment]
We discussed this ticket at the bugscrub today. We have generally gone in the direction of adding performance related recommendations directly to the Site Health panel. We also have broken the plugin out into features that each address a different issue/area. 

Given that, adding a separate checklist seems duplicative. I'm going  to close this as "wontfix" - @dainemawer if you feel there is still some value in working on a checklist feature, feel free to re-open.
