### ISSUE TITLE
Need to update inline documentation in settings.php

### ISSUE THREAD

**Issue by mayurprajapatii** [WordPress/performance#1158]
## Bug Description

In webp-uploads/settings.php Line no 72 

`Adds custom style for media settings.` it should be `Adds custom styles to hide specific elements in media settings.`

## Screenshot

![webp-upload](https://github.com/WordPress/performance/assets/91679132/0dad9a0f-af2a-4867-a407-250b4fe7b04e)

## Steps to reproduce

1. Go to 'webp-uploads/settings.php Line no 72
2. you will able to see the that comment texts needs to update

**Comment by westonruter** [comment]
Yeah, while the existing description is not wrong, your suggestion is more specific. Feel free to open a PR to improve this.

**Comment by mayurprajapatii** [comment]
Thanks @westonruter for the feedback. 

I have created PR: https://github.com/WordPress/performance/pull/1160

**Comment by mukeshpanchal27** [comment]
Closed in #1160
