### ISSUE TITLE
Performance Budgets

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#116]
One item we haven't really spoken about is Performance Budgets. There is a ton of theory and opinion on this subject, so I could see this issue becoming pretty lengthy. We often do not build sites with the question of: "What is my performance budget" in mind? As if you were budgeting financially for a month, so too should your site be budgeted, tightly coupled with your goals. 

This is a feature that considering the media attention WP has received from "slipping" on the performance side of things, no other platform (to my knowledge has implemented). Yes, WP is extensible and you can do virtually anything with it, but that doesnt mean you should. Having an active performance budget on every site, keeps you honest, helps you make more insightful and meaningful decisions and has the ability to keep your site clean (of too many plugins, etc).

According to Addy, a Performance Budget can be:
1) Milestone-based (Healthy Core Web Vitals)
2) Quantity-based (raw metrics like the size of your JS files)
3) Rule-based (such as your Lighthouse score)

Has a huge proponent of Open Source and creative-computer freedom, WP should consider the need for developing a performance-based culture around these objects, or at least extending it. 

I think an internal tool, could be useful in this regard where a user can say: "I want my site to load in 5 seconds" and we tell them the ideal ratio of resources, based on server requests, script counts and other metrics" its a bit ambitious I know and probably needs a lot more thought, but finding someway to integrate performance budgets into WordPress could be just what we need to keep innovating.

**Comment by mitogh** [comment]
This metric can be compared against all the assets used on the site via themes and plugins for specific pages and offer a report of which assets goes beyond this budget. 

I like the idea of having a metric that can be customized via (filters) or other ways from the developer's side in order to customize the report offered in the site health:

Related tickets: 

- #63 
- #97

**Comment by sgomes** [comment]
This sounds like something for the Measurement focus area to consider.

**Comment by swissspidy** [comment]
Closing in favor of #145 which is about the same topic and has more comments
