### ISSUE TITLE
Compatibility issue between WooCommerce 8.8.2 and two plugins Performance Lab and Modern Image Formats

### ISSUE THREAD

**Issue by phanduynam** [WordPress/performance#1161]
## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

**Comment by phanduynam** [comment]
Compatibility issue between WooCommerce 8.8.2 and two plugins Performance Lab and Modern Image Formats

I encountered a problem using WooCommerce due to a conflict with two plugins, Performance Lab and Modern Image Formats. We hope to resolve this compatibility issue. Subcategory error with the same name when importing product data into WooCommerce 8.8.2.

When importing product data into WooCommerce 8.8.2 via CSV file, I encountered an error that caused two subcategories with the same name to appear. During data import, I imported two products of the same category:

- "Product A" belongs to the category "Family and life > Utility tools and equipment"
- "Product B" is also in the category "Home and Life > Utility Tools and Equipment"

As you can see, both of these products belong to the same main category and sub-category. However, after importing data into WooCommerce 8.8.2, the system automatically created two separate subcategories. Initially, I thought this error might be due to the text formatting of the two products' category columns being different, but when I checked the duplicate entries on the Google Sheet, I realized that they were exactly the same. All WordPress versions, website themes and plugins have been updated to the latest version and I have also cleared the website cache, but this error continues to occur.

Here are links to the illustrations and CSV files:
- Illustration image 1: [Link](https://drive.google.com/file/d/1GCMAha_gAy8KscBzEi05b_oxUopkV3Ux/view?usp=sharing)
- Illustration image 2: [Link](https://drive.google.com/file/d/1ZX6LktODsulPnOFcd_u5batfWAXjEQCk/view?usp=sharing)
- Illustration image 3: [Link](https://drive.google.com/file/d/1eLb3N0fV1PZDZEvGxyUIL8hJ1Uaf82FW/view?usp=sharing)
- CSV file: [Link](https://drive.google.com/file/d/1Ho5LSxkgytcCFwrwBOju5FszfJyCj_fa/view?usp=sharing)

**Comment by westonruter** [comment]
Hummm. I don't see how this would be related to Performance Lab or Modern Image Formats. How do you know it's not just a bug in WooCommerce itself?

**Comment by westonruter** [comment]
Closing for now. Can be reopened if there is a confirmed problem.
