### ISSUE TITLE
`srcset` not created when "Generate JPEG files in addition to WebP" enabled

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#1207]
## Bug Description

When the "Generate JPEG files in addition to WebP" option is enabled, the HTML output does not include the expected `srcset`, instead, only the main image is referenced.

## Steps to reproduce

1. Install the modern images feature
2. enabled the Generate JPEG option under settings->media
3. upload a jpeg image to a post
4. check the source code

Expected results: in `img` tag uses `srcset`
Actual results: the `img` tag lags a `srcset` attribute

## Screenshots

Setting:
![image](https://github.com/WordPress/performance/assets/2676022/ecca08d3-c62b-46f6-ab44-adeae29a31ff)

With setting **disabled**:
![image](https://github.com/WordPress/performance/assets/2676022/3a430da8-842d-482f-9814-58ef3e83c6b5)

With setting **enabled**:
![image](https://github.com/WordPress/performance/assets/2676022/c9b76be6-4d26-4a72-b717-96c65c31201e)

Note: I discovered this issue when working to update the plugin to support AVIF: https://github.com/WordPress/performance/pull/1176

**Comment by adamsilverstein** [comment]
Note: the behavior may depend on the size of the original uploaded image, my test image was 3000x2000 pixels.

This was the image I tested with:
![My Flower Photo](https://github.com/WordPress/performance/assets/2676022/e7b17cc5-c46f-4e2b-b84a-df77bd4379fa)

**Comment by mukeshpanchal27** [comment]
Should be punt to next release.

**Comment by adamsilverstein** [comment]
Posted a fix for this in https://github.com/WordPress/performance/pull/1236

**Comment by adamsilverstein** [comment]
This was fixed in https://github.com/WordPress/performance/pull/73, closing as resolved
