### ISSUE TITLE
Using new default image sizes for new site.

### ISSUE THREAD

**Issue by khoipro** [WordPress/performance#121]
Currently when you install a new site, there is 3 image sizes:
- Thumbnail -150x150 cropped
- Medium - 300px
- Large - 1024px

Actually based on responsive devices, we should consider changing to:
- Medium or Mobile: 395px
- Large: 1080px

And somehow the srcset calculation should adapt well with mobile image better. Also retina support (need another ticket?)

Currently many themes will load 1024px images on 375px iPhone screen.

**Comment by jonoalderson** [comment]
'Large' should ideally be 1200px, as the minimum-optimal size for most social sharing contexts is 1200px x 675px.

**Comment by adamsilverstein** [comment]
@khoipro I don't think we can change the defaults for new sites in a plugin so this might progress better as a Trac ticket. 

Can you open a ticket there to request this change?

> Actually based on responsive devices, we should consider changing to:
>Medium or Mobile: 395px
>Large: 1080px

it would be great to have more data to back up these proposed changes.
