### ISSUE TITLE
Prepare 3.1.0 release

### ISSUE THREAD

**Issue by sstopfer** [WordPress/performance#1212]
This issue is to track preparation of the upcoming 3.1.0 release up until publishing, which is due May 20, 2024.

- [x]  Create release/3.1.0 branch closer to the release date
- [x]  Finalize scope and punt unfinished pull requests to following release
- [x]  Prepare the release (Monday May 20, 2024)

**Comment by westonruter** [comment]
Note: we should wait to cut the release branch until the PRs in the open milestones are merged: https://github.com/WordPress/performance/milestones
