### ISSUE TITLE
Images with partial transpency return "false" for "has-transparency"

### ISSUE THREAD

**Issue by JacobDB** [WordPress/performance#1214]
## Bug Description

Images that have partial transparency return `false` for `has-transparency`

## Steps to reproduce

1. Upload a partially transparent image, such as [this one](https://github.com/WordPress/performance/assets/1123997/be3cea2a-f917-4f7c-b84b-0240b645dd2b)
2. View the source code on the front end
3. Observer `data-transparency="false"` is added to the image

## Screenshots

![image](https://github.com/WordPress/performance/assets/1123997/0724357b-0ba2-47ad-aae8-da530a85ee39)

![image](https://github.com/WordPress/performance/assets/1123997/1d5fe7a4-def7-46f7-a31c-4a504a7a4770)

## Additional Context

 - PHP Version: 8.2.18
 - OS: All
 - Browser: All
 - Plugin Version: Performance Lab 3.0.0, Image Placeholders v1.1.0
 - Device: All

**Comment by westonruter** [comment]
From looking at the code it seems like this should be working correctly, where if alpha is zero then it is fully opaque:

https://github.com/WordPress/performance/blob/3febac9702806accbeb59adb76e5979a0e55e235/plugins/dominant-color-images/class-dominant-color-image-editor-gd.php#L84-L86

https://github.com/WordPress/performance/blob/3febac9702806accbeb59adb76e5979a0e55e235/plugins/dominant-color-images/class-dominant-color-image-editor-imagick.php#L86-L88

**Comment by JacobDB** [comment]
So are you saying that's intentional?

**Comment by westonruter** [comment]
No, but I'm confused why it isn't working for you because it seems to be coded correctly. It doesn't seem to be working for me either.

**Comment by JacobDB** [comment]
Interesting, glad it's not just me then! I did some more testing and yeah, it seems to be consistently occurring.

**Comment by westonruter** [comment]
I found the problem. I've proposed a fix in #1215. It's a one-line change you can easily test yourself.

**Comment by JacobDB** [comment]
Awesome, thanks much!
