### ISSUE TITLE
Remove `object-cache.php` drop-in on uninstall

### ISSUE THREAD

**Issue by swissspidy** [WordPress/performance#1220]
## Feature Description

A user on Trac [reported](https://core.trac.wordpress.org/ticket/61188#comment:6) a fatal error when using `switch_to_blog` apparently because the `object-cache.php` drop-in is still present after uninstalling Performance Lab.

We should investigate this and

- Ideally update the drop-in so that this can't happen
- Add an `uninstall.php` file to remove the drop-in upon uninstall

**Comment by westonruter** [comment]
@swissspidy Are you investigating this? Can we get it into 3.1.0?

**Comment by swissspidy** [comment]
I haven‘t looked into it further so far, but I can try tomorrow

**Comment by swissspidy** [comment]
Maybe it should even be done on deactivation?

**Comment by westonruter** [comment]
Yes, great point. I also wonder if this hack is too hacky to be worthwhile.

**Comment by swissspidy** [comment]
Agreed. Long term we should look into ways to make that obsolete, for example by either porting the whole Server-Timing feature to core (albeit I'd vote for a slightly different API) or at the minimum add some more globals à la `$timestart`.

**Comment by swissspidy** [comment]
Sooo.... There is already `perflab_maybe_remove_object_cache_dropin` hooked to plugin deactivation 💡 🤦
