### ISSUE TITLE
WP_Query performance for multiple taxonomies and post meta filters

### ISSUE THREAD

**Issue by khoipro** [WordPress/performance#123]
This is only a proposal to see how could we improve a way to handle a filter for large database.

**My issues**

We need to build a large app with main purpose is real estate classified. Each post will contain some data, but mostly it will be a few terms and have some post meta.

The filters based on those taxonomies work, however the performance will be slow and slow when having 100.000 and more.

I know there is an exiting solution to build custom table and using custom SQL query to filters, but if we rely on default taxonomy route, the query seems need to destroy existing WP_Query.

So what is a best way, or any flexible way to handle that kind of performance well?

**Comment by XVII** [comment]
As a thought exercise, it would potentially become more efficient to store each combination of taxonomy and give them an ID, then use that ID to identify the posts instead.

Therefore, a query would just be looking for posts with a particular ID (representing a specific combination of taxonomies, i.e. Taxonomy Set ID). Taxonomies would be responsible for maintaining the unique combination lookup table as taxonomies are added/removed.

We saw something similar used in a system that had scale issues when storing "tags" of sorts across millions of rows.

**Comment by swissspidy** [comment]
Architecture support questions like this are better suited for StackOverflow. Closing this issue as there is nothing actionable here for core or Performance Lab.
