### ISSUE TITLE
Update test prefix in test files and classes

### ISSUE THREAD

**Issue by thelovekesh** [WordPress/performance#1245]
As @westonruter mentioned in https://github.com/WordPress/performance/issues/514#issuecomment-2129970271, we should maintain consistency in the naming of test classes and files by adding the prefixes `Test_` for classes and `test-` for files. This approach aligns with the naming conventions of core test files and classes.

**Comment by imrraaj** [comment]
Hey @thelovekesh, I would like to work on this issue
