### ISSUE TITLE
Prepare Performance Lab 3.2.0 release

### ISSUE THREAD

**Issue by sstopfer** [WordPress/performance#1253]
This issue is to track preparation of the upcoming 3.2.0 release up until publishing, which is due June 6, 2024.

- [x]  Create release/3.2.0 branch closer to the release date
- [x]  Finalize scope and punt unfinished pull requests to following release
- [x]  Prepare the release (Thursday June 6, 2024)

**Comment by sstopfer** [comment]
@westonruter Here is the issue for the next release. I added June 6, but feel free to change the date based on what you decide will be release day.

**Comment by mukeshpanchal27** [comment]
Closing this as we completed the release on June 6.
