### ISSUE TITLE
`composer test:plugins` failed with error

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1256]
## Bug Description

Run `composer test:plugins` command.

```
> phpunit '--verbose' '--testsuite' 'auto-sizes'
Error: The following required constants are not defined: WP_TESTS_DOMAIN, WP_TESTS_EMAIL, WP_TESTS_TITLE, WP_PHP_BINARY.
Please check out `wp-tests-config-sample.php` for an example.
Script phpunit handling the test event returned with error code 1
Script @test --verbose --testsuite auto-sizes was called via test:auto-sizes
Script @test:auto-sizes was called via test:plugins
```

## Screenshots

<img width="860" alt="Screenshot 2024-05-29 at 10 57 27 AM" src="https://github.com/WordPress/performance/assets/10103365/6d75f94d-6064-4a4d-b513-7c45ff49554e">

**Comment by westonruter** [comment]
You can't run that command directly unless you have set up tests on your host environment. You gave to use the npm wrapper instead, AFAIK.

**Comment by mukeshpanchal27** [comment]
Got it. But we should document this somewhere so others understand why it’s not working. What do you think?

**Comment by westonruter** [comment]
Yeah, agreed. That error message should explain this, and reference the npm command to use instead. It could link to the handbook with instructions for how to set up the test environment without using wp-env as well.

**Comment by AhmarZaidi** [comment]
Hey, I was thinking of a an approach where we can define a `pretest` script to run before `composer test` like this:
```
"pretest": "php pretest.php",
"test":  ["@pretest", "phpunit"],
```

In the `pretest.php` script we can check if the environment is correct and print error message accordingly.

Should I go ahead with this approach or is there a better way?

**Comment by westonruter** [comment]
@AhmarZaidi that seems good to me.
