### ISSUE TITLE
Improve Settings for Modern Image Formats

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#1258]
## Feature Description

Since adding AVIF and `<picture>` element support, some potential improvements to the settings screen became apparent.

**Potential Improvements**

* As @joemcgill mentioned in https://github.com/WordPress/performance/pull/73#discussion_r1619478285 we should properly handle sites that lack both AVIF and WebP support (~2% of sites).
* `<picture>` element support is only useful when there is both a modern format (WebP/AVIF) and a JPEG fallback available for each sub size, eg. when the "Also output JPEG images" setting is enabled. Therefore, maybe the picture element support toggle should **only be enabled when JPEGs are being generated?** (and otherwise displayed in a greyed out "disabled" state)

**Comment by westonruter** [comment]
@adamsilverstein Good points. Could this be done for the next release on June 6th?

**Comment by adamsilverstein** [comment]
> @adamsilverstein Good points. Could this be done for the next release on June 6th?

Sure I am happy to work on this unless someone else wants to pick it up!
