### ISSUE TITLE
Performance Telemetry

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#126]
Im not sure if this goes against any best practices in open source in general or if it would be a security risk - but much like Chrome is collecting data from users browsers for CrUX, would it be worth collecting valuable data from WordPress sites when it comes to performance? This seems like a no brainer when it comes the large amount of sites that WordPress powers across the internet. 

Collecting data around:
1. Page weights
2. Number of 3rd-party resources used on average
3. Resource sizes of CSS / JS
4. Use of CDN's
5. Use of HTTPS

This could provide a far more detailed understanding of the WordPress landscape when it comes to performance in general.

**Comment by rviscomi** [comment]
I'm one of the maintainers of the public HTTP Archive project, which collects this kind of data for millions of websites, including 2.5 million WordPress sites. Let me know if there's anything I can do to help with this.

**Comment by westonruter** [comment]
For a previous discussion on telemetry in WordPress core, see https://core.trac.wordpress.org/ticket/38418

**Comment by adamsilverstein** [comment]
Closing this as "wontfix" based on the discussion on the linked trac ticket. Tl;DR; we already have all the data we need to make decisions from public data sources like httparchive, and for data we can't get externally, we also have one source already: upgrader telemetry - which we recently updated to include image format support data for example.

**Comment by westonruter** [comment]
This might actually make sense in the performance dashboard which is proposed to be part of the PL plugin in https://github.com/WordPress/performance/issues/1324

**Comment by adamsilverstein** [comment]
> This might actually make sense in the performance dashboard which is proposed to be part of the PL plugin in #1324

True, especially for users to collect their own sit metrics. I took this ticket to be more about collecting wider telemetry to "provide a far more detailed understanding of the WordPress landscape when it comes to performance".
