### ISSUE TITLE
Site Health: detect web server AVIF mime type support

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#1263]
## Feature Description

When the server supports AVIF processing, add detection in site health to check if AVIF images are being served with the avif type or with octet-stream. Warn users when avif isn't being used. Consider attempting to apply fix via .htaccess?

## Details

Since launching AVIF support in WordPress 6.5, some users are discovering that their AVIF images are being served with the network type "octet-stream".  The impact is relatively low since browsers know to serve these `.avif` files as AVIF images, however it is worth trying to detect and fix if possible.

## Examples

The website https://ground-cd.com/blog/avif/ uses AVIF images, checking the network panel the type shows as "octet-stream" instead of "avif".
![image](https://github.com/user-attachments/assets/25790cd5-9772-43e7-bbb8-87ea07b36d21)

On the other hand, this site serves up AVIF images correctly, with the avif type: https://aomedia.org/blog%20posts/avif-meet-the-next-level-image-file-format/
![image](https://github.com/user-attachments/assets/63f560fa-a459-4955-ba61-13b2435787b8)

## Underlying issue

This issue can happen if the web server does not include the `image/avif` MIME types in its configuration. For Apache, the host may have a custom config, and configurations could (possibly) be added via `.htaccess`

Nginx added AVIF to their base config in 2021 ([PR](https://github.com/nginx/nginx/commit/67d2a9541826ecd5db97d604f23460210fd3e517)).

Apache config would probably be host or distribution dependent, so these might need updating. For Apache, I opened [this PR](https://github.com/apache/httpd/pull/451) to add it to their config. Users can ask their hosts to add the configuration and this is a very low risk change for hosts.

## Suggested fix
* Add detection for the file type served when an AVIF image is loaded and warn users when the type is not correct
* Offer/try to fix the issue automatically (?)
* Maybe no need to run test if server doesn't support AVIF
* Suggest users ask their hosts add support and link to docs

**Comment by westonruter** [comment]
I see this is labelled for the Modern Image Formats plugin, however all of the Site Health tests have been located in the Performance Lab plugin. I think it makes sense to move Site Health tests which are closely related to certain plugins to actually move them to those plugins.

**Comment by adamsilverstein** [comment]
>  I think it makes sense to move Site Health tests which are closely related to certain plugins to actually move them to those plugins.

+1 -  Good point, I think we discussed that already.

**Comment by adamsilverstein** [comment]
I'll pick this one up!
