### ISSUE TITLE
Ad Performance

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#128]
I know this is something that is generally out of our control - however, ad tech is simultaneously the biggest monetary benefit to sites, and its biggest thorn when it comes to performance. This is mainly because ad tech bootstraps itself on page load and requests all sorts of other 3rd-party scripts that we have no control over. 

I don't have any solutions here off the bat, but I would like to setup a discussion around how we can improve ad implementation / performance within the WordPress eco-system. 

When referencing the [Web Almanac](https://almanac.httparchive.org/en/2021/third-parties) - it shows the state of 3rd-party libraries and it does not look so good in general!

**Comment by mukeshpanchal27** [comment]
We discussed in today's scrub and decide to close this as it's not the current priority. We can reopen to discuss if it comes up in future.
