### ISSUE TITLE
Cost to Load Site

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#129]
Not sure if its worth extrapolating this from WebPageTest but I think its an incredibly impactful metric that will really make users think. WebPageTest gives an indication of how much it costs to load a site using [What Does My Site Cost ](https://whatdoesmysitecost.com/) - this is something that users (I think) would pay attention to, and work towards bringing under control, as they can relate directly with the metric.

Up for discussion - just spitballing here!

**Comment by mukeshpanchal27** [comment]
We discussed in today's scrub and decide to close this as it's not the current priority. We can reopen to discuss if it comes up in future.
