### ISSUE TITLE
Lazy load embeds with facades

### ISSUE THREAD

**Issue by asafm7** [WordPress/performance#1299]
Was this considered?

https://developer.chrome.com/docs/lighthouse/performance/third-party-facades/

**Comment by westonruter** [comment]
The problem is that there is a very bad UX problem with façades, specifically for video. On mobile they require a second tap to play. See https://github.com/paulirish/lite-youtube-embed/issues/6

**Comment by asafm7** [comment]
Interesting, @westonruter. Thanks.

I have my own implementation that I thought was working but now I see isn't auto-playing on iOS.

BTW, it might be worth mentioning in the plugin's description how what it does is different (and better) than just adding `loading="lazy"` to the iframe.

**Comment by westonruter** [comment]
> BTW, it might be worth mentioning in the plugin's description how what it does is different (and better) than just adding `loading="lazy"` to the iframe.

@asafm7 Well, that _is_ what it does if the embed merely consists of an `iframe`. If there are scripts too then it will do additional work to delay loading them.

**Comment by swissspidy** [comment]
We're already tracking this in #113, so closing as a duplicate.
