### ISSUE TITLE
Modern Image Formats `picture` support breaks gallery block cropping

### ISSUE THREAD

**Issue by joemcgill** [WordPress/performance#1300]
## Bug Description

When using the new Modern Image Formats `picture` element support on my personal site, I noticed that the markup conflicted with the style for an image gallery created using the `wp:gallery` block when the "Crop images to fit" setting was enabled for the block.

I've left the feature enabled [on my site](https://joemcgill.net/2024/01/a-2023-retrospective/) for now so the behavior can be observed.

## Steps to reproduce

1. Activate the Modern Image Formats plugin and enable `picture` support from the Media Settings screen.
2. Create an image gallery using the core gallery block that includes images with different aspect ratios
3. Turn on the "Crop images to fit" setting on the Gallery block settings panel (screenshot below)
4. Preview the page in the front end

### Screenshot of the settings panel

<img width="278" alt="image" src="https://github.com/WordPress/performance/assets/801097/ee68a784-0689-4e77-8c13-f1cf8d9a6291">

### Before using `picture`

<img width="854" alt="image" src="https://github.com/WordPress/performance/assets/801097/e29fd870-8af3-46ac-aa8a-c3d8c92d7f12">

### With `picture` support enabled

<img width="1101" alt="image" src="https://github.com/WordPress/performance/assets/801097/134a7c53-ea4b-4ec2-81e3-4f0dcebbd4d3">

**Comment by adamsilverstein** [comment]
@joemcgill thanks for the bug report (and ouch that first photo!). This is likely due to a CSS selector that isn't applying correctly. We will either need to change the specificity to make it work, or add an additional selector for the picture element version.

**Comment by joemcgill** [comment]
No problem, and sorry for my face. I've recovered! I assumed there was a CSS issue but haven't dug into it. Wanted to report it while it was top of mind.

**Comment by devansh016** [comment]
Would like to work on this issue. Can you assign me this?

Adding the following css to picture tag should solve this issue.
```HTML
style="display: contents;"
```

@joemcgill @adamsilverstein
