### ISSUE TITLE
Ignore query parameters in URL metrics

### ISSUE THREAD

**Issue by parmar-pratik-85** [WordPress/performance#1303]
## Feature Description
looking at the logs in wordpress, it looks like od_url_metrics post type is being updated and post titles (url) being updated with changing UTMs while the underlying URL is still the same. So the question is:

1) does the plugin ignore UTMs and query parameters in general while collecting and learing heuristic stats?
2) If not, every url with UTMs is unique and it won't have enough numbers to analyze and come up with optimization plan and the underlying page will remain unoptimized even if it has enough traffic while the DB will just keep growing. This is similar to cache hash which is affected by query parameters in URL.

It would be great if we can get a clarity on how is this being handled and if we can get this feature incorporated.

**Comment by westonruter** [comment]
Hello! Good question. Yes, arbitrary URL parameters are being ignored currently. The URL itself is not used in the computation of the `post_name` for the `od_url_metrics` post type. Instead it is the WordPress-recognized "query vars" which are used, with some modifications. 

The slug (`post_name`) computation is seen here:

https://github.com/WordPress/performance/blob/31c6ee9f8eb76a5b34bac089e24326c3db0c508a/plugins/optimization-detective/optimization.php#L148

And the logic for `od_get_normalized_query_vars()` is as follows:

https://github.com/WordPress/performance/blob/31c6ee9f8eb76a5b34bac089e24326c3db0c508a/plugins/optimization-detective/storage/data.php#L66-L86

So you shouldn't see arbitrary URL parameters being showing up in the computation of slug. You will see them mentioned in individual URL metrics that populate a given `od_url_metrics` post, but the full URLs are included there just for debugging purposes. Also, the most recent URL populating a given set of URL metrics is used as the `post_title`, again just for debugging purposes. You should see that the `post_name` is not changing. Once the sample size has been populated for each breakpoint viewport group, then it should stop collecting metrics when loading a page until the metrics get stale.

Please let me know if you're seeing something different!

**Comment by westonruter** [comment]
I'll close this for now, but please do follow-up if something isn't right.
