### ISSUE TITLE
Server-timing API not working in WP 6.5.4

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1305]
While doing manual benchmarking i found that Server timing API shows error in 6.5.4 version.

`Notice:  Function Perflab_Server_Timing::register_metric was called incorrectly. The method must be called before or during the perflab_server_timing_send_header action. Please see Debugging in WordPress for more information.  in wordpress/wp-includes/functions.php on line 6078`

Test site: https://instructfan.s1-tastewp.com/

Install and activate [this one-liner plugin](https://gist.github.com/felixarntz/9c3d7150c74082e69bb426393b68b12e). It enables output buffering for the Performance Lab’s Server-Timing API, which is disabled by default, and by that allows the API to also record and send metrics that can only be measured after page output has started.

**Comment by mukeshpanchal27** [comment]
We should update the doc https://make.wordpress.org/performance/handbook/measuring-performance/benchmarking-php-performance-with-server-timing/#preparing-a-wordpress-site-for-server-timing-benchmarks and remove the third point for `Install and activate this one-liner plugin` and instead ask to active it from Admin Panel > Tools > Server-Timing > Check " Enable output buffering of template rendering"

cc. @joemcgill

**Comment by westonruter** [comment]
@mukeshpanchal27 [Updated](https://make.wordpress.org/performance/handbook/measuring-performance/benchmarking-php-performance-with-server-timing/#:~:text=Follow%20these%20steps%20to%20prepare%20a%20WordPress%20site%20to%20perform%20a%20Server%2DTiming%20benchmark%20using%20the%20Performance%20Lab%20plugin%3A).
