### ISSUE TITLE
Add release documentation

### ISSUE THREAD

**Issue by JustinyAhin** [WordPress/performance#131]
It'll benefit all the contributors to have some documentation about how we release the plugin (GitHub releases and deployment to w.org).

This will include any pre-release checks, scripts to run (linting, formatting?) before the releases, and any other useful information.

**Comment by jeffpaul** [comment]
100% in favor of this, would recommend its either part of https://github.com/WordPress/performance/blob/trunk/CONTRIBUTING.md as a `Release Instructions` section or if its rather lengthy then could be in its own `RELEASING.md` file in the repo.

**Comment by felixarntz** [comment]
@jeffpaul We have a `docs` directory intended for most documentation, so I suggest we put the release documentation in there. Potentially it could be linked in the `CONTRIBUTING.md` file - although I'm personally not sure that's necessary, given that releasing is not exactly the most relevant task for people who want to start contributing. But we should definitely have an easy-to-reach entry point where it is linked.
