### ISSUE TITLE
Preload links can be sent via `Link` HTTP response headers over HTML `link` tags

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1321]
As noted in the web.dev article, [Preload critical assets to improve loading speed](https://web.dev/articles/preload-critical-assets#how_to_implement_relpreload:~:text=You%20can%20also%20preload%20any%20type%20of%20resource%20via%20the%20Link%20HTTP%20header%3A), sending the preload links via `Link` HTTP response headers has a slight performance advantage over HTML `link` tags:

> You can also preload any type of resource via the [Link HTTP header](https://developer.mozilla.org/docs/Web/HTTP/Headers/Link):
> 
> ```http
> Link: </css/style.css>; rel="preload"; as="style"
> ```
> 
> A benefit of specifying preload in the HTTP Header is that the browser doesn't need to parse the document to discover it, which can offer small improvements in some cases.

Since Optimization Detective is output-buffering the page, this can be very straightforward to implement. Instead of (or rather _in addition to_) doing this:

https://github.com/WordPress/performance/blob/2f2691a153cf1819a907a7cb54205d44c008bb62/plugins/optimization-detective/optimization.php#L192-L195

A new method can be added to `OD_Preload_Link_Collection` like `send_headers()` which can construct the `Link` response header and send it via `header()`.

**Comment by AhmarZaidi** [comment]
Hey, I'd like to work on this.
