### ISSUE TITLE
Update plugin name for Initial work on Accurate Sizes in Auto Sizes Plugin

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1330]
As we are in the phase where we are about to merge the initial work for accurate sizes for images in the Auto Sizes plugin, we should update the plugin name to reflect these changes so the end user knows that initial changes have been implemented. Additionally, we should add an Upgrade Notice that references these changes.

https://github.com/WordPress/performance/pull/1329

**Comment by mukeshpanchal27** [comment]
I suggest updating the plugin name to `Accurate Sizes for Images` instead of `Auto-sizes for Lazy-loaded Images`.

Any suggestions are welcome!

**Comment by westonruter** [comment]
Slightly better than `Accurate Sizes for Images` I think would be `Accurate Image Sizes`.

**Comment by joemcgill** [comment]
Thanks for getting this conversation going. I agree we need to decide on a new plugin name to more accurately reflect the broadened focus.

I like `Accurate Image Sizes` as an option, though making sure the `sizes` attribute is 100% accurate is not a goal of this plugin, so I think considering options that avoids that implication could be good.

Some options if we want to focus on the `sizes` attribute optimizations:

* Dynamic Image Sizes
* Enhanced Image Sizes
* Image Sizes Optimizer
* Image Sizes Booster

However, I could see the work on improving the `sizes` attribute lead to responsive image optimizations that focus on the `srcset` side of the problem space in the future (there are no plans for that right now, just thinking ahead). I wonder if it would be wise to pick a name that would allow for that broadening in scope as well? Some initial options:

* Responsive Image Optimizer
* Smart Responsive Images
* Responsive Image Enhancer
* Advanced Responsive Images

What do you all think?

**Comment by westonruter** [comment]
Another idea that just came to mind: **Resized Responsive Images**

Another idea is to mash together "Enhanced Image Sizes" and "Responsive Image Enhancer" into **Enhanced Responsive Images**.

**Comment by mukeshpanchal27** [comment]
I will go with the **Enhanced Responsive Images**.

**Comment by mukeshpanchal27** [comment]
@joemcgill @westonruter I have opened a draft PR to update the plugin name and make other related changes. Please feel free to review it.
