### ISSUE TITLE
wp_editor_set_quality not changing image quality for AVIF images

### ISSUE THREAD

**Issue by jamesozzie** [WordPress/performance#1331]
## Bug Description

As raised by [one user in the support forums](https://wordpress.org/support/topic/avif-image-quality/), applying a wp_editor_set_quality filter has no effect to AVIF images generated by the plugin. 

## Steps to reproduce

1. Download [this JPEG image](https://www.gstatic.com/webp/gallery/5.jpg) (120.78 KB in size, taken from [here](https://developers.google.com/speed/webp/gallery1)) and upload it with the AVIF format enabled. The compressed image should be 39KBs. 
2. Apply the `wp_editor_set_quality` filter, as [per this guide](https://make.wordpress.org/core/2024/02/23/wordpress-6-5-adds-avif-support/#:~:text=Q%3A%20How%20do%20I%20adjust%20the%20compression%20level%20used%20for%20generated%20AVIF%20images%3F), using the below example snippet. 

```php
function filter_avif_quality( $quality, $mime_type ) {
	if ( 'image/avif' === $mime_type ) {
		return 15;
	}
	return $quality;
}
add_filter( 'wp_editor_set_quality', 'filter_avif_quality', 10, 2 );
```
3. Upload the same JPEG image once more. The AVIF image size remains at 39KBs

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

**Comment by mukeshpanchal27** [comment]
I also replicate same issue.

**Comment by mukeshpanchal27** [comment]
It seems like the issue with AVIF image quality settings might be related to bugs within the WordPress Core or the library ImageMagick.

https://kiwix.ounapuu.ee/content/stackoverflow.com_en_all_2023-11/questions/73549733/php-imagick-avif-image-quality-options-not-working

@adamsilverstein @westonruter do we needs to open issue in WordPress Trac and close this one?

**Comment by adamsilverstein** [comment]
> do we needs to open issue in WordPress Trac and close this one?

possibly, I will review and test further.

**Comment by adamsilverstein** [comment]
I also verified this bug, it seems like the core call to `setImageCompressionQuality` doesn't actually work and maybe this needs to be `setCompressionQuality` - testing further. I'm not sure if this is isolated to AVIFs or extends to other image types as well.

**Comment by adamsilverstein** [comment]
the code works fine when adjusting WebP quality, it fails with Imagick and AVIF. I'm going to search for possible upstream bugs.

**Comment by adamsilverstein** [comment]
I verified that this is fixed by adding a single line into core's Imagick editor class with `setCompressionQuality` in addition to `setImageCompressionQuality`. I'm not sure why PHP behaves differently with WebP vs. AVIF.

I will open a ticket to fix this in core, I think we should call `$this->image->setCompressionQuality( $quality );` for all types.

**Comment by adamsilverstein** [comment]
Closing in favor of https://core.trac.wordpress.org/ticket/61614.

@jamesozzie @mukeshpanchal27 - if possible can you test the fix I am proposing there?

**Comment by jamesozzie** [comment]
Happy to test any fix you're proposing @adamsilverstein. I can confirm the same issue as descibed in trac [ticket #61614](https://core.trac.wordpress.org/ticket/61614), where the quality settings make no difference at present.

![Image](https://github.com/user-attachments/assets/6c78fd14-5ec7-4792-a6ef-facc3e4e14d9)

**Comment by adamsilverstein** [comment]
@jamesozzie  The fix is in https://github.com/WordPress/wordpress-develop/pull/7004 which I am preparing to merge now.
