### ISSUE TITLE
Enhance reliability of how Site Health enqueued assets module detects assets

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#135]
The initial implementation for the Site Health enqueued assets module (see #25) is a solid start, but there's room for enhancement in how reliably it detects enqueued assets. This was already pointed out in the [initial PR](https://github.com/WordPress/performance/pull/54) review, but it was decided to merge the large first PR first and then implement this enhancement separately, to allow for a more focused review.

This issue is primarily to address the following review comment: https://github.com/WordPress/performance/pull/54#discussion_r793498014

There are potentially more aspects we can improve around this, let's explore this here.

**Comment by felixarntz** [comment]
@aristath Anything to add? Do you think this is already good to open a PR for addressing your comment, or should we evaluate the technical approach a bit more before writing code?

cc @manuelRod

**Comment by aristath** [comment]
Assigning this one to myself so I can take a look again on Monday.
I think the code posted in https://github.com/WordPress/performance/pull/54#discussion_r793498014 will be a good starting point, I'll just need to polish and properly test it before submitting a PR 👍

**Comment by manuelRod** [comment]
Hello, @aristath @felixarntz I was working already on the proposed enhances, I didn't realise you have merged the previous PR :D

Anyways, here is the new PR with a few of the things addressed, we can keep the conversation going on there!

[#136](https://github.com/WordPress/performance/pull/136)

**Comment by felixarntz** [comment]
@manuelRod Oh, sorry about that - I guess I merged that a bit too quickly. But that's great, will review soon!

**Comment by manuelRod** [comment]
@aristath can you review this PR too?

**Comment by felixarntz** [comment]
Fixed via #136
