### ISSUE TITLE
Accurate sizes improvement didn't account for the disable filter for sizes

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1389]
## Bug Description

WordPress core has a mechanism to disable responsive images through some filters.

```php
add_filter( 'wp_calculate_image_srcset', '__return_empty_array' );
add_filter( 'wp_calculate_image_sizes', '__return_false' );
```

If we disable responsive images, the Enhance Responsive Image plugin still adds the sizes and srcset values. We should fix this.

## Steps to reproduce

1. Add `add_filter( 'wp_calculate_image_sizes', '__return_false' )` in your functions.php 
2. Add image through Image block
3. See image markup.

## Screenshots

<img width="1587" alt="Screenshot 2024-07-23 at 5 53 15 PM" src="https://github.com/user-attachments/assets/0ea9e51c-4361-4d58-a9b9-307de982dad2">

**Comment by westonruter** [comment]
I wonder why anyone would want to disable responsive images?

**Comment by mukeshpanchal27** [comment]
> I wonder why anyone would want to disable responsive images?

As it's core feature may someone use that 🤔 

We also find that for `thumbnail` size the sizes was not added by core, but the improve sizes filter still added sizes there.
