### ISSUE TITLE
Image Placeholder: Improve unit tests execution, to slow

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1397]
## Description

When we run Unit tests for Image Placeholders (dominant-color-images) it takes 4.86 minutes. We should check if anyway we can improve it. As `npm run test-php` runs all plugin test in single command so other plugins take less time then these.

## Screenshots
<img width="596" alt="Screenshot 2024-07-25 at 3 46 29 PM" src="https://github.com/user-attachments/assets/5e4f5fbd-60a8-49c4-8b74-380e8705c06f">

**Comment by westonruter** [comment]
I've opened #1401 to help with this, but we should have commands exposed to make it easy to run the tests for individual plugins as well. This is something that @thelovekesh was exploring, but I've also opened #1402 real quick.

**Comment by thelovekesh** [comment]
@mukeshpanchal27 On which OS/environment are you running these tests? I reviewed the CI execution time and noticed that all plugin tests typically take around 1 minute on GH runners with 16GB of RAM.

On my Linux machine with 16GB of RAM, the `dominant-color-images` test suite executed in `3.73 seconds`.

**Comment by mukeshpanchal27** [comment]
After resetting the `wp-env` it executed in `~5 seconds`.
