### ISSUE TITLE
Modern Image Formats: Improve unit tests execution, to slow

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1398]
## Description

When we run Unit tests for Modern Image Formats (webp-uploads) it takes 3.2 minutes. We should check if anyway we can improve it. As `npm run test-php` runs all plugin test in single command so other plugins take less time then these.

## Screenshots
<img width="590" alt="Screenshot 2024-07-25 at 3 50 44 PM" src="https://github.com/user-attachments/assets/968818b2-7250-454e-94f4-91722f0ea87f">

**Comment by westonruter** [comment]
As per https://github.com/WordPress/performance/issues/1397#issuecomment-2250993308:

> I've opened #1401 to help with this, but we should have commands exposed to make it easy to run the tests for individual plugins as well. This is something that @thelovekesh was exploring, but I've also opened #1402 real quick.

**Comment by swissspidy** [comment]
I suppose all the image crunching takes a lot of time. Maybe we could use smaller images or so?

**Comment by mukeshpanchal27** [comment]
After resetting the `wp-env` it executed in `~40 seconds`.

**Comment by swissspidy** [comment]
Then I suppose we can close this one :-)
