### ISSUE TITLE
API to facilitate more accurate “sizes” attribute

### ISSUE THREAD

**Issue by eugene-manuilov** [WordPress/performance#140]
## Feature Description

Other than lack of modern image formats like WebP, the most significant performance problem per our analysis has been that the image sizes used on WordPress sites are often not sufficient for how images are being displayed in the frontend.

To clarify, an example: If an image exists in 300px, 800px, and 1200px width, but in the frontend on desktops it shows in 500px width, WordPress can only use the 800px one, which will waste quite some bandwidth - having a version with ~500px width would be much better.

**Comment by eclarke1** [comment]
Updating the title here as the original epic 'Responsive image sizes' has been broken down into 2 epics:
- API to facilitate more accurate “sizes” attribute
- Client-side routine to automatically identify appropriate “sizes” attribute

We will use this issue to progress the first epic **API to facilitate more accurate “sizes” attribute**

**Comment by eclarke1** [comment]
@eugene-manuilov @mitogh @felixarntz @adamsilverstein as per our discussions, I have updated the title of this issue to reflect the separation of 'Providing images in the appropriate responsive sizes' into:
- API to facilitate more accurate “sizes” attribute
- Client-side routine to automatically identify appropriate “sizes” attribute  (still requires a GH issue creating)

**Comment by felixarntz** [comment]
As we are now prioritizing this via #760, I'm going to close this issue.
