### ISSUE TITLE
Saving Media settings page causes 500 under certain conditions

### ISSUE THREAD

**Issue by adam-ainsworth** [WordPress/performance#1409]
## Bug Description

If the media settings page is open when the plugin is activated in a different tab, saving the settings causes a 500 if the page is not refreshed.

## Steps to reproduce

1. Ensure the plugin is deactivated
2. Go to media settings at /wp-admin/options-media.php
3. Open the plugins page in a different browser tab
4. Activate the plugin
5. Go back to the media settings tab, make a change and click Save Changes *without refreshing*
6. A 500 error will occur, although the changes were saved

## Additional Context

 - PHP Version: 8.1
 - OS: Linux Mint (the web server environment is Lando v3.20.8)
 - Browser: Vivaldi, although it'll happen in any browser
 - Plugin Version: 2.0.2
 - Device: PC

**Comment by swissspidy** [comment]
What's in the error log when this happens?

**Comment by adam-ainsworth** [comment]
Sorry - I should have thought to include that:

```
Fatal error: Uncaught TypeError: webp_uploads_sanitize_image_format():
Argument #1 ($image_format) must be of type string, null given, called in /app/public_html/wp/wp-includes/class-wp-hook.php on line 326 and defined in /app/public_html/app/plugins/webp-uploads/helper.php:384

Stack trace:
#0 /app/public_html/wp/wp-includes/class-wp-hook.php(326): webp_uploads_sanitize_image_format(NULL)
#1 /app/public_html/wp/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
#2 /app/public_html/wp/wp-includes/formatting.php(5115): apply_filters('sanitize_option...', NULL, 'perflab_modern_...', NULL)
#3 /app/public_html/wp/wp-includes/option.php(866): sanitize_option('perflab_modern_...', NULL)
#4 /app/public_html/wp/wp-admin/options.php(344): update_option('perflab_modern_...', NULL)
#5 {main} thrown in /app/public_html/app/plugins/webp-uploads/helper.php on line 384
```

**Comment by westonruter** [comment]
@adam-ainsworth Good catch! I've opened https://github.com/WordPress/performance/pull/1410 to fix this. If you can test the build I provided there in https://github.com/WordPress/performance/pull/1410#issuecomment-2256549465 I would be grateful.

**Comment by westonruter** [comment]
It doesn't seem like this warrants a hotfix release given that the scenario is unlikely to be a common occurrence.

**Comment by adam-ainsworth** [comment]
Great - thanks for jumping on this so quickly. I'll give it a run through when I am back in the office tomorrow.

**Comment by adam-ainsworth** [comment]
Just tried out the new version and the 500 error no longer occurs. Thanks again!
