### ISSUE TITLE
Injection of sizes=auto into images can be more robust with HTML Tag Processor

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1446]
As [discussed](https://github.com/WordPress/performance/pull/1445/files#r1707668911) in #1445, there is an opportunity to leverage the HTML Tag Processor to make [`auto_sizes_update_content_img_tag()`](https://github.com/WordPress/performance/blob/471a1d0be46808a937e884b1897d0a0cd5328d47/plugins/auto-sizes/hooks.php#L55-L78) more robust as follows:

```php
function auto_sizes_update_content_img_tag( $html ): string {
	if ( ! is_string( $html ) ) {
		$html = '';
	}

	$processor = new WP_HTML_Tag_Processor( $html );

	// Bail if there is no IMG tag.
	if ( ! $processor->next_tag( array( 'tag_name' => 'IMG' ) ) ) {
		return $html;
	}

	// Bail early if the image is not lazy-loaded.
	if ( 'lazy' !== $processor->get_attribute( 'loading' ) ) {
		return $html;
	}

	$sizes = $processor->get_attribute( 'sizes' );

	// Bail early if the image is not responsive.
	if ( ! is_string( $sizes ) ) {
		return $html;
	}

	// Don't add 'auto' to the sizes attribute if it already exists.
	if ( auto_sizes_attribute_includes_auto( $sizes ) ) {
		return $html;
	}

	$processor->set_attribute( 'sizes', "auto, $sizes" );
	return $processor->get_updated_html();
}
```

This not only provides a better DX, but it is safer and ensures the result is correct. It's being [used increasingly throughout core](https://github.com/search?q=repo%3AWordPress%2FWordPress%20%2Fnew%20WP_HTML_Tag_Processor%2F&type=code) as this is its intended purpose. We're also using it in our Performance plugins:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/auto-sizes/hooks.php#L122-L141

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/auto-sizes/hooks.php#L153-L157

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/webp-uploads/picture-element.php#L84-L89

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/webp-uploads/hooks.php#L542-L562

# Test Cases

Here are some cases where the current implementation breaks. Some of them rely on attribute values being single-quoted, and it's true that core only emits double quotes for attribute values. However, images can come from other places than core. For example, these snippets can be pasted in a Custom HTML block to reproduce the problems. Problematic attribute modifications could also come from plugin filters. Additionally, images may come from Embed blocks. (Aside: I just discovered that if I have these four images in Custom HTML blocks and then put a Flickr embed as the 5th block, core's heuristics are incorrectly adding `fetchpriority=high` to this image from Flickr since it apparently doesn't count the images in the Custom HTML blocks.)

Incorrectly not adding `auto` when it should be present due to the use of single quotes:

```html
<img
    src='https://pd.w.org/2024/08/36566abfcb2952e20.99062056-300x225.jpg'
    srcset='https://pd.w.org/2024/08/36566abfcb2952e20.99062056-300x225.jpg 300w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-1024x768.jpg 1024w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-768x576.jpg 768w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-1536x1152.jpg 1536w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-2048x1536.jpg 2048w'
    sizes='(max-width: 650px) 100vw, 650px'
    loading='lazy'
>
```

Incorrectly prefixing a `data-tshirt-sizes` attribute with `auto` and duplicating `auto` on an existing `sizes` attribute:

```html
<img
    data-tshirt-sizes="S M L"
    src="https://pd.w.org/2024/08/36566abfcb2952e20.99062056-300x225.jpg"
    srcset="https://pd.w.org/2024/08/36566abfcb2952e20.99062056-300x225.jpg 300w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-1024x768.jpg 1024w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-768x576.jpg 768w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-1536x1152.jpg 1536w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-2048x1536.jpg 2048w"
    sizes="auto, (max-width: 650px) 100vw, 650px"
    loading="lazy"
>
```

Incorrectly adding `auto` due to `loading="lazy"` appearing in an attribute value:

```html
<img
    src="https://pd.w.org/2024/08/36566abfcb2952e20.99062056-300x225.jpg"
    srcset="https://pd.w.org/2024/08/36566abfcb2952e20.99062056-300x225.jpg 300w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-1024x768.jpg 1024w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-768x576.jpg 768w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-1536x1152.jpg 1536w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-2048x1536.jpg 2048w"
    sizes="(max-width: 650px) 100vw, 650px"
    alt='This is the LCP image and it should not get loading="lazy"!'
>
```

Incorrectly adding `auto` for an eager-loaded image when there is a `data-removed-loading="lazy"` attribute:

```html
<img
    src="https://pd.w.org/2024/08/36566abfcb2952e20.99062056-300x225.jpg"
    srcset="https://pd.w.org/2024/08/36566abfcb2952e20.99062056-300x225.jpg 300w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-1024x768.jpg 1024w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-768x576.jpg 768w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-1536x1152.jpg 1536w, https://pd.w.org/2024/08/36566abfcb2952e20.99062056-2048x1536.jpg 2048w"
    sizes="(max-width: 650px) 100vw, 650px"
    data-removed-loading="lazy"
>
```

All of these cases are fixed by using the HTML Tag Processor.

Other scenarios from @dmsnell in https://github.com/WordPress/performance/pull/1445#discussion_r1710076536:

> * the `sizes` attribute could be in any case, but this only tests for all-lowercase matches
> * the `sizes` attribute could have single quotes, or no quotes, and have whitespace around the equals sign, e.g. `Sizes = Auto`
> * the `sizes` attribute _must_ be preceded by whitespace or a `/`, but this test also matches `data-sizes="unrelated attribute"`

**Comment by joemcgill** [comment]
I like this idea and would like to see the performance impact of this change (though I know that's not the goal).

**Comment by westonruter** [comment]
Comment moved to https://github.com/WordPress/performance/issues/1475.

<details><summary>Original Comment</summary>

I just realized a case where this drafted code using HTML Tag Processor might not work as expected, and that is specifically in relation to the `PICTURE` element output by Modern Image Formats. Enhanced Responsive Images is adding the `auto` value at priority 10 of the `wp_content_img_tag` filter:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/auto-sizes/hooks.php#L79

However, Modern Image Formats is also using this same filter and priority to rewrite the `IMG` as `PICTURE`:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/webp-uploads/hooks.php#L769

Since the `auto-sizes` slug is alphabetically before `webp-uploads`, then it seems the `auto` value is injected first so that when the `PICTURE` is generated by Modern Image Formats, it has `auto` in all the `sizes` attributes as expected. However, this seems brittle. To be even more robust, it seems the HTML Tag Processor code here should be updated to support adding `auto` to the `SOURCE` tags. Otherwise, the priorities of the filters could be made distinctly different, either having `auto_sizes_update_content_img_tag()` run at a priority below 10 or have `webp_uploads_wrap_image_in_picture()` run at a priority over 10.

Nevertheless, take note that Enhanced Responsive Images also has a `wp_content_img_tag` filter that runs at priority 9, so it would need to be bumped down to priority 8 if we go in that direction:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/auto-sizes/hooks.php#L226

Lastly, Image Placeholders is also filtering `wp_content_img_tag` but at priority 20:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/dominant-color-images/hooks.php#L166

I was worried that this would mean that `PICTURE` elements generated by Modern Image Formats would be broken with Image Placeholders. But this doesn't seem to be the case. Example image with picture element turned off:

```html
<img
  data-dominant-color="8c7d58"
  data-has-transparency="false"
  style="--dominant-color: #8c7d58"
  fetchpriority="high"
  decoding="async"
  width="1024"
  height="668"
  src="http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp"
  alt=""
  class="not-transparent wp-image-13"
  srcset="
    http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp 1024w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-300x196-jpg.webp   300w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-768x501-jpg.webp   768w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-1536x1002.jpg     1536w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-2048x1336.jpg     2048w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-1568x1023.jpg     1568w
  "
  sizes="(max-width: 650px) 100vw, 650px"
/>
```

And with picture element turned on:

```html
<picture
  class="not-transparent wp-picture-13"
  style="--dominant-color: #8c7d58; display: contents"
  ><source
    type="image/webp"
    srcset="
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp 1024w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-300x196-jpg.webp   300w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-768x501-jpg.webp   768w
    "
    sizes="(max-width: 650px) 100vw, 650px" />
  <source
    type="image/jpeg"
    srcset="
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668.jpg 1024w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-300x196.jpg   300w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-768x501.jpg   768w
    "
    sizes="(max-width: 650px) 100vw, 650px" />
  <img
    data-dominant-color="8c7d58"
    data-has-transparency="false"
    fetchpriority="high"
    decoding="async"
    width="1024"
    height="668"
    src="http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp"
    alt=""
    class="not-transparent wp-image-13"
    srcset="
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp 1024w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-300x196-jpg.webp   300w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-768x501-jpg.webp   768w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1536x1002.jpg     1536w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-2048x1336.jpg     2048w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1568x1023.jpg     1568w
    "
    sizes="(max-width: 650px) 100vw, 650px"
/></picture>
```

This is still working. Interestingly, the result is `--dominant-color: #8c7d58;` appearing on the `PICTURE` tag whereas `data-dominant-color` and `data-has-transparency` remain on the `IMG` tag. This is because we added `style="display:contents;"` to the `PICTURE` in #1307, so Image Placeholders is accidentally amending the `style` attribute on the `PICTURE` tag as oppose to adding/updating the `style` attribute on the `IMG` tag:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/dominant-color-images/hooks.php#L143-L147

Fortunately this didn't break anything, but we just got lucky. We should update Image Placeholders to use the HTML Tag Processor too to be more reliable/consistent.

</details>

**Comment by mukeshpanchal27** [comment]
Assign my self to finish the work for Enhanced Responsive Images.
