### ISSUE TITLE
Speculative Loading readme needs improvement

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1459]
## Feature Description

See feedback from @felixarntz in https://github.com/WordPress/performance/pull/1155#pullrequestreview-2222128866

A [Google Doc](https://docs.google.com/document/d/1cQQG7WUCJolqwdWHSIuj1D05AFHLCdaPUIA1uyNJk0g/edit?usp=drivesdk&resourcekey=0-7L9olr8TFD2oPzw701Warg) has been shared for collaboration.

**Comment by felixarntz** [comment]
I added some references and one concrete wording suggestion to the readme in the doc. Let me know what you think!

**Comment by westonruter** [comment]
Looks like this won't land in time for Monday's release. Since it's the only substantive user-facing change in plugin's milestone, I'm not planning to do a release for this plugin on Monday. I've removed the milestone's due date from being set to Monday.

**Comment by felixarntz** [comment]
This got stalled a bit, apologies. I just took a fresh look at the [readme doc](https://docs.google.com/document/d/1cQQG7WUCJolqwdWHSIuj1D05AFHLCdaPUIA1uyNJk0g/edit) and added a few more suggestions.

Let's keep using suggestions (without approving them) so that it's easy to spot the changes and paste them back into the `readme.txt` file later.

I'd appreciate another review from you @tunetheweb @westonruter.

**Comment by westonruter** [comment]
@felixarntz I added a few more suggestions/comments! But it's looking close.

**Comment by felixarntz** [comment]
@westonruter Just reviewed, and made 2 more small suggestions, but at this point, all suggestions that are on there look good to me.

I think there's enough benefit to these updates to move forward and already update the readme, despite an outstanding comment on https://docs.google.com/document/d/1cQQG7WUCJolqwdWHSIuj1D05AFHLCdaPUIA1uyNJk0g/edit?resourcekey=0-7L9olr8TFD2oPzw701Warg&disco=AAABNWfek_c.

I'll open a PR with the changes later today or tomorrow, we could still follow up with any further updates if needed.

**Comment by westonruter** [comment]
Great. Once you've opened that PR and then it and #1636 are merged, we can commit those readme updates to SVN.
