### ISSUE TITLE
Option Page now completely broke without remote access

### ISSUE THREAD

**Issue by chimok** [WordPress/performance#1473]
## Steps to reproduce

1. Upgrade plugin to 3.3.1
2. Visit Plugin option page

## Screenshots
![image](https://github.com/user-attachments/assets/633731ba-4a69-412f-b7be-bf2da6be93c7)

## Additional Context

> Due to your site's configuration, you may not be able to activate the performance features, unless the underlying plugin is already installed. Please install the relevant plugins manually.

There is nothing wrong with our server configuration. There is something wrong with your plugin.
We don't want the website is calling home, that's why we disable any remote request. And we don't need then, because we're using a composer based setup and update/install everything in our local DEV system.

It should be still possible to change plugin options, but now i can't do anything.

 - PHP Version: 8.2
 - Plugin Version: 3.3.1

**Comment by swissspidy** [comment]
Thanks for your report, that's certainly not a great experience. We shouldn't be cluttering the admin page if we can't fetch information about the plugins recommended/used by Performance Lab.

Which of the few Performance Lab plugins do you have installed?

How are you disabling remote requests?

**Comment by chimok** [comment]
@swissspidy  I use `pre_http_request`, it worked well with the previous version. I use only modern images (former webp uploads)

```php
/**
 * Block external WordPress API request
 */
function vdplug_api_block_request($pre, $args, $url)
{
    if (strpos($url, 'wordpress.org')) {
        return true;
    } else {
        return $pre;
    }
}
add_filter('pre_http_request', 'vdplug_api_block_request', 10, 3);
```

**Comment by westonruter** [comment]
@chimok Note that this screen includes no plugin options, other than to facilitate installation and activation of the standalone plugins:

![image](https://github.com/user-attachments/assets/25630014-3885-480c-be6f-d8813b8ea62e)

All of the Settings links simply point to the plugins' respective settings screens in the admin. They are also accessible via Settings links in the plugin list table, for example:

![image](https://github.com/user-attachments/assets/2e0fa29e-dd2f-47f3-b4b0-8a09ba638d2a)


I've opened #1474 to improve the error message on the Performance screen.

**Comment by vegetable-bits** [comment]
@westonruter @mukeshpanchal27 The problem is back with 4.0.0.

<img width="1152" height="333" alt="Image" src="https://github.com/user-attachments/assets/01cebced-dd7b-4d64-a976-213c7ccbd61f" />

**Comment by westonruter** [comment]
@vegetable-bits Where is your site hosted where you're experiencing this issue?

The issue could also be a temporary network issue.

**Comment by vegetable-bits** [comment]
@westonruter It's a private company server, I do simply not allow external connections.

You see I have 4 plugins (active), I can configure the plugins like webp-uploads in their plugin settings. But if you could show the settings in performance plugin if a plugin is already active, that would be so much more convenient. There's no reason for remote connection if the plugin is install and active.

**Comment by westonruter** [comment]
@vegetable-bits Thanks, I've opened #2189 to track this.

In any case, the problem is not back as was originally reported for this issue. It's a different issue, because you are blocking external requests.
