### ISSUE TITLE
Unminified source JS files and source maps are not distributed with builds

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1493]
I just realized that when doing a production build of a plugin, the JavaScript is getting minified (which is good) but there is no unminified version which is also being distributed. When `SCRIPT_DEBUG` is enabled, the unminified dev version of scripts should be used instead. Additionally, when using the minified version it would be great if a source map could connect it to the unminified version.

As it stands, the only JS distributed with Optimization Detective is the minified versions: 

- https://plugins.trac.wordpress.org/browser/optimization-detective/tags/0.5.0/detect.js
- https://plugins.trac.wordpress.org/browser/optimization-detective/tags/0.5.0/build/web-vitals.js

**Comment by adamsilverstein** [comment]
This one would be a good ticket to work on at WCUS contributor day.

**Comment by westonruter** [comment]
@adamsilverstein Unassigning as I assume the assignment was specifically for the sake of your leading the WCUS Contributor Day.

**Comment by ShyamGadde** [comment]
Hi, could this issue be assigned to me? I'd like to work on it. Thanks!
