### ISSUE TITLE
Detection time window may not allow enough URL Metrics to be collected

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1496]
Originally in https://github.com/WordPress/performance/issues/1494#issuecomment-2305825246.

I discovered on my blog that I had a very old URL Metric from before the XPath indices were fixed to be 1-based instead of 0-based (#1191). Looking at the URL Metric data, I see the timestamp is `1712354502.752218` which is for a day back in April. It appears that URL Metrics are not being collected frequently enough, or my site is truly devoid of traffic. I think for my site it may be in part due to page caching, where the detection time window (`od_detection_time_window`) is too short, so it is only collecting metrics for visitors who happen to visit when there is a MISS to the page cache, and if there is a stale-while-revalidate caching strategy going on with Varnish then it is even more likely for the visitor to never be within the detection time window (`currentTime - serveTime > detectionTimeWindow`):

https://github.com/WordPress/performance/blob/f8dad3497f6240e2975733c3b277e91e35b254a6/plugins/optimization-detective/detect.js#L179-L187

I think this logic needs to be revisited.

**Comment by felixarntz** [comment]
Related is a conversation @westonruter and I had at WordCamp US: To reliably handle dynamic behavior on the client-side, the behavior needs to be controlled by the client-side, to account for full page caches which will lead to most requests not to reach the PHP logic. This basically means two things:
* We need to inject the script, or at least a very minimal version of the script, unconditionally, because we can't know from the server-side whether the current request needs the detection to run (e.g. if it never hits the PHP process).
* We need to retrieve data that is dynamic in another way, it is not reliable to inline it with the script. Some data that is specific to the current URL (e.g. `urlMetricsSlug`) or a general configuration setting (e.g. `storageLockTTL`) is probably okay to inline, but most other data (e.g. `urlMetricsGroupStatuses`) will get out of date when a full page cache is used. Such data would probably need to come from a REST endpoint instead.

Defining the right solution for this probably goes beyond this issue, maybe we should open a new one, that is more broadly about how to support full page caches in a way that the Optimization Detective functionality is still reliable? I think prioritizing this will be crucial to get broader adoption, as lots of sites use a full page cache which will affect the behavior negatively - sometimes minor, sometimes more severely, depending on the cache configuration.

**Comment by westonruter** [comment]
Here is a table for what I've found the default max-age to be for caching plugins:

Plugin Name | Default Max-Age
--|--:
Batcache | [5 minutes](https://github.com/Automattic/batcache/blob/ed0e6b2d9bcbab3924c49a6c3247646fb87a0957/advanced-cache.php#L43C18-L43C21)
Pantheon Advanced Page Cache v1 | [10 minutes](https://github.com/pantheon-systems/pantheon-advanced-page-cache/pull/269)
WP Super Cache | [30 minutes](https://github.com/Automattic/wp-super-cache/blob/73b428d2fce397fd874b3056ad3120c343bc1a0c/wp-cache.php#L4125)
W3 Total Cache | [1 hour](https://github.com/BoldGrid/w3-total-cache/blob/ab08f104294c6a8dcb00f1c66aaacd0615c42850/Util_PageSpeed.php#L799-L801)
Jetpack Boost | [1 hour](https://jetpack.com/support/jetpack-boost/caching-site-content/#:~:text=stays%20cached%20for-,1%20hour,-.%20This%20can%20be)
WP Rocket | [10 hours](https://docs.wp-rocket.me/article/1383-cache-lifespan#:~:text=The%20default%20value%20for%20Cache,See%20our%20related%20article.)
Pantheon Advanced Page Cache v2 | [1 week](https://github.com/pantheon-systems/pantheon-advanced-page-cache/blob/e3b5552b0cb9268d9b696cb200af56cc044920d9/inc/admin-interface.php#L586-L587)
LightSpeed Cache | [1 week](https://docs.litespeedtech.com/lscache/lscwp/cache/#default-public-cache-ttl)
WP Fastest Cache | None. Requires [Timeout](https://www.wpfastestcache.com/features/cache-timeout-page/) rule config.

**Comment by westonruter** [comment]
I've been tackling this problem in the following sequential PRs:

- #1637
- #1640 
- #1641

The first two remove what is specifically broken with page caching: nonces and the detection time window. The third begins to proactively address the problem of a page caching plugin holding onto an unoptimized cached page even after URL Metrics have been submitted by visitors and the corollary problem of the inline script data not being up-to-date.

By ensuring that page caching plugins flush the caches for cached URLs which have updated URL Metrics, then we _can_ actually rely on the inline script to be relatively up-to-date on the needs for URL Metrics. We may not need to move the `urlMetricsGroupStatuses` data to a new REST API endpoint, which itself could be subject to page caches holding onto the data for too long and so it may not be fresh.

**Comment by westonruter** [comment]
Ideas discussed with @felixarntz:

* To deal with the page cache stampede problem, we can schedule the clearing of the cache for a URL periodically via WP Cron. (This is addressed in https://github.com/WordPress/performance/pull/1641.)
* Do we add an endpoint for getting the which URL Metrics are needed. The problem is that the endpoint cache wouldn't be reliably flushed. But if it were reliably flushed, 
* Check what happens when there is a race condition between two requests to store a URL Metric from two application servers connected to the same database when there wasn't a `od_url_metrics` post that already existed.
* Do we need a lock or throttling mechanism? 
* When a persistent object cache is available, perhaps the POST request would only write to the object cache and then WP Cron would read from the object cache to actually create the URL Metrics posts.

I just looked at LightSpeed Cache and they purge caches in response to the [`transition_post_status` action](https://github.com/litespeedtech/lscache_wp/blob/7c707469b3c88b4f45d9955593b92f9aeaed54c3/src/purge.cls.php#L68). Similar to Pantheon Advanced Page Cache with its surrogate keys, LightSpeed Cache [constructs](https://github.com/litespeedtech/lscache_wp/blob/7c707469b3c88b4f45d9955593b92f9aeaed54c3/src/purge.cls.php#L1147-L1276) a list of purge tags which correspond to the list of tags [constructed](https://github.com/litespeedtech/lscache_wp/blob/7c707469b3c88b4f45d9955593b92f9aeaed54c3/src/tag.cls.php#L229-L313) when a page is served. Notably there is a tag for post type archives. With such sophisticated surrogate keys employed by caching (in Varnish) it's safer to have longer cache TTLs since it is less likely stale content will persist. Pantheon Advanced Page Cache also [accounts](https://github.com/pantheon-systems/pantheon-advanced-page-cache/blob/e3b5552b0cb9268d9b696cb200af56cc044920d9/inc/class-emitter.php#L283-L293) for post type archives.

**Comment by westonruter** [comment]
I've filed https://github.com/WordPress/performance/issues/1655 to address the points raised in https://github.com/WordPress/performance/issues/1496#issuecomment-2471868739.
