### ISSUE TITLE
Convert all images to WebP or AVIF regardless of the file size output 

### ISSUE THREAD

**Issue by jamesozzie** [WordPress/performance#1510]
## Feature Description

At present the plugin will generate a WebP or AVIF version of an image but only if the new image is lower in file size. Consider a filter or an option to ensure all images are converted, regardless of the file size output. 

This is based on a user query in the support forums: https://wordpress.org/support/topic/convert-to-webp-even-if-larger-than-original-file/

**Comment by mukeshpanchal27** [comment]
@jamesozzie We already have the filter `webp_uploads_discard_larger_generated_images` that disables the file size check and ensures a WebP or AVIF version of the image is generated even if it's larger than the original.


```
add_filter( 'webp_uploads_discard_larger_generated_images', '__return_false' );
```

**Comment by jamesozzie** [comment]
Excellent! Good to know. Thanks @mukeshpanchal27. Closing.
