### ISSUE TITLE
Enable end user opt-in to generate all sizes in fallback format 

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#1513]
## Feature Description

As discussed in https://github.com/WordPress/performance/pull/1421 when "generate fallback images" is enabled, we only generate the core default sizes in the fallback format. The reasoning here is that users can have many sizes and generating all of the sub-sizes can require an unexpectedly large amount of storage for users. I am unsure about this so let's give users the _option to generate all sizes_.

This proposal is to add a checkbox users can check right below the "generate fallback images" checkbox (and it would only be enabled when that checkbox is checked).  Similar the the generate fallback checkbox, the note would indicate this requires even more disk space.

Something like:

```
 - [ ] **Generate fallback images in all sizes including custom sizes** 
 * Note: uses even more storage space.
```

Ideally when users enable this feature we should notate that in the Generator tag so we can later discover how many sites opt into generating all image sizes.

**Comment by b1ink0** [comment]
Hi, I am interested in working on this issue can it be assigned to me.

**Comment by b1ink0** [comment]
@adamsilverstein @felixarntz 

I was trying to implement the required feature but I am facing confusion about the `generate all sizes` option.

Currently if I add these custom sizes 
```php
add_image_size( 'custom_size_1', 400, 400, true );
add_image_size( 'custom_size_2', 800, 800, true );
add_image_size( 'custom_size_3', 1200, 1200, true );
```

When the `output fallback images` is enabled these are the images generated for a demo img.
![Image](https://github.com/user-attachments/assets/ae7478d3-9e8c-486f-8dc3-8bf11bdd87a7)

When the new proposed `output all fallback images` is enabled are these the images that should be generated?
![Image](https://github.com/user-attachments/assets/531c8c0b-6a17-4a07-80a6-5040d81bac14)

**Comment by felixarntz** [comment]
@b1ink0 Yes, that's correct. If the new option is enabled, all existing image sizes should receive a converted file in the modern image formats, whereas the default only covers the WordPress Core built-in sizes.
