### ISSUE TITLE
Post is not being published

### ISSUE THREAD

**Issue by rhmunna143** [WordPress/performance#1523]
## Bug Description
![image](https://github.com/user-attachments/assets/84da95ed-ddb3-4c0c-a45f-abd3484e4d61)
This is saying publishing and publishing, or auto-saving and auto-saving but this state is not finishing. This happened after the last WordPress update (6.6.1).

## Steps to reproduce

1. Go to 'new post'
2. Click on 'Publish post'

## Screenshots
![image](https://github.com/user-attachments/assets/fa481071-7a33-4a9e-a696-d3f272d7ac3a)

![image](https://github.com/user-attachments/assets/42a0367e-9c74-4edb-8938-7eaa75d4d923)

## Additional Context

 - PHP Version: 8.1.27
 - OS: W11
 - Browser:  Chrome

**Comment by swissspidy** [comment]
Hi there

As this is not related to performance or the Performance Lab suite of plugins, please ask for help in the support forums at https://wordpress.org/documentation/
Common tips include temporarily deactivating all plugins to see if the issue still occurs.
