### ISSUE TITLE
Update auto sizes logic in Enhanced Responsive Images plugin to no longer load if already in Core

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#1531]
Per the core code being merged in https://core.trac.wordpress.org/changeset/59008, we need to modify the Enhanced Responsive Images plugin to ensure the relevant logic is only loaded if not already available in Core, for compatibility with the upcoming 6.7 release.

Maybe a good way would be to check for existence of the `wp_sizes_attribute_includes_valid_auto()` function?

We still have some time to do that, but good to have an issue already. We could get started on this at any point prior to the WP 6.7 release.

**Comment by felixarntz** [comment]
cc @joemcgill @mukeshpanchal27

**Comment by joemcgill** [comment]
💥 I was just having this thought after committing https://core.trac.wordpress.org/changeset/59008. Thanks for opening this.
