### ISSUE TITLE
Fix failing tests with WordPress `trunk`

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#1532]
## Bug Description

See e.g. https://github.com/WordPress/performance/actions/runs/10820446352/job/30020524054?pr=1492: The PHPUnit tests fail, but that's entirely independent of that PR.

It looks like these failures are because we're looking at the _exact_ `img` tag markup for the "Modern Image Formats" plugin, which of course was changed as of [committing `sizes="auto"` to Core](https://core.trac.wordpress.org/changeset/59008).

## Steps to reproduce

You should see those failures as soon as you open any PR, or run unit tests locally against WordPress trunk.

**Comment by felixarntz** [comment]
@adamsilverstein @mukeshpanchal27 @joemcgill Could one of you please take a look at this, so we can unblock other PRs with these failing tests?

**Comment by westonruter** [comment]
PR with fix: https://github.com/WordPress/performance/pull/1533
