### ISSUE TITLE
Use a single WordPress.org API request to get plugin information

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#1542]
Currently, the Performance features screen makes individual `plugin_information` queries to the WordPress.org API, which is rather inefficient, especially the more plugins we have. We can enhance this by instead using a single request as follows:
```
https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request[author]=wordpressdotorg&request[per_page]=100
```

While the WordPress.org Plugins API does not support passing multiple specific slugs (which would be ideal), this is a decent workaround: Since all our plugins use the `wordpressdotorg` author, we can safely assume our plugins are included in that list.

This will obviously return many other plugins too, but we'd be able to filter out just the plugins we care about. While this request returns too much data, it's still far more efficient than making all those individual requests.

**Comment by lecapitainenemo** [comment]
Hi! I’d like to take on this issue. If there are any specific requirements or additional context I should know about, please let me know. I read the code of conduct and the section on coding standards.
Thank you!

**Comment by mukeshpanchal27** [comment]
If we query only by the author, it will return `64` plugins. In the future, this number is likely to exceed `100`, meaning we needs to update the limit.

```
https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request[author]=wordpressdotorg&request[per_page]=100
```

However, if we also include the `performance` tag in the query parameters, it will narrow down the results to `11` plugins, ensuring that all our plugins are listed since we use the `performance` tag for all plugins developed by the Performance Team.

```
https://api.wordpress.org/plugins/info/1.2/?action=query_plugins&request[author]=wordpressdotorg&request[tag]=performance&request[per_page]=100
```

**Comment by felixarntz** [comment]
@mukeshpanchal27 That's a great idea, thank you for exploring this further.
