### ISSUE TITLE
Convert WebP to AVIF on upload

### ISSUE THREAD

**Issue by phanduynam** [WordPress/performance#1557]
Modern Image Formats 2.2.0 does not support converting uploaded WebP files to AVIF

**Comment by mukeshpanchal27** [comment]
Thanks, @phanduynam, for raising this issue.

Currently the plugin didn't added support for WebP to AVIF image but in future if possible we can add it.

cc. @adamsilverstein

**Comment by phanduynam** [comment]
@mukeshpanchal27 Thanks, I'm looking forward to this.

**Comment by adamsilverstein** [comment]
> Currently the plugin didn't added support for WebP to AVIF image but in future if possible we can add it.

This should be a relatively small change. No new UI is needed, if the selected output format is AVIF and users upload a WebP we can convert them.

> @mukeshpanchal27 Thanks, I'm looking forward to this.

@phanduynam I'm curious about your use case / why you have WebP's you are trying to upload in the first place. It makes sense to "upgrade" to AVIF, but I thought most users would be coming from JPEGs.

**Comment by phanduynam** [comment]
> > Currently the plugin didn't added support for WebP to AVIF image but in future if possible we can add it.
> 
> This should be a relatively small change. No new UI is needed, if the selected output format is AVIF and users upload a WebP we can convert them.
> 
> > [@mukeshpanchal27](https://github.com/mukeshpanchal27) Thanks, I'm looking forward to this.
> 
> [@phanduynam](https://github.com/phanduynam) I'm curious about your use case / why you have WebP's you are trying to upload in the first place. It makes sense to "upgrade" to AVIF, but I thought most users would be coming from JPEGs.

I'm doing a website crawl, there will be webp images, but I want them all converted to avif. Simple as that

**Comment by mukeshpanchal27** [comment]
> > Currently the plugin didn't added support for WebP to AVIF image but in future if possible we can add it.
> 
> This should be a relatively small change. No new UI is needed, if the selected output format is AVIF and users upload a WebP we can convert them.

This change fix the WebP to AVIF transforms.

```php
diff --git a/plugins/webp-uploads/helper.php b/plugins/webp-uploads/helper.php
index 7669154b..d4a5047b 100644
--- a/plugins/webp-uploads/helper.php
+++ b/plugins/webp-uploads/helper.php
@@ -28,7 +28,7 @@ function webp_uploads_get_upload_image_mime_transforms(): array {
 
        $default_transforms = array(
                'image/jpeg' => array( 'image/' . $output_format ),
-               'image/webp' => array( 'image/webp' ),
+               'image/webp' => array( 'image/' . $output_format ),
                'image/avif' => array( 'image/avif' ),
                'image/png'  => array( 'image/' . $output_format ),
        );
```

**Comment by phanduynam** [comment]
@adamsilverstein I would like to know if this add-on applies to the 18/11 update?

**Comment by adamsilverstein** [comment]
> This change fix the WebP to AVIF transforms.

That change makes sense @mukeshpanchal27, since the user has explicitly selected AVIF output. Can you open a PR with that change?
