### ISSUE TITLE
Cannot view Avif images on browser

### ISSUE THREAD

**Issue by phanduynam** [WordPress/performance#1558]
In the current Modern Image Formats 2.2.0 plugin I am facing the following issue. For example when I set the conversion to webp format, I can view http://nam.000.pe/wp-content/uploads/2024/09/sm_1726654680855lQMvXjTOjU-1-jpg.webp directly in the browser. But when I set the conversion to avif format, when I click on the url http://nam.000.pe/wp-content/uploads/2024/09/sm_1726654680855lQMvXjTOjU-jpg.avif I cannot view the image in the browser but instead download the image to my computer. It is confusing.

**Comment by mukeshpanchal27** [comment]
Thanks, @phanduynam, for raising this issue.

When I tested the AVIF image on my local server, it worked fine in the browser. However, when I tried to access the AVIF image from the URL you provided, I received the following notice from the browser. It seems to be related to your domain or hosting setup. I'm not entirely sure, but it's working fine on my end.

<img width="616" alt="Screenshot 2024-09-24 at 9:49 AM" src="https://github.com/user-attachments/assets/81a496bc-6e94-42f3-92db-fea44796822b">

**Comment by phanduynam** [comment]
@mukeshpanchal27 Can you tell me your avif image url?

**Comment by mukeshpanchal27** [comment]
@phanduynam I checked in local server but you can check [this url](https://www.fabiobernini.it/wp-content/uploads/2024/09/pdfgear-jpg.avif).

**Comment by phanduynam** [comment]
@mukeshpanchal27 My server uses ImageMagick 7.1.1-19 and LibGD 2.3.3 image processing component, after I tried to load an original avif image, this phenomenon still occurs, so the problem must be on the server side. I think jminhf will change to another web server. Thank you for your support.

**Comment by mukeshpanchal27** [comment]
Thanks!
