### ISSUE TITLE
Why is the original image still saved after converting to a modern image format?

### ISSUE THREAD

**Issue by phanduynam** [WordPress/performance#1559]
As you can see, I converted to modern image format but why is the original image still saved? Doesn't that make the memory heavier? In the plugin settings, I also don't check the "Output fallback images" box, I think this box is to keep the original image, right?

![image](https://github.com/user-attachments/assets/15ec51f2-eee7-415f-9d85-735f2678087c)
![image](https://github.com/user-attachments/assets/a5ed84a9-5c35-4343-8938-dbd5bbd95114)

**Comment by mukeshpanchal27** [comment]
Thanks, @phanduynam, for raising this issue.

The original image will always present as mention in plugin description. we can use it for future thumbnail generation as the additional mime didn't support it.

> – only the original uploaded file will still exist as a JPEG/PNG image

@adamsilverstein @westonruter better to add note in plugin description for this. WDYT?

**Comment by phanduynam** [comment]
@mukeshpanchal27 Thanks for explaining

**Comment by phanduynam** [comment]
@mukeshpanchal27 Do you know why the original image is still stored on the server but not showing in the media section in WordPress?

**Comment by swissspidy** [comment]
That's by design, we don't want to show duplicate entries for every image you upload to the media library.

**Comment by phanduynam** [comment]
> That's by design, we don't want to show duplicate entries for every image you upload to the media library.

Thank you
