### ISSUE TITLE
Support for `wp_cache_delete_group`

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#156]
## Feature Description

Some of the benefits of having a function like `wp_cache_delete_group` 

- Align with #77 
- Purge a full group when a post is updated/deleted/added
- Quickly manage cache state by just grouping those cache mechanism

The function would allow a developer to remove all the entries associated with that particular group key, so a full cache group can be cleaned up. 

 
LInks:

- Existing core ticket: https://core.trac.wordpress.org/ticket/4476

**Comment by tillkruss** [comment]
We do have an issues for that: https://github.com/WordPress/performance/issues/38

**Comment by mitogh** [comment]
Fantastic, closing this one as a duplicate :)
