### ISSUE TITLE
Improve video poster image URL based on actual dimensions

### ISSUE THREAD

**Issue by swissspidy** [WordPress/performance#1575]
## Feature Description

On [my recent blog post](https://pascalbirchler.com/web-ai-wordpress/) just noticed that my videos are as wide as the content width, but the poster image is still the full size URL. This could be improved by using a more appropriate image size. The `video[poster]` attribute doesn't support `srcset` or anything, so this needs to be done differently.

We could:

1. Detect width of the video
2. Check the poster URL and get the attachment ID from that URL
3. Get a smaller sized version of that image and use that as the poster instead.

@westonruter Something for Optimization Detective?

@joemcgill @mukeshpanchal27 Something that could perhaps also be done with the thing you're looking into where we take a block's layout into account for image sizes?

**Comment by westonruter** [comment]
@swissspidy Yeah, we could use Optimization Detective to determine the widest possible width for the `video` element and then use that width to pick the image size. For smaller viewport widths the poster image size would still be too large, but at least it wouldn't be the full size.

**Comment by westonruter** [comment]
As with https://github.com/WordPress/performance/issues/1183, I think this makes sense as part of the Image Prioritizer plugin. Let's see if we can get merged https://github.com/WordPress/performance/pull/1498 quickly so you can build on it perhaps.
