### ISSUE TITLE
Improve autoplay for videos outside initial viewport

### ISSUE THREAD

**Issue by swissspidy** [WordPress/performance#1590]
This is a follow-up to #1498 /  #1183

[`autoplay` takes precedence over `preload`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#preload). When we know that a video is not in the initial viewport, we could remove `autoplay` in favor of an `IntersectionObserver`-based implementation that only autoplays the video when actually visible.

Related to #1035 which involves `IntersectionObserver` to lazy-load background images.

**Comment by westonruter** [comment]
Also related, we can lazy-load the `poster` image when video enters the viewport: #1591.

**Comment by westonruter** [comment]
Conversely, as I've noted now in the description of https://github.com/WordPress/performance/issues/1592:

> When a video is in all initial viewports, it should probably get `preload=auto` especially when it is the LCP element. ~It may even make sense to add `fetchpriority=high` preload links when it is the LCP element, particularly when the video has `autoplay`.~
