### ISSUE TITLE
Poster images for videos outside viewport should be lazy-loaded

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1591]
When a `VIDEO` with a `poster` is outside the viewport, the `poster` image will be downloaded with a medium priority even though the element is not visible:

> ![Image](https://github.com/user-attachments/assets/1e758349-88dd-43a6-872c-c516b787c32d)

This being the case, the `poster` should ideally be lazy-loaded when the video nears the viewport using `IntersectionObserver`.

Related:

* https://github.com/WordPress/performance/issues/1590
* https://github.com/WordPress/performance/issues/1035

**Comment by westonruter** [comment]
As noted in https://github.com/WordPress/performance/issues/10#issuecomment-2415176375, the `video` element's initial dimensions are set to match the `poster` image's intrinsic dimensions when no `width` and `height` are specified. However, if we are setting the `width` and `height` based on gathered client-side metrics, lazily-supplying the `poster` shouldn't cause any layout shift.

**Comment by swissspidy** [comment]
This would be a big win. Even with `preload=none`, the browser always downloads the poster image right now, even if it's way outside the viewport.
