### ISSUE TITLE
Add Wappalyzer detection for Web Worker Offloading plugin

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#1597]
## Feature Description

Now that https://wordpress.org/plugins/web-worker-offloading/ is live, we should add Wappalyzer detection for it.  Opening this issue to track that work.

I noticed we didn't include a generator tag in this plugin, should we go ahead and add that? 

Currently we could possibly detect usage with the `web-worker-offloading` path, but adding a generator tag would make detection cleaner. It might make sense to only add the generator tag when the worker strategy is actually used. 

cc: @westonruter

**Comment by westonruter** [comment]
Oh, woops. Not including a generator tag was an oversight. Let's add it.

**Comment by westonruter** [comment]
Since Web Worker Offloading is not yet featured in the Features screen in the latest version, there are very few installs of the plugin in the wild. This will change once we release the next version of PL, which would happen at the same time this meta tag from #1598 goes out.

**Comment by adamsilverstein** [comment]
> Oh, woops. Not including a generator tag was an oversight. Let's add it.

I'll create a sub-issue!

**Comment by westonruter** [comment]
@adamsilverstein I've opened #1598 to fix this already.

**Comment by adamsilverstein** [comment]
> I've opened [#1598](https://github.com/WordPress/performance/pull/1598) to fix this already.

Perfect, thanks! I can take care of adding the wappalyzer sniff

**Comment by adamsilverstein** [comment]
I submitted a PR to add the Wappalyzer sniff: https://github.com/HTTPArchive/wappalyzer/pull/71

**Comment by adamsilverstein** [comment]
PR was merged
