### ISSUE TITLE
Web Worker Offloading: add Generator tag

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#1599]
## Feature Description

Add a generator tag so this plugin can easily be identified in the wild.

Consider adding only when the worker strategy is used, or at least ensuring we have some way of detecting that to help make measuring impact more accurate.

**Comment by westonruter** [comment]
> Consider adding only when the worker strategy is used, or at least ensuring we have some way of detecting that to help make measuring impact more accurate.

Oh, I didn't account for this. To detect whether the functionality is being used, you can check to see if there are any scripts on the page that have the `text/partytown` type attribute.
