### ISSUE TITLE
Improve core image handling to support modern images

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#16]
* Use correct image engine for image type (https://github.com/adamsilverstein/modern-images-wp/issues/13) 

* Ensure images/feeds use compatible image formats - https://github.com/adamsilverstein/modern-images-wp/issues/25

**Comment by dainemawer** [comment]
@adamsilverstein apologies if this comment is not placed in the correct issue / PR but would it be feasible to handle alternative image formats as a query param on the image permalink? You see some CDN's manage it that way:

`<img src="https://cdn.com/images/image.jpg?format=webp">` - that way we could still make a request to the image, but perhaps return a `webp` version in the response as `image/webp`? Just spit balling!

**Comment by adamsilverstein** [comment]
I am closing this as "wontfix". We are already working on correctly showing the dropdown selection in the Modern Image Formats plugin and have some improvements to AVIF support detection planned for core.
