### ISSUE TITLE
Prepare PL 3.6 release

### ISSUE THREAD

**Issue by macka61** [WordPress/performance#1645]
This issue is to track preparation of the upcoming 3.6 release up until publishing, which is due November 18, 2024.

- [x]  Create release/3.6 branch closer to the release date
- [x]  Finalize scope and punt unfinished pull requests to following release
- [x]  Smoke test (Thursday, November 14, 2024)
- [x]  Prepare the release (Monday, November 18, 2024)

**Comment by felixarntz** [comment]
* Release branch created: https://github.com/WordPress/performance/tree/release/3.6.0
* All milestones for Monday's release are clear (except this issue of course):
    * [performance-lab 3.6.0](https://github.com/WordPress/performance/milestone/83)
    * [optimization-detective 0.8.0](https://github.com/WordPress/performance/milestone/82)
    * [webp-uploads 2.3.0](https://github.com/WordPress/performance/milestone/78)

We're a bit late this time around, but hopefully some more smoke testing can be done on Monday in the hours before the release.

**Comment by westonruter** [comment]
I opened a PR with the release preparations: https://github.com/WordPress/performance/pull/1657

It has [RC builds](https://github.com/WordPress/performance/pull/1657#issuecomment-2480632840) of the 3 plugins.
