### ISSUE TITLE
Create epic and overview github templates

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#165]
## Feature Description

Would it be possible to create GitHub issue templates for:

### Epic
To detail high-level projects, to include feature overview and a comprehensive list of all issues associated with that piece of work / epic
Headings to include:
- High level feature
- Overview
- Key enhancements (checklist of all issues)
- Exploration (checklist of all issues)
- Misc Bugs (checklist of all issues)
- Misc Enhancements (checklist of all issues)

### Overview
To provide a single point of reference for all documentation and materials related to each focus area
- Focus area overview
- Focus area documentation
- Issue specific documentation (referencing issues)

**Comment by eclarke1** [comment]
@felixarntz @adamsilverstein I chatted to @ThierryA about this one, and would like to suggest also amending our current [Type] Overview label to be for a single issue on each focus area and that issue to be a single point of reference for all documentation, including those 'Big Picture' docs, and any associated proposals for individual issues etc. 
Then we add a new label [Type] Epic to our high-level projects such as #22 
What do you think?

**Comment by mxbclang** [comment]
Assigning to myself to create new templates.
