### ISSUE TITLE
[Images] Overview

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#166]
### Point of Contact
@adamsilverstein @getsource 

### Focus Area Overview
To be added

### Key Documentation
- [Modern image format in WordPress](https://docs.google.com/document/d/1FuaHwJAmkObDCKR2PRaXODlfRVFRGTUtpDwXQtc24BM/edit?usp=sharing) document detailing 'Adding WebP support to WordPress core and preparing for other more progressive image formats' **AVAILABLE FOR COMMUNITY INPUT**

### Epics
Below is a comprehensive list of all high-level projects to be completed within the [Images] Focus Area:

- #22 
- #24 
- #21 
- #140 
- #11 

When creating new epics / high-level projects, please add to the list above.

#### Complete
- [Generating image sizes in multiple MIME types](https://docs.google.com/document/d/1nVFhMXacydGce1ZjSvh14MQeKPS26TcQDeIPw0vmuig/edit#) proposal for #142

#### Available for Community Input
- [The HTML5 Picture Element: WordPress](https://docs.google.com/document/d/1XX9QERfakIbE55oai5OmDzbDoxOtpo1aKAA7b0cUONs/edit?usp=sharing) proposal for #21 

#### Work In Progress
- [Analysis of existing plugins that convert to WebP](https://docs.google.com/document/d/18UdUoJnBnScwxRjMIEmCjN9h9aF6uJHHk2cMSwtlwMg/edit?usp=sharing) proposal for #160 
- [Responsive Image Enhancements](https://docs.google.com/document/d/14YH7AjXoHdCWR99DKbE7fZ6BsKecaGrOS78AD9UDO_s/edit?usp=sharing) proposal for #140 
- [WordPress core functions to be updated to support multiple mime types](https://docs.google.com/document/d/1CSi61ky0b9A84VOYkTXCE7wfl3QUSCtuHzF78T3t0CU/edit?usp=sharing) proposal for #155 

#### On Hold
- [Bulk Images Transformation](https://docs.google.com/document/d/1Wrf4K1x7rxHEaQsQ6OLiI4R05fahMikoy3znkETv9Q0/edit?usp=sharing) proposal for #24

**Comment by eclarke1** [comment]
@felixarntz @adamsilverstein my idea behind this, as discussed with @ThierryA , was to create a single issue for each focus area, detailing any high-level documents, list our individual epics / projects and also have a single point of reference for any associated proposals and their status. Please let me know thoughts here.
cc @bethanylang

**Comment by felixarntz** [comment]
@eclarke1 +1 from my perspective, I like the idea of having two types of overviews, one for the focus area and one for each project (within a focus area). The latter would then be named "epic" as far as I understand the suggestion, correct?

**Comment by eclarke1** [comment]
@felixarntz yep absolutely. Was thinking of using the `[Type] Overview` label for those focus area overviews, and a `[Type] Epic` for the projects within a focus area.
I have updated our epics within `[Images]` to have this labelling system. Question will be if we want to recommend using this format for other focus areas too. Up for discussion perhaps?
cc @bethanylang

**Comment by felixarntz** [comment]
@eclarke1 Given that we now have a [dedicated project board](https://github.com/orgs/WordPress/projects/116), I think we can close this issue in favor of that board?
