### ISSUE TITLE
Expose `source_url` for all additional mime types via REST API

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#167]
## Feature Description

WordPress already has a defined endpoint for each media item located at `wp-json/wp/v2/media/{ATTACHMENT_ID}` this ticket is to suggest the inclusion of additional mime types (if present) for that particular image beside the default mime type for an image, this would allow API consumers to have access to both image mime types using the REST API.

Another suggested approach could be to add a new query parameter to allow developers to request a specific mime type instead so the API would remain the same but with the difference that internally would query for the requested mime type if present and deliver those results back via the REST API.

This can be accomplished from within the plugin filtering `rest_prepare_attachment` to insert or update the response as need it. 

### Related issues

- #142 
- #150 
- #155

**Comment by adamsilverstein** [comment]
This would be a good one to collaborate on with @spacedmonkey.

**Comment by mitogh** [comment]
## Suggested approach

Include a new property `source_url` for every mime type inside of the `sources` property of each image size, currently, the 2 properties available are:

- `file`
- `filesize`

This property should have a full URL to access the image resource in the same way the top-level `source_url` property for the size is accessible. 

Every image size includes a dynamic property that is present only on the REST endpoint, this property is added dynamically for media attachment and contains the full URL to access to full URL of each image based on the size of an image.

The affected endpoint can be found at:

- `wp-json/wp/v2/media/ATTACHMENT_ID`

Expected behavior:

```diff
"thumbnail": {
  "file": "CJt-MthF9d8-150x150.jpeg",
  "width": 150,
  "height": 150,
  "sources": {
    "image/jpeg": {
      "file": "CJt-MthF9d8-150x150.jpeg",
      "filesize": 5856,
+     "source_url": "https://example.site/wp-content/uploads/2022/03/CJt-MthF9d8-150x150.jpeg"
    },
    "image/webp": {
      "file": "CJt-MthF9d8-150x150.webp",
      "filesize": 5270,
+     "source_url": "https://example.site/wp-content/uploads/2022/03/CJt-MthF9d8-150x150.webp"
    }
  },
  "mime_type": "image/jpeg",
  "source_url": "https://example.site/wp-content/uploads/2022/03/CJt-MthF9d8-150x150.jpeg"
},
```

This behavior should be replicated in all available image sizes, as the example above just describes one image size in particular _thumbnail_ image size. including the full image size, once #194  Is merged.

### Suggested steps to include the property.

1. Loop into all the available sizes for the attachment
2. If the size does not have a sources property
3. For every source property loop into every mime type
4. Create the `source_url` for the specified mime type with the `file` property.
5. If the top-level `metadata` for the attachment has a `sources` loop into every single mime type
6. Add the `source_url` property to every single mime type for the top-level API.

A possible place where the logic can hook into it is `rest_prepare_attachment`

- https://developer.wordpress.org/reference/hooks/rest_prepare_attachment/

**Comment by spacedmonkey** [comment]
Can you find some context on how the data is stored in post meta? @adamsilverstein

Currently I am seeing this structure. 
<img width="1267" alt="Screenshot 2022-03-02 at 11 12 52" src="https://user-images.githubusercontent.com/237508/156351249-903751f8-b152-4c78-9327-b9f441e64081.png">

For compatibility, I would not change the shape of this. I would do this

```
      "sizes": {
        "medium": {
          "file": "valery-fedotov-CqX6IhVj2TI-unsplash-600x337.jpg",
          "width": 600,
          "height": 337,
          "mime_type": "image/jpeg",
          "source_url": "https://assets.computingcorner.co.uk/uploads/sites/27/2022/01/valery-fedotov-CqX6IhVj2TI-unsplash.jpg"
        },
         "medium-webp": {
          "file": "valery-fedotov-CqX6IhVj2TI-unsplash-600x337.webp",
          "width": 600,
          "height": 337,
          "mime_type": "image/webp",
          "source_url": "https://assets.computingcorner.co.uk/uploads/sites/27/2022/01/valery-fedotov-CqX6IhVj2TI-unsplash.webp"
        },
```

To ensure no breakage with third party plugins. With this structure, it should simple enough to get data in the format you require.

**Comment by mitogh** [comment]
Example of the meta data @spacedmonkey from an image having multiple mime-types available 

```php
// slice of a metadata from an image  stored in `_wp_attachment_metadata`
array(
  // ...additional image sizes
  'medium'  => array (
    'file' => '7rMFIAVGlVg-240x300.jpeg'
    'width' => 240,
    'height' => 300,
    'mime-type' => 'image/jpeg',
    'sources' => array(
      'image/jpeg' => array(
        'file' => '7rMFIAVGlVg-240x300.jpeg',
        'filesize' => 3831,
      ),
      'image/webp' => array(
        'file' => '7rMFIAVGlVg-240x300.webp',
        'filesize' => 2016
      )
    ),
  )
/// ...additional image sizes
)
```

That's a great approach just adding the sources as new images, we are adding a new key on the meta as you can see so when rendering the size the `sources` is still added regardless, so essentially this won't break the existing API due it does not remove any property but instead adds new properties. 

Personally, I like your approach more tho, but that means we need to update how the data is presented in the API instead of just adding a new dynamic property in how the data is stored in the meta for an image. One little thing I would change is moving the mime type as the first part of the image like:

```
webp-medium
webp-full
webp-thumbnail
```

This approach can "group" similar mime types regardless of the length of the size name for example:

```
large-image--name-webp 
// vs
webp-large-image-name
```

**Comment by adamsilverstein** [comment]
> To ensure no breakage with third party plugins. With this structure, it should simple enough to get data in the format you require.

We should research this more by looking at how plugins (and core!) actually use this API. although the second approach doesn't change the shape of the data structure, it will introduce a bunch of new sizes and multiple mime types in `sizes` which are both new and will need to be accommodated by REST consumers. On the other hand adding a new "source" attribute as originally proposed is unlikely to break any existing usage because the original data isn't changed. This is the same reason we decided to store the meta as we have.

**Comment by spacedmonkey** [comment]
Adding a new source property to the REST API, is changing the shape of the response by adding a new field. By adding mock image sizes like this `medium-webp`, this doesn't change the shape by just adds new sizes. New sizes should be automatically be handled by all consumers of the api, as this is already something plugins / themes do, adding new image sizes.

**Comment by adamsilverstein** [comment]
> New sizes should be automatically be handled by all consumers of the api, as this is already something plugins / themes do, adding new image sizes.

The difference here is these new "sizes" are **actually the same size** (duplicates) as the existing sizes, they are different mime types.  They aren't really new sizes and that will lead to unexpected results.

Consumers of the API may actually get unexpected results based on expecting a set of unique sizes. For example, if you are constructing a `srcset` attribute for an `img` tag in a headless app and you read all the "sizes" from the REST API and then add all of those sizes to your `srcset`, you would wind up with duplicated sizes in the `srcset` which isn't what you probably want or expect.

Putting the new mime types in the sources array on the other hand means consumers will still get the same results in "sizes" AND will have all the data they need to construct a `picture` element with multiple mime types (for example to fall back to older mime types for non supporting browsers).

**Comment by felixarntz** [comment]
@spacedmonkey Also noting that this storage has already been decided on for the metadata itself, we shouldn't add more sizes since these aren't additional sizes, but additional _formats_ (or MIME types). We have considered this approach at an earlier point, but it came with more problems than benefits.

The way the new data is stored will require plugins to update _if_ they want to use the new formats, but it won't cause any breakage if they don't. Since this is a completely new feature of images, it is reasonable to expect developers to "opt in" to using it by adopting the enhanced APIs and storage approach.

So the discussion that's happening here right now is a bit unrelated to the REST API, we shouldn't choose a different approach for the REST API data shape than what we chose for the metadata, that wouldn't make sense.
