### ISSUE TITLE
DB Performance: Allow getting of multiple options

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/performance#169]
## Feature Description

Presently `get_options()` etc are limited to returning a single option. For autoloaded options this doesn't present a great problem as the functions defer to the existing object cache. For options that are not autoloaded, it requires a separate database query each time a group of options are required.

An options getter to retrieve multiple database options would allow developers to group these in to a single database request.

## Considerations

The `get_option()` function includes three main filters that would need to be supported and run against each option:

* `pre_option_{$option’}` -- modifies the return value, runs before the DB query and prevents the option being queried
* `default_option_{$option’}` -- modifies the default value
* `option_{$option’}` -- modifies the return value, runs after the DB query

The `update_option()` function includes a number of filters and actions; the `delete_option()` function includes a number of actions.

There are similar consideration for the network wide `*_site_option()` functions.

Updating options in a single query may not be possible due to back-compat considerations. An attempt was made to so so for post meta and it proved to be a little bit of a rabbit hole, see [WP#34848](https://core.trac.wordpress.org/ticket/34848)

## Example

In WP Core, an example of this can be seen by setting and getting an expiring transient. Transients are stored in the database as two options, the transient and the expiry time of the transient, an expiring transient is not auto-loaded.

Note: this **will not** work on a site with a persistent object cache as the transients will not be stored in the object tables.

Use WP CLI to set an expiring transient: `wp transient set wp_perf wp_perf 36000` (10 hours)

Run `wp shell`

```
wp> get_num_queries();
int(13)

wp> get_transient( 'wp_perf' );
string(7) "wp_perf"

wp> get_num_queries();
int(15)
```

**Comment by tillkruss** [comment]
Are there any other examples in WP core, except for the transients since that is solved by using a persistent object cache?

**Comment by eclarke1** [comment]
@tillkruss just added the Object Cache label and to the project board, but please let me know if this should not be the case.

**Comment by peterwilsoncc** [comment]
> Are there any other examples in WP core, except for the transients since that is solved by using a persistent object cache?

No, it's only an issue on sites without a persistent cache as the `*_options()` functions cache whenever possible.

**Comment by swissspidy** [comment]
`get_options()` was added in WP 6.4, closing this.
