### ISSUE TITLE
Features should be able to be deactivated from the Performance screen

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#1695]
## Feature Description

This was raised by @paaljoachim in a [support topic](https://wordpress.org/support/topic/deactivating-modules/): 

> I turned on many of the Performance Feature modules. I do not see any deactivate buttons though. How would I go about deactivating?

When we were implementing the Performance screen for standalone plugins I recall discussing whether there should be deactivate functionality, but it was ruled out. I didn't really understand why, so I'm opening this issue to discuss further. There was early discussion of adding a deactivate button at https://github.com/WordPress/performance/issues/651#issuecomment-1644360794.

**Comment by felixarntz** [comment]
Worth noting that this was not raised as a problem in the survey from https://github.com/WordPress/performance/issues/1032#issuecomment-2384151984.

To look at another reference: Does Jetpack allow deactivating the plugins for their features from their own UI?

**Comment by westonruter** [comment]
From the main Jetpack screen, apparently not. But they have a [separate Modules screen](https://jetpack.com/support/control-jetpack-features-on-one-page/) that allows you to activate/deactivate modules, even in bulk:

![Image](https://github.com/user-attachments/assets/8a8fe073-e10d-485c-aba7-b2c13db37378)

**Comment by felixarntz** [comment]
I'd argue that modules screen is quite similar like the WordPress Plugins screen, in that it's far more granular in what it allows, so it makes sense.

But in the interest of keeping the main UI simple and focused, I think it makes sense not to include deactivation in that UI - similar to how Jetpack does it for its main UI. Basically making the common and intended actions intuitive and easily accessible, while making the "advanced" actions _possible_, but not at the cost of bloating the key interactions UI.

**Comment by westonruter** [comment]
The problem is that users don't necessarily know that the features are plugins. Therefore they don't know to go to the plugins screen to deactivate Performance features.

**Comment by paaljoachim** [comment]
I would say that in a UI when something can be enabled the user should also be able to disable it, or else in a sense I feel stuck not knowing how to disable the specific feature.

Use case.
I turn on everything to see if it improves a specific area. If I do not see any improvement then I would like the opportunity to disable.
One can do the same as the Jetpack screen and add the Deactivate button instead of a greyed out Active button.

![Image](https://github.com/user-attachments/assets/2f9094ba-0d11-4da2-b95b-15b33cad8186)

**Comment by felixarntz** [comment]
@westonruter 
> The problem is that users don't necessarily know that the features are plugins. Therefore they don't know to go to the plugins screen to deactivate Performance features.

This is a fair concern. I wonder whether we can clarify that better in some way.

@paaljoachim 
> I would say that in a UI when something can be enabled the user should also be able to disable it, or else in a sense I feel stuck not knowing how to disable the specific feature.
>
> Use case.
> I turn on everything to see if it improves a specific area. If I do not see any improvement then I would like the opportunity to disable.
One can do the same as the Jetpack screen and add the Deactivate button instead of a greyed out Active button.

It depends. Jetpack does not show a deactivate button on its main features screen either. And even in WP Core, `wp-admin/plugin-install.php`, which uses similar UI as our screen, does not allow deactivating plugins.

Rather than overloading UI with additional abilities that are not key to the purpose of this screen, I think we should try to clarify where to manage those "features", e.g. clarify that they are technically plugins and can be managed in the "Plugins" screen as well.

**Comment by westonruter** [comment]
We could add a paragraph to the bottom saying something like:

> Performance features are installed as plugins. To update features or remove them, [manage them on the plugins screen](#).

Where the link goes to `/wp-admin/plugins.php?s=WordPress%20Performance%20Team&plugin_status=all`

The pre-populated search for "WordPress Performance Team" should usually result in only our PL plugins being listed, although it is possible for WordPress Performance Team to appear elsewhere: 

![Image](https://github.com/user-attachments/assets/9953c193-e678-4a13-9b9a-5781cb871ede)

Alternatively we could roll our own query parameter and filtering logic to only list out our plugins and their dependencies.

**Comment by felixarntz** [comment]
I think the approach to link with a search query like you said is definitely good enough. Implementing a custom query parameter IMO would be overkill.

**Comment by paaljoachim** [comment]
The important part is making it fully clear for the user:
- When activating features in the Performance Lab plugin screen. Additional plugins will be Installed and be activated. 
Information could be added below the modules. Activating a module will automatically install and activate a separate plugin. To deactivate a module go to the installed plugin screen and deactivate the new Performance lab module plugin...

- Can all the module/separate plugins be prefixed with Performance helping create a bigger association with the Performance Lab plugin? Something like: Performance - Image Placeholders. Performance - Performant Translations. Etc
It will also keep all Performance modules/plugins close to each other in the Installed plugins screen making it even more obvious that all of these are associated with each other.

- Would it be natural to add Performance into this area of the Installed plugins screen?
![Image](https://github.com/user-attachments/assets/41a81deb-08e1-469a-9fc6-8365c59655d7)

**Comment by westonruter** [comment]
> * When activating features in the Performance Lab plugin screen. Additional plugins will be Installed and be activated.
>   Information could be added below the modules. Activating a module will automatically install and activate a separate plugin. To deactivate a module go to the installed plugin screen and deactivate the new Performance lab module plugin...

I think a single paragraph added to the bottom of the screen that directs the user to the plugins screen will be enough, as suggested in https://github.com/WordPress/performance/issues/1695#issuecomment-2504555995.

> * Can all the module/separate plugins be prefixed with Performance helping create a bigger association with the Performance Lab plugin? Something like: Performance - Image Placeholders. Performance - Performant Translations. Etc
>   It will also keep all Performance modules/plugins close to each other in the Installed plugins screen making it even more obvious that all of these are associated with each other.

We discussed this in #1222 but since each plugin already shows it is authored by "WordPress Performance Team" then prefixing each with "Performance" would be verbose. Instead we went with #1265 where we add a line that says it was installed by Performance Lab.

> * Would it be natural to add Performance into this area of the Installed plugins screen?

I think that would be excessive.

**Comment by krishnachandak-2004** [comment]
I'd like to work on this issue. Planning to implement a Site Health check that flags unauthenticated frontend responses using the `Cache-Control: no-store` header. Please assign it to me.
