### ISSUE TITLE
[Measurement] Overview

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#172]
### Point of Contact
@AymenLoukil @josephscott

### Focus Area Overview
To be added

### Key Documentation
- [WordPress Performance Measurement: The Big Picture](https://docs.google.com/document/d/1NzURb3u-KZTgYYHK9Gx_KPvSCX4N8Ci3oZfLsfVF7Tk/edit#) document looking at the big picture of all the measurement pieces in a concise way and the various use cases and high-level requirements  **AVAILABLE FOR COMMUNITY INPUT**

### Epics
Below is a comprehensive list of all high-level projects to be completed within the [Measurement] Focus Area:

- #45 
- Declarative standard for plugin/theme demo configurations  _(no associated GH issue yet)_
- WordPress performance testing CI for WP core  _(no associated GH issue yet)_
- WordPress performance testing CI for WP plugins and themes  _(no associated GH issue yet)_

When creating new epics / high-level projects, please add to the list above.

#### Complete
- TBC

#### Available for Community Input
- [Capturing Frontend Performance Metrics in WordPress](https://docs.google.com/document/d/1elY0vgrLU2373mX3jSUj_vFZeGDyhED1WMPYwzSYiVA/edit?usp=sharing) document for #63 and #64 

#### Work In Progress
- TBC

#### On Hold
- TBC

**Comment by felixarntz** [comment]
@eclarke1 Given that we now have a [dedicated project board](https://github.com/orgs/WordPress/projects/120), I think we can close this issue in favor of that board?
