### ISSUE TITLE
Newer formats not generated for custom images sizes if Output fallback images is enabled

### ISSUE THREAD

**Issue by jamesozzie** [WordPress/performance#1720]
## Bug Description

As raised by [one user in the support forums](https://wordpress.org/support/topic/custom-thumbnail-and-image-sizes/#post-18176100), if custom image sizes are defined via `add_image_size` ([reference](https://developer.wordpress.org/reference/functions/add_image_size/)), there won't be any WebP or AVIF image generated if the [Output fallback images configuration](https://i.imgur.com/y8WN7Fw.png) is enabled. 

## Steps to reproduce

1. Add custom image sizes via `add_image_size` ([ref](https://developer.wordpress.org/reference/functions/add_image_size/))
2. Enable Fallback images
3. Upload any image
4. WebP or AVIF versions of those custom images are not generated
5. Disable the fallback image option and repeat the process
6. WebP or AVIF images of those custom sizes are generated

## Screenshots

Screenshot below - showing the code snippet added, with WebP images generated for the sizes defined

<kbd> ![Image](https://github.com/user-attachments/assets/5189936b-cb14-4205-8324-35ffb38b8101)

Screenshot below - showing the code snippet added, with no WebP image generated for the sizes defined

<kbd> ![Image](https://github.com/user-attachments/assets/773d4a12-2f15-43ba-b316-dba80235ee48)

## Additional Context

 - Modern Image Formats 2.3.0

**Comment by b1ink0** [comment]
@westonruter  This issue seems related to the #1513 which is begin addressed in #1689. Which will add new settings field to allow generation of both selected modern image format image and its respective fallback image for custom sizes.

**Comment by westonruter** [comment]
I'm not sure, but @adamsilverstein would know better.

**Comment by adamsilverstein** [comment]
> This issue seems related to the [#1513](https://github.com/WordPress/performance/issues/1513) which is begin addressed in [#1689](https://github.com/WordPress/performance/pull/1689). Which will add new settings field to allow generation of both selected modern image format image and its respective fallback image for custom sizes.

Right - we only generate core sizes currently when fallback images are enabled. This ticket should be resolved by https://github.com/WordPress/performance/pull/1689, maybe the reporter can test?

**Comment by jamesozzie** [comment]
It does indeed seem related. Thanks all. I'll close this and let the user know we are working on this.
