### ISSUE TITLE
Prepare PL 3.7 Release

### ISSUE THREAD

**Issue by joemcgill** [WordPress/performance#1739]
This issue is to track preparation of the upcoming 3.7 release up until publishing, which is due December 16, 2024.

- [x]  Create release/3.7 branch closer to the release date
- [x]  Finalize scope and punt unfinished pull requests to following release
- [x]  Smoke test (Friday, December 13, 2024)
- [x]  Prepare the release (Monday, December 16, 2024)

**Comment by joemcgill** [comment]
All [milestones](https://github.com/WordPress/performance/milestones?direction=asc&sort=due_date&state=open) for Monday's release:

- [dominant-color-images 1.2.0](https://github.com/WordPress/performance/milestone/79)
- [embed-optimizer 0.4.0](https://github.com/WordPress/performance/milestone/84)
- [image-prioritizer 0.3.0](https://github.com/WordPress/performance/milestone/85)
- [webp-uploads 2.4.0](https://github.com/WordPress/performance/milestone/87)
- [optimization-detective 0.9.0](https://github.com/WordPress/performance/milestone/88)
- [performance-lab 3.7.0](https://github.com/WordPress/performance/milestone/89)
- [web-worker-offloading 0.2.0](https://github.com/WordPress/performance/milestone/91)
- [auto-sizes 1.4.0](https://github.com/WordPress/performance/milestone/92)

**Comment by mukeshpanchal27** [comment]
I open some follow-up PRs that is ready for review and merge for current release of Enhanced Responsive Images plugin.
- #1743
- #1744

Found one non-blocking issue for Image Placeholder plugin.
- #1747

**Comment by mukeshpanchal27** [comment]
I performed a smoke test for the following plugins:  

- **Performance Lab**  
- **Enhanced Responsive Images**  
- **Modern Image Formats**  
- **Image Placeholders**  

Everything looks good based on my testing. ✅

**Comment by westonruter** [comment]
Release branch has been created: https://github.com/WordPress/performance/tree/release/3.7.0

**Comment by westonruter** [comment]
# Testing: Performance Lab

I see the link in the footer to manage the plugins on the settings screen:

![Image](https://github.com/user-attachments/assets/7b161245-6d86-485c-a885-fa77142c00c1)

Tapping to activate Image Prioritizer successfully resulted in Optimization Detective being installed:

![Image](https://github.com/user-attachments/assets/f36dd1e3-4f9f-44e7-88d6-e7a0d846d880)

After deactivating and uninstalling Image Prioritizer and Optimization Detective, I then tried activating Embed Optimizer and this resulted in that plugin and Optimization Detective also getting installed (even though it's not a hard dependency):

![Image](https://github.com/user-attachments/assets/c2e6cd3f-6957-4aa5-80c1-c659a9a4310e)

The script for ajax activation of plugins is minified:

![Image](https://github.com/user-attachments/assets/73038f57-04d7-4acb-98b6-d70f5ff7ac80)

**Comment by westonruter** [comment]
# Testing: Web Worker Offloading

I installed the Storefront theme, the WooCommerce plugin, and the Google Analytics for WooCommerce. I imported the sample products and I added a made-up Google Analytics account ID in the settings. When I visited the shop page and added an item to the cart, I successfully saw the request originating from a worker instead of the main thread:

![Image](https://github.com/user-attachments/assets/364f637a-3e3c-4cca-aad1-7af28a22f117)

**Comment by westonruter** [comment]
I encountered a fatal error with Image Placeholders: https://github.com/WordPress/performance/issues/1755

**Update:** Fix proposed in https://github.com/WordPress/performance/pull/1756

**Comment by westonruter** [comment]
# Testing: Image Placeholders

With the above fix, I'm now seeing images with placeholders showing up in the admin UI as expected:

![Image](https://github.com/user-attachments/assets/ba0e3ee5-170e-402e-a434-3d5aef2c8bb7)

**Comment by westonruter** [comment]
# Testing: Embed Optimizer

On my blog I have [a post](https://weston.ruter.net/2010/01/24/portland-oregon-snow-driving/?cachebust) with a YouTube video in the initial viewport. I'm now seeing `preconnect` links added with media queries, whereas before there were none:

```html
<link data-od-added-tag rel="preconnect" href="https://i.ytimg.com/" media="(max-width: 480px)">
<link data-od-added-tag rel="preconnect" href="https://i.ytimg.com/" media="(min-width: 783px)">
<link data-od-added-tag rel="preconnect" href="https://www.youtube.com/" media="(max-width: 480px)">
<link data-od-added-tag rel="preconnect" href="https://www.youtube.com/" media="(min-width: 783px)">
```

I did notice a small bug, however, which I have filed as https://github.com/WordPress/performance/issues/1757 for the next release. The bug just prevents the `preconnect` links from being added unless there are URL Metrics collected for _both_ desktop and mobile, when in reality this restriction is not needed.

**Comment by westonruter** [comment]
# Testing: Image Prioritizer

I activated the Twenty Thirteen theme, and after loading a page three times over the course of three minutes to obtain three URL Metrics on desktop, I then as expected saw the preload link fo the header appear:

```html
<link
  data-od-added-tag
  rel="preload"
  fetchpriority="high"
  as="image"
  href="https://perflab-3-7-0.instawp.xyz/wp-content/themes/twentythirteen/images/headers/circle.png"
  media="screen and (min-width: 783px)"
/>
```

Also, I added post with a bunch of lorem ipsum and then way below the viewport I added a cover block with a fixed background. After loading the page twice so that a URL Metric was collected on desktop and mobile, I then saw that the background image of the cover block was lazy-loaded as expected:

```html
<div class="wp-block-cover is-light has-parallax">
  <span
    aria-hidden="true"
    class="wp-block-cover__background has-background-dim"
    style="background-color: #93835c"
  ></span>
  <div
    data-od-replaced-class="wp-block-cover__image-background wp-image-119 has-parallax"
    data-od-xpath="/*[1][self::HTML]/*[2][self::BODY]/*[1][self::DIV]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::DIV]/*[1][self::ARTICLE]/*[2][self::DIV]/*[16][self::DIV]/*[2][self::DIV]"
    class="wp-block-cover__image-background wp-image-119 has-parallax od-lazy-bg-image"
    style="
      background-position: 50% 50%;
      background-image: url(https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison1-scaled.webp);
    "
  ></div>
  <div
    class="wp-block-cover__inner-container is-layout-constrained wp-block-cover-is-layout-constrained"
  >
    <p class="has-text-align-center has-large-font-size">Lazy??</p>
  </div>
</div>
```

https://github.com/user-attachments/assets/d9ac207d-3635-4684-b75b-a09fcdd9e416

I also enabled Picture Element in Modern Image Formats. Then I added an Image block to the beginning of a post so that it is the LCP element. After loading a page (on mobile) so that a URL Metric is collected, I then saw the expected preload link for the WebP image (and not the JPEG fallback):

```html
<link
  data-od-added-tag
  rel="preload"
  fetchpriority="high"
  as="image"
  imagesrcset="
    https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-1024x768-jpg.webp 1024w, 
    https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-300x225-jpg.webp 300w, 
    https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-768x576-jpg.webp 768w, 
    https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-1536x1152-jpg.webp 1536w, 
    https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-2048x1536-jpg.webp 2048w
  "
  imagesizes="(max-width: 1024px) 100vw, 1024px"
  type="image/webp"
  media="screen and (max-width: 480px)"
/>
```

The `picture` element:

```html
<figure class="wp-block-image size-large">
  <picture class="wp-picture-125" style="display: contents"
    ><source
      type="image/webp"
      srcset="
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-1024x768-jpg.webp  1024w,
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-300x225-jpg.webp    300w,
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-768x576-jpg.webp    768w,
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-1536x1152-jpg.webp 1536w,
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-2048x1536-jpg.webp 2048w
      "
      sizes="(max-width: 1024px) 100vw, 1024px" />
    <img
      data-od-removed-fetchpriority="high"
      data-od-xpath="/*[1][self::HTML]/*[2][self::BODY]/*[1][self::DIV]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::DIV]/*[1][self::ARTICLE]/*[2][self::DIV]/*[1][self::FIGURE]/*[1][self::PICTURE]/*[2][self::IMG]"
      data-dominant-color="8d816f"
      data-has-transparency="false"
      style="--dominant-color: #8d816f"
      decoding="async"
      width="1024"
      height="768"
      sizes="(max-width: 1024px) 100vw, 1024px"
      src="https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-1024x768.jpg"
      alt=""
      class="wp-image-125 not-transparent"
      srcset="
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-1024x768.jpg  1024w,
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-300x225.jpg    300w,
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-768x576.jpg    768w,
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-1536x1152.jpg 1536w,
        https://perflab-3-7-0.instawp.xyz/wp-content/uploads/2024/12/bison4-2048x1536.jpg 2048w
      "
  /></picture>
</figure>
```
