### ISSUE TITLE
When generating WebPs, ensure full size is generated(`-scaled` for large images)

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#174]
## Bug Description

After #152 "Full"" sized images inserted by users will still use the original jpeg image or (`-scaled` version for larger images) because the WebP version is not being generated. See https://github.com/WordPress/performance/pull/152#issuecomment-1051118813.

Proposal to fix:
* Always generate a full sized WebP version when WebP output is active
* For larger images (over `big_image_size_threshold`), generate a `-scaled.webp` file

## Steps to reproduce

1. Enable webp-uploads
2. Upload and insert an image, select full size in the image properties sidebar
3. view the post and check the image source

#### Expected:
* All image references are to `.webp` files

#### Actual 
* some references are to a `.jpg` file.

## Screenshots

![image](https://user-images.githubusercontent.com/2676022/154166217-e878ac4b-f91a-468c-8329-53adac14c96e.png)
![image](https://user-images.githubusercontent.com/2676022/154166320-30f8b5c3-f55f-4aa4-b8e8-2f01927a5295.png)
![image](https://user-images.githubusercontent.com/2676022/155782710-20b37645-4ee5-479a-92ba-f62f70318901.png)

**Comment by mitogh** [comment]
I agree with this behavior, however, the opposite of this behavior was introduced here:

- #143 

Closing #122 

Just want to make sure we are consistent with those behaviors moving forward.

**Comment by felixarntz** [comment]
@mitogh #122 was opened based on the current implementation where all sub-sizes are only created in one version (e.g. WebP), while the original image is remaining in the original format (e.g. JPEG).

But now, given we're working towards keeping JPEG available for all sizes and using WebP _in addition_, this may still be a relevant issue, it doesn't conflict with #122.

@adamsilverstein I wonder though whether we should rephrase the purpose of this issue. It wouldn't make sense to me to create a WebP version of the `-scaled` image if we don't also create a WebP version for the full image if it is small enough. We should either make the decision to only create WebP versions of the sub-sizes or we should make the decision to create WebP versions of the `full` size as well, no matter whether that `full` size is a downscaled version (i.e. if the original is too large, as mentioned here) or small enough to not need a downscaled version (i.e. not a "big" image).

**Comment by adamsilverstein** [comment]
> We should either make the decision to only create WebP versions of the sub-sizes or we should make the decision to create WebP versions of the full size as well, no matter whether that full size is a downscaled version (i.e. if the original is too large, as mentioned here) or small enough to not need a downscaled version (i.e. not a "big" image).

We need the full sized web- to generate correct markup when the user selects a large image, see https://github.com/WordPress/performance/pull/152#issuecomment-1051118813

**Comment by adamsilverstein** [comment]
I updated this ticket's title and description to more accurately describe the issue: we need to generate the "Full" sized image as a WebP in all cases (small or large image) when we are generating WebPs. For larger images this is the `-scaled` image, otherwise its just the original image we need a WebP version of.

**Comment by felixarntz** [comment]
Marking this as `Needs Dev` - a PR for this can be started anytime, since the dependency of #142 is now completely implemented.

**Comment by mitogh** [comment]
Taking over this one as I think I have a good idea of how we can implement it on top of what we already have in place. :)
