### ISSUE TITLE
Image Placeholders: Remove dominant color attributes from old media images

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#1747]
## Summary

In #1719, we introduced dominant color support for images in the media library. This feature adds a `data-dominant-color`, `data-has-transparency` attribute and inline styles to each image.

However, this behaviour is unnecessary for old media images that do not have dominant color attributes pre-populated. These attributes should only be applied to newly uploaded images or existing images that already have values for these attributes.

For better, we should remove the attributes and inline styles for old media images where these attributes are not relevant or populated.

## Screenshot
<img width="1117" alt="Image" src="https://github.com/user-attachments/assets/0811aea2-9c58-4d3c-9f1d-8406ab8d5f6a" />

**Comment by swissspidy** [comment]
I don't think this is actually possible or feasible. #1719 changes the JavaScript template that's used by the media modal to render each and every media item. So it's not a part of the render logic where you have access to the actual attachment.

It might be possible to write some custom logic that hooks into the media modal Backbone app, but given that it's a giant piece of undocumented legacy code, I would advise that.

Empty attributes are maybe not nice to look at, but no user looks at that anyway :) So I suggest closing as wontfix.

**Comment by mukeshpanchal27** [comment]
Thanks. Make sense.
