### ISSUE TITLE
Automate PHPCS/PHPCBF run after commit with Husky

### ISSUE THREAD

**Issue by kirtangajjar** [WordPress/performance#175]
## Feature Description

We're expecting developers to run `phpcs/phpcbf` manually before creating a PR. This can be automated easily via [husky](https://typicode.github.io/husky/). Husky is also [used by Gutenberg](https://github.com/WordPress/gutenberg/blob/trunk/.husky/pre-commit) to lint before commit.

So here are things that we need to do:
1. Add a pre-commit hook via husky to run `phpcbf` before commit to auto-fix phpcs errors. 
2. Run `phpcs`  so that users can manually resolve any errors which are not automatically fixable.

**Comment by kirtangajjar** [comment]
@felixarntz I'm willing to work on this. Can you please assign it to me?

**Comment by eclarke1** [comment]
@kirtangajjar assigned to you and added to the 'Infrastructure' project. I have put the issue in To Do and removed the 'Needs Dev' label as you are picking this up. Thanks so much.
