### ISSUE TITLE
Can't deactivate experimental Plugins

### ISSUE THREAD

**Issue by lisapower123** [WordPress/performance#1753]

**Comment by westonruter** [comment]
I'm guessing you're reporting the same issue as https://github.com/WordPress/performance/issues/1695?

Each of the experimental features are just regular WordPress plugins which you can deactivate from the plugins screen. This will be made clear in the next release with https://github.com/WordPress/performance/pull/1734.

Please let us know if this addresses your issue.

**Comment by westonruter** [comment]
@lisapower123 Please confirm.
