### ISSUE TITLE
Provide Insight into 3rd-party Scripts

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#179]
## Feature Description

As an end-user it would be incredibly useful to see just how many 3rd-party scripts are loading on the site. 
3rd-party scripts can be a huge bottleneck when it comes to performance. They're also very difficult to diagnose at times. 

My suggestion is that we offer the user some recorded data in the Site Health widget, which potentially contains:

1. The number of 3rd-party scripts being loaded directly from the site.
2. The total transfer-size of these scripts
3. Flag any scripts that are known to hinder performance (Chartbeat, Ads, etc)

I think this could go a long way to making the landscape of 3rd-party scripts more accessible.

**Comment by manuelRod** [comment]
Hello @dainemawer.
Points 1 and 2 were covered (indirectly) already by [this](https://github.com/WordPress/performance/issues/25)

There are a couple of follow up tasks for that one:
See [137](https://github.com/WordPress/performance/issues/137)
See [134](https://github.com/WordPress/performance/issues/134)

How can we agree/define a list of typical offenders?

**Comment by dainemawer** [comment]
Thanks @manuelRod ! I think I will close this then - I'll open up another ticket regarding typical offenders!
