### ISSUE TITLE
Add Lighthouse / bundlesize to WP VIP Pipelines

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#180]
## Feature Description

Not sure if this is the most suitable place to add this ticket, but I thought I would add it anyhow.

It would be great to see an update in the continuous integration for VIP sites that tracked the [bundlesize](https://www.npmjs.com/package/bundlesize) of assets as well as ran [Lighthouse reports](https://github.com/GoogleChrome/lighthouse-ci) on pull request. This is a relatively contrived effort and quite well-documented. Even thought VIP is a premium service from Automattic, I think it would be great to see a step forward in this direction, considering their overall standards for code-quality are pretty high as is.

**Comment by swissspidy** [comment]
This is something that VIP can add on their own infrastructure, not something the WP community's performance team can or should work on.
