### ISSUE TITLE
[Object Cache] Overview

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#183]
### Point of Contact
@tillkruss @spacedmonkey

### Focus Area Overview
To be added

### Key Documentation
- TBC

### Epics
Below is a comprehensive list of all high-level projects to be completed within the [Object Cache] Focus Area:

- #34 
- #35 
- #105 
- #38 
- Improve core object cache implementation  **_(no associated GH issue yet)_**
- SQL query caching  **_(no associated GH issue yet)_**

When creating new epics / high-level projects, please add to the list above.

#### Complete
- TBC

#### Available for Community Input
- TBC

#### Work In Progress
- TBC

#### On Hold
- TBC

**Comment by eclarke1** [comment]
@tillkruss @spacedmonkey as per last weeks Slack chat, I've created an 'Overview' issue to capture the high-level projects / epics from the [original Google Doc](https://docs.google.com/document/d/1IbxskyHVcRi_PKeSR10IIeO5y9cuR32Gh8Zqx7ddIZ8/edit)
Please let me know if any are missing, happy to help maintain this overview issue to help bring visibility to the wider group :)

**Comment by tillkruss** [comment]
@eclarke1: Please do. I'll make sure to keep the project board and labels up-to-date.

**Comment by felixarntz** [comment]
@eclarke1 Given that we now have a [dedicated project board](https://github.com/orgs/WordPress/projects/112) for server response time, which encompasses object cache, I think we can close this issue in favor of that board?
