### ISSUE TITLE
[JavaScript] Overview

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#184]
### Point of Contact
@aristath @sgomes

### Focus Area Overview
To be added

### Key Documentation
- TBC

### Epics
Below is a comprehensive list of all high-level projects to be completed within the [JavaScript] Focus Area:

- #168 
- Others to be added from the [original Google Doc](https://docs.google.com/document/d/1GD0X3bNUa73Afsi8OZjrSDb0VfEgDg-PLlBvw5aL-sc/edit#)

When creating new epics / high-level projects, please add to the list above.

#### Complete
- TBC

#### Available for Community Input
- TBC

#### Work In Progress
- TBC

#### On Hold
- TBC

**Comment by eclarke1** [comment]
@aristath @sgomes as per last weeks Slack chat, I've created an 'Overview' issue to capture the high-level projects / epics from the [original Google Doc](https://docs.google.com/document/d/1GD0X3bNUa73Afsi8OZjrSDb0VfEgDg-PLlBvw5aL-sc/edit#)
Please let me know if there's anything I can do to support transferring those projects from the Google Doc to here to help bring visibility to the wider group :)

**Comment by felixarntz** [comment]
@eclarke1 Given that we now have a [dedicated project board](https://github.com/orgs/WordPress/projects/114), I think we can close this issue in favor of that board?
