### ISSUE TITLE
Provide admin pointer informing about the plugin's admin screen

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#193]
For WordPress plugins that don't add their own top-level menu item to the WordPress admin menu it has been notoriously hard to be noticeable after plugin activation. The "Performance Lab" plugin adds a new submenu item "Settings > Performance", but that's obviously hard to find since it's under the existing "Settings" top-level menu item.

Displaying a WP admin pointer was suggested in https://github.com/WordPress/performance/issues/61#issuecomment-1012844968, and this issue is focused on implementing that.

Related is #192 which also adds an alternative way to discover the plugin's admin screen.

My suggestion for the admin pointer copy would be a simple text like this:
* Title: _Performance Lab_
* Content: _You can now test upcoming WordPress performance features. Open Settings > Performance to individually toggle the performance features included in the plugin._
* The _Settings > Performance_ part could be a link to the admin screen.

cc @JustinyAhin

**Comment by felixarntz** [comment]
Putting `Needs Discussion` here, mostly to review/iterate on the suggested copy in the issue description.

**Comment by JustinyAhin** [comment]
The copy seems to be a solid start IMO.

**Comment by dainemawer** [comment]
Closing this out as it has been merged into the first release :)
