### ISSUE TITLE
Add async decoding attribute to image tags

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#20]
@khoipro: Seems most finished and needs testing. If there is an option to toggle this option, it will be the same toggle loading=”lazy” option in each image.

Trac ticket: https://core.trac.wordpress.org/ticket/53232

**Comment by eclarke1** [comment]
@adamsilverstein just assigning this issue to yourself as it's in progress

**Comment by dainemawer** [comment]
Looks like @mitogh has a ticket for this aswell: https://github.com/WordPress/performance/issues/86 duplicate perhaps?

**Comment by mitogh** [comment]
That's right @dainemawer I wasn't aware of this ticket and 

- #86 

Seems like a dupe from this one. Let's wait for @eclarke1 to see which one should we close. Thanks for the heads up.

**Comment by sgomes** [comment]
I'm not sure whether this or trac is the best place for discussion. [I went with trac](https://core.trac.wordpress.org/ticket/53232#comment:32) (sorry if I got that wrong!), but please let me know if you prefer to continue the discussion here!

**Comment by adamsilverstein** [comment]
Closing this as a duplicate of https://github.com/WordPress/performance/issues/86
