### ISSUE TITLE
Not necessary singular/plural translation 

### ISSUE THREAD

**Issue by erikyo** [WordPress/performance#215]
## Bug Description

Some singular and plural translation in Site Health are not necessary or misleading. if a user finds this message he should think about removing some style/scripts before minifying them.

## Steps to reproduce

1. You must use a single css file and a single js file
2. Navigate to the dashboard under site-health
3. You should find a message like "Your website enqueues 1 style (size: 86187). Try to reduce the number or to concatenate them." 

## Additional Context
https://github.com/WordPress/performance/blob/ef0d26b78c37923dbef806ac8b0b332c879fd215/modules/site-health/audit-enqueued-assets/load.php#L198
https://github.com/WordPress/performance/blob/ef0d26b78c37923dbef806ac8b0b332c879fd215/modules/site-health/audit-enqueued-assets/load.php#L250

**Comment by swissspidy** [comment]
As mentioned on Slack, this **_is_** necessary for certain languages with more complex plural forms, such as for example in Russian, where the singular form is also used for counts like 21, 31, etc.

This is not a bug.
