### ISSUE TITLE
Introduce `.gitattributes` in favor of `.distignore`

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#217]
## Feature Description

The current release zips created by GH everytime a new tag is created includes files that are not part of the release, for example:

- https://github.com/WordPress/performance/archive/refs/tags/1.0.0-beta.1.zip

Contains tests and configuration files, non required for testing or usage of the plugin.

![2022-03-07_16-43](https://user-images.githubusercontent.com/3921289/157131814-f4caccb0-ebfc-404d-b8bd-f6745a30a505.png)

The deploy action would use either:

- `.disignore` 
- `.gitattributes`

To exclude files that are going to be deployed so we can safely move `.disignore` to `.gitattributes` one of the things to consider is when moving the content into `.gitattributes` is the fact that the setting `export-ignore` should be added after each file for example:

```
/.git export-ignore
/node_modules export-ignore
```

`export-ignore`

> Files and directories with the attribute export-ignore won’t be added to archive files.

Additional [parameters](https://git-scm.com/docs/gitattributes).

**Comment by jeffpaul** [comment]
Will also want to make sure that `README.md` gets added to either file as that's currently being published to WP.org (alongside the more useful `readme.txt` file), see: https://plugins.trac.wordpress.org/browser/performance-lab/trunk/README.md

**Comment by felixarntz** [comment]
@mitogh Why should we be using `.gitattributes` over `.distignore`? I'm not sure I see the benefits of that.

@jeffpaul Great catch, `README.md` should definitely be excluded as well.

**Comment by mitogh** [comment]
>  Why should we be using .gitattributes over .distignore? I'm not sure I see the benefits of that.

ZIPs created from a release tag contains non required files: 

- https://github.com/WordPress/performance/archive/refs/tags/1.0.0-beta.1.zip

**Benefits**

- When using `gitattributes` those files won't be included on the created file instead.
- Zip from the release tag would match closely the ZIP from WP.org instead
- `gitattributes` works for the WP release action so we get both benefits in both areas.

**Comment by felixarntz** [comment]
@mitogh Good point, that makes sense to me.

So as a **summary** what needs to be done here:
* Migrate the current `.distignore` to a `.gitattributes` file (using `export-ignore`, see https://github.com/WordPress/performance/issues/217#issue-1162021106).
* Include `README.md` in that file so that it is excluded from ZIP files as well.
