### ISSUE TITLE
Default settings not working as expected in multisite

### ISSUE THREAD

**Issue by gagan0123** [WordPress/performance#218]
## Bug Description

When we install the plugin in a multisite environment and "Network Activate" the plugin, the default settings are only saved for the main site and not all the sites in the network.

## Steps to reproduce

1. Install Performance Lab plugin in a WordPress multisite environment
2. "Network Activate" the plugin
3. Check the default settings for the Performance Lab plugin in any site other than main site

## Screenshots

As can be seen none of the options are selected.
![image](https://user-images.githubusercontent.com/1535505/157274755-209d029d-2c53-4f3a-8d25-75be2c46e092.png)

## Additional Context

 - PHP Version: 7.4
 - Plugin Version: [1.0.0-beta.1](https://github.com/WordPress/performance/releases/tag/1.0.0-beta.1)

**Comment by felixarntz** [comment]
Activation hooks are unfortunately unreliable on certain environments like multisite or when using WP-CLI, which is a long-standing problem with WordPress core that is extremely hard to fix. Fortunately, in the case here, it is possible to remove the hook entirely and replace it by using a default value for our modules setting.

I'm currently working on a pull request to implement that, in a way that we don't have to manually maintain this list of modules and in a way that it also doesn't read the filesystem on every page load.
