### ISSUE TITLE
Default settings not working with WP-CLI

### ISSUE THREAD

**Issue by gagan0123** [WordPress/performance#219]
## Bug Description

When the plugin is activated using `wp-cli` the default options are not saved.

## Steps to reproduce

1. Install the plugin either via GUI `wp-admin/plugins.php` or via CLI `wp plugin install performance-lab`
2. Activate the plugin using `wp plugin activate performance-lab`
3. Check Performance Lab plugin settings

## Screenshots

![image](https://user-images.githubusercontent.com/1535505/157277064-cf83bc18-0544-479e-97af-69d67b44ef93.png)

## Additional Context

 - PHP Version: 7.4
 - Plugin Version: [1.0.0-beta.1](https://github.com/WordPress/performance/releases/tag/1.0.0-beta.1)

**Comment by felixarntz** [comment]
This can be fixed together with #218, as it's the same cause for both of these problems. I'll open a PR.
