### ISSUE TITLE
Add Site Health test for full page caching (advanced cache)

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#220]
## Feature Description

I previously reported this in trac ([#54423](https://core.trac.wordpress.org/ticket/54423)), but I'm copying it here for visibility:

> A [best practice](https://make.wordpress.org/hosting/handbook/performance/#full-page-cache) for performance is to enable full page caching for a WordPress site. Doing so reduces the time to first byte (TTFB) and thus directly impacts Core Web Vitals. This is especially important on shared hosts which have limited compute power, while also protecting a site from going down due to traffic spikes. 
>
> As with XML Sitemaps, it may make sense for WordPress core to include a basic full page caching solution out of the box which can be extended by the many plugins that provide page caching today. In the meantime, there should at least be a Site Health test with a low-severity `recommended` status to point users to where to go to enable page caching. Since hosts often have built-in caching solutions in place, the Site Health test should be easily filterable so they can provide a link to their specific dashboard or documentation to enable caching which may not be a plugin at all but rather a reverse proxy like Varnish.
>
> In the context of the AMP plugin for WordPress, we've already developed such a test which could be adapted for core. See https://github.com/ampproject/amp-wp/pull/6456. It's an async test which issues three loopback requests to the homepage, and the test will pass if responses include either of the following headers:
> 
> 1. `Cache-Control` with non-zero `max-age`.
> 2. `Expires` with a future time.
> 3. `Age` with a positive number (as is set via a proxy like Varnish).

Since the above was written and, after releasing the page caching site health test in the AMP plugin v2.2, it came to light that the detection was not robust enough. A major improvement followed (https://github.com/ampproject/amp-wp/pull/6849) which accounts for many more scenarios (https://github.com/ampproject/amp-wp/pull/6849#issuecomment-1023762369). These were uncovered with help from @piotrbak in a WP Rocket issue (https://github.com/wp-media/wp-rocket/issues/4638#issuecomment-1011429544).

The page caching code in question: https://github.com/ampproject/amp-wp/blob/f7c7230a27fb23932606f9847bfcf04c83b8ff06/src/Admin/SiteHealth.php#L333-L661

## Scenarios

Via https://github.com/ampproject/amp-wp/pull/6849#issuecomment-1023762369:

<blockquote cite="https://github.com/ampproject/amp-wp/pull/6849#issuecomment-1023762369">

### Failure to Do Loopback Request

With this plugin active:

```php
add_action('template_redirect', function () {
	status_header( 500 );
	exit;
});
```

![image](https://user-images.githubusercontent.com/134745/151463425-0d7631dc-4373-4329-9f3d-f5467cf48229.png)

### No Page Caching with Slow Response Time

With this plugin active:

```php
add_action( 'wp_footer', function () {
	sleep(1);
} );
```

![image](https://user-images.githubusercontent.com/134745/151461486-2e4b6f08-14a3-475b-a613-f3d0818c15f2.png)

### No Page Caching with Good Response Time

No special plugins active.

![image](https://user-images.githubusercontent.com/134745/151463516-88b0bcdc-7413-48ec-aff0-b67547d2b0f6.png)

### Page Caching Header(s) with Bad Response Time

Test plugin:

```php
add_filter(
	'wp_headers',
	function ( $headers ) {
		$headers['etag'] = '"foo"';
		$headers['last-modified'] = gmdate('r');
		return $headers;
	}
);

add_action( 'wp_footer', function () {
	sleep(1);
} );
```

Note that since page caching response headers are present, the lack of a page caching plugin is not mentioned (since it's likely an external page cache is being used):

![image](https://user-images.githubusercontent.com/134745/151464680-ed4f2ee5-3fd3-4ae1-b9ac-ce0b5ac0c1f6.png)

### Page Caching Header with Good Response Time

Plugin:

```php
add_filter(
	'wp_headers',
	function ( $headers ) {
		$headers['etag'] = '"foo"';
		$headers['last-modified'] = gmdate('r');
		return $headers;
	}
);
```

Note that since page caching response headers are present, the lack of a page caching plugin is not mentioned (since it's likely an external page cache is being used):

![image](https://user-images.githubusercontent.com/134745/151463823-09f5b522-ca9e-45ed-b000-ce10d70572cb.png)

### Page Caching Plugin with Good Response Time

With WP Super Cache active and with the following plugin active:

```php
add_action( 'wp_footer', function () {
	sleep(1);
} );
```

Note that since the median time is used, the 1-second response time is disregarded:

![image](https://user-images.githubusercontent.com/134745/151464538-ef77e432-0257-48cf-b0b6-24895e81617b.png)

</blockquote>

**Comment by manuelRod** [comment]
Hello, @westonruter I would love to take a look, you can assign it to me!

**Comment by eclarke1** [comment]
Just added this to the Site Health project and it's currently in the backlog. I've added the 'Needs Dev' label and assigned to @manuelRod

**Comment by manuelRod** [comment]
@westonruter I believe I found a bug in the AMP implementation.
get_page_cache_headers() doesn't receive any argument, however it's using $header_value inside. [See](https://github.com/ampproject/amp-wp/blob/2.2/src/Admin/SiteHealth.php#L540).
This is making me fail some tests ( on my side at least ), I'm also trying to figure out, what's this method purpose, especially the callback part.

**Comment by manuelRod** [comment]
@westonruter you can take a look at my draft: [PR](https://github.com/WordPress/performance/pull/263)
Are you missing something?

As I was checking AMP code, I figured out a couple of things: 
- Notice :
`[24-Mar-2022 16:40:35 UTC] PHP Notice:  Undefined variable: header_value in /Users/xxx/Desktop/development/xwp/app/public/wp-content/plugins/amp-wp-develop/src/Admin/SiteHealth.php on line 542`
[get_page_cache_headers](https://github.com/ampproject/amp-wp/blob/develop/src/Admin/SiteHealth.php#L540)() is provoking that notice as $header_value is not passed as argument.

- Unit test Error:
Callback for [cache-control](https://github.com/ampproject/amp-wp/blob/develop/src/Admin/SiteHealth.php#L548) is expecting a string as $header_value, not an array, that is failing the test when using this index from [no-cache-arrays](https://github.com/ampproject/amp-wp/blob/develop/tests/php/src/Admin/SiteHealthTest.php#L755) from get_page_cache_data dataprovider.
I've implemented a workaround on my [PR](https://github.com/WordPress/performance/pull/263/files#diff-ee3452ae642decca0d0b4540507be873e6f43d1a32f45b0669ea3835d16d7bbcR26)

**Comment by westonruter** [comment]
@manuelRod I think you may have been seeing https://github.com/ampproject/amp-wp/issues/6937 which is addressed by https://github.com/ampproject/amp-wp/pull/6938.

The `$header_value` should be getting passed via `array_filter()` here: https://github.com/ampproject/amp-wp/blob/4bd0387b0a68c06806f139d15befe9de21717b79/src/Admin/SiteHealth.php#L638

**Comment by manuelRod** [comment]
@westonruter indeed, that was it. I've implemented your approach and fixed the tests, it's ready to be reviewed.

**Comment by manuelRod** [comment]
@eclarke1 can you add the Needs Review tag on this? Thanks!

**Comment by eclarke1** [comment]
@manuelRod absolutely 👍 done and also moved to the 'In Review' column. Thanks so much

**Comment by manuelRod** [comment]
@westonruter Thanks for the feedback, I've addressed it. We need another reviewer, maybe @felixarntz wants to take an eye?

**Comment by tommydv** [comment]
Hello westonruter.

I am the owner of a wordpress website.

I use amp plugin and wp rocket plugin.

I then removed wp rocket and replaced it with wp super cache.

Checking my system got this message.

![11](https://user-images.githubusercontent.com/28681946/163687503-e3510afd-63c2-4060-b3e0-aa2b3cbc7a46.png)

Can you show me how to fix this error?

Thank you.

**Comment by mxbclang** [comment]
@tommydv It sounds like your issue is not related to the Performance Lab plugin, which is what this repo and issue are for. Can you please post to the <a href="https://wordpress.org/support/plugin/amp/">AMP plugin support forum</a> for assistance? Thanks!

**Comment by manuelRod** [comment]
~~@felixarntz why do we move this to 1.2.0? The PR is _ready_, it could get in this week.~~
I saw the comment in the PR.

**Comment by felixarntz** [comment]
@manuelRod @westonruter I've added a `[Module] Audit Full Page Cache` label for the eventual module here.
