### ISSUE TITLE
Add Asset Bundling to Plugin

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#226]
## Feature Description
At some point in the near future I think we're going to need some form of static asset (JS/CSS) bundling in the plugin. This can be achieved by adding in a relatively simple `webpack` configuration. 

There is `@wordpress/scripts` which can handle asset bundling and transpiling from ES6 to ES5. Im not sure if its as versatile as a custom webpack configuration. Mainly because it seems to be centred around Gutenberg Block development.

Im putting this ticket out there so we can get some ideas going about how to handle this moving forward.

**Comment by thelovekesh** [comment]
> Im not sure if its as versatile as a custom webpack configuration.

@dainemawer IMO we can extend the Webpack config from `@wordpress/scripts` according to the use cases in this plugin. Some workaround examples can be found in the AMP plugin Webpack [config](https://github.com/ampproject/amp-wp/blob/develop/webpack.config.js) file which extends the `@wordpress/scripts` Webpack configuration.

**Comment by thelovekesh** [comment]
@dainemawer I would like to work upon this. Can you assign it to me?

**Comment by dainemawer** [comment]
@thelovekesh sure - Im not sure we have any real use cases for this at the moment - as in no functionality requires JS/CSS at this point, but would be great to have this ready to be merged when we do.

**Comment by thelovekesh** [comment]
Thank you @dainemawer for assigning this to me. Once we have a discussion and real use case we can go forward with adding the functionality in the plugin.

**Comment by adamsilverstein** [comment]
Closing as fixed in https://github.com/WordPress/performance/pull/953.
