### ISSUE TITLE
Replace original images with the WebP ones

### ISSUE THREAD

**Issue by Tangol** [WordPress/performance#232]
At the moment, the Performance Module allows us to create WebP versions for all uploaded images which is great, but comes with an issue related to the number of files hosted, as every image will have a duplicate WebP one.

Taking into consideration that most WordPress installs are on **shared hosting**, which imposes an [Inode](https://en.wikipedia.org/wiki/Inode) limit (even premium hosts), this becomes an issue for websites that have a lot of images (travel blogs, news outlets etc.)

The way to fix this issue, would be to add an option in the settings, to permanently replace all new and old image files, with optimized WebP versions.
Something like this:
![WebP](https://user-images.githubusercontent.com/3336728/158567359-677a7f0e-ebee-4fd2-b5d3-5974463ec36b.png)

Adding this option would save us the pain of using plugins like [this](https://wordpress.org/plugins/plus-webp/), that aren't supported and have compatibility issues (E.g. with WooCommerce).

Also, the ability to regenerate the existing images (https://github.com/WordPress/performance/issues/24) is a must, and it's closely related to this feature request.

### Impact
A radical setting like this, by the system the powers 40% of all websites, would basically move the entire industry forward, forcing everyone to fully support WebP (https://github.com/WordPress/performance/issues/74) - https://caniuse.com/webp

**Comment by adamsilverstein** [comment]
Hey @Tangol thanks for opening this issue. A couple of comments:

* While we decided to generate both WebP and JPEG for the initial release, we may transition to only generating WebP in the future. Already you (and developers/hosts) can choose to generate only WebP using a filter, we will be sure to release a mini plugin that does this as well.
* We are unlikely to introduce a core toggle for this option although plugins can add it. For core, we want to pick the best approach for most people and stick to that as a default.
* Note that image regeneration is actually reversible (not irreversible as your screenshot indicates) because the original image is always kept, so it is possible go back and re-generate the jpeg images should you need to.

**Comment by Tangol** [comment]
@adamsilverstein Image regeneration would actually be irreversible if my suggestion is to be implemented and the option enabled, as the original images would be deleted.
This is actually the entire goal, to give the user the option to save hosting space and keep the inode count low by removing all JPEGs and have only WebP.

Thanks!

**Comment by dainemawer** [comment]
@Tangol deleting all JPEGs could potentially be quite harmful. Especially when it comes to 3rd-party services consuming blog posts and data, think RSS / Atom feed aggregators / email clients / mobile apps etc, or a host of other platforms where WebP isn't supported. Ideally, we always want to ensure we have a fallback to account for these situations.

**Comment by Tangol** [comment]
@dainemawer I totally agree, that's why I would add this option with a note/warning that it's an irreversible process.
As the fallback functionality is implemented by default, my suggestion was aimed at offering users the option to save web server resources (physical space and inodes) by keeping only the WebP images.
And taking into consideration that the WebP support is growing, the compatibility aspect won't be an issue in the near future.

But it's up to you guys, if this gets accepted or not.
I personally, searched a lot for a plugin that would allow me to only have the WebP images, and sadly the offering is scarce (either [premium](https://docs.litespeedtech.com/lscache/lscwp/imageopt/#remove-original-image-backups) or free but incomplete/buggy).

**Comment by Tangol** [comment]
@dainemawer @adamsilverstein 
Some more comments related to this matter, and why it's important to take this into proper consideration: 
https://make.wordpress.org/core/2022/03/28/enabling-webp-by-default/#comment-42770 
https://make.wordpress.org/core/2022/03/28/enabling-webp-by-default/#comment-42816
https://make.wordpress.org/core/2022/03/28/enabling-webp-by-default/#comment-42820
https://make.wordpress.org/core/2022/03/28/enabling-webp-by-default/#comment-42823

So yeah, you be the judge...

**Comment by dainemawer** [comment]
Hey @Tangol thanks yes - we have been following the feedback on the proposal. We are definitely taking things into consideration, from our side and for the community sake.

**Comment by felixarntz** [comment]
This has been addressed almost a year ago, the Performance Lab plugin provides a checkbox under _Settings > Media_ which allows configuring whether to generate _only_ WebP or _both_ WebP and JPEG.

**Comment by whanklee** [comment]
Where do

> At the moment, the Performance Module allows us to create WebP versions for all uploaded images which is great, but comes with an issue related to the number of files hosted, as every image will have a duplicate WebP one.
> 
> Taking into consideration that most WordPress installs are on **shared hosting**, which imposes an [Inode](https://en.wikipedia.org/wiki/Inode) limit (even premium hosts), this becomes an issue for websites that have a lot of images (travel blogs, news outlets etc.)
> 
> The way to fix this issue, would be to add an option in the settings, to permanently replace all new and old image files, with optimized WebP versions. Something like this: ![WebP](https://user-images.githubusercontent.com/3336728/158567359-677a7f0e-ebee-4fd2-b5d3-5974463ec36b.png)
> 
> Adding this option would save us the pain of using plugins like [this](https://wordpress.org/plugins/plus-webp/), that aren't supported and have compatibility issues (E.g. with WooCommerce).
> 
> Also, the ability to regenerate the existing images (#24) is a must, and it's closely related to this feature request.
> 
> ### Impact
> A radical setting like this, by the system the powers 40% of all websites, would basically move the entire industry forward, forcing everyone to fully support WebP (#74) - https://caniuse.com/webp

"The way to fix this issue, would be to add an option in the settings, to permanently replace all new and old image files, with optimized WebP versions." where can I find it?

**Comment by felixarntz** [comment]
@whanklee There is a checkbox to only generate WebP instead of JPEG under _Settings > Media_ when the WebP Uploads module is active.
