### ISSUE TITLE
Create Autoloaded Options Core Documentation

### ISSUE THREAD

**Issue by manuelRod** [WordPress/performance#234]
## Feature Description

As a #92 follow-up, as we cannot rely only on hosting using the filters to link to their own information/recommendation, we need to offer a default link with some call to action on how to solve the problem.

The consensus was we should use the following [article](https://wordpress.org/support/article/optimization/) Maybe using #autoload anchor. https://wordpress.org/support/article/optimization/#autoload
In this topic, we need to explain the why and how to solve it.

Hosting article examples:
[Kinsta](https://kinsta.com/knowledgebase/wp-options-autoloaded-data/)
[WPEngine](https://wpengine.com/support/database-optimization-best-practices/#Autoloaded_Data)
[Pantheon](https://pantheon.io/docs/optimize-wp-options-table-autoloaded-data)
...

**Comment by tillkruss** [comment]
Related #163

**Comment by mxbclang** [comment]
@manuelRod I’m happy to work an initial draft for this!

**Comment by mxbclang** [comment]
@manuelRod @felixarntz I've prepared an initial draft here: https://docs.google.com/document/d/1LyEDpAvqDcE_vAJNJRioe_2LrorOZt9NMoetBzYC3Vw/edit?usp=sharing. This follows the general format of the different sections in the overall Optimization guide in that it does not provide step-by-step instructions, but gives a broad overview of the issue and then directs the user to further reading. Let me know what you think.

**Comment by manuelRod** [comment]
@bethanylang should we recap more guides from different hosting? so we cover _most cases_. ?

**Comment by mxbclang** [comment]
Thanks for reviewing, @manuelRod! I replied to your comments.

The other sections in the [Optimization guide](https://wordpress.org/support/article/optimization/) tend to only include 4-5 examples per section, so I think it makes sense to keep in line with that and only share a few examples that are from hosting providers that we know are popular. I think adding in too many could make it difficult for folks to find what they're looking for.

@felixarntz Over to you!

**Comment by manuelRod** [comment]
Thanks for the changes @bethanylang I like it, good to go from my side!

**Comment by mxbclang** [comment]
@felixarntz Circling back on this – if you have a moment to take a look at [the doc](https://docs.google.com/document/d/1LyEDpAvqDcE_vAJNJRioe_2LrorOZt9NMoetBzYC3Vw/edit?usp=sharing) and give your okay, I can then work on getting this added.

**Comment by felixarntz** [comment]
@bethanylang Review the draft, overall looks solid to me! I left one comment with a suggestion.

@zzap We would like to add the section in [the doc](https://docs.google.com/document/d/1LyEDpAvqDcE_vAJNJRioe_2LrorOZt9NMoetBzYC3Vw/edit) to `https://wordpress.org/support/`. Is that something you could potentially help with? We're not entirely sure what the next steps would be.

**Comment by zzap** [comment]
Hi @felixarntz, thanks for pinging me. Yes, we can and should add that. I can help with everything needed. 

For now, the easiest thing to do is to open [new issue in Docs repo](https://github.com/WordPress/Documentation-Issue-Tracker/issues). I created [new label](https://github.com/WordPress/Documentation-Issue-Tracker/labels/performance) for you, `performance` so you can combine it with `developer documentation` or `user documentation`, depending on where you want to add your docs.

For the next steps, I'm gonna reply in slack as there is more context and we can definitely discuss the possible workflow at WCEU.

**Comment by mxbclang** [comment]
Thanks @zzap! I've opened https://github.com/WordPress/Documentation-Issue-Tracker/issues/358, but it doesn't appear that I can change the label; let me know if there's anything that I need to do there.

**Comment by manuelRod** [comment]
@bethanylang I see this already published, but without the links due to the external link policy (to clarify). Should we move forward with the module to point to the [article](https://wordpress.org/support/article/optimization/#autoloaded-options) or do we want to wait until clarification?

**Comment by mxbclang** [comment]
@manuelRod I'd like to hold on clarification for now, as I personally find the links quite important in terms of providing concrete next steps for users. But don't worry, this is on my radar to continue to follow up and file an issue to remove the "experimental" label once we confirm!

**Comment by OllieJones** [comment]
A bit late to this party (if I'm too late, Never Mind this remark). I suggest editing the article to mention persistent object caching. https://developer.wordpress.org/reference/classes/wp_object_cache/#persistent-caching

**Comment by mxbclang** [comment]
Thanks @OllieJones! Did you have a particular mention in mind? The intention behind updating this article was to provide some guidance to non-technical users on how to address the results of the autoloaded options health check, so just want to make sure that whatever we add will be helpful for that audience.

@manuelRod Once I get an idea on next steps from Ollie above, I'm going to mark this issue as closed since the documentation is now complete and linked in v1.3.0, released today. We have #409 for the question of removing the Experimental label from this module. Thanks!

**Comment by OllieJones** [comment]
Sure, here's a draft of what I'm thinking of. I'm cribbing it from a page on [developer.wordpress.org](https://developer.wordpress.org/reference/classes/wp_object_cache/#persistent-caching)  @tillkruss  should definitely review this stuff, it's his baby.

--------------
To the [Caching](https://wordpress.org/support/article/optimization/#Caching) section, add a subsection after **Browser caching.**

### Persistent Object Caching

**Persistent Object Caching** helps speed up page load times by saving on trips to the database from your web server.  For example, your site's options data needs to be available for each page view. Without it, your web server must read those options from the database to handle every page view. Those extra trips to the database slow down your web server and your database server.

For your site to use persistent object caching, your hosting provider must offer you a particular type of server: a cache server. Popular cache servers are [Redis](https://redis.io/) and [Memcached](https://memcached.org/).  Ask your hosting provider to help you install and configure a persistent object cache: they will recommend the right plugin. Here are some.
* [Memcached Object Cache](https://wordpress.org/extend/plugins/memcached/) provides a persistent backend for the WordPress object cache. A memcached server and the PECL memcached extension are required.
* [Redis Object Cache](https://wordpress.org/plugins/redis-cache/) supports the use of [Predis](https://github.com/nrk/predis) (PHP client library), [HHVM’s Redis extension](https://github.com/facebook/hhvm/blob/master/hphp/system/php/redis/Redis.php) and the [PECL Redis extension](https://pecl.php.net/package/redis) to provide a persistent backend for the WordPress object cache. [Redis](http://redis.io/) is required.
* [W3 Total Cache](https://wordpress.org/extend/plugins/w3-total-cache/) provides object level caching using disk, opcode or memcache(d) memory stores. W3TC also provides: browser, page and database caching, in addition to Content Delivery Network Support, Mobile Support, Minification and more.
* [LiteSpeed Cache](https://wordpress.org/plugins/litespeed-cache/) supports the use of Redis, Memcached, and LSMCD object caches. LSCWP also provides server-level full-page caching, support for browser cache and CDN, and other optimization features. [LiteSpeed Web Server](https://en.wikipedia.org/wiki/LiteSpeed_Web_Server) required.
 
-------------------
To the **Further Reading** section add this line item

* [WP Object Cache](https://developer.wordpress.org/reference/classes/wp_object_cache/#persistent-cache-plugins) -- Making the Object Cache persistent.

---------------------
To the [autoloaded options](https://wordpress.org/support/article/optimization/#autoloaded-options)  add a third one-sentence paragraph.

If you use a Persistent Object Cache, options (whether autoloaded or not) load faster and more efficiently.

**Comment by mxbclang** [comment]
Thanks @OllieJones! I'm actually going to open a few new issues for this: 1) to add this new documentation and 2) to link to it from the Autoloaded Options health check. I'll also move your proposed documentation into a Google doc and share it so that folks can more easily comment.

Closing this issue and will tag folks on the new ones.
