### ISSUE TITLE
Look into Client Hints

### ISSUE THREAD

**Issue by dainemawer** [WordPress/performance#244]
## Feature Description
This may be a stab in the dark, but it could be a real game changer. Client Hints are a set of HTTP headers we can use to subjectively serve resources based on the users bandwidth, device pixel ratio and device type and viewport. 

A client hint can be implemented in a number of different ways:

1. By setting headers on the server: `Accept: Viewport-Width`
2. Through the HTML meta tag: `<meta http-equiv="Accept-CH" content="Viewport-Width, Downlink">`

This functionality lends itself to responsive images as we can set headers on image resources on server, rather than on the frontend, saving parsing time and text transfer. Global support for [Client Hints is at around 71% according to caniuse.com](https://caniuse.com/?search=client-hints)

There is a great summary [here]( https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints#responsive_images) on how we could compress this:

```html
<picture>
  <source srcset="company-photo-256w.webp 256w,
                  company-photo-512w.webp 512w,
                  company-photo-768w.webp 768w,
                  company-photo-1024w.webp 1024w,
                  company-photo-1280w.webp 1280w"
          type="image/webp">
  <img srcset="company-photo-256w.jpg 256w,
               company-photo-512w.jpg 512w,
               company-photo-768w.jpg 768w,
               company-photo-1024w.jpg 1024w,
               company-photo-1280w.jpg 1280w"
       src="company-photo-256w.jpg"
       sizes="(min-width: 560px) 251px, 88.43vw"
       alt="The Sconnie Timber Staff!">
</picture>
```
into this:

```html
<img src="/image/sizes:true/company-photo.jpg"
     sizes="(min-width: 560px) 251px, 88.43vw"
     alt="SAY CHEESY PICKLES.">
```

Taking this approach would mean we could do the work of both `srcset` and `sizes` on the server, without generating the markup as Client Hints would handle the appropriate conditions for us. 

Further to this we could also look into making making image serving far more inclusive by providing use cases for Data Saving Modes, Device Memory and Slow Bandwidth.

**Comment by mukeshpanchal27** [comment]
> There is a great summary [here](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints#responsive_images) on how we could compress this:

@dainemawer The link return 404 can you please update it if you know it?

**Comment by dainemawer** [comment]
Hmm, looks like its been taken down :/

**Comment by graylaurenm** [comment]
Updated article link: https://web.dev/performance-optimizing-content-efficiency-client-hints/#responsive-images

**Comment by graylaurenm** [comment]
Wanted to note here that implementation of Client Hints would not negate the need for a relevant `sizes` definition. That's explicitly noted in the following two articles:
1. https://cloudfour.com/thinks/responsive-images-201-client-hints/
2. https://developer.chrome.com/blog/automating-resource-selection-with-client-hints/

I did find a plugin that's using these: https://wordpress.org/plugins/imghaste/

**Comment by westonruter** [comment]
Since Client Hints are HTTP request headers and since images are served by the web server and not WordPress (typically, multisite notwithstanding), would they be in scope? If WordPress PHP isn't serving the images, how would we handle the headers? The IMGHaste plugin loads images from a CDN, as I understand, so that's how they can utilize Client Hints.

**Comment by adamsilverstein** [comment]
This is similar to https://github.com/WordPress/performance/issues/14

Given the extra overhead of serving images from PHP rather than from the web server directly and the very wide compatibility of formats like WebP. While this is a great feature for image CDNs, it doesn't feel viable for core. Closing as such.
