### ISSUE TITLE
Clean up the package.json file

### ISSUE THREAD

**Issue by eugene-manuilov** [WordPress/performance#252]
## Feature Description

Currently, the `package.json` file contains information that is usually required for publishing npm packages on npmjs.org which is not the case for our plugin. The only needed information in the package.json file is `devDependencies` and `scripts`, everything else is redundant and can be removed to avoid a need to maintain that information in the future. Let's get rid of anything that is not needed for the plugin development and keep our `package.json` file in a good fit 😄

**Comment by felixarntz** [comment]
That works for me 👍 

Let's see what others think. It's a trivial change in any case, so unless there are concerns, we can probably get that done quickly. We need to keep in mind to then also remove these two files from the release documentation.

**Comment by felixarntz** [comment]
@eugene-manuilov Looks like now that I've merged the PR our CI check for JS broke somehow: https://github.com/WordPress/performance/runs/5684008563 Can you check?

**Comment by eugene-manuilov** [comment]
@felixarntz, looks like one of installed packages requires `name` property to be present in the `package.json` file. I have added it back in #265 PR. Do you mind reviewing it?
