### ISSUE TITLE
Enqueued Assets check does not appear in Site Health

### ISSUE THREAD

**Issue by mxbclang** [WordPress/performance#257]
## Bug Description

I've tested on multiple sites and the Enqueued Assets check never seems to appear in Site Health when activated.

## Steps to reproduce

1. Install and activate the plugin
2. Go to Settings > Performance and turn on Audit Enqueued Assets and click Save Changes
3. Go to Tools > Site Health; the check does not appear

## Screenshots

Video: https://jmp.sh/98BittW

## Additional Context

 - PHP Version: 8.0.11
 - OS: macOS Monterey
 - Browser: Chrome
 - Plugin Version: 1.0.0-beta.3
 - Device: Macbook Pro

**Comment by mxbclang** [comment]
@felixarntz wasn't able to recreate this, but @adamsilverstein and I have. 

I tried to recreate today and I am now seeing the Enqueued styles check on one of my test sites, but still not seeing Enqueued scripts. On the other test site, I still don't see either check.

## Test site 1: yeziza.us.instawp.xyz

<details>
<summary>Site Health</summary>

### wp-core ###

version: 5.9.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /index.php/%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/zeromosumomopahe/webapps/yeziza
wordpress_size: 46.81 MB (49086175 bytes)
uploads_path: /home/zeromosumomopahe/webapps/yeziza/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /home/zeromosumomopahe/webapps/yeziza/wp-content/themes
themes_size: 8.72 MB (9143438 bytes)
plugins_path: /home/zeromosumomopahe/webapps/yeziza/wp-content/plugins
plugins_size: 350.80 KB (359219 bytes)
database_size: 2.67 MB (2801664 bytes)
total_size: 58.55 MB (61390496 bytes)

### wp-active-theme ###

name: Twenty Twenty-Two (twentytwentytwo)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor, wp-block-styles, editor-style
theme_path: /home/zeromosumomopahe/webapps/yeziza/wp-content/themes/twentytwentytwo

### wp-themes-inactive (2) ###

Twenty Twenty: version: 1.9, author: the WordPress team
Twenty Twenty-One: version: 1.5, author: the WordPress team

### wp-plugins-active (1) ###

Performance Lab: version: 1.0.0-beta.3, author: WordPress Performance Group

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: version: 4.2.2, author: Automattic
Hello Dolly: version: 1.7.2, author: Matt Mullenweg

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-81-generic x86_64
httpd_software: Apache/2.4.52 (Unix) OpenSSL/1.1.1f
php_version: 7.4.28 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.4.24-MariaDB-1:10.4.24+maria~focal-log
client_version: mysqlnd 7.4.28
max_allowed_packet: 16777216
max_connections: 100

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/zeromosumomopahe/webapps/yeziza/wp-content
WP_PLUGIN_DIR: /home/zeromosumomopahe/webapps/yeziza/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

</details>

Only seeing Enqueued styles:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/12189958/159954824-808af446-3e3d-4738-8d1c-e3777b66a092.png">

<img width="791" alt="image" src="https://user-images.githubusercontent.com/12189958/159934526-d48b4edd-3db4-42bf-aa5c-19300c2af572.png">

This site only has the Performance Lab plugin installed and activated and is using WP 5.9.2 with the Twenty Twenty-Two theme.

## Test site 2: bethanychobanianlang.com

<details>
<summary>Site Health</summary>

### wp-core ###

version: 5.9.2
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: 206.85 MB (216902747 bytes)
uploads_path: /var/www/html/wp-content/uploads
uploads_size: 139.01 MB (145759110 bytes)
themes_path: /var/www/html/wp-content/themes
themes_size: 4.83 MB (5066966 bytes)
plugins_path: /var/www/html/wp-content/plugins
plugins_size: 43.42 MB (45527004 bytes)
database_size: 10.98 MB (11517952 bytes)
total_size: 405.10 MB (424773779 bytes)

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.9
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, editor-styles, widgets, menus, editor-style
theme_path: /var/www/html/wp-content/themes/twentytwenty
auto_update: Disabled

### wp-themes-inactive (2) ###

Artpop: version: 1.0.9, author: Design Lab, Auto-updates enabled
Twenty Twenty-Two: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.7.2

### wp-plugins-active (1) ###

Performance Lab: version: 1.0.0-beta.3, author: WordPress Performance Group, Auto-updates disabled

### wp-plugins-inactive (9) ###

Akismet Anti-Spam: version: 4.2.2, author: Automattic, Auto-updates enabled
DreamHost Panel Login: version: 1.0.0, author: DreamHost, danielbachhuber, Auto-updates disabled
Fonts Plugin | Google Fonts Typography: version: 3.0.14, author: Fonts Plugin, Auto-updates enabled
Health Check & Troubleshooting: version: 1.4.5, author: The WordPress.org community, Auto-updates disabled
Proxy Cache Purge: version: 5.1.0, author: Mika Epstein, Auto-updates disabled
Redirection: version: 5.2.3, author: John Godley, Auto-updates enabled
Site Kit by Google: version: 1.70.0, author: Google, Auto-updates enabled
Site Kit by Google Tester: version: 1.6.0, author: Google, Auto-updates enabled
Web Stories: version: 1.18.1, author: Google, Auto-updates enabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 300M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
gd_version: 2.3.0
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.4.0-88-generic x86_64
httpd_software: Apache/2.4.41 (Ubuntu)
php_version: 8.0.11 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 300
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: -1
upload_max_filesize: 300M
php_post_max_size: 300M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.26
client_version: mysqlnd 8.0.11
max_allowed_packet: 67108864
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

</details>

On my personal website, https://www.bethanychobanianlang.com/, I'm still not seeing either check:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/12189958/159954885-9fcf5322-40b7-46f9-8ce6-7ab9939412dd.png">

<img width="750" alt="image" src="https://user-images.githubusercontent.com/12189958/159954924-608b1519-c0a4-49c2-92d5-a3c8fc72eaf3.png">

This site is using multiple plugins and the Artpop theme. I tried Troubleshooting Mode with just the Performance Lab plugin activated and the Twenty Twenty theme and still don't see the Enqueued assets checks in Site Health.

**Comment by manuelRod** [comment]
@bethanylang I'm gonna try to reproduce it, but as far as I can see in your video, after activating the test checkbox, if you don't visit your website (frontend), assets won't be audited, therefore checks won't popup in Site Health Screen. 
This would be fixed in one of the proposed enhancements [#134 ](https://github.com/WordPress/performance/issues/134)

**Comment by mxbclang** [comment]
@manuelRod Thank you for clarifying! To confirm, with #134, the user would no longer need to visit the front-end of their site after activating this module in order for it to display in Site Health?

**Comment by manuelRod** [comment]
@bethanylang it will depend on the final implementation, but that was one of the main ideas (as far as I understood)

**Comment by mxbclang** [comment]
Thanks @manuelRod! I'll close this for now but make a note to recheck after #134 is merged.
