### ISSUE TITLE
WebP are not created when the default editor does not support WebP

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#258]
## Bug Description

Given 2 image editors: `WP_Image_Editor_Imagick` and `WP_Image_Editor_GD` and the default is `WP_Image_Editor_Imagick` if the default editor does not supports WebP but `WP_Image_Editor_GD` it does support WebP the tests on Site Health would return that the site supports WebP, however the current implementation does handle this case instead it uses the default image editor regardless of the support.

## Support tickets:

- https://wordpress.org/support/topic/webp-image-not-created-2/
- https://wordpress.org/support/topic/webp-image-not-created/

**Comment by mitogh** [comment]
Adding a possible workaround for current users experiencing this problem: 

This workaround is only supported on PHP 7.1 and above due the usage of anonymous functions.

```php
add_filter(
	'wp_image_editors',
	function ( $editors ) {
		usort(
			$editors,
			static function( $editor ) {
				if ( call_user_func( array( $editor, 'supports_mime_type' ), 'image/webp' ) ) {
					return -1;
				}

				return 1;
			}
		);
		return $editors;
	},
	10
);
```

**Comment by adamsilverstein** [comment]
Related ticket where current core implementation for editor check can fail in some cases: [core.trac.wordpress.org/ticket/54476](https://core.trac.wordpress.org/ticket/54476) / https://github.com/WordPress/wordpress-develop/pull/1918
