### ISSUE TITLE
Removal of release branches

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#275]
## Feature Description

Currently, the project still has the branches for the releases like `release/1.0.0-beta.1` the idea for this issue is to remove the branches as soon as the release has been completed, as there's no point in keeping the branches around if not required.

In a scenario where a hotfix is required a branch can always be created out of the tags for that particular release.

So the removal of the branch should happen only if a tag has been created for the release branch for an easier rollback process.

**Comment by swissspidy** [comment]
Doesn't really hurt to keep this branches, closing this for now.
