### ISSUE TITLE
Featured Image does not use WebP

### ISSUE THREAD

**Issue by pixel-paul** [WordPress/performance#283]
## Bug Description

Not exactly a bug, more of a question:

Should the featured image also be WebP?

## Steps to reproduce

1. Create a post
2. Add an image block and upload an image
3. Add a featured image
4. Save and view post
5. Featured image is jpg, post block image is webp

## Screenshots
![Screenshot from 2022-04-06 11-03-25](https://user-images.githubusercontent.com/389303/161951390-c246bcf7-df54-4d07-b7a9-0e4abaf0735c.png)

## Additional Context

 - PHP Version: 7.4
 - OS: RHEL 8.5
 - Browser: Firefox
 - Plugin Version: 1.0.0 rc1
 - Device: Desktop

**Comment by mxbclang** [comment]
Hi @pixel-paul! Right now, whether or not the featured image is converted to WebP is dependent on how your theme inserts images into `the_content`. Any images inserted *outside* of `the_content` will *not* be replaced by WebP.

We do have a GitHub issue here: https://github.com/WordPress/performance/issues/155 which could be used as a mechanism to enable the replacement of images outside of `the_content`.

Let me know if you have any other questions.

**Comment by pixel-paul** [comment]
Thanks @bethanylang :)

**Comment by anteksiler** [comment]
This would be a great addition! #155 seems to be closed.

**Comment by mxbclang** [comment]
Hi @anteksiler! #155 is still open and we're still exploring the best approach there. Feel free to review and comment in [the proposal document](https://docs.google.com/document/d/1CSi61ky0b9A84VOYkTXCE7wfl3QUSCtuHzF78T3t0CU/edit#heading=h.2aigy8pb1r18) with your thoughts!
