### ISSUE TITLE
Only use smaller file size based on opt-in since it is not part of the core feature scope

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#286]
Follow-up to #186: While this enhancement certainly makes sense here, we need to consider that the WebP by default implementation for WordPress core as of now is not going to select the smaller file size, as that implementation doesn't even store file sizes for the generated images.

Due to this, I would advise we make this enhancement opt-in at this point, since otherwise it would explicitly behave differently from the core implementation, which to a degree would defeat the primary purpose of this plugin which is testing future core features. It may be that we eventually decide to add this to the core implementation, at which point we could change it to be enabled by default here as well, but right now this is clearly different behavior, so I think we should keep this piece as opt-in.

I suggest we add a filter to enable it, e.g. `webp_uploads_prefer_smaller_file`.

cc @jjgrainger @mitogh @adamsilverstein

**Comment by adamsilverstein** [comment]
> as that implementation doesn't even store file sizes for the generated images.

Note that the current core implementation/patch does include file size (via the new [`wp_filesize`](https://github.com/WordPress/wordpress-develop/pull/2393/files#diff-c8719b0a67432e25fb08dad2ad0d081998f835186937dba96966f592bc9d9706R422)) data. Still I would be in favor of a filter to control the behavior.

This might be important behavior to include especially after [confirming](https://github.com/WordPress/performance/issues/7#issuecomment-1092975500) that (especially full sized) WebP versions of JPEG uploads might be larger than the original.
