### ISSUE TITLE
Plugin Asset Handler - load no asset unless needed

### ISSUE THREAD

**Issue by estlacksensory** [WordPress/performance#296]
Can "lazy loading" be applied to plugin management? When a user installs a plugin, WordPress attempts to load all assets (images, scripts (server-side, client)) on page load, regardless if those assets are needed or not.

If a user decides to install a plugin for purpose X, to run on page Y, on user interaction Z. Then only under those circumstances, should the page attempt to load those scripts. This is an oversimplification. But WordPress handlers for plugin management currently, call for loading of all assets regardless of need. Core Web Vitals identifies plugin-related scripts as problematic, but often times, those assets might not be needed.

**Comment by swissspidy** [comment]
It's really up to the plugins to only enqueue things only when needed. It's really impossible for WordPress to know whether something is going to be used on a specific page or interaction or not.
