### ISSUE TITLE
When an image is edited, perform updates only to the specified target

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#299]
## Feature Description

This is a follow up issue from 

- #158 
- #235 

When an image is edited a user is able to select multiple targets from the edit screen (see attached screenshot).

![2022-04-14_21-03](https://user-images.githubusercontent.com/3921289/163506176-cd96d372-3435-45cd-9318-1b0733f08336.png)

The edits can happen to:

- All the images
- Thumbnail - Only the thumbnail image is updated
- All sizes except the thumbnail 

When either of those targets are selected, make sure that only the target is modified and subsequent edits uses the specified source.

**All images**

This is the current behavior and when an edit takes place all the subsizes as well with the full image source is modified applying the specified updates, all the available mime types should reflect this change as well besides the default mime type.

**Thumbnail**

Only the thumbnail size is modified, the rest of the image sizes remains the same, the thumbnail and sources for the thumbnail should reflect this change making sure all the specified mime types create a source with the same details as the primary mime type for the image.

**All sizes except the thumbnail**

This behavior is similar to all images, with the difference that the changes shouldn't be applied to  thumbnail image sizes and sources for that subsize.

All the available subsizes, including the full image size should be modified with the specified changes, and the sources property should be created for all the specified mime types.

**Comment by felixarntz** [comment]
Fixed via #301.
