### ISSUE TITLE
Dominant color background for lazy-loading images needs to back fill existing images

### ISSUE THREAD

**Issue by pbearne** [WordPress/performance#309]
## Feature Description

Currently, the dominant colour background for lazy-loading images code only adds to new/edited images
I believe we should backfill the existing images

I have created some code that adds a run once cron task for each image that does have the data when the image is loaded on a page

https://github.com/WordPress/performance/pull/303

Is this the correct approach?

There are filters that can be used to disable or to force it to run as part of the page load (this slows the page down the first time it is called after the code is added)

**Comment by estlacksensory** [comment]
I think dominant color should be up to the designer (maybe as a checkbox option). Is this an ADA or performance consideration? It can be a bit problematic to the site design if dominant color appears where it wasn't initially intended. Dominant Color project seems to be moving from performance to the design space, IMHO. Recommend checking with more designers to see what they might have to say.

**Comment by joemcgill** [comment]
@pbearne I see that the PR you linked to was closed as "not needed". Should this issue be closed as not planned?
