### ISSUE TITLE
Define owners for each module

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#310]
This is a proposal to define ownership for each module in the Performance Lab plugin. This should help with the following:
* Have clearly defined points of contact per module, someone to reach out to in case questions come up.
* Have dedicated code owners per module, since the focus area leads cannot be expected to know every module inside out, especially with a growing number of modules.
* Have people to monitor a to incoming issues related to the module.
* Have people to take responsibility for eventually moving the module towards a WordPress core merge.

Every module should at least have one owner, but having 2-3 is encouraged if possible. Of course the above points are not going to be entirely dependent on the module owners, there will always be support from the wider performance team and community. Yet, it is crucial to have someone to keep things moving over time.

Let's discuss. If there is consensus on this idea, a good first step as part of this issue would be to define the owners for the existing modules and add them as `CODEOWNERS` for the respective module directories.

**Comment by felixarntz** [comment]
Pinging a few of you that have previously worked quite a bit on the existing modules here, to provide feedback on the proposal. What do you think about the above?

@adamsilverstein @mitogh @eugene-manuilov @tillkruss @spacedmonkey @manuelRod

**Comment by tillkruss** [comment]
I agree and will gladly own all object cache modules.

**Comment by mitogh** [comment]
I like this approach as would allow iterating faster by having more owners as new modules are added as well, as you described is not easier to keep track of which changes are happening under a specific focus area. @felixarntz

**Comment by eugene-manuilov** [comment]
Yes, this is a good idea. I think we definitely need at least 2 owners per module to make sure that we don't have a bottleneck if a module owner disappears or is offline for some period of time.

**Comment by manuelRod** [comment]
I agree too.

**Comment by spacedmonkey** [comment]
> I agree and will gladly own all object cache modules.

Me too.

**Comment by felixarntz** [comment]
Thanks all for the replies so far! I've opened #317 with a take on the `CODEOWNERS` file to define the module owners. Please review.

I'd also like to ask for additional support for the following modules:
* **Site Health: Audit Autoloaded Options**
* **Site Health: Audit Enqueued Assets**

Based on the work so far, these are currently owned by only @manuelRod. Is anyone here interested and willing to be an additional code owner for one or both of them? Per @eugene-manuilov's comment above, it would be best to have more than one owner for each module.
