### ISSUE TITLE
"More info about performance optimization" should link to #database-tuning

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/performance#312]
Right now it's not linking to anything specific. Also nothing specifically talks about autoloaded options in the article, so best option seems to be https://wordpress.org/support/article/optimization/#database-tuning 
 

![image](https://user-images.githubusercontent.com/10998875/164275705-598a5109-0b85-498b-8095-cf62f5ea1ba7.png)

**Comment by mxbclang** [comment]
Hi @LukaszJaro Good catch! We're working on building out autoload-specific documentation in #234, but until that's ready to go, I agree that we should link this to https://wordpress.org/support/article/optimization/#database-tuning. We'll make that update. Thank you again!
