### ISSUE TITLE
Define plugin release cadence

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#320]
After #300, this is the second of two critical issues defining how we're going to release new versions of the Performance Lab plugin. As part of that first issue, it was decided to follow WordPress core's versioning approach, i.e. the next releases will be 1.1.0, 1.2.0, 1.3.0, and so on, up until 1.9.0, before it will become 2.0.0.

We also have to decide how regularly we want to publish new stable releases. WordPress core publishes them every 3-4 months typically, which I believe makes sense for that project, but not as much for a plugin like ours. On the other hand, Gutenberg for example publishes stable releases every 2 weeks.

During the beta and RC phase, we also published releases every 2 weeks, but now that the plugin itself is stable we need to re-evaluate that, which is what this issue is for. I would say 2 weeks would be the minimum, as anything more regular than that would mean too much of a maintenance burden for probably very little benefit. (Of course, hot fix releases are not subject to whatever we decide here, they would be published as needed.)

To throw some initial options out there for considerations:
1. Every 2 weeks
2. Every 4 weeks
3. Every 6 weeks
4. Every 8 weeks

When thinking about the best cadence, let's consider both how many features, enhancements, and fixes can realistically be landed in each time frame vs how much additional maintenance is needed the more regularly we publish a release. The release always involves a couple of administrative processes around managing milestones and branches, as well as the release party Slack chat on the day of the release.

**Comment by felixarntz** [comment]
I think it might make sense to have a vote on this issue eventually, but let's briefly check first whether the initial options provided even make sense or whether there are additional suggestions for which cadences to consider.

Also, just for reference: The 1.0.0 release was on April 18, which means that technically today is the 2-week mark after that. Which doesn't mean the "Every 2 weeks" option is out of question, it just means we missed it for this one cycle :) Any of the other options we could actually stick to given we make a decision on this soon.

**Comment by mxbclang** [comment]
_Please vote for a release cadence using the following emojis. Voting will close on **Monday, May 9, 2022 at 5pm UTC**._

* 👍 for every 2 weeks
* 👎 for every 4 weeks
* 😄 for every 6 weeks
* 🎉 for every 8 weeks
* ❤️ for monthly, e.g. second Monday of the month

**Comment by mxbclang** [comment]
**Voting is now closed.**

Based on **7** heart votes, we'll proceed with monthly releases. @felixarntz and I will work to define the exact day (e.g. second Monday of the month) and update here. Thanks, all!

**Comment by mxbclang** [comment]
Confirmed that releases will occur on the **third Monday of every month**, beginning with next Monday, 16 May. We'll plan to hold release party chats on the third Monday of the month at 5pm UTC in the #performance Slack channel.

**Comment by felixarntz** [comment]
[Milestones](https://github.com/WordPress/performance/milestones) for the next couple releases (for now up to 1.4.0 in August) have been added accordingly.
