### ISSUE TITLE
Update Settings language for health checks

### ISSUE THREAD

**Issue by mxbclang** [WordPress/performance#326]
## Feature Description

Currently, the Persistent Object Cache health check is the only one of the four health checks in the plugin that includes that phrase on the Settings screen:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/12189958/166720625-f5652567-c72f-4045-9bc7-defe0aafb03c.png">

The other health checks should be updated to add the word "Health Check" to make them easier to parse without having to read their description text.

**Comment by mukeshpanchal27** [comment]
I have removed the `Needs Dev` label as @OllieJones has already submitted a PR for this and also linked the PR to this issue.

**Comment by mukeshpanchal27** [comment]
Punting to `1.4.0` as per Felix's comment on PR.

**Comment by felixarntz** [comment]
Fixed via #423
