### ISSUE TITLE
Old content images not show in webp format

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#339]
## Bug Description

As discussed on #325. 

Some old content images already have WebP format images but they will not load because the new image has a different attachment ID than the old attachment ID.

## Steps to reproduce
1. Activate the Performance Lab plugin
2. Import posts and attachments using theme unit test data https://codex.wordpress.org/Theme_Unit_Test
3. Go to Block Image post.
4. It will have various images on the post and those are different sizes for the images.

**Comment by mxbclang** [comment]
:wave: @mukeshpanchal27 Can you confirm if this issue is currently in the Performance Lab plugin or if it's specific to PR #325? #325 is a WIP PR that has been put on hold for now as we explore some alternatives, so this issue/PR isn't necessary unless this is an issue that is in the Performance Lab plugin in its current release.

cc @felixarntz @adamsilverstein

**Comment by mukeshpanchal27** [comment]
@bethanylang Yes, this issue is for the Performance Lab plugin. Please follow the steps to reproduce the issue.

Check screenshot and issue here: https://github.com/WordPress/performance/pull/325#issuecomment-1118474023

**Comment by mxbclang** [comment]
Thanks for clarifying, @mukeshpanchal27! I'm assigning this to someone on our team to take a look.

**Comment by adamsilverstein** [comment]
> Some old content images already have WebP format images but they will not load because the new image has a different attachment ID than the old attachment ID.

to clarify, does this mean the image class ID is no longer accurate? 

> Import posts and attachments using theme unit test data codex.wordpress.org/Theme_Unit_Test

Is that a normal import process and did you "import media"?

I feel like this is a valid problem and fix, however it is somewhat unrelated to WebP support. Wouldn't this also cause srcset to not be generated correctly for images (without WebP). If so, this is really more of an importer problem - it should probably correct the class IDs during import, what do you think?

**Comment by felixarntz** [comment]
@mukeshpanchal27 Apologies for not reviewing this issue earlier, but after my review of the PR in https://github.com/WordPress/performance/pull/340#pullrequestreview-986759883, I wonder whether this is something that we realistically can (and should) address. 🤔 

My main question is: Why do the post images have the incorrect attachment ID classes in the first place? To me that seems to be the underlying problem. I'd argue the theme unit test data is not fully appropriate in that regard, or maybe this needs to be implemented as an enhancement to the WP Importer. But I feel like patching around that here would not address the problem at its root. More importantly though, I think the large performance cost of what we would need to do to address it makes it infeasible to do in the Performance Lab plugin IMO.

Let me know what you think.

**Comment by mukeshpanchal27** [comment]
> to clarify, does this mean the image class ID is no longer accurate?
Right.

> Is that a normal import process and did you "import media"?
Yes. I import media.

> I feel like this is a valid problem and fix, however it is somewhat unrelated to WebP support. Wouldn't this also cause srcset to not be generated correctly for images (without WebP). If so, this is really more of an importer problem - it should probably correct the class IDs during import, what do you think?

Yes, I think. Imported does not change updated attachment ID in the IMG tag class.

**Comment by mukeshpanchal27** [comment]
@felixarntz and @adamsilverstein Thanks for your review and comment.

I think it was the WP Imported issue that they doesn't change the updated attachment ID in IMG tag classes. So do you think i/we have to create this issue in WP Importer if they solve this issue then we don't need to work on this ticket and PR?

**Comment by adamsilverstein** [comment]
> So do you think i/we have to create this issue in WP Importer if they solve this issue then we don't need to work on this ticket and PR?

It is worth raising and proposing fixing there, yes. 

My guess is this also prevents the `srcset` attribute from being applied as well (because the image meta cannot be located to find the available sizes). so this is a wider problem and not something specific to the performance plugin.

**Comment by mukeshpanchal27** [comment]
I quickly checked on the WP Import code base and they change only the old to new image URL in https://github.com/WordPress/wordpress-importer/blob/master/src/class-wp-import.php#L1269-L1280 function with an update query.

`$wpdb->query( $wpdb->prepare( "UPDATE {$wpdb->posts} SET post_content = REPLACE(post_content, %s, %s)", $from_url, $to_url ) );`

There may be some major work for WP Importer to change the old image class to a new image class.

**Comment by felixarntz** [comment]
@mukeshpanchal27 Could you open an issue on the WP Importer repo to address this change? I think that would be a good path forward here. Once that issue has been opened, I'd say we can close this issue here with a reference to it.

**Comment by mxbclang** [comment]
@mukeshpanchal27 @akshitsethi Checking in on this one – I see that Akshit is assigned, but it looks like the next step was for Mukesh to open an issue in the WP Importer repo. Has that been done? If so, can you please share a link to that issue here? And what are the next steps and who is handling them?

**Comment by mukeshpanchal27** [comment]
This issue is open in the WordPress Importer repo [#129](https://github.com/WordPress/wordpress-importer/issues/129).

I'm going to mark this issue as closed.
