### ISSUE TITLE
Improve object caching in core

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#34]
- ~Add query cache to `WP_User_Query` class ([40613](https://core.trac.wordpress.org/ticket/40613))~
- In `wp_term_query` on cache ids ([37189](https://core.trac.wordpress.org/ticket/37189))
- Cache the results of the `posts_request_ids` query ([22176](https://core.trac.wordpress.org/ticket/22176))
- ~Add caching to comment feed in `WP_Query` ([36904](https://core.trac.wordpress.org/ticket/36904))~
- ~Term exists should use `get_terms` internally ([36949](https://core.trac.wordpress.org/ticket/36949))~
- ~Remove cache time limitation in `WP_Term_Query` ([54511](https://core.trac.wordpress.org/ticket/54511))~
- ~Add `wp_cache_*_multiple` functions ([54574](https://core.trac.wordpress.org/ticket/54574))~

**Comment by tillkruss** [comment]
Ping @spacedmonkey

**Comment by tillkruss** [comment]
See https://github.com/WordPress/wordpress-develop/pull/2018

**Comment by tillkruss** [comment]
Moved to #77

**Comment by tillkruss** [comment]
Moved to  #78

**Comment by tillkruss** [comment]
Moved to  #79

**Comment by tillkruss** [comment]
Moved to #80.

**Comment by eclarke1** [comment]
Just popping this [Type] Overview issue into 'In Progress' as the 4 x subtasks (#77 #78 #79 #80 ) are party started, hope that's ok, let me know if there's any issues with this :)

**Comment by felixarntz** [comment]
All items listed in the issue description have been completed a while ago, hence closing this issue as completed.
