### ISSUE TITLE
`accepted_args` parameter issue in `add_action`

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#342]
## Bug Description

In the admin_menu action we use `add_action( "load-{$hook_suffix}", 'perflab_load_modules_page', 10, 0 );` action which tell user that it's the number of arguments this function accepts and we use 0 so this function will not take any arguments. But on function we use two arguments https://github.com/WordPress/performance/blob/trunk/admin/load.php#L49, https://github.com/WordPress/performance/blob/trunk/tests/admin/load-tests.php#L100 and https://github.com/WordPress/performance/blob/trunk/tests/admin/load-tests.php#L109

It will miss guide users so if I'm not wrong do we need to add 2 in the accepted_args(4th parameter) of the action?

Additionally, we have to add a return doc for the `perflab_add_modules_page` https://github.com/WordPress/performance/blob/trunk/admin/load.php#L13-L35 something like the below context.

`* @return string|false The resulting page's hook_suffix, or false if the user does not have the capability required.`

**Comment by mxbclang** [comment]
Closing this issue per @felixarntz's comment on #343.
