### ISSUE TITLE
Promote object caching in Site Health

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#35]
Recommend the use of an object cache under Site Health for sites with non-trivial amounts of data.

- Detect available extensions and make recommendations
  - [See AMP](https://github.com/ampproject/amp-wp/blob/5405daa38e65f0ec16ffc920014d0110b03ee773/src/Admin/SiteHealth.php#L227-L330)
- What are the criteria for running the check?
- Allow WooCommerce (etc.) to enable running the check?

>Would you see this as being something that checks for APCu, or a reachable memcache / redis install?

**Comment by tillkruss** [comment]
Per @westonruter:

>There is heavy transient usage in the AMP plugin. Whenever there is an img that lacks a width and height attribute, the plugin will fetch the image to obtain the dimensions and store them in a transient. Also, during stylesheet processing, it will use php-css-parser to parse the stylesheets and since the parsing is computationally-expensive, it stores the result in transients as well. So without persistent object caching, the wp_options table can get huge indeed.

**Comment by eclarke1** [comment]
@tillkruss if it's ok I just removed the 'Needs Discussion' label here as it looks like it's been started with a draft PR
