### ISSUE TITLE
Improve audit wp_options results with Autoload top list

### ISSUE THREAD

**Issue by merkys7** [WordPress/performance#350]
## Feature Description

Improve audit wp_options results with Autoload top list.

At the moment, it's not clear what options could potentially slow down your website.
Introducing Autoload top list would greatly help to diagnose slow loading websites due to overloaded `wp_options` table

**Comment by mxbclang** [comment]
@manuelRod Tagging you in on this suggestion from WCEU Contributors Day.

**Comment by rlankhorst** [comment]
Some tools that can help to clean this up would be really great. I noticed that some options in the list are very short (just a 10 character string for example) and others are very large. Ordering based on size would be helpful I think. Additionally, based on the used prefixes, it could be deduced if the option is from a deactivated plugin. 

I think it would be helpful to:
- distinguish between large and very short options, which have less impact on memory usage
- options from deactivated plugins. 

E.g. I have removed a large list of BBPress options and transients (9000!), as BBPress was not active anymore.

**Comment by merkys7** [comment]
@rlankhorst I totally agree with your points. 
Regarding the Transients, I have opened a separate issue with sample SQL queries. https://github.com/WordPress/performance/issues/349
During the WordCamp, we have discussed that such enhancements should be done in iterations
