### ISSUE TITLE
Use dominant color as background color in media modal

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/performance#354]
## Feature Description
Use dominant color as background color in media modal for preview thumbnail. 

<img width="1203" alt="Screenshot 2022-06-02 at 16 59 53" src="https://user-images.githubusercontent.com/237508/171674005-4ad62af5-1115-4500-971d-d695e45b0f69.png">

Follow on from https://github.com/WordPress/performance/issues/19 https://github.com/WordPress/performance/pull/282

**Comment by mxbclang** [comment]
@felixarntz Looks like this needs to push to 1.4.0 as there isn't a PR, can you confirm?

**Comment by pbearne** [comment]
I don't think we can add this to the performance plugin as it needs a core patch 
https://github.com/WordPress/wordpress-develop/compare/trunk...pbearne:wordpress-develop:use_dominat_color_in_media_libary?expand=1

**Comment by felixarntz** [comment]
Thanks @bethanylang @pbearne. Definitely won't make it in time for 1.3.0, but if it's not feasible in the plugin anyway, let's remove the milestone entirely and keep this simply as a tracking task for the core patch work.

**Comment by adamsilverstein** [comment]
> I don't think we can add this to the performance plugin as it needs a core patch
https://github.com/WordPress/wordpress-develop/compare/trunk...pbearne:wordpress-develop:use_dominat_color_in_media_libary?expand=1

Thanks for sharing this code sample @pbearne I see how adding this in core would be much easier, however I'm going to dig in a little more to see if we can add the correct classes to the template. A possible solution would be to unhook core's template and insert our own instead (`add_action( 'admin_footer', 'wp_print_media_templates' );`)

**Comment by estlacksensory** [comment]
I didn't know there was a git repo for performance lab. Issue with dominant color reading transparent pixels incorrectly and then adding background color to them. Deactivated this, to an extent. Rest of performance lab seems to be working nicely though. https://github.com/estlacksensory/WP-Performance-Lab

**Comment by estlacksensory** [comment]
Is this "dominant color" idea only supposed to exist in the media library? It keeps adding "dominant colors" to PNG images etc., in site layouts etc., where there shouldn't be solid colors, according to design. I keep deinstalling updates of Performance lab and reverting files back to version mentioned in comment above. I'm advising admins and other users against updating this plugin until this is sorted out.

This feature might be useful if it was an option that could be activated or not - per user/admin choice - checkbox?

I'll do a pull or a fork or something if I have time, maybe. Thanks.

**Comment by felixarntz** [comment]
@estlacksensory The dominant color module adds background colors to newly uploaded images throughout the site. This should only have any visual effect when those images haven't loaded yet though. If you see any adverse effects, could you please open a separate bug issue describing the problem?

Separately, you can always disable the Dominant Color Images module, by navigating to _Settings > Performance_ and toggling off the corresponding checkbox.

**Comment by estlacksensory** [comment]
Thanks @felixarntz - perhaps this was fixed with a recent update. I'll describe in further detail where I think someone else opened a bug report.

**Comment by pbearne** [comment]
I think I have a way to do this.

We can add some JS to replace this script with our own by

Would that be OK with core?

```

add_action( 'admin_enqueue_scripts', function (){
	$handle = 'dominant-color-admin-styles';
	// PHPCS ignore reason: Version not used since this handle is only registered for adding an inline style.
	// phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion
	wp_register_style( $handle, false );
	wp_enqueue_style( $handle );
	$custom_css = '.wp-core-ui .attachment-preview[data-dominant-color]:not(.has-transparency) { background-color: var(--dominant-color); }';
	wp_add_inline_style( $handle, $custom_css );
});

add_action( 'admin_print_footer_scripts', function (){
?>
<script>
	(function() {
		var s = jQuery( '#tmpl-attachment' )
		var n = s[0].innerText.replace( '{{ data.orientation }}"', '{{ data.orientation }} {{ data.hasTransparencyClass }}"	data-dominant-color="{{ data.dominantColor }}" data-has-transparency="{{ data.hasTransparency }}" style="--dominant-color: #{{ data.dominantColor }};"')
s.replaceWith( '<script type="text/html" id="tmpl-attachment">' + n  );
	}());
</script>
<?php

}, 1000 );

add_filter( 'wp_prepare_attachment_for_js', function( $response, $attachment, $meta ){

	$response['dominantColor'] = '';
	if ( isset( $meta['dominant_color'] ) ) {
		$response['dominantColor'] = $meta['dominant_color'];
	}
	$response['hasTransparency'] = '';
	$response['hasTransparencyClass'] = '';
	if ( isset( $meta['has_transparency'] ) ) {
		$response['hasTransparency'] = $meta['has_transparency'];
		$response['hasTransparencyClass'] = $meta['has_transparency'] ? 'has-transparency' : 'not-transparent';
	}

	return $response;
}, 10, 3 );
```

**Comment by joemcgill** [comment]
Thanks @pbearne. I copied that snippet into the `/plugins/dominant-color-mages/hooks.php` file and it does seem to add placeholder background in the media library. I assume that this still would only add background colors for images uploaded while the plugin is active, otherwise the metadata won't exist, which seems like a fine first step.
