### ISSUE TITLE
Object cache utility functions

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#37]
WP VIP has several wrappers for core functions that are cached, should we adopt some?

- https://github.com/Automattic/vip-go-mu-plugins/blob/master/vip-helpers/vip-utils.php
- https://github.com/Automattic/vip-go-mu-plugins

**Comment by tillkruss** [comment]
@sboisvert

<img width="828" alt="Screen Shot 2021-12-03 at 10 40 45 AM" src="https://user-images.githubusercontent.com/665029/144655703-89134020-72a9-4905-95b6-09f59e44d846.png">

**Comment by sboisvert** [comment]
Thanks!

I'm sure we can clean up this ramble if thoughts into something cohesive :)

**Comment by swissspidy** [comment]
I don't see a need in core itself for a fancy `vip_safe_wp_remote_request` equivalent that does things like caching and exponential backoff etc. And for plugins and projects, the requirements will always be very different, so it's impossible to create a one-size-fits-all solution. I'd recommend building something in a library first or something. And for proposing something in core, Trac is the right place.
