### ISSUE TITLE
Dominant color upload process ignores potential third-party editors

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#374]
## Bug Description

Follow-up to #19 / #282: The current Dominant Color module enforces usage of its extended `WP_Image_Editor` classes. While this works with WordPress core alone, it is problematic in environments where e.g. a plugin has already added its own extended `WP_Image_Editor` classes.

We need to make sure that the Dominant Color implementation doesn't conflict with such plugins. The `dominant_color_set_image_editors()` filter callback function should be fixed to not override the entire array of editor class names, but rather only replace the specific WordPress core editors `WP_Image_Editor_GD` and `WP_Image_Editor_Imagick` with their customized variants from the module.

cc @pbearne @spacedmonkey

**Comment by spacedmonkey** [comment]
Before calling the methods, we do check to see if they exist. See. 

https://github.com/WordPress/performance/blob/11bf31c6c2bb033aa458e8c985c9ba2756ee034c/modules/images/dominant-color/load.php#L306-L308

https://github.com/WordPress/performance/blob/11bf31c6c2bb033aa458e8c985c9ba2756ee034c/modules/images/dominant-color/load.php#L274-L276

If you have filter the editor class to a custom one, these methods will not exist and nothing will happen.

**Comment by felixarntz** [comment]
@spacedmonkey That's not the point I'm making here. The current filter overrides all registered `WP_Image_Editor` classes - which is a problem if other plugins have added their own ones.

The `dominant_color_set_image_editors()` function needs to be adjusted to not "recklessly" overwrite all classes. It should only replace the specific WP core image editor classes `WP_Image_Editor_GD` and `WP_Image_Editor_Imagick`, but avoid the risk of unsetting/modifying image editor classes potentially added by plugins.

**Comment by spacedmonkey** [comment]
This is only really an issue in this plugin. Once in core, it will not be a problem. But I agree, we want to not break anything for anyone doing something really custom.

**Comment by felixarntz** [comment]
@spacedmonkey 
> This is only really an issue in this plugin. Once in core, it will not be a problem.

Correct, but I think that should be enough of a reason to fix this. We shouldn't have known bugs in this plugin without addressing them, since this plugin is also used in the wild. So we should still do our best to have it working as reliably as possible.

> But I agree, we want to not break anything for anyone doing something really custom.

Exactly :)

**Comment by spacedmonkey** [comment]
PR ready to review.
