### ISSUE TITLE
WebP images not deleted when saved in backend after edit

### ISSUE THREAD

**Issue by mehulkaklotar** [WordPress/performance#375]
## Bug Description

WebP images that are generated when uploaded and edited and saved. When deleted the image, the WebP versions are not being removed from files.

## Steps to reproduce

1. Go to Media, Upload the image
2. Open the image in backend image editor and rotate it and save the image.
3. Delete the image completely and check the files.
4. See that original WebP version of the files are not removed.

## Additional Context

 - PHP Version: 7.4
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.1.0
 - Device: MacBook Pro

**Comment by mxbclang** [comment]
@mehulkaklotar Nice catch! @felixarntz @adamsilverstein Can you please take a look at this and let me know if this is expected behavior and/or something that we should address sooner than later?

**Comment by felixarntz** [comment]
@mehulkaklotar Good catch indeed! I can confirm this is missing from our implementation. We should add support for deleting any backed up `sources` to our `webp_uploads_remove_sources_files()` function. It needs to cover:
* Delete the `sources` files for each sizes within `_wp_attachment_backup_sizes`.
* Delete the `sources` files from `_wp_attachment_backup_sources`.
