### ISSUE TITLE
Support flushing cache groups

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#38]
Cache groups are a core concept of the WordPress object cache and it’s an often requested feature to flush an individual group, without flushing the entire cache.

```php
function wp_cache_flush_group(string $group): bool;
```

This would be most in-line with the currently signatures.

We could optionally accept an array as well, I'm not sure about the WP conventions around this.

**Comment by tillkruss** [comment]
Ping @spacedmonkey

**Comment by pbearne** [comment]
I can pick this one up if you want

**Comment by pbearne** [comment]
is there a trac ticket for this?

**Comment by tillkruss** [comment]
I'd definitively add a note in the docblock about using this function carefully, because if you flush the `users` group, but not the `user_meta` group the results might be catastrophic.

- https://core.trac.wordpress.org/ticket/4476
- https://core.trac.wordpress.org/ticket/9773

**Comment by pbearne** [comment]
Should we add protection for that and delete both?

Looking at the tickets lets add a test for the function before use and fall back to flush all if the function is missing

**Comment by tillkruss** [comment]
I'd just document it in the docblock, instead of writing various rules in the function.

**Comment by tillkruss** [comment]
Currently being reviewed at XWP before opening a core PR.

https://github.com/xwp/wordpress-develop/pull/4

**Comment by pbearne** [comment]
I have created the pull request for this against this ticket https://core.trac.wordpress.org/ticket/4476
I haven't added the function cache-compat.php as I am not it is needed or if it would work as we need support from the caching layer for this

**Comment by tillkruss** [comment]
Refreshed new PR: https://github.com/WordPress/wordpress-develop/pull/2969

**Comment by tillkruss** [comment]
This was merged into core.
