### ISSUE TITLE
Remove plugin option for Multisite

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#382]
## Bug Description

Its follow-up enhancement for [#353](https://github.com/WordPress/performance/pull/345) and feedback https://github.com/WordPress/performance/pull/345#issuecomment-1155608644

If we set up multisite in WP then it will save the option in their sub-site DB. Like if you have two sub-site then the plugin option will save the option in the below tables.

wp_options - Main site option table
wp_2_options - 1st Sub-site option table
wp_3_options - 2nd Sub-site option table

The current uninstaller route only deletes options from the main site `perflab_modules_settings` but it will not remove the option for its subsite.

## Steps to reproduce

1. Setup [Multisite](https://wordpress.org/support/article/create-a-network/)
2. Create 2-3 subsite
3. Download and activate the Performance Lab plugin for all sites.
4. Delete plugin
5. Check the DB `perflab_modules_settings` option for sub-site.

## Screenshots
![image](https://user-images.githubusercontent.com/10103365/174580062-d62a6c72-7fa9-47fe-b341-5f3eacf9b184.png)

**Comment by mxbclang** [comment]
@merkys7 Tagging you in on this one, as well – please assign to yourself if you can pick this up. Thanks!

**Comment by merkys7** [comment]
Yes, I would love to take this one, I just don't have permissions to assign it to myself.
Thank you for the ping :)
