### ISSUE TITLE
Introduce plugin config for not removing DB setting option when uninstall

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#383]
## Bug Description

Its follow-up enhancement for https://github.com/WordPress/performance/pull/345 and feedback https://github.com/WordPress/performance/pull/345#issuecomment-1155608644

Felix's feedback on this approach.

> Normally I would agree with this, but I think for this plugin it's not really necessary since the options are so basic and easy to reconfigure. If we at some point want to allow control on _not_ deleting the data on uninstall, I think we should rather go a separate approach and include a checkbox somewhere so that the site administrator can control that without writing code.

**Comment by mxbclang** [comment]
@merkys7 Tagging you in here as it looks like you were interested in picking this one up. If you still are, please assign to yourself so know that you will move it forward. Thanks!

**Comment by merkys7** [comment]
Yes, I would love to take this one, I just don't have permissions to assign it to myself.
Thank you for the ping :)

**Comment by mxbclang** [comment]
@merkys7 Assigned to you and I can work on getting you add to the repo so you can make updates, too! I'll let you know when you've been added.

**Comment by merkys7** [comment]
@felixarntz I am starting to work on this issue and I have a small question related to the `checkbox`.

On uninstall.php, I plan to use the following approach:
```
function perflab_is_delete_plugin_option_enabled() {
	$perflab_settings = get_option( 'perflab_modules_settings' );

	if ( ! empty( $perflab_settings['perflab_delete_data_on_uninstall'] ) ) {
		return true;
	}

	return false;
}
```
In order to add the checkbox in the settings tab (`options-general.php?page=perflab-modules`) - am I required to create a new module as per https://github.com/WordPress/performance/blob/trunk/admin/load.php? creating uninstall module would be the correct approach or shall I add the checkbox without a module?

**Comment by felixarntz** [comment]
@merkys7 The uninstall checkbox shouldn't be a new module as modules are only for the actual features of the Performance Lab plugin that should eventually become part of WordPress core. The checkbox here is part of the Performance Lab infrastructure though, so it should be implemented as part of the plugin core code, e.g. in the https://github.com/WordPress/performance/blob/trunk/admin/load.php file.

**Comment by merkys7** [comment]
Thank you for the answer! :bowtie:

**Comment by mukeshpanchal27** [comment]
Closing in favour we removed the module infrastructure to standalone plugins also added uninstall routing #1116 #1128 for plugins that register settings.

cc. @sstopfer @joemcgill
