### ISSUE TITLE
Site health warning to remove index.php from theme if server has activated "disable directory listing"

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/performance#384]
With WP 6.0 not requiring index.php, it may be a helpful performance improvement to remove the blank index.php from themes but leave it DEV/end users to make decision.

**Comment by tillkruss** [comment]
How would it improve performance?

**Comment by LukaszJaro** [comment]
By not having to process/read empty PHP file but I wasn't sure which is why I wrote may be helpful and let the WP perf pros provide their insight.

**Comment by swissspidy** [comment]
This doesn't really affect performance in any way, closing as such.
