### ISSUE TITLE
Investigate unexpected input `Warning` message during release build/test process

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#388]
## Bug Description

During the release process for version 1.2.0 of the plugin the "Setup Node" step threw a warning:

Warning: Unexpected input(s) 'cache', valid inputs are ['always-auth', 'node-version', 'registry-url', 'scope', 'version']

Possibly this is coming from this line: https://github.com/WordPress/performance/blob/751e4bdb58112e734017d014affcb93e966eb53e/.github/workflows/php-test.yml#L48

although this matches the docs for  "actions/setup-node"

## Steps to reproduce

1. Run a release build

## Screenshots
![image](https://user-images.githubusercontent.com/2676022/174867216-55f84727-20ef-4d12-ba4a-69cbfe7a1154.png)

**Comment by mxbclang** [comment]
@felixarntz Should this be something that we try to fix for the 1.3.0 release if possible?

**Comment by felixarntz** [comment]
@bethanylang Would be nice, but not a blocker.
