### ISSUE TITLE
Add docs on contributing to the performance plugin

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#39]
This issue is about creating a `/docs/Getting-started.md` file with the most important information needed to contribute to the performance plugin. That documentation should follow a similar structure like Gutenberg's https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/getting-started-with-code-contribution.md, e.g.:
* explain how to clone the repository
* which local tools are required (Node.js, Docker)
* any commands that need to be run (e.g. linting, tests)
* high-level code requirements (e.g. follow WordPress coding standards and WordPress core coding patterns in general)

We should also include there with which WordPress and PHP versions the code should be compatible, which ties into a greater product question: **Which WordPress and PHP version should we require and how far back do we support?**

^ That is probably the main question to answer here before we can get started with the documentation.

In addition to the above file, which is the main part of this issue, we should also add the regular `CONTRIBUTING.md` file. That one can be really short and mostly link to the above documentation file. At a high level, we can look at Gutenberg's https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/README.md and https://github.com/WordPress/gutenberg/blob/trunk/CONTRIBUTING.md for inspiration what to include here.

The main part of this issue will be coming up with the above documentation in a PR and reviewing it.

**Comment by felixarntz** [comment]
My initial suggestion for WordPress and PHP compatibility here is the following:
* **WordPress:** No backward-compatibility other than the latest release, i.e. the latest release is also the minimum required version (right now 5.8). We will need the latest core features for many things here, that's the nature of feature plugins.
* **PHP:** Always match the latest WordPress core version, i.e. minimum requirement should be PHP 5.6.

How does everyone feel about the above? That would mean in our eventual `readme.txt` we would initially require WordPress 5.8 and PHP 5.6.

**Comment by ThierryA** [comment]
> Which WordPress and PHP version should we require and how far back do we support?

An easy approach would be to follow the same requirements as the WordPress version features are targeted to.

**Comment by adamsilverstein** [comment]
WordPress: requiring latest version makes sense (we might even need patches in some cases).  For PHP version, matching the WordPress minimum makes sense since we are targeting core merge for much of this code.

**Comment by felixarntz** [comment]
@ThierryA 
> An easy approach would be to follow the same requirements as the WordPress version features are targeted to.

We can't really define that per feature though, it's about the WordPress version the performance plugin requires. Given that all features we're building will target a future WordPress core version, I think requiring the latest existing WordPress core version makes most sense.

**Comment by JustinyAhin** [comment]
It definitely makes sense to support t

**Comment by JustinyAhin** [comment]
+1 to the initial proposal of Felix https://github.com/WordPress/performance/issues/39#issuecomment-985830941
