### ISSUE TITLE
Core Feature Proposal: Site Health modules (object cache, full page cache)

### ISSUE THREAD

**Issue by manuelRod** [WordPress/performance#391]
As part of the performance modules lifecycle, we want to port these 2 specific Site Health modules to Core.
- Persistent Object Cache Health Check. [Trac](https://core.trac.wordpress.org/ticket/56040)
- Audit Full Page Cache. [Trac](https://core.trac.wordpress.org/ticket/56041)

You can find the Make proposal [here](https://make.wordpress.org/core/2022/07/13/proposal-persistent-object-cache-and-full-page-cache-site-health-checks/)

Edit: 
Persistent Object Cache P.R: https://github.com/WordPress/wordpress-develop/pull/2890
Audit Full Page Cache P.R: https://github.com/WordPress/wordpress-develop/pull/2894

**Comment by mxbclang** [comment]
Thanks, @manuelRod! I've assigned this to you for now to work on the proposal draft. Once it's ready for review, please reassign to me and I can coordinate that!

**Comment by manuelRod** [comment]
@bethanylang I've made the initial draft, could you take a look and see if it is aligned with what we need? Thanks!

**Comment by mxbclang** [comment]
Thanks @manuelRod! I'm about to leave for a few days of vacation, but I will review this later next week.

**Comment by manuelRod** [comment]
@audrasjb @felixarntz while I'm moving this functionality to core, It came to my attention, that all Site Health-related things are contained in just a class _WP_Site_Health_, that class is already almost 3k lines. :/
If we start adding tests to this class ( most of our tests have quite a few helper methods ) it will get really large and ugly. 
I'm not sure if we should consider splitting functionality somewhere else, do you know anyone from this site health team to discuss this with?
I will anyways, prepare the PRs, but I think is worth doing a little refactoring, though I know refactoring for the sake of refactoring is not liked in the core.

cc: @Clorith @afragen

**Comment by Clorith** [comment]
Hiya, it is indeed a pretty chunky class :)

I can bring some backstory, the initial reason was that this was developed as a plugin, so everything had to be self-contained without knowing about core method locations.

Containing everything in one location means we don't need to worry about a file having been included already to ensure it has added filters before the Site Health component runs. Although it could probably be split over multiple files within a `Site_Health` directory or similar,  but then you're hitting increased disk  operations, even if they are minuscule, it all adds up.

I see no problem in creating the initial patches from within the areas they refer to, so long as we can guarantee that those areas will actually be included early enough to be included in the results. I'm not a huge fan of a refactoring as part of adding new features though, if anything that should be a separate task to ensure that the best approach to ensure everything is included and nothing is lost happens, if that makes sense?

**Comment by afragen** [comment]
@Clorith has a much better understanding than I do. I'll simply say that any refactoring will be a core committer level decision, that leaves me out. 😅

**Comment by manuelRod** [comment]
Thanks, @Clorith and @afragen for chiming in. Alright, I'll prepare then the PRs following the current Site Health fashion.
I'll tag you once they are ready

**Comment by manuelRod** [comment]
@felixarntz @Clorith @afragen @spacedmonkey PRs ready for both modules:
https://github.com/WordPress/wordpress-develop/pull/2890
https://github.com/WordPress/wordpress-develop/pull/2894

**Comment by felixarntz** [comment]
@Clorith 
> Containing everything in one location means we don't need to worry about a file having been included already to ensure it has added filters before the Site Health component runs. Although it could probably be split over multiple files within a `Site_Health` directory or similar, but then you're hitting increased disk operations, even if they are minuscule, it all adds up.

I think loading additional small PHP files instead of one massive PHP file has a negligible impact if any, so I would say the code maintainability should trump that here. I do agree with your next point though:
> I'm not a huge fan of a refactoring as part of adding new features though, if anything that should be a separate task to ensure that the best approach to ensure everything is included and nothing is lost happens, if that makes sense?

So +1 on implementing this in the existing `Site_Health` class as a refactoring would be out of scope here.

**Comment by felixarntz** [comment]
@manuelRod Thanks a lot for writing up the draft! I just reviewed it and it looks very solid to me. I left some minor suggestions, the most important feedback from my end would be to add a more actionable last section and provide a bit more context on how the modules are supposed to behave and how people can test them.

**Comment by manuelRod** [comment]
@felixarntz @bethanylang thanks for the review, i did another iteration and created the last section for feedback and testing. Let me know!

**Comment by manuelRod** [comment]
BTW, should I expand on the filters available?

**Comment by felixarntz** [comment]
@manuelRod Yes, a brief mention of them would be great, maybe just as a simple list of available filters, and you could link to the plugin source code for them.

The detailed documentation on the filters with examples etc. is more important to add later in a `dev-note` post once this has been committed to core.

**Comment by manuelRod** [comment]
@felixarntz @bethanylang I've applied latest revision and added some brief info about the filters available in both modules.
Can you take another look? I'm confident we are close now :)

**Comment by manuelRod** [comment]
@bethanylang @felixarntz here is the draft make post: https://make.wordpress.org/core/wp-admin/post.php?post=97544&action=edit

**Comment by manuelRod** [comment]
Proposal published: https://make.wordpress.org/core/2022/07/13/proposal-persistent-object-cache-and-full-page-cache-site-health-checks/

**Comment by felixarntz** [comment]
Awesome work, thank you @manuelRod!
