### ISSUE TITLE
Thumbnails not converted to webp since update 1.2.0

### ISSUE THREAD

**Issue by Joaojack** [WordPress/performance#395]
Hello, since update 1.2.0, my different thumbnail sizes are not automatically converted to webp. The options are still checked in settings, and it worked before. 

I'm using Real Thumbnail Generator to generate several thumbnails on each upload, and it worked fine with performance.

**Comment by Joaojack** [comment]
My original picture is correctly converted (apple.webp), but the generated thumbnails (apple-large.jpg, apple-thumbnail.jpg) were not

**Comment by Joaojack** [comment]
@mukeshpanchal27 if you need any precisions on my issue don't hesitate to ask me, thanks !

**Comment by mukeshpanchal27** [comment]
@Joaojack Thanks for reporting the bug. I recreated it in the `1.2.0` version using the free [Real Thumbnail Generator](https://wordpress.org/plugins/real-thumbnail-generator-lite/) plugin and the [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) plugin.

It was related to [Avoid overwriting existing WebP files when creating WebP images](https://github.com/WordPress/performance/pull/359).

cc @felixarntz

**Comment by felixarntz** [comment]
@mukeshpanchal27 @Joaojack I left a reply in https://github.com/WordPress/performance/pull/422#discussion_r920401681, this issue definitely needs some further thought. We cannot risk overwriting files that may be used in other images, so as long as we are unable to know whether an existing file belonged to the same attachment, we cannot move forward here. Unfortunately there is no straightforward fix for this which wouldn't introduce a bug that's worse than this one.

I'm still curious why the old `sources` aren't available when regenerating files for an image. Do the regenerate images plugins completely delete the image's attachment metadata before regenerating files for it? 🤔

**Comment by Joaojack** [comment]
Bu why did it work before ?

Le mer. 13 juil. 2022 à 20:54, Felix Arntz ***@***.***> a
écrit :

**Comment by felixarntz** [comment]
@Joaojack Before there was another bug #359, and when that was fixed, we introduced the bug you encountered here. The problem of addressing both bugs at the same time is quite complex, so this will require more exploration from an engineering perspective.

While the bug in #359 is quite specific, it unfortunately is the more severe bug (accidentally mixing up image files with another attachment), so we also cannot just revert the fix.

We will have to look into this problem further.

**Comment by Joaojack** [comment]
Thank you @felixarntz for this answer. Is there any way for me to download the previous version ? I've developed a whole vue frontend calling webp versions for each thumbnail and everything is broken since the update.

**Comment by mukeshpanchal27** [comment]
@Joaojack You can download the previous version of the plugin from the WordPress.org website: https://wordpress.org/plugins/performance-lab/advanced/ at the bottom. 

Please download the 1.1.0 version here: https://downloads.wordpress.org/plugin/performance-lab.1.1.0.zip

**Comment by adamsilverstein** [comment]
Noting that in the core patch, we took the approach of adding the original file extension as a suffix when building the alternate mime filenames which neatly avoids the name conflict in the first place (cat.jpeg becomes cat-jpeg.wep, cat.jpg becomes cat-jpg.webp).

**Comment by felixarntz** [comment]
@mukeshpanchal27 Would you mind reviewing the above implementation from the core patch? It would be great to find a way to bring the same enhancement to the Performance Lab's WebP module implementation so that we can fix this issue by generally avoiding conflicts.

**Comment by mukeshpanchal27** [comment]
Yes. Let me review the core patch.

**Comment by dajana91** [comment]
Hello, I am experiencing the same problem with "Regenerate Thumbnails" and "EWWW Image Optimizer". I now have quite a few *.jpg.webp" files on the server. How can this be fixed? Why does this happen? Instead of "file.webp" I have a "file.jpg.webp", which causes errors.
