### ISSUE TITLE
Add plugin `readme.txt`

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#40]
Like every plugin, the performance plugin needs a `readme.txt`. We already have a plugin name (see #1) and a preliminary plugin description (https://github.com/WordPress/performance/blob/trunk/load.php#L5), and we are currently defining WP and PHP version support as part of #39.

What should our `readme.txt` contain? Any ideas on the detailed outline, what to put in the FAQ etc? Let's brainstorm.

**Comment by dainemawer** [comment]
@felixarntz couple of ideas here to get this thread going:

1. First off should be a list of the improvement modules as well as why they improve performance (motivation)
2. Where we see this plugin headed (dreams/aspirations)
3. Any specific call outs (Gutenberg, Media Library etc)
4. Link to contributing guidelines
5. Perhaps a detailed section about what Web Vitals this plugin will have an impact on?
6. I think most importantly, what to do and who to reach out to if you (the user) doesn't see immediate impacts - could be a number of reasons - this is obviously very specific to each user, so maybe we should cover our bases here.
7. Links to CHANGELOG and Issues
8. Perhaps some direction on auditing / measuring metrics holistically? https://web.dev/vitals-tools-workflow/
9. FAQ's I think could be quite far reaching, here are a few ideas:

- How does this plugin effect caching?
- How well does it play with existing Media Library plugins (SmushIt / Regenerate Thumbnails)
- Can data be sent to Google Analytics / Google Tag Manager / Search Console integrations?
- Any Gutenberg specific functionality?
- Any effects on the server? DB queries / effects on Core / wp-uploads?

Happy to create a PR outlining this in coherent English!

**Comment by felixarntz** [comment]
@dainemawer I opened a PR with an initial `readme.txt` draft. It also includes a script to facilitate maintenance of it, but specifically the readme content itself is merely a first draft, so please review and iterate on it as you please. That also applies to anyone else, we should collaborate on the content as much as possible. With that said, let's keep the first version somewhat simple, it should have everything that we think should be there, but it doesn't need to be perfect and document every detail etc. - we can always iterate in follow-up issues/PRs :)

Here's the initial proposal: https://github.com/WordPress/performance/pull/72/files#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6

**Comment by dainemawer** [comment]
Sorry @felixarntz was out when this was merged - I'll take a quick look at the merged code and open up any further items in issues. Nice work!
