### ISSUE TITLE
Delete terms from disabled taxonomies

### ISSUE THREAD

**Issue by Exalik** [WordPress/performance#400]
Hello,

I have an alert about terms from disabled taxonomies.
On the bottom of the terms list, there's a "Delete Terms" button.
When I click on it, it does not do the job !

Could you solve it please ?

**Comment by mxbclang** [comment]
Hi there @Exalik! Can you clarify where you are seeing this error? It does not sound like it is part of the Performance Lab plugin.

**Comment by Exalik** [comment]
![Capture d’écran du 2022-06-28 19-16-12](https://user-images.githubusercontent.com/39555992/176243476-54edf6cd-e66d-48da-b448-fde8fdd36dda.png)
![Capture d’écran du 2022-06-28 19-17-37](https://user-images.githubusercontent.com/39555992/176243641-02b76180-7d0b-49c4-9e86-bb563db78ef9.png)
![Capture d’écran du 2022-06-28 19-18-24](https://user-images.githubusercontent.com/39555992/176243762-8a6b847c-47c8-45a1-8828-60414fd89af4.png)

**Comment by mxbclang** [comment]
@Exalik Thank you! These messages aren't coming from the Performance Lab plugin, which this is the repository for, so unfortunately this isn't something that we can assist with. I'd recommend posting to the <a href="https://wordpress.org/support/forum/how-to-and-troubleshooting/">Fixing WordPress Forum</a> for assistance.

**Comment by Exalik** [comment]
Thanks @bethanylang !
