### ISSUE TITLE
Remove experimental label from dominant color module and turn on by default for new installs

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/performance#402]
## Feature Description

Enable dominant color module by default and remove experiemently flag.

**Comment by spacedmonkey** [comment]
Thoughts on this one @pbearne @felixarntz

**Comment by pbearne** [comment]
yes I feel we should do this

**Comment by felixarntz** [comment]
@spacedmonkey @pbearne I agree with the additional polishing this has been getting we should be good making this non-experimental. Let's make sure to look out for additional feedback. It would be great if we could ship this as non-experimental in the upcoming 1.3.0 release and shortly after publish the feature proposal post for WordPress core.

**Comment by mxbclang** [comment]
@felixarntz Just to clarify, is the plan for 1.3.0 to remove the experimental flag *and* enable the module by default? I'd like to update the issue title if we're only doing the former.
