### ISSUE TITLE
Remove Experimental label from Autoloaded Options Site Health audit

### ISSUE THREAD

**Issue by mxbclang** [WordPress/performance#409]
As noted in #92, the Autoloaded Options Site Health audit is currently marked as Experimental, mainly because of the lack of documentation on how to clean up autoloaded options. We've created a [new autoloaded options guide](https://wordpress.org/support/article/optimization/#autoloaded-options) as part of the main WP Optimization guide, which will be updated in the plugin in v1.3.0 per #407.

This is an issue to discuss if we're now ready to remove the Experimental label from this module.

cc @felixarntz @manuelRod

**Comment by felixarntz** [comment]
I think we could potentially remove the experimental label, certainly this is a lot closer than before. With that said though, I do think it would be great to define a bit more what the goal with this module should be. For example, there is #350 (and corresponding PR #353) which IMO would make this a lot more helpful. From that perspective, I still feel like the current implementation feels somewhat incomplete.

I think it would be good to at least have a bigger plan and outline any necessary issues for what this Site Health audit _should_ encompass eventually. Maybe we can review the module holistically and think about it here. Are there more ways where we can help the site owner?

**Comment by manuelRod** [comment]
We should remove the experimental label on #350  merge since it adds useful information.
@felixarntz why do you think this implementation is somewhat incomplete? I think at this stage it would have enough info to help the user (is true that not everyone would know how to do it, but at least we are pointing them in the right direction).

**Comment by mukeshpanchal27** [comment]
Already fixed @sstopfer
