### ISSUE TITLE
Define changelog approach / tooling

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#41]
As the performance plugin will be released in the WordPress plugin repository at some point (and also in general 😄), we should think about how to create and maintain a changelog for new features, enhancements, and bug fixes.

Some high level questions:
* Should we maintain the changelog manually or through automated tooling (e.g. like https://github.com/WordPress/gutenberg/blob/trunk/bin/plugin/commands/changelog.js)? Manually is probably going to read more nicely, but it's also only maintainable to a limited degree. Potentially we could start with a manual approach, since it's hard to foresee how exactly an automated tooling approach should be structured for our purposes?
* Do we want to have a separate changelog file (e.g. `CHANGELOG.md` on GitHub), have the changelog only on the release tags on GitHub, or should the changelog be within the `readme.txt` file (visible on wordpress.org directly)?

The decision for the latter will also tie into #40 - the `readme.txt` file either needs to continue the changelog itself or a link to where it is at.

**Comment by jeremyfelt** [comment]
Please include a changelog in the plugin readme. It's so nice to see a list of changes directly in the WordPress dashboard when upgrading a plugin. 😄

**Comment by tillkruss** [comment]
I'd vote for a `readme.txt` Changelog for sure, maybe instead of a `CHANGELOG.md` duplicate, we could just copy the changes from `readme.txt` into the GitHub release notes?

I guess if all changes are approved via PRs, then we can either **enforce** a `readme.txt` entry via a GitHub Action, or just mention it manually when it's missing from the PR.

**Comment by ThierryA** [comment]
> I guess if all changes are approved via PRs, then we can either enforce a readme.txt entry via a GitHub Action

+1 to that

**Comment by felixarntz** [comment]
Thanks for the feedback! Given the replies so far, maybe we can indeed recycle a lot from Gutenberg's https://github.com/WordPress/gutenberg/blob/trunk/bin/plugin/commands/changelog.js and adjust it for our purposes? How about the following:

* We use GitHub milestones for each release.
* Every pull-request should receive a GitHub milestone at least by the time when it is merged.
* Every pull-request should also, at a minimum, receive a `[Type] xyz` label and either a `[Focus] xyz` or `Infrastructure` label.
* Exception to the above are pull-requests that don't affect the release at all (e.g. only adding tests or a GitHub action etc.).
* The title of each pull-request should be used as changelog message, i.e. it should be a human-readable text starting with an infinitive verb (e.g. "Add xyz", "Do this and that", "Enhance feature blabla").
* A changelog generator script (which we can heavily pull the code for from Gutenberg) should then generate a changelog as follows:
    * High-level groups should come from the `[Type] xyz` labels used.
    * Within those groups, changelog messages (PR titles) should be listed. Every message should be prefixed with a focus based on `[Focus] xyz` or `Infrastructure` labels used.
    * Every message should include a link to its PR.

Example output would be (fits into the `readme.txt` file based on wordpress.org readme formatting guidelines):
```
= 1.0.0 =

**Features**

* Images: Add WebP for uploads module. See [#32](https://github.com/WordPress/performance/pull/32).
* Infrastructure: Add settings screen to control individual modules. See [#30](https://github.com/WordPress/performance/pull/30).

**Enhancements**

* Infrastructure: Do blablabla. See [#99999](https://github.com/WordPress/performance/pull/99999).

```

How does the above sound to y'all?

**Comment by felixarntz** [comment]
I just created a first milestone https://github.com/WordPress/performance/milestone/1 so that we can get started to assign merged issues/PRs to it. I kept any details open since we haven't defined yet what the scope and version number should be.

**Comment by adamsilverstein** [comment]
Excellent! Thanks for kick starting this @felixarntz.  

Everything in https://github.com/WordPress/performance/issues/41#issuecomment-987120029 sounds good to me, makes sense to adapt the `changelog.js` script approach.

**Comment by ThierryA** [comment]
SGTM. How are we thinking about ensuring these practices are applied consistently?

**Comment by felixarntz** [comment]
@ThierryA I think for the start we'll have to do some occasional triaging of pull-requests. #47 is a good start for including a note on adding the necessary labels to every pull-request.

I think eventually it would be a good idea to require the merger of a pull-request to ensure the labels are present. We could add workflow documentation for this. Even better would be if we could have a GitHub action to check those requirements that would prevent a PR from being merged before.

**Comment by ThierryA** [comment]
> Even better would be if we could have a GitHub action to check those requirements that would prevent a PR from being merged before

Seems to be the only bullet proof way IMO. At minimum, we could also have a PR template with a checklist with one of them being "My PR as a label with ... as per documentation<link>"

**Comment by felixarntz** [comment]
Sounds good. I suggest we create two PRs: one with the changelog tooling itself (to generate it, as mentioned above inspired by the similar Gutenberg scripts), and another one with the PR integration (both template and GitHub workflow).

I'm gonna look into this today.
