### ISSUE TITLE
Core Feature Proposal: Dominant Color

### ISSUE THREAD

**Issue by pbearne** [WordPress/performance#417]
As part of the performance modules lifecycle, we want to port the dominant color module to Core.

Dominant color . [Trac][([https://core.trac.wordpress.org/ticket/56151](https://core.trac.wordpress.org/ticket/56151))

You can find the Make proposal/merge draft [here]
Core feature proposal https://docs.google.com/document/d/1VJuA2HQ90x5qvMc0aC9wfz7FsroyJPGJB3H-AuqzOgc/edit#
Dominant color dev notes https://docs.google.com/document/d/1C7S-5GMw9R81fQOXrc2PjzEaQniMpIgg2dT1ta69LmQ/edit#heading=h.l8wdvygotok4

Dominant color P.R: https://github.com/WordPress/wordpress-develop/pull/2906

**Comment by mxbclang** [comment]
This has been posted: https://make.wordpress.org/core/2022/07/21/proposal-add-a-dominant-color-background-to-images. Closing this issue.
