### ISSUE TITLE
Configure GitHub action for automated plugin deployment to wordpress.org

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#42]
Once the plugin is released on the wordpress.org plugin repository, we will need to regularly push updates. Since this is somewhat of a tedious and potentially error-prone process, it should be automated: We need a GitHub action that deploys the plugin release to wordpress.org when a GitHub release is published.

Some potential approaches / inspiration:
* https://github.com/10up/action-wordpress-plugin-deploy
* https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/upload-release-to-plugin-repo.yml

We don't need this _yet_, but it certainly doesn't hurt starting to already think about and discuss how we should go about it.

**Comment by adamsilverstein** [comment]
👍🏼  I've used the 10up action and found it reliable and straightforward to set up. the changelog management stuff in the Gutenberg script might be useful, I'm not sure what it does exactly.

**Comment by felixarntz** [comment]
@Otto42 Can you assist us or give us access to set up the [GitHub secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets) for this repository (`SVN_USERNAME` and `SVN_PASSWORD`) needed to automatically deploy from here to the wordpress.org plugin repository?

Also I wonder whether you have any advice on whose SVN credentials to use for this. Since this is a somewhat official wordpress.org plugin, should it be SVN credentials for some wordpress.org-controlled account (e.g. [this one](https://profiles.wordpress.org/wordpressdotorg/))? Or can it be the SVN credentials from any of us that would then need commit access to the plugin?

**Comment by Otto42** [comment]
Looks like the only place we have using such an action is the Gutenberg repository at the moment. They did it by creating an account on org specific for that purpose alone (named "gutenbergplugin").

We have the wordpressdotorg account, however that is mainly a placeholder, it is not used to commit any code to the repository. The account you use should be the account of a committer to the plugin on org, and it can be a purpose made one if needed, or just one of the people's accounts. Of course, this is moot until the plugin is uploaded and approved into the directory.

**Comment by JustinyAhin** [comment]
Now that #89 is close to ready, we will need to decide whether to use a dedicated w.org account, or one of the committer's account to deploy the plugin to WordPress. Can we mention this during the next meeting @bethanylang?

See Otto's comment above, https://github.com/WordPress/performance/issues/42#issuecomment-1000428780.

**Comment by eclarke1** [comment]
Also adding the 'Needs Decision' label here @bethanylang and perhaps we can discuss on the meeting on Jan 25 as @JustinyAhin suggested

**Comment by felixarntz** [comment]
Reopening this to figure out which WordPress account credentials to use for deployment, as well as actually configure this on GitHub. Since we can't modify the settings of this repository ourselves, we'll need to ask for help on this once we've decided which account credentials to use.

cc @JustinyAhin @ThierryA

**Comment by JustinyAhin** [comment]
@felixarntz IMO, it will make more sense to go with creating a w.org account for the plugin. Something like performanceteam for instance.

**Comment by felixarntz** [comment]
After [discussion on Slack](https://wordpress.slack.com/archives/C02KGN5K076/p1643129257383400), I'm going to move forward creating a `performanceteam` account for us to use for deployments. I'll share the credentials with all focus PoCs so that we co-own this account.

**Comment by felixarntz** [comment]
We now have a https://profiles.wordpress.org/performanceteam/ account on wordpress.org. This account will not be used for anything other than automated deployment of the plugin. IMO we don't need to bother adding any more details to it since it shouldn't be linked in prominent places, it's purely a "tool" for our automated deployment workflow.

I've also submitted the current version of the `performance-lab` plugin to the repo, where it was approved. We now have to complete and prepare our initial release (see #133).

Once we're clear on that issue #133, I'll take care of the next steps here to set up the GitHub repository for the automated deployment to work.

**Comment by felixarntz** [comment]
See https://github.com/WordPress/performance/issues/133#issuecomment-1058240566, the repository is now correctly set up with the GitHub secrets using the above `performanceteam` account.
