### ISSUE TITLE
Use Platform.sh to deploy WordPress vanilla instances for testing

### ISSUE THREAD

**Issue by lolautruche** [WordPress/performance#44]
Platform.sh is a PaaS that can be easily leveraged to deploy any app.

In addition to #43 (P.sh owns Blackfire), **we're also willing to help on the infrastructure side by providing one or several free Platform.sh projects**.
We would be able to deploy automatically any branch/PR, and thus run some tests (e.g. Blackfire automated tests).

WDYT?

**Comment by josephscott** [comment]
Being able to test PRs against a consistent WordPress site, and then compare against the existing master branch would be really helpful.  The idea being that for a given change we'd like to be able to detect if it making some aspect better/worse/no change.

Related, would be being able to run those same tests against every commit to master and trend the results over time.

**Comment by felixarntz** [comment]
Thanks @lolautruche, that is great to hear!

I suggest we continue the non-logistic parts of this topic (e.g. how would we use platform.sh for our purposes?) in #45, which goes more into how to approach this - platform.sh may be a great service to achieve our goals there.

**Comment by felixarntz** [comment]
@lolautruche If it's okay with you, can we continue and centralize this conversation in #64 (potentially in parts also #63) and close this issue here?

**Comment by eclarke1** [comment]
As per above comment, closing this issue, thanks
