### ISSUE TITLE
Add new Persistent Object Caching section to Optimization documentation

### ISSUE THREAD

**Issue by mxbclang** [WordPress/performance#448]
As discussed in #234, @olliejones has proposed a new Persistent Object Caching section for the [Optimization guide](https://wordpress.org/support/article/optimization/). I've added the proposed content to [this Google doc](https://docs.google.com/document/d/18EqOMteeJvn2_rZamJn_EDYW7z04oPmkHxHOc-A7I7c/edit).

@tillkruss @felixarntz Can you please take a look and leave comments and any suggested edits? Thanks!

**Comment by tillkruss** [comment]
Will do!

**Comment by mxbclang** [comment]
Thanks for reviewing, @tillkruss! I've accepted your (excellent) suggestions. @olliejones Heads up that Till has suggested removing the recommendations for W3 Total Cache and LiteSpeed Cache as they're quite large plugins that do a lot more than just object caching. I agree with that recommendation, but let us know what you think.

@felixarntz No huge rush, but can you please take a look at this as well when you get a moment? Thanks!

**Comment by mxbclang** [comment]
Reassigned to myself to update.

**Comment by mxbclang** [comment]
@OllieJones @tillkruss These changes have been made to https://wordpress.org/support/article/optimization/ as part of https://github.com/WordPress/Documentation-Issue-Tracker/issues/415. Thank you both for your help in putting this together and reviewing! Closing this issue.

**Comment by tillkruss** [comment]
Great work!

Reading this and seeing all those links, maybe we can simplify the 2nd bullet item.

The first one `Memcached Object Cache` is great, but the `Redis Object Cache` could be made simpler with a single link:

```markdown
[Redis Object Cache](https://wordpress.org/plugins/redis-cache/) – Provides a
persistent Redis object cache backend for WordPress that works with various
Redis clients. A Redis Server is required.
```

**Comment by mxbclang** [comment]
@tillkruss Agreed and updated, thank you!
