### ISSUE TITLE
Incorrect return type documented for site-health/audit-enqueued-assets module

### ISSUE THREAD

**Issue by dilipbheda** [WordPress/performance#450]
In the doc block of site-health/audit-enqueued-assets module/helper.php file, we can read that it always returns an int|False. This is incorrect. As the return value is int|bool

**Comment by mukeshpanchal27** [comment]
The function never returns a `true` value so I don't think we need to change it. A similar function with a `False` return is available in the WordPress core.

Some examples.
https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/includes/class-custom-image-header.php#L1573-L1599
https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/class-wp-customize-nav-menus.php#L1552-L1585
