### ISSUE TITLE
Mapping output from WebP to PNG loads replacement code does not work

### ISSUE THREAD

**Issue by erikyo** [WordPress/performance#469]
## Bug Description

I know the main intent was to provide a replacement jpeg->webp but for an ecommerce I had to change the normal operation of the plugin (otherwise it would have been of little use since the images were almost all png with transparency)

## Steps to reproduce

1. Add the filter 
```php
add_filter('webp_uploads_upload_image_mime_transforms', function() {
    return array(
        'image/png' => array( 'image/png', 'image/webp' ),
        'image/webp' => array( 'image/webp', 'image/png' ),
    );
});
```
2. Create a page and upload a bunch of png images
3. When you view that page and the fallback script is activated it tries to replace images [jpg images](https://github.com/WordPress/performance/blob/trunk/modules/images/webp-uploads/load.php#L529) only

## Additional Context

- was previously discussed here https://github.com/WordPress/performance/pull/360#issuecomment-1155988625

**Comment by mxbclang** [comment]
Tagging @adamsilverstein based on our discussion of this in today's chat.

**Comment by adamsilverstein** [comment]
It looks like our JavaScript has [hard coded](https://github.com/WordPress/performance/blob/308f61a3af95dc83e5a8d34b8e7c58d5d3354160/plugins/webp-uploads/fallback.js#L32) mime types it looks for; this is something we will need to address when adding AVIF support. Leveraging `picture` element support would likely eliminate the need for this script entirely.

**Comment by adamsilverstein** [comment]
the new version of the fallback script in https://github.com/WordPress/performance/pull/1176 addresses AVIF and WebP.

@erikyo We are now working on [adding picture element](https://github.com/WordPress/performance/pull/73) support - this should work better than the fallback script in your use case, could you give that a test to see if it resolves this issue?

**Comment by erikyo** [comment]
yes i can confirm that now I get it working with this 👇filter

```php
add_filter('webp_uploads_upload_image_mime_transforms', function() {
	return array(
		'image/png' => array( 'image/webp' )
	);
});
```

thanks!
