### ISSUE TITLE
Module Proposal: Database Performance Health Checks

### ISSUE THREAD

**Issue by OllieJones** [WordPress/performance#475]
## Overview
- Proposed module name:  Database Health Check
- Proposed module slug: `site_health/audit_database`
- Proposed module owner GitHub username(s): @OllieJones

## About the module

This replaces a more extensive and complex module proposal at #455.

Performance of the MariaDB or MySQL SQL server can strongly affect site performance. Large and busier sites are affected more strongly than smaller sites. This module provides specific health checks to detect common issues and suggest fixes.

### Purpose
When Site Health detects and explains opportunities to improve a site's MariaDB or MySQL database, it makes site operators aware of common issues. In some cases it also empowers them to fix those issues.

### Scope

This module is a pure health-check module. It makes no configuration changes to MariaDB, MySQL, or WordPress.

### Rationale

The opportunity to improve SQL server configuration and performance are the result of continued evolution of the MariaDB and MySQL database software products used by WordPress site operators. In the early days of WordPress, MySQL only offered the MyISAM storage engine, and all WordPress sites used it. Later, MySQL and its MariaDB fork added the InnoDB storage engine with the COMPACT row format (known as Antelope). Most recently, since MySQL 5.7 and MariaDB 10.2, the InnoDB storage engine with the DYNAMIC row format has become available (known as Barracuda). Each new feature helps reduce database lookup latency, especially for concurrent lookups under heavy load.  This Health Check module suggests things the hosting provider can do to improve database performance.

In the real world, WordPress sites use many different versions of MariaDB or MySQL. Not all the technology improvements are available to every site operator. Educating site operators and hosting providers is an important part of the proposed Database Performance site health module. The module does not make suggestions unless they are relevant to a particular site's configuration.

Many site operators are not technically minded, so they know very little about their sites' configurations. Site Health is a good way to surface performance problems in the SQL server, a component many people don't think about. And many "performance" and "caching" plugins in the WordPress ecosystem offer quasi-magical solutions. The proposed Site Health module demystifies the issues.

Why should this Site Health module be implemented in core someday?  Many sites have SQL server obsolescence and performance problems, and this module can potentially help all site operators improve them. If nothing else, it will help put some gentle pressure on hosting services to upgrade their obsolete MySQL server software.

A feature branch with a draft of working code is [here](https://github.com/OllieJones/performance/tree/audit-database).

### Other

This module reports problems it detects with server configuration.   Example:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/9804013/187470704-c4f4145f-c3b7-4cb6-9bf0-495257adf3a2.png">

If it detects no problems it shows the current status of its tests in the Passed Tests section. Example.
<img width="401" alt="image" src="https://user-images.githubusercontent.com/9804013/187471345-10179d5c-6cdd-4152-b770-3fd29661c511.png">

**Comment by javiercasares** [comment]
Should we make a list of "what's the best for databases for WordPress" and add that documentation to the WordPress Hosting Handbook, so we can push from the Hosting Team?

**Comment by mxbclang** [comment]
@OllieJones Based on the discussion in the <a href="https://make.wordpress.org/core/2022/08/30/performance-team-meeting-summary-30-august-2022/">August 30 chat</a>, this module is ready to proceed! I've created a new label for this module, [Module] Database Performance Health Checks, and a new issue for the initial implementation: #522. I can't assign this to you just yet as you need to be added to the GitHub Performance team (I've requested that [in Slack](https://wordpress.slack.com/archives/C02QB8GMM/p1662987492405229)), but once you've been added I can reassign to you or you can assign to yourself. I'm thinking we can use #522 to link to the initial PR as @felixarntz suggested in the performance chat, then create future issues as needed for additional components. Let me know if you have any questions!

@javiercasares Typically with these Health Check modules, changes to documentation have come up organically as we build out the check and determine what relevant guides we should link to, or if we need to create one or more new guides to fill in any gaps. So for a next step here, I'd recommend that we proceed on #522 and then Ollie, myself, and you (if you'd like!) can work together to determine what if any new documentation we'll need for the initial implementation of this module.

I'm going to close out this issue as the proposal has now been approved – see everyone in #522!
