### ISSUE TITLE
Create Background Processing Infrastructure: Create background_job taxonomy

### ISSUE THREAD

**Issue by mxbclang** [WordPress/performance#478]
Create a new Background Jobs taxonomy to store each job to run in the background process infrastructure. The taxonomy will be registered in the `modules/regenerate-existing-images/load.php` file.

## Acceptance Criteria
- A new `background_job` taxonomy is registered
- The taxonomy has the following attributes
    - Assigned to all public post types
    - Set `public` to false
    - Set `show_in_rest` to false

**Comment by felixarntz** [comment]
Fixed via #497
