### ISSUE TITLE
Create Background Processing Infrastructure: Create perflab_create_background_job function

### ISSUE THREAD

**Issue by mxbclang** [WordPress/performance#479]
Create a new `perflab_create_background_job()` function that creates a new job. The job will be a new term within the `background_job` taxonomy.

## Acceptance Criteria
- Create a new `perflab_create_background_job()` function
- Function accepts the following parameters
    - `$job_name` - A string the defines the job action to be run. This is required.
    - `$job_data` - An array of additional data to pass to the job action. This is optional and defaults to an empty array.
- The function will process the parameters and create a new `background_job` term as follows.
    - The `$job_name` is used as the term name.
    - The `$job_data` will be assigned to the term as term meta with the key `job_data`.
- The function will return the following depending on success or failure.
    - On failure, the function returns the `WP_Error` from `wp_insert_term`.
    - On success, the function returns the newly created Term ID.

**Comment by felixarntz** [comment]
@jjgrainger A note on the function names: `perflab_` is the prefix for the entire plugin, or at least for the plugin infrastructure. While it could work using it for module code too, in the past we have advised using module specific code prefixes to avoid naming conflicts between modules, so here we could use e.g. `perflab_rei_` or something like that. Just a thought.

**Comment by felixarntz** [comment]
@jjgrainger Just to clarify here: The `$job_name` will technically act as the "job type", is that correct (as in it could be e.g. "regenerate_existing_images")? I _think_ this works, but we should double-check whether it would also work if multiple jobs with that name existed (is it possible to have multiple terms of the same taxonomy and term name?).

Part of me thinks it might be better to use something more descriptive for the term name that allows to distinguish one job from another job of the same type (e.g. there could be one `regenerate_existing_images` job for all images with a certain parent post, and another `regenerate_existing_images` job for a specific selection of a few images). In that case, we could pass the action / "job type" as a separate parameter and store it as another meta field like `job_action`. What do you think?

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I will look at updating the `perflab_` prefix to `perflab_rei_` across issues. We may need a separate ticket to make sure any previous work is updated too.

As for the `$job_name` terms can share the same name, but not the same slug. Having descriptive term names could be useful to differentiate between jobs of the same "job type", but in a lot of cases these jobs are created programatically.

So using Regenerate Existing Images as an example, if we have 2 jobs both regenerating images for specific attachment ID's do we want to create a descriptive term name using those ID's? Something like `regenerate_existing_images_ids-1-2-3-4`?

I can give this some thought and think about it in the wider context with other background jobs.

**Comment by felixarntz** [comment]
@jjgrainger 
> I will look at updating the `perflab_` prefix to `perflab_rei_` across issues. We may need a separate ticket to make sure any previous work is updated too.

Thanks, sounds good. Definitely feel free to open an extra issues for just a single PR to update all existing code. cc @ankitrox as that is also relevant for the PR(s) you're currently working on.

> As for the `$job_name` terms can share the same name, but not the same slug. Having descriptive term names could be useful to differentiate between jobs of the same "job type", but in a lot of cases these jobs are created programatically.
> 
> So using Regenerate Existing Images as an example, if we have 2 jobs both regenerating images for specific attachment ID's do we want to create a descriptive term name using those ID's? Something like `regenerate_existing_images_ids-1-2-3-4`?

That makes sense. We don't have to use overly verbose term names that include IDs, but it may be a good idea to have term names that are based on some more specific aspect of what variant of the "job type" the job is for. E.g. we could have term names like `regenerate_existing_images_bulk_media` or `regenerate_existing_images_parent_posts` or something like that, so that we could query for jobs of similar origin. We don't have to fully specify that right now, but I think in any case it would be a safer option to use a specific meta key for the "job type" / job action. _Or_, alternatively, if we want to avoid using an extra meta key (which is also a good idea), we could include the job action/type in the term name in a clearly parseable way, e.g. `regenerate_existing_images:bulk_media` (and then always consider the first segment before the `:` as the job action).

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I've assigned this ticket to me and will pick this up later in the week.

I agree with the job naming being more descriptive and it appears we have the job type meta being created as part of #503 

I'll make sure to include a note about the "job type" in the comments for #486 

This is where we'll be creating our first job, something like `regenerate_existing_images:all_media`

**Comment by jjgrainger** [comment]
Fixed via #507
