### ISSUE TITLE
Create Regenerate existing images module

### ISSUE THREAD

**Issue by mxbclang** [WordPress/performance#489]
Create the initial module infrastructure for the Regenerate Existing Images module. This is required before any further development of the feature can take place. Additionally, as part of this work, the main feature branch `feature/regenerate-existing-images` should be created for all future work to be branched from and merged into.

## Acceptance criteria

- A new folder `modules/images/regenerate-existing-images` is added to the plugin
- Inside the new folder a `can-load.php` exists and return an anonymous function
    - The anonymous function returns `true` for now
- Inside the new folder a `load.php` file is created and has the correct docblock at the top of the file
- A new `feature/regenerate-existing-images` branch is created

**Comment by felixarntz** [comment]
@jjgrainger @ankitrox Leaving 2 minor notes here:
* The `can-load.php` file shouldn't be needed. It only needs to be present if we actually want to have custom logic, but if we just load this module unconditionally, it's unnecessary.
* Just emphasizing that of course the PR should also be created against that new feature branch :)

**Comment by felixarntz** [comment]
Fixed via #496
