### ISSUE TITLE
Create Background Processing Infrastructure: Create perflab_background_job_is_completed function

### ISSUE THREAD

**Issue by jjgrainger** [WordPress/performance#495]
Create a new `perflab_background_job_is_completed` function. This function is used within the background process to determine if the job being run is complete.

## Acceptance Criteria
- Create a new `perflab_background_job_is_completed` function
- The function accepts the `$job_id` as it's only parameter
- The function returns a boolean
- This function checks if the job is complete by testing if the `job_completed_at` meta is set. If it is set the job is considered complete.

**Comment by felixarntz** [comment]
@jjgrainger See my comment in https://github.com/WordPress/performance/issues/482#issuecomment-1224996357, potentially this may be more logical as a method on a job class.

**Comment by jjgrainger** [comment]
@felixarntz I've closed this issue as it has been replaced by the `is_complete()` method on the [`Background_Process_Job`](https://github.com/WordPress/performance/issues/503) class. This has been updated based on your [comments on #482](https://github.com/WordPress/performance/issues/482#issuecomment-1224996357).
