### ISSUE TITLE
Add additional documentation for each module

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#50]
Each module should include some basic documentation (both user facing and developer oriented) about what it does and how to use it.

- Add a `README.md` in each module's folder root. Primarily for developers who would be browsing the repository.
- Display a long description alongside the module in the settings screen. Primarily for users who are using the plugin.

**Comment by adamsilverstein** [comment]
Question: for the long description part, do we want to use the existing `Description` field (https://github.com/WordPress/performance/blob/dcbea35a795d28cdadfed2fe88c90a7b97ed0e49/docs/Writing-a-module.md?plain=1#L44) or add a new field to the header?

**Comment by felixarntz** [comment]
@adamsilverstein I think sticking to a brief description in the `Description` field would be more in line with how plugins handle this.

Regarding the longer description, I think that's a great idea, but I'm not sure a module header would be suitable for that. What if for example we want multiple sections or any formatting such as bold/italic text etc? Maybe we need another approach here.

I think what would be a neat approach here would be even if we could make the contents of the `README.md` for each module actually available in the plugin's settings screen - almost like the readme for wordpress.org plugins can also be viewed in the WordPress Plugins screen. For example:
* Show a little "i" info icon next to each module in the settings screen.
* Clicking that would open a modal.
* The modal would show the full readme content from `README.md` - it would basically need to parse that markdown into HTML, which shouldn't be too much of a stretch using a library.

The above would allow us to show as flexible information in the plugin we could possibly need, and even more importantly it would allow us to keep maintenance low - a single `README.md` file would serve for both people looking at the repo and people using the plugin.

If we wanted to include contributor-/developer-specific information in the `README.md` files, we could even define a special heading (e.g. `## Development` or `## Contributing`), and then everything after that could be cut off and not be displayed within the plugin.

What do you think?

**Comment by swissspidy** [comment]
Now that we split modules into standalone plugins, I don't think this applies anymore. Each plugin has a thorough readme already, and for contributing we have dedicated docs too.
