### ISSUE TITLE
Bump PHP version requirement

### ISSUE THREAD

**Issue by FleetingCloud** [WordPress/performance#505]
## Feature Description

Hi,
It’s been around 4 years since wordpress last increased its minimum PHP requirement.
Make post => https://make.wordpress.org/core/2018/12/08/updating-the-minimum-php-version/
At that time, only 85% websites were using PHP version 5.6 or higher but wordpress still decided to increase its minimum PHP requirement to 5.6 for security and performance reasons.
Buw now, as per wordpress statistics, only 5.8% wordpress installations are currently running on PHP version 5.6.
I think we are now ready to further increase minimum PHP requirement to 7.0.
With proper coordination with hosting companies and encouraging the sites to increase PHP version to 7.0 by showing message in WordPress 6.1, we will be able to further decrease that 5.8% statistics.
We can target wordpress version 6.2 for this change but we should make a proposal on make blog and try to include message that wordpress version 6.1 will be last version to support PHP version 5.6.
This change will allow wordpress to enhance the security while at the same time get rid some bloat from core, improving the performance. I think this will also pave the way for some good new feature
such as https://github.com/WordPress/performance/issues/427.
Trac ticket => https://core.trac.wordpress.org/ticket/56454#ticket
Thanks for your time.

**Comment by masteradhoc** [comment]
+1, long overdue...

**Comment by lukecav** [comment]
Some hosts no longer display EOL PHP versions in their portals/control panels to customers so that the lowest version would be PHP 7.4.
https://www.php.net/eol.php
https://help.dreamhost.com/hc/en-us/articles/215082337-What-versions-of-PHP-are-available-at-DreamHost-
PHP 7.4 is EOL November 2022.
https://www.php.net/supported-versions.php

**Comment by FleetingCloud** [comment]
Hi, thanks for your reply.
For us to make 7.4 minimum PHP version, all the lower PHP version should have only around 5% websites (wordpress installations) running on them. This is a requirement for increasing minimum PHP version.
As per WordPress statistics, 42% WordPress installation are running on PHP version **lower** than 7.4
For this number to reduce around 5% (requirements for updating minimum php version), it will take us 5 to 8 years according to past years trend.
While PHP version 9.0 will come out in next 3 years.
Well, hard to say WordPress can support PHP 5, 7 and future 9 together.
On the other hand, those hosting providers would have also stopped offering PHP version 7.4 (maybe even 8.0) by that time.
(Edited)

**Comment by mxbclang** [comment]
👋 @FleetingCloud While this is something that the Core Performance team can help to advocate for and ultimately work on, this repository is for tracking issues for the Performance Lab plugin only. I'm going to close this issue out but we'll continue to monitor the Trac ticket and jump in there as needed. Thank you!

**Comment by FleetingCloud** [comment]
> 👋 @FleetingCloud While this is something that the Core Performance team can help to advocate for and ultimately work on, this repository is for tracking issues for the Performance Lab plugin only. I'm going to close this issue out but we'll continue to monitor the Trac ticket and jump in there as needed. Thank you!

No problem. Thanks.
