### ISSUE TITLE
Implement GitHub action to ensure necessary labels and milestone are present on pull requests

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#52]
Based on https://github.com/WordPress/performance/issues/41#issuecomment-994746944, we should have a GitHub workflow that ensures that every pull request has the necessary labels and milestones. This can later be set up as a requirement that has to be met before a pull request can be merged.

Here's the specifications that the GitHub workflow should implemented (based on #41 as well):
* Every pull request must have one of the `[Type] xyz` labels. This is used to group pull requests in the changelog.
* Every pull request must have _either_ one of the `[Focus] xyz` labels _or_ the `Infrastructure` label. This is used to further categorize and prefix pull requests in the changelog.
* Every pull request must have _either_ a milestone set _or_ be marked with the `no milestone` label. This is used to define which release a pull request belongs to, or to explicitly define that a certain issue is "release-irrelevant" and therefore does not need a milestone.

**Comment by felixarntz** [comment]
@ThierryA Does this sound good to you? (Paging you here expicitly due to your comment in https://github.com/WordPress/performance/issues/41#issuecomment-994746944.)

**Comment by ThierryA** [comment]
@felixarntz yep the brief is great :)

**Comment by eugene-manuilov** [comment]
Hi @JustinyAhin. Do you need help with this ticket? Do you mind if I also take a look at it?

**Comment by JustinyAhin** [comment]
> Hi @JustinyAhin. Do you need help with this ticket? Do you mind if I also take a look at it?

Hello @eugene-manuilov. Yes definitely, I'd like some help.

I've been working on this in this PR https://github.com/WordPress/performance/pull/53.
I'll add a summary later today about what I have done so far, and what's remaining.

**Comment by eugene-manuilov** [comment]
Awesome! I'll work on it.

**Comment by eugene-manuilov** [comment]
Ok, I have prepared a new PR using the workflow file created in the Justin's PR as an example. The workflow file in the #85 checks required labels using the [`agilepathway/pull-request-label-checker`](https://github.com/agilepathway/label-checker) action and adds a basic PR template which is needed to trigger the mileston check because there is no event that can trigger the workflow.

**Comment by eclarke1** [comment]
@eugene-manuilov @bethanylang we can remove the Needs Dev label from here right, as it's In Progress / Review?

**Comment by eugene-manuilov** [comment]
Done.

**Comment by felixarntz** [comment]
Fixed via #85
