### ISSUE TITLE
Bump minimum WordPress requirement to 6.0

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#531]
**With this issue, I'm proposing to bump the minimum WordPress version requirement of the Performance Lab plugin to 6.0 in the upcoming 1.6.0 version (October 17).**

This is in line with https://github.com/WordPress/performance/blob/trunk/docs/Version-support-policy.md#wordpress-core-versions, and even more so, if we do this in the upcoming 1.6.0 release (October 17), we would be very close to even the WordPress 6.1 release (November 1), so realistically we would support the latest _two_ WordPress versions in the coming months (similar to how initially we supported 5.9 and 5.8 when 5.9 was the latest version).

Currently, the Performance Lab plugin requires at least WordPress 5.8.

As mentioned in the version policy, as soon as there's a benefit to bumping the WordPress version requirement, we should be able to do so as long as it is to a stable version. One of those is the introduction of the `filesize` metadata for attachments, which was added in 6.0 and heavily benefits logic in the WebP Uploads module. While this is just one benefit, with this being a feature plugin, we don't need to worry too much about keeping support for old WordPress core versions as long as the newer one provides us a clear benefit from a code perspective.

**Comment by mxbclang** [comment]
_Please vote for if we should bump the minimum requirement for Performance Lab to WP 6.0 with a thumbs-up for yes or thumbs-down emoji for no on this comment. Voting will close on **Friday, September 30, 2022 at 5pm UTC**._

**Comment by ecotechie** [comment]
Isn't the point to eventually merge these modules into Core? How would backward compatibility work then?

**Comment by felixarntz** [comment]
@ecotechie Whenever a module gets merged into WP core, it would by definition only be merged into the latest core version. So I'd argue that's a point for always working against the latest core version when developing this plugin. Of course we don't need to bump the WP version requirement of the plugin unnecessarily, but IMO nothing is holding us back from doing so whenever we need it, due to the above.

Of course once a feature gets merged into WordPress core, it will need to remain backward compatible as per core standards.

**Comment by mukeshpanchal27** [comment]
In addition to version bump we have to remove `polyfills.php` file that we added in #376 for `wp_filesize` function.

**Comment by mxbclang** [comment]
**Voting is now closed.**

Based on **11** thumbs up votes and **0** thumbs down votes, we'll proceed with bumping the minimum requirement for Performance Lab to WP 6.0.

@felixarntz Reassigning to you!

**Comment by felixarntz** [comment]
Thanks everyone for voting!

So this should be ready for a PR to created. We should throughout all the codebase (including documentation) update the minimum WP version reference to be 6.0 (instead of 5.8), and also remove any polyfills that aren't needed anymore with the new minimum version requirement (see https://github.com/WordPress/performance/issues/531#issuecomment-1259136232).
