### ISSUE TITLE
wordpress upgrade from php7.2 to php74 caused errors in debug log

### ISSUE THREAD

**Issue by JMaartenW** [WordPress/performance#532]
## Bug Description

I recently took over an old website which had not been upgraded for some time. it was running php7.2 and no plugins had been updated for years. I took a copy of the website to do a test upgrade of all plugins and php7.4 and the debug log is showing the following notices and warnings now. the question is how to fix these or should I just ignore the errors? 

The Debug log errors are:
1.	Notice: Function id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/saint-it-child/woocommerce/archive-product.php'), wc_get_template_part, load_template, require('/plugins/woocommerce/templates/content-product.php'), wc_product_class, wc_get_product_class, WC_Product_Bundle->is_on_sale, WC_Product_Bundle->sync_bundle, WC_Product_Bundle->load_bundled_items, WC_Bundled_Item->__construct, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in /var/www/vhosts/httpdocs/uat/wp-includes/functions.php on line 5831

2.	Warning: Declaration of WC_Product_Bundle::get_price() should be compatible with WC_Product::get_price($context = 'view') in /var/www/vhosts/httpdocs/uat/wp-content/plugins/woocommerce-product-bundles/includes/class-wc-product-bundle.php on line 693

3.	Warning: Declaration of WC_Product_Bundle::get_regular_price() should be compatible with WC_Product::get_regular_price($context = 'view') in /var/www/vhosts/httpdocs/uat/wp-content/plugins/woocommerce-product-bundles/includes/class-wc-product-bundle.php on line 702

4.	Warning: Declaration of WC_Product_Bundle::get_sale_price() should be compatible with WC_Product::get_sale_price($context = 'view') in /var/www/vhosts/httpdocs/uat/wp-content/plugins/woocommerce-product-bundles/includes/class-wc-product-bundle.php on line 711

5.	Warning: Declaration of WC_Product_Bundle::is_on_sale() should be compatible with WC_Product::is_on_sale($context = 'view') in /var/www/vhosts/httpdocs/uat/wp-content/plugins/woocommerce-product-bundles/includes/class-wc-product-bundle.php on line 1200

6.	Warning: Parameter 2 to advanced_custom_search() expected to be a reference, value given in /var/www/vhosts/httpdocs/uat/wp-includes/class-wp-hook.php on line 307

## Steps to reproduce

simply enabling debugging will show these errors on the page. but with debugging set to false the website looks ok. 
how serious are these issues?

## Additional Context

 - PHP Version: 7.4
 - Wordpress: 6.0.2
 - OS: Linux Debian 11.05 Apache / NGinx
 - Plesk Obsidian Version 18.0.46 
 - Browser: [e.g. chrome, safari] Chrome 
 - Plugin Version: woocommerce 6.8.2

**Comment by tillkruss** [comment]
These errors are not related to the performance plugin.
