### ISSUE TITLE
Revamp available focus areas

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#554]
In the [performance chat on October 11](https://wordpress.slack.com/archives/C02KGN5K076/p1665500425205239), a few proposals for aligning our focus areas were discussed, based on some requests and how the current focus areas have been working.

1. Introduce a "Database" focus area?
    * see [chat log](https://wordpress.slack.com/archives/C02KGN5K076/p1665502442523129)
2. Introduce a "CSS" focus area or expand the "JavaScript" focus to become "Assets" / "CSS & JS"?
    * see [chat log](https://wordpress.slack.com/archives/C02KGN5K076/p1665502713000599)
3. Remove the "Site Health" focus area and instead relocate those checks to their relevant topic focus area?
    * see [chat log](https://wordpress.slack.com/archives/C02KGN5K076/p1665503433054589)

Let's vote on these items here, and once decisions have been made, we can follow up on focus leads. Eventually, a PR should be opened against this issue to make the relevant changes to the plugin codebase (e.g. update `CODEOWNERS` and `perflab_get_focus_areas()` function, as well as potentially migrate modules).

**Comment by mxbclang** [comment]
For proposal 1, please vote on this comment with a 👍 or 👎 emoji to **introduce a new Database focus area**. Voting will close on **Tuesday, October 18, 2022 at 5pm UTC**.

**Comment by mxbclang** [comment]
For proposal 2, please vote on this comment with:
- 😄 to introduce a new CSS focus area
- 🎉 to expand the JavaScript focus area to include CSS and rename it to "CSS & JS" or "Assets"
- ❤️ to keep things as is and not add a new CSS focus area nor add it to the JS focus area

Voting will close on **Tuesday, October 18, 2022 at 5pm UTC**.

**Comment by mxbclang** [comment]
For proposal 3, please vote on this comment with a 👍 or 👎 emoji to **remove the Site Health focus area and relocate existing Site Health modules to the relevant topic focus area**. Voting will close on **Tuesday, October 18, 2022 at 5pm UTC**.

**Comment by mxbclang** [comment]
**Voting is now closed.**

For proposal 1, based on **10** thumbs up votes, we will **introduce a new Database focus area**.

For proposal 2, based on **7** 🎉 votes and **1** 😄 votes, we will **expand the JavaScript focus area to include CSS and rename it to "CSS & JS" or "Assets"**.

For proposal 3, based on **7** 👍 votes and **1** 👎 vote, we will **remove the Site Health focus area and relocate existing Site Health modules to the relevant topic focus area**.

@felixarntz and I will work on making the appropriate changes related to these results and update the team in our October 25 performance chat.

Thanks to everyone for voting! Closing this issue.

**Comment by felixarntz** [comment]
@bethanylang I would suggest we reopen this to have it as an overview for any PRs that address this. We also still need to follow up on asking for focus leads.

I think what we need in terms of code changes are:
* PR that updates focus areas in `CODEOWNERS` (see #564)
* PR that updates focus areas in the codebase (to do)
    * Update `perflab_get_focus_areas()` to return the latest focus areas
    * Rename `javascript` focus area accordingly, including the directory in `modules`
    * Move `site-health` modules into their new focus area directories
    * Implement logic in `perflab_get_module_settings()` to migrate all old ("legacy") module slugs to the new ones (e.g. if you have `site-health/audit-autoloaded-options` in the DB, it should become `database/audit-autoloaded-options`)

We will also need to create/rename the GitHub focus area labels accordingly. Regarding the Site Health focus area label, let's keep it (for the history), but just rename it to something like "[LEGACY] [Focus] Site Health" or something like that.
