### ISSUE TITLE
WebP upload configuration checkbox not showing in Settings > Media for multisite

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#560]
## Bug Description

The checkbox introduced in #525 does not show up when using Multisite. This is because the entire settings section (group `media`, section `uploads`) is not rendered for multisites. We have to fix this, which I think could be done in two alternative ways:
* Either we keep control about this per site in the multisite, thus just conditionally render it in another settings section on the same page when using a multisite (e.g. the `default` section).
* Or we only grant control about this at the network level, thus add the checkbox to the Network Admin's settings screen.

## Steps to reproduce

1. Use a Multisite.
2. Ensure the WebP Uploads module is active.
3. Go to Settings > Media, and notice that the checkbox to opt in to WebP _and_ JPEG generation is not there.

## Screenshots

**Settings > Media when using a multisite**
<img width="1005" alt="Screen Shot 2022-10-17 at 10 35 17 AM" src="https://user-images.githubusercontent.com/3531426/196244840-1c43f807-3492-4cc1-9c76-0ca2dc5e4070.png">

**Comment by felixarntz** [comment]
I'm personally leaning towards still rendering the checkbox in Settings > Media (i.e. per site), just in the `default` section when using a multisite, so that it still shows up at the bottom for both scenarios (generally I'd say the "Uploads" section is most appropriate so that's why I'd still leave it there for single site environments).

Another reason IMO to not move it to the network level is that there is no Network Settings API, so it would be quite a bit more challenging.

Curious what others think though.

**Comment by mehulkaklotar** [comment]
@felixarntz I agree to render the checkbox in Settings > Media per site. It makes more sense to put it in site settings instead of network settings.

**Comment by pushpakpop** [comment]
Per site settings option seems better as it provides more control.
