### ISSUE TITLE
With Dominant Color enabled, loses focal point settings

### ISSUE THREAD

**Issue by bachjessen** [WordPress/performance#562]
## Bug Description

When the Dominant Color is enabled in the performance plug-in the image looses its focal point

## Steps to reproduce

1. make sure Dominant Color is enabled in performance plug-in
2. Go to a page or post
3. add a cover to the post/page
4. set a focal point
5. update image and see the image just centering
6. disable Dominant Color and reload page/post
7. the focal point set in admin is used

## Additional Context

 - PHP Version: 7.4.32 
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.6.0
 - Device: MacBook pro m1 pro

**Comment by pbearne** [comment]
@simon-bd thanks for spotting this. It turns out we had some extra CSS left from when we used low rez images as placeholders
