### ISSUE TITLE
Improve error handling: Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by jamesozzie** [WordPress/performance#567]
## Bug Description

[One user in the support forums ](https://wordpress.org/support/topic/php-error-cannot-use-object-of-type-stdclass-as-array/) reported the below error:

Uncaught Error: Cannot use object of type stdClass as array in /wp-content/plugins/performance-lab/modules/images/webp-uploads/rest-api.php:21 Stack trace: 

```
#0 /wp-includes/class-wp-hook.php(307): webp_uploads_update_rest_attachment() 
#1 /wp-includes/plugin.php(191): WP_Hook->apply_filters() 
#2 /wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(843): apply_filters() 
#3 /wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(377): WP_REST_Attachments_Controller->prepare_item_for_response() 
#4 /wp-includes/rest-api/class-wp-rest-server.php(1143): WP_REST_Posts_Controller->get_items() 
#5 /mnt/data/home/502433.cloudw
```

Awaiting feedback from impacted user. No further details at present. 

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

**Comment by mxbclang** [comment]
@mukeshpanchal27 Assigning this bug to you to take a look at when you return from PTO next week, thank you!
