### ISSUE TITLE
Bump minimum required PHP version to 7.0 and minimum required WP version to 6.3

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#606]
## Bug Description

As WordPress bumps the [minimum required PHP version to 7.0](https://core.trac.wordpress.org/ticket/57345), we should do the same for plugins.

**Comment by Soean** [comment]
Until now, it is not clear, if PHP support for 7.0 and 7.1 will be dropped or only 5.6, so we should wait for the decision and the commit.

**Comment by mukeshpanchal27** [comment]
Now that we have a clear path to bump the minimum required PHP version to 7.0 for WordPress, it should be prioritized for the current release cycle `6.3`. Let's address this sooner.

cc. @joemcgill @felixarntz @eclarke1

**Comment by felixarntz** [comment]
@mukeshpanchal27 Let's keep an eye on https://core.trac.wordpress.org/ticket/57345, we don't need to rush this. We should only bump our minimum requirement once WordPress core has actually bumped its own.

**Comment by mukeshpanchal27** [comment]
@felixarntz WordPress core bumped the minimum version in https://core.trac.wordpress.org/changeset/56141.

**Comment by felixarntz** [comment]
Thanks @mukeshpanchal27. Given that the plugin currently still supports WordPress 6.1 and 6.2, I think we should hold off until we also bump the minimum WordPress version requirement to 6.3. That way the change is "synced" with WordPress core.

I'd say once WordPress 6.3 is released, we can move forward with this, maybe for the September or October release?

**Comment by swissspidy** [comment]
Just a note for the future:

Once we bump the requirement, there's no need for checks like `defined( 'PHP_INT_MIN' ) ? PHP_INT_MIN : ~PHP_INT_MAX` anymore as `PHP_INT_MIN` is always defined in PHP 7+

**Comment by felixarntz** [comment]
Now that WordPress 6.3 is out for a month, I think we can go ahead and bump the minimum required WordPress version of Performance Lab to 6.3, and at the same time the minimum required PHP version to 7.0.

When opening a PR for this, we can also get rid of <PHP 7 shims (e.g. what @swissspidy shared above), and compatibility code for <WP 6.3 versions, including some that we could have already removed before (e.g. the `dominant_color_filter_content_tags()` function and a <WP 6.1 specific check in the WebP Uploads module).
