### ISSUE TITLE
Clarify language around multi-server environment in SQLite settings

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/performance#609]
## Bug Description

When activating the SQLite module, users receive a warning:

`Warning: Do not activate if your site is implemented in a multi-server environment`

This message is somewhat confusing, when I read it originally I thought it referred to WordPress multi-site. @felixarntz clarifies that: "Since SQLite puts a file into the filesystem, it won't work on a site that is across multiple servers (some enterprise sites etc.)"

That sentence explains the reasoning much more clearly, maybe we can use that instead? Alternately, remove the confusing language entirely since it only applies to a very small percentage of sites.

## Steps to reproduce

1. Install the plugin
2. Check the settings screen

## Screenshots

![image](https://user-images.githubusercontent.com/2676022/208681705-67c28ede-4f56-423f-b8fb-b6f68507d7e3.png)

**Comment by felixarntz** [comment]
@adamsilverstein @aristath As discussed on Slack, I would vote for removing this last "Warning: ..." sentence entirely since it only applies to a relatively tiny subset of WordPress sites (typically enterprise level). Those sites are unlikely to enable SQLite module anyway :)

**Comment by OllieJones** [comment]
For the SQLite Object Cache, I handled the multiple-load-balanced-server question [this way](https://wordpress.org/plugins/sqlite-object-cache/#if%20i%20operate%20a%20scaled-up%20load-balanced%20installation%2C%20can%20i%20use%20this%3F).  FYI.
