### ISSUE TITLE
MySQL warnings when using SQLite

### ISSUE THREAD

**Issue by jamesozzie** [WordPress/performance#611]
## Bug Description

If running a site with an SQLite database, the plugin will still output MySQL related errors or warnings. An example, highlighted in a [WordPress forum support topic](https://wordpress.org/support/topic/mysql-warnings-when-using-sqlite/), shows one such warning related to the not in use MySQL database:

![image](https://user-images.githubusercontent.com/41326532/208732122-7723a4d6-0134-4106-aa6d-9b277f29ac16.png)

Considering not displaying MySQL warnings or opportunities if the site is connected to a SQLite database, or handling the errors differently, such as highlighted that this database is no longer in use.

**Comment by mxbclang** [comment]
@aristath Tagging you in here to take a look – I'm guessing we just didn't do anything specific to account for the Site Health checks, but should we? cc @felixarntz

**Comment by aristath** [comment]
We actually did a lot on the health-chech screen and already removed a lot of checks... I guess we missed this one. Thanks for reporting it!
I'll be away for the next 2 weeks so if someone else can submit a fix that would be great, otherwise I'm adding it to my to-do list for after the holidays 👍

**Comment by mxbclang** [comment]
Thanks @aristath! Fine to wait until after the holidays. Enjoy your time off!

**Comment by wocsol** [comment]
if your wordpress site is broken – due to sqlite option checked and save — watch this video how to resolve ..

https://youtu.be/Udu_gwTdEkg

**Comment by wocsol** [comment]
i  found a new bug in this plugin - named performance lab - Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in /plugins/performance-lab/modules/images/webp-uploads/load.php on line 594'

really broking whole site ,, with http 500 error

**Comment by felixarntz** [comment]
The SQLite module will be removed from Performance Lab in the upcoming release, see #737 for additional context. As such, please report this issue in the [standalone plugin repository](https://github.com/WordPress/sqlite-database-integration) instead.
