### ISSUE TITLE
The server performance object-cache.php dropin needs a useful header

### ISSUE THREAD

**Issue by OllieJones** [WordPress/performance#615]
## Bug Description

When Performance Lab is activated, visiting `/wp-admin/plugins.php?plugin_status=dropins` shows no useful information. 

This isn't just a dashboard cosmetic issue; other code that handles drop-ins uses [get_plugin_data()](https://developer.wordpress.org/reference/functions/get_plugin_data/) to figure out what's going on. The ability to understand the drop-in situation from code will be critical to the success of other drop-ins if this particular hack lives a long time (like hacks tend to do...).

## Steps to reproduce

1. Install and activate some any object cache drop-in.
2. View the drop-ins via  `/wp-admin/plugins.php?plugin_status=dropins` and observe useful info about the drop-in.
3. Install and activate Performance Lab.
4. View the drop-ins via  `/wp-admin/plugins.php?plugin_status=dropins` and observe just rudimentary data.

## Additional Context

 - PHP Version:  7.4.3
 - OS: Linux
 - Browser: any
 - Plugin Version: 1.8.0
 - Device: any

##

Till did a good job of this in the redis object cache.  https://github.com/rhubarbgroup/redis-cache/blob/develop/includes/object-cache.php

**Comment by felixarntz** [comment]
Thanks @OllieJones, I'll work on enhancing this. I keep forgetting that having a plugin header on drop-ins actually helps. Great catch!
