### ISSUE TITLE
Benefit from static analysis

### ISSUE THREAD

**Issue by szepeviktor** [WordPress/performance#622]
## Bug Description

There are errors in the code.
e.g. `webp_uploads_update_image_onchange`: _Callback expects 5 parameters, $accepted_args is set to 7._

## Steps to reproduce

1. `composer require --dev szepeviktor/phpstan-wordpress`
2. `vendor/bin/phpstan analyse -c vendor/szepeviktor/phpstan-wordpress/extension.neon admin/ modules/ server-timing/ *.php --level=0` then raise level by one
3. Benefit!

Please consider using PHPStan.
Thank you!

**Comment by felixarntz** [comment]
Thank you for the report @szepeviktor! We'll have a look and should get those bugs fixed soon.

**Comment by szepeviktor** [comment]
I declare a **miracle** if WC will meet PHPStan :)
