### ISSUE TITLE
Integrating Wordpress with the existing react application

### ISSUE THREAD

**Issue by AjithKumarRaviChandran** [WordPress/performance#626]
I have a Wordpress blog and hosted in the domain blog.domain.com now I want to move this my main domain which is domain.com/blog , the main domain run the web app which is built with react js and we use nginx as our web server to run both the application.

How can I integrate the Wordpress with the existing react application do let me know if you have done something on similar work

**Comment by eclarke1** [comment]
@jamesozzie tagging you here to kindly seek your guidance on where this issue should live. I don't feel like it's perhaps the right place in the performance repo. cc @joemcgill @felixarntz for guidance also.

**Comment by jamesozzie** [comment]
@eclarke1 Agreed that the Performance Lab repository may not be the most suitable resource for assistance with integrating a WordPress install with a web app. 

@AjithKumarRaviChandran Have you tried reaching out on Stackoverflow or other resource on this? You may also consider using a headless WordPress setup with your web app. This isn't something we provide support with here in the Performance Lab forums.

**Comment by joemcgill** [comment]
I'm going to go ahead and close this issue, as it is not relevant to the Performance Lab plugin and there haven't been any responses in a few weeks. Thanks all.
