### ISSUE TITLE
Bump minimum WP version to 6.1, remove merged modules

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#627]
For context on why I'm opening this issue, please see https://make.wordpress.org/performance/handbook/performance-lab/version-support-policy/. Specifically the following:
> The Performance Lab plugin commits to supporting the latest stable version of WordPress core.

> The Performance Lab plugin commits to only removing a module in combination with bumping the minimum WordPress version requirement to the same stable core release that the merged module code was published with.

The two Performance Lab modules for the Site Health checks on full page cache and persistent object cache have been launched in WordPress core's version 6.1, see https://make.wordpress.org/core/2022/10/06/new-cache-site-health-checks-in-wordpress-6-1/. Any iterations of them make most sense to happen in core, and as such the modules in the Performance Lab are now obsolete (they are already disabled from loading when using WP 6.1 anyway).

Therefore I suggest to remove the two modules now entirely. Per the above policy, this also means we have to bump the minimum required WordPress version of the Performance Lab plugin to 6.1, since that is when those two modules were made available in WordPress core.

**Comment by jeffpaul** [comment]
I'd recommend we increment the PL version by a major number here and call out that those are being removed in case anyone extended hooks from PL that will now need to be validated against core.  The chances of that seem low, but probably important enough to do in any case.

**Comment by joemcgill** [comment]
I agree with @jeffpaul and wonder if we should plan a 1.10 release prior to this change that deprecates any functions that could cause fatals if they have been extended on sites that are not on the latest release?

**Comment by joemcgill** [comment]
On a closer read of the version support policy, it seems pretty clear, so removing is probably fine. It would probably be worth adding some docs to the handbook about the version number scheme being followed.

**Comment by jeffpaul** [comment]
Noting what's being removed is worth calling out in the Upgrade Notice section and as a top line note in the Changelog section in readme.txt.

**Comment by felixarntz** [comment]
This issue is now ready for development, requiring a minimum WP version bump to 6.1, and the two Site Health modules merged in 6.1 need to be removed completely.
