### ISSUE TITLE
Disable Server Timing via filter

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#628]
## Feature Description

Object Cache Pro and Redis Object Cache both allow users to enable and disable the Redis cache via CLI and UI. 

This plugin hijacking the `object-cache.php` file prevents that core functionality.

I’d like to disable the Server Timing hijack using a filter, not a constant, from my plugins.

It created an unnecessary support burden over the past weeks.

**Comment by OllieJones** [comment]
My fairly new object cache plugin, modeled on Till's, has this FAQ https://wordpress.org/plugins/sqlite-object-cache/#can%20i%20use%20this%20with%20the%20performance%20lab%20plugin%3F 

At drop-in load time, ordinary plugins haven't had a chance to register hooks.

With respect, I think this approach of borrowing the drop-in is not workable for widespread production.
