### ISSUE TITLE
Revisit how we handle object-cache.php conflicts

### ISSUE THREAD

**Issue by jamesozzie** [WordPress/performance#630]
## Bug Description

Based on [one users testing](https://wordpress.org/support/topic/plugin-overwrites-existing-third-party-wp-content-object-cache-php/#post-16403840) with the plugin when also using Redis Object Caching pro, Redis Cache pro is disabled when it determines an object-cache.php file present that isn't generated from Redis Object Caching pro. All the features of Redis Cache Pro are disabled when it comes across a non Redis Cache Pro object-cache file. 

While it's possible any resolution on this may be applicable on the Redis Object Cache pro side, it may be an opportunity to check how the plugin handles such conflicts. At present we're moving the contents of a third party plugins `object-cach.php` file to `object-cache-plst-orig.php`, and then requesting that within the footer of the PL placed `object-cache.php` file. Maybe there's another way of using a third party caching plugin alongside the PL object-cache.php file. 

Note also that we did make changes recently (PR #616) to resolve issues with third party plugin caching file contents being added to both the `object-cache.php` and `object-cache-plst-orig.php` files. 

There is also an [existing PL GitHub issue](https://github.com/WordPress/performance/issues/628) specific to Redis Cache Pro which, once actioned will provide a solution.  

## Steps to reproduce

1. Install the PL plugin on a site that already have Redis Object Cache Pro active
2. Check the `object-cache.php` file contents to ensure the PL plugin has overwritten the existing `obect-cache` file (while moving the existing one to `object-cache-plst-orig.php`
3. Check your WP dashboard and notice the [invalid status](https://i.snipboard.io/fjVKcY.jpg) of the drop-in file

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/214602675-bc62e62f-0452-4a8e-8d27-0b72582d782a.png)

**Comment by tillkruss** [comment]
See #629.

**Comment by felixarntz** [comment]
Noting that, while we keep working on a solution here, #628 / #629 will allow disabling this behavior of the PL plugin via filter, making it reasonable for plugins to do so. It is already possible to do that by defining a constant, however that approach is less suitable for a plugin and rather for an individual site via `wp-config.php`, so adding the filter is helpful.

I will keep investigating to find a more reliable solution for this problem.

**Comment by tillkruss** [comment]
@felixarntz: It would be really nice if this was a core feature to load even before `advanced-cache.php`:

https://github.com/WordPress/wordpress-develop/blob/4a9eb3d31f045e265fe9e75e87a5ebd6023bb4cd/wp-settings.php#L52-L60

We could also scan the `wp-config.php` file for `require_once(ABSPATH . 'wp-settings.php');` and include `server-timing.php` right before it. The WP CLI package has helper methods for that.

**Comment by felixarntz** [comment]
Noting here that we should also avoid introducing any global functions or classes: Due to another bug, they can raise a fatal error, see https://wordpress.org/support/topic/fatal-error-when-reactivates-performance-lab-plugin/.

**Comment by tillkruss** [comment]
> Noting here that we should also avoid introducing any global functions or classes: Due to another bug, they can raise a fatal error...

Some `advanced-cache.php` implementations (like Batcache) will load `object-cache.php` very early in the request to get access to `wp_cache_*()` functions for page caching.

**Comment by felixarntz** [comment]
@tillkruss Thanks, that is useful context to have. Not sure how relevant it is for the current problems, but I certainly hadn't considered that so far. 👍
