### ISSUE TITLE
Add module-specific readme files and enhance CLI command to include standalone plugin readme files

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#636]
## Feature Description

Follow up to #635: Since we're going to publish modules as individual plugins, we will need to have `readme.txt` files for them. While this is required for the plugins anyway, it is also a great way for us to provide an overview for each individual module in the GitHub repository.

We can add a `README.md` file in every module directory and then potentially transform it into a `readme.txt` in a build step; or alternatively we can simply format the `README.md` file as a plugin readme from the very start (see https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/).

For the initial scope of this implementation, let's limit the work to just the `images/webp-uploads` module, similar to #635.

### Requirements

* A `readme.txt` file for the WebP Uploads standalone plugin should be added to the `image/webp-uploads` module folder. Some notes on the content:
    * We should focus on a basic foundation, let's not get too caught up in the initial readme content. We can always iterate.
    * The readme can generally follow what the overall Performance Lab readme contains, however of course scoped to just the future standalone WebP Uploads plugin.
    * Let's use version number 1.0.0.
    * For the short description of the plugin, we can use what's currently the short description of the module. Maybe we can tweak it to start with "WordPress core feature plugin to ..." (do xyz)
    * For the longer description, we don't need to provide too much detail for now since this issue is mainly about setting up a minimum viable readme version. It would be a good idea to include links that provide more context, e.g. to the different WebP for WordPress core proposal posts and the Trac ticket.
    * The Installation and FAQ sections can be almost taken over from Performance Lab as is, since the questions are all either generic (just need minor tweaks to focus on "WebP Uploads" instead of "Performance Lab") or already specific to the WebP feature.
    * Let's start with a fresh changelog, just to cover the upcoming initial 1.0.0 release.
* A new `export-ignore` rule should be added to `.gitattributes` that ensures that no `readme.txt` file from any module directory is included in an overall ZIP build, so that the overall Performance Lab plugin ZIP build does not include those readme files. Of course it still needs to include its own `readme.txt` file though.
* As a result of the above, we need to ensure that the `webp-uploads` standalone plugin built via the `build-plugins` script from #635 now contains the new `readme.txt` file.

**Comment by joemcgill** [comment]
I agree that it would be nice to include module-specific README.md files with each module, and using those to auto-generate the readme.txt files seems like a good approach. I think we should handle organizing modules into individual folders with README files in this task, and do this before #635. Then we can make building the readme.txt file a part of the build process.

**Comment by felixarntz** [comment]
@joemcgill See my reply https://github.com/WordPress/performance/issues/635#issuecomment-1414175036, can you expand why you think this needs to be done before #635? To me those tasks can easily be separated, and we can start working on both of them at the same time.

But implementing the basic build command doesn't have to wait for the readme files to be present. Of course, actually _deploying_ plugins that way for sure needs to wait for both issues to be completed, but I'd prefer if we iterated in smaller chunks, and to me blocking #635 with this shouldn't be necessary.

**Comment by mukeshpanchal27** [comment]
Closed this as completed in #664
