### ISSUE TITLE
Set up WordPress.org repositories for standalone plugins

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#637]
## Feature Description

Once we have made a decision on which modules to publish as standalone plugins (see #618), we need to set up their directories in the WordPress.org plugin repository. This needs to be manually handled, by using the `performanceteam` wordpress.org account that was created for that purpose.

We should start doing that once we have implemented #635 and #636, as we will be able to use those built plugin directories as ZIP files to submit for the plugin review.

Repositories for the following modules need to be created:
* [x] ~~SQLite Integration (`https://wordpress.org/plugins/sqlite-database-integration/`)~~
* [x] WebP Uploads (`https://wordpress.org/plugins/webp-uploads/`)
* [x] Fetchpriority (`https://wordpress.org/plugins/fetchpriority/`)
* [x] Dominant Color (`https://wordpress.org/plugins/dominant-color-images/`)

**Comment by mukeshpanchal27** [comment]
@felixarntz, As we already merged #635 and #636 is almost ready for merge, can you please setup a repository for the first standalone plugin (WebP Uploads) so we can start #638?

**Comment by felixarntz** [comment]
@mukeshpanchal27 I will set it up by end of this week.

**Comment by mukeshpanchal27** [comment]
@felixarntz We already got approval for WebP Uploads, so can we close this issue or wait until other repositories are setup on WordPress.org?

**Comment by felixarntz** [comment]
@mukeshpanchal27 I think we should keep this open until we have the other repositories too.

**Comment by joemcgill** [comment]
@felixarntz can you update the description with a checklist of each of the repos that need to be open before this is closed?

**Comment by felixarntz** [comment]
@joemcgill Added!

**Comment by mukeshpanchal27** [comment]
Updated `Fetchpriority` plugin detail in description.

**Comment by felixarntz** [comment]
Thanks @mukeshpanchal27!

**Comment by mukeshpanchal27** [comment]
We are currently awaiting approval for the Dominant Color feature from the plugin review team. Once we receive their approval, we can proceed to the next milestone.

**Comment by felixarntz** [comment]
I am happy to report that the Dominant Color Images standalone plugin has been approved! So we now have the `https://wordpress.org/plugins/dominant-color-images/` repository set up. Opening a PR shortly to configure the module to be published to that plugin repo.
