### ISSUE TITLE
Example wp-config.php for sqlite site

### ISSUE THREAD

**Issue by rchrd2** [WordPress/performance#643]
## Feature Description

Hello, I am trying to setup a local development Wordpress site, and would love to just use sqlite from the start. It seems like in order to use sqlite, I first need to have MySQL setup and then switch to sqlite. Is there a way to just run sqlite from the very beginning? I copied the `performance-lab` folder into `wp-content/plugins`, but it's unclear how to activate sqlite.

Thank you.

**Comment by OllieJones** [comment]
As of the end of February 2023, SQLite-only installations aren't yet available.

**Comment by felixarntz** [comment]
The SQLite module will be removed from Performance Lab in the upcoming release, see #737 for additional context. As such, please report this issue in the [standalone plugin repository](https://github.com/WordPress/sqlite-database-integration) instead.
