### ISSUE TITLE
SQLite: Support PHPUnit test suite

### ISSUE THREAD

**Issue by adamziel** [WordPress/performance#644]
## Description

#547 added SQLite support through the [aaemnnosttv/wp-sqlite-db](https://github.com/aaemnnosttv/wp-sqlite-db) drop-in database plugin which rewrites MySQL queries to SQLite queries. Unfortunately, [many MySQL queries are unsupported at the moment](https://github.com/aaemnnosttv/wp-sqlite-db/issues/55) and [a lot of WordPress unit tests fail](https://github.com/WordPress/wordpress-playground/issues/111).

Let's find a way to support all the MySQL queries that can be translated to SQLite.

cc @aristath @felixarntz

**Comment by felixarntz** [comment]
The SQLite module will be removed from Performance Lab in the upcoming release, see #737 for additional context. As such, please report this issue in the [standalone plugin repository](https://github.com/WordPress/sqlite-database-integration) instead.

**Comment by adamziel** [comment]
@felixarntz GitHub has a [Transfer Issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) feature which allows you to move issues to other repositories without losing the conversation or having to re-create them. It would be handy for keeping a continuity of all the SQLite-related issues. cc @aristath
