### ISSUE TITLE
Add a performance tab under Site Health

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#66]
Each module or specific modules from the performance plugin can take advantage of the site Helth from WordPress to indicate whether a module was not installed due to specific dependency does not exist and is recommended to enable at the server level, the site health can be used as well in order to provide a piece of more detail information or run reports for specific metrics.

![2021-12-22_15-35](https://user-images.githubusercontent.com/3921289/147157996-dae1fbc5-523f-4983-8a7b-0e9296e52448.png)

**Comment by tillkruss** [comment]
We could use the new `site_health_navigation_tabs` filter added in 5.8:

https://make.wordpress.org/core/2021/06/22/extending-the-site-health-interface-in-wordpress-5-8/
