### ISSUE TITLE
Migrate SQLite integration plugin back into monorepo for development

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#661]
## Feature Description

As part of the creation of standalone plugins from the Performance Lab modules and unbundling the overall Performance Lab plugin, the codebase and development of [standalone SQLite integration plugin](https://wordpress.org/plugins/sqlite-database-integration/) should be migrated back into this monorepo from its current repository https://github.com/WordPress/sqlite-database-integration.

Note that this is only to simplify development, contributor onboarding, and maintenance, but most importantly this is crucial to unify the codebases, since currently the code for the feature is being developed in two places.

Migrating the codebase back into this repository can only happen once #635 #636 #637 #638 have been completed, and preferably we should have already launched a first version to ensure the new build process for deploying modules as standalone plugins works as expected.

### Requirements

* The codebase from the https://github.com/WordPress/sqlite-database-integration repository should be copied into the `database/sqlite` module folder. Any differences should be individually reviewed to decide which of the two versions to keep (almost as if it was a merge conflict).
* The `readme.txt` file should be reviewed and be in line with the other `readme.txt` files for the standalone plugins in this monorepo.
* The `plugins.json` file should be expanded to include the `database/sqlite` module with its plugin slug `sqlite-database-integration` and the next version number (needs to be higher than the current version available on https://wordpress.org/plugins/sqlite-database-integration/).

**Comment by felixarntz** [comment]
@aristath Let me know if the above sounds reasonable to you.

Note that we will likely need a few weeks until we can do this, as we first have to build out the infrastructure to deploy the plugins.

**Comment by aristath** [comment]
Sounds reasonable 👍

**Comment by mukeshpanchal27** [comment]
@aristath I'm going to assign this issue to you, as you are more involved in it. Is PR #677 sufficient to address this issue, or do we require a new PR?

**Comment by felixarntz** [comment]
@mukeshpanchal27 I think #677 is part of the way there, but we'll eventually need to coordinate a few more things, for example adding the necessary constant, generator tag, and also outside of writing code we'll need to coordinate to define a clear cut-off for when this repository becomes the source of truth and the other GitHub repository gets deprecated.

I think most of this issue is not about code but coordinating those things.

**Comment by aristath** [comment]
Closing this one, as in the performance team's meeting on 2023-04-25 it was decided to decouple the SQLite module from the Performance Lab plugin 👍
