### ISSUE TITLE
Check for each module to only load it if the corresponding standalone plugin is not loaded

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#666]
## Feature Description

As part of #656, a temporary state between completion of Milestone 1 and Milestone 2 will be that certain features will exist both as a Performance Lab module and as a standalone plugin. We should make sure there are no conflicts. Specifically, we can ensure that, if a certain standalone plugin is active, we don't load or allow enabling the corresponding Performance Lab module.

### Requirements

* The function that loads the active modules should for each module check whether it also exists as a standalone plugin and whether that standalone plugin is active. If yes, the respective module should not be loaded.
* The same check should happen on the Performance Lab admin screen. Any module where the standalone plugin is active should as disabled and with a message similar to when it cannot be loaded for another reason: `The module cannot be managed with Performance Lab since it is already active as a standalone plugin.`

**Comment by mukeshpanchal27** [comment]
Closed this as completed in https://github.com/WordPress/performance/pull/670
