### ISSUE TITLE
Setup `.github` templates

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#68]
As a feature request would be ideal to define templates for Bugs / Feature Requests in order to have a standard format for both. 

Details:

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by eugene-manuilov** [comment]
Created a pull request that adds two templates: one for bug reports and one for feature requests. #88

**Comment by felixarntz** [comment]
Fixed via #88
