### ISSUE TITLE
Fix `WordPress-Extra` rules resulting problems for SQLite module

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#698]
## Bug Description

Followup issue for https://github.com/WordPress/performance/pull/695#pullrequestreview-1371142493

Performance Lab plugin Include `WordPress-Extra` rules in PHPCS configuration and fix resulting problems for all other modules except SQLite.

Open [phpcs.xml.dist](https://github.com/WordPress/performance/blob/trunk/phpcs.xml.dist#L11-L12) and remove that two line then run 'npm run lint-php` you can see the error/notice in output.

**Comment by mukeshpanchal27** [comment]
@felixarntz @joemcgill Can i transfer issue to https://github.com/WordPress/sqlite-database-integration repo?

**Comment by mukeshpanchal27** [comment]
@felixarntz @joemcgill ☝️

**Comment by joemcgill** [comment]
Since we're not managing the development of the SQLite plugin in this repo any more, I think we can go ahead and close this issue and leave decisions about PHPCS rules to that project.
