### ISSUE TITLE
"Generate JPEG files in addition to WebP" presents JPG files instead of WEBP

### ISSUE THREAD

**Issue by ipajen** [WordPress/performance#706]
## Bug Description

"Generate JPEG files in addition to WebP
Enabling JPEG in addition to WebP can improve compatibility, but will effectively double the filesystem storage use of your images."

When enabling "Generate JPEG files in addition to WebP" jpg files is presented and used in media library. (The .webp files are created). If the "Generate JPEG files in addition to WebP" is not enabled then .webp are created and presented.

## Steps to reproduce

1. Install and activate WebP Uploads 1.0.0
2. Enable "Generate JPEG files in addition to WebP" in /wp-admin/options-media.php
3. Go to wp-admin/media-new.php and upload a new .jpg file
4. The .jpg file are presented instead of .webp
5. Expected the .webp file to be presented or "Generate JPEG files in addition to WebP" to renamed to "Generate WebP files in addition to JPEG"

### Environment
- WordPress: 6.2
- PHP: 8.2.3
- Server: LiteSpeed
- Database: mysqli (Server: 10.4.28-MariaDB / Client: mysqlnd 8.2.3)
- Browser: Edge 111.0.1661.62 (Windows 10/11)
- Theme: Twenty Twenty 2.2
- MU-Plugins:
  * Health Check Troubleshooting Mode 1.9.0
  * WordPress automation by Installatron
- Plugins:
  * Enable jQuery Migrate Helper 1.3.0
  * Health Check & Troubleshooting 1.6.0
  * PHP Compatibility Checker 1.6.1
  * Plugin Compatibility Checker 1.9
  * Query Monitor 3.12.1
  * WebP Uploads 1.0.0
  * WordPress Beta Tester 3.3.7

**Comment by eclarke1** [comment]
@mukeshpanchal27 is this anything you could verify please? For now, adding to the Images focus area and Needs Triage label please. cc @adamsilverstein

**Comment by mukeshpanchal27** [comment]
Hi @ipajen 

Thanks for the issue.

When the any new image is uploaded, the plugin will generate the WebP versions, and the source URL for the WebP file is stored in the attachment metadata. The WebP file isn’t directly available in the media library. You can see this WebP images in the page content.

Regarding `Generate JPEG files in addition to WebP`, check issue #525 for more details.

Let me know if you have any other questions.

Thanks

**Comment by ipajen** [comment]
@mukeshpanchal27 Thanks for feedback, if the "Generate JPEG files in addition to WebP" is not in used only a .webp picture will be generated and presented in the media library.  

I still believe and expects the .webp file to be presented if the settings "Generate JPEG files in addition to WebP" are ticked or  should be renamed to "Generate WebP files in addition to JPEG" as a improvement and not a bug.

**Comment by mukeshpanchal27** [comment]
> @mukeshpanchal27 Thanks for feedback, if the "Generate JPEG files in addition to WebP" is not in used only a .webp picture will be generated and presented in the media library.

The WebP images are only available in the frontend, not in the admin panel.

> I still believe and expects the .webp file to be presented if the settings "Generate JPEG files in addition to WebP" are ticked or should be renamed to "Generate WebP files in addition to JPEG" as a improvement and not a bug.

As the plugin's default settings, it only generates WebP images, and if you checked these settings, it will also generate JPEG images, so I don't think we need to change it.

**Comment by ipajen** [comment]
Thank you, Ok. No need to to change name as its default behavior, but I really don't understand why it should be different behavior when .webp is presented, see pictures for example when .webp is shown in admin panel. And when .webp is default i still expect it to be presented.

https://ibb.co/rbBFqBG
https://ibb.co/Lz4WBv9

**Comment by mukeshpanchal27** [comment]
Thanks @ipajen, for the screenshots and details.

It seems you have use default setting for "Generate JPEG files in addition to Web" option, so it will generate WebP versions of thumbnail images, and you uploaded a bigger image than the [WordPress `big_image threshold` of 2560px](https://make.wordpress.org/core/2019/10/09/introducing-handling-of-big-images-in-wordpress-5-3/#:~:text=The%20default%20threshold%20value%20is,as%20the%20largest%20available%20size.), so it will generate a `-scale` version of the image, and it will load that image in the admin panel instead of full JPEG version.

You have two options here.
- Enable the "Generate JPEG files in addition to Web" option so it generates JPEG images for bigger images.
- Upload a smaller image then 2560px, so it will use the original JPEG image.

I hope this answers your question. Thanks.

**Comment by mukeshpanchal27** [comment]
As we didn’t receive a response I’ll mark this as closed. Feel free to open a new support topic if you continue to encounter issues, or reopen this topic and we’d be happy to assist.
