### ISSUE TITLE
Cannot make dominant color option work

### ISSUE THREAD

**Issue by jouino16** [WordPress/performance#707]
## Bug Description

Dominant color option is not working when enabled. I'm using a Blocksy theme with Stackable blocks.

## Steps to reproduce

1. Activate the dominalt color option (it is activated by deafult)
2. Refresh a web page that has images, and you will notice that there are no dominant colors displayed.

## Additional Context

 - PHP Version: 8.0
 - OS: Ubuntu server
 - Browser: Edge
 - Plugin Version: Perfomance Lab Version 2.1.0

**Comment by jamesozzie** [comment]
@jouino16 Thanks for reaching out and sharing your experience. Can you share an example URL if possible, or details of how you're adding images? 

In my case, when I try to recreate the same with Stackable library item that includes external images I get the same (no dominant color), but when I replace the image with one of my own the dominant color does display ([recording](https://recordit.co/ftW1diIciA)). This is using the Blocksy theme 1.8.82.

**Comment by mukeshpanchal27** [comment]
@jouino16 For your information, dominant color only work for newly uploaded images after the feature is enabled.

**Comment by jouino16** [comment]
@jamesozzie Thank you for your quick reply. I Only tested on already uploaded images.

@mukeshpanchal27 Thank you for your reply. You are right, it didn't work because of that. I uploaded a new image after activating the option and it did work. As feedback, it would be better to add the option on whether to apply it on already uploaded images or not.

Thank you both you for your reactivity :)

**Comment by jamesozzie** [comment]
@jouino16 Just a quick note on this issue. You can use the [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) plugin in order to regenerate all your featured images. After doing so, the dominant color markup will appear for your pre-existing images also.

I'll close this GitHub issue but do ask if you have any further questions on this. Thank you!

**Comment by jouino16** [comment]
@jamesozzie Thank you very much for your note. Yes, this is what I meant through my previous feedback.
So to wrap up my feedback, it would be better to include images regeneration in order to convert them to WebP and generate dominant colors. For the WebP regeneration, it should keep track of the old image and use them in case the browser does not support WebP. And one last thing, is to do the same with Avif format.
I don't know where to post these suggestions in order to enhance the plugin. If you are OK with these suggestions, please add them to the roadmap.

**Comment by jamesozzie** [comment]
Thanks for the update @jouino16. Based on your suggestions, you may wish to subscribe to https://github.com/WordPress/performance/issues/24. When compete, this will ensure pre-existing images are regenerated. The dominant color styling will also apply for any regenerated images.

**Comment by jouino16** [comment]
Thank you, @jamesozzie, for sharing the thread, I subscribed.
