### ISSUE TITLE
Fix standalone plugin publishing script to not attempt re-publishing the same version of a plugin

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#714]
## Bug Description

Standalone plugins are published either manually (via `workflow_dispatch`) or as part of the main Performance Lab plugin release process. However, they should only be published if the configured version of the standalone plugin is actually different from the version that is already released for it.

As part of the Performance Lab plugin 2.2.0 release, we noticed that there is a problem with that workflow still. We had already published [WebP Uploads](https://wordpress.org/plugins/webp-uploads/) version 1.0.0 manually before, but the workflow tried to publish the same version again. While it fortunately did not re-publish the plugin in any way (so no short-term urgent fix was required), the workflow attempted to re-publish and then failed, which is undesirable. We should instead include a check that, if the version is the same as the already published one, it should bail early.

## Steps to reproduce

This cannot be realistically reproduced without doing a plugin release, which should not be attempted for testing purposes. Instead, please look at workflow run https://github.com/WordPress/performance/actions/runs/4723956809/jobs/8380581174 to see exactly how it went wrong.

Also see the [relevant release chat](https://wordpress.slack.com/archives/C02KGN5K076/p1681750922587389) for additional context.

## Proposed solution

* After checking out the SVN repository, first check whether the current version configured to publish in `plugins.json` for the standalone plugin (e.g. `1.0.0`) already exists as a SVN tag folder (e.g. `tags/1.0.0`).
* If so, none of the remaining steps should be performed. Instead, a message should be logged (e.g. "Version x of standalone plugin y was already published"), and the workflow should terminate successfully.

**Comment by mukeshpanchal27** [comment]
@felixarntz I spent some time on issue, I think we can easily fix this issue in 10up action `deploy.sh`. I can't find any workaround solution for GitHub action in which we can check versions.

```
if [[ -d "tags/$VERSION" ]]; then
    echo "Version $VERSION of plugin $SLUG was already published";
    exit
fi
```

I tried this in folk repo and here is the result for it. At the moment the [WebP Uploads](http://plugins.svn.wordpress.org/webp-uploads/tags/) is release with version `1.0.0`

- Run the deploy workflow with the slug `webp-uploads` and version `1.0.0`. It will show the message "Version 1.0.0 of plugin webp-uploads was already published" and skip the script execution without throwing any errors. [Check result here](https://github.com/mukeshpanchal27/performance/actions/runs/4742549334/jobs/8420966951#step:6:74)
- Run the deploy workflow with the slug `webp-uploads` and version `1.0.1`. It will execute all the steps and commit the new version to the SVN repository(For testing i have comment the SVN commit step). [Check result here](https://github.com/mukeshpanchal27/performance/actions/runs/4742553012/jobs/8420973341#step:6:97)

@joemcgill Can we open an issue in the 10up deploy action repo and address it? It benefits all users who perform this kind of action.

**Comment by joemcgill** [comment]
I think addressing this upstream is a great idea, @mukeshpanchal27. Do you feel comfortable making the ticket there?

**Comment by felixarntz** [comment]
Thanks @mukeshpanchal27, that sounds good to me as well!

**Comment by mukeshpanchal27** [comment]
Thank you both for feedback. I have raise the [issue 123](https://github.com/10up/action-wordpress-plugin-deploy/issues/123) and [PR 124](https://github.com/10up/action-wordpress-plugin-deploy/pull/124) on upstream. When you get moment please review it.

Going to close this issue now. Thanks!

**Comment by joemcgill** [comment]
Thanks @mukeshpanchal27! I've added a review to that PR.
