### ISSUE TITLE
Put menu class into BODY tag

### ISSUE THREAD

**Issue by LukeDouglas2** [WordPress/performance#721]
For the life of me, I simply do not understand why a class entered on a menu is only assigned to the LI tag when it should be added to both the BODY tag and the LI tag or at least have a "Page Class" field for menu links or have a check-box to "Add class to BODY".

Yea, I know. I could go into the code and edit it directly but this should be out of box functionality for WordPress.

This would add so much functionality for CSS styling.

**Comment by felixarntz** [comment]
Thanks for raising the issue @LukeDouglas2! This repository is primarily focused on the Performance Lab plugin and the efforts of the WordPress performance team.

What you're outlining sounds like it is more generally applicable to WordPress core. Therefore I would like to ask you to please open a [ticket on WordPress Core Trac](https://core.trac.wordpress.org/newticket) instead.
