### ISSUE TITLE
Some warning messages on the Site Health screen

### ISSUE THREAD

**Issue by iMatrix75** [WordPress/performance#735]
## Bug Description

There are some warning messages on the Site Health screen

Warning: Undefined array key "wp_comments" in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

Warning: Attempt to read property "rows" on null in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

Warning: Undefined array key "wp_options" in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

Warning: Attempt to read property "rows" on null in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

Warning: Undefined array key "wp_posts" in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

Warning: Attempt to read property "rows" on null in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

Warning: Undefined array key "wp_terms" in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

Warning: Attempt to read property "rows" on null in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

Warning: Undefined array key "wp_users" in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

Warning: Attempt to read property "rows" on null in C:\xampp\htdocs\wp-admin\includes\class-wp-site-health.php on line 3406

## Steps to reproduce

1. Go to 'Dashboard'
2. Click on 'Site Health screen'
3. See error

## Additional Context

 - PHP Version: PHP/8.2.4 + Apache/2.4.56 (Win64)
 - OS: Windows Server  
 - Browser: Edge
 - Plugin Version: performance-lab 2.3.0

**Comment by mukeshpanchal27** [comment]
Hi @iMatrix75, thank you for bringing this issue to our attention.

I have tried to replicate the same issue with the Performance Lab plugin and the latest version of WordPress, but I couldn't encounter the problem you described. To further investigate, could you please try disabling the Performance Lab plugin and see if that resolves the issue? If the problem persists, it's possible that another plugin may be causing the conflict. In that case, I would recommend deactivating your plugins one by one and checking if the issue persists after each deactivation.

Please let me know the results of these steps, and if you have any further information or questions, feel free to share.

**Comment by iMatrix75** [comment]
Thank you for getting back to me. I reinstalled latest xampp and wordpeess, and only installed this plugin on my computer.  These warning messages will appear when activate this checkbox(Enable SQLite integration). By turn off the checkbox and the WordPress works fine.
Attach the apache  error.log file
[error.log](https://github.com/WordPress/performance/files/11631853/error.log)

**Comment by mukeshpanchal27** [comment]
Thank you for sharing the report.

The SQLite module is not part of the Performance Lab plugin and will be removed in the upcoming release. Please check [this issue](https://github.com/WordPress/performance/issues/738) and note that it is now available as a standalone plugin at https://wordpress.org/plugins/sqlite-database-integration/. We recommend using that plugin instead of the module.

If you encounter any errors with the plugin, please report them on https://github.com/WordPress/sqlite-database-integration.
