### ISSUE TITLE
Better handle large core JS files

### ISSUE THREAD

**Issue by asafm7** [WordPress/performance#740]
## Feature Description

Better handle large core JS files.

These large JS core files are loaded, but mostly unused in many cases.

Maybe there is a way to load their sections that are actually needed conditionally:
![image](https://github.com/WordPress/performance/assets/14274769/4a9f0f48-351e-48ab-ba8e-2bf19f9bc7d6)

**Comment by lkraav** [comment]
I see blocks-checkout.js listed, so this might be about https://github.com/woocommerce/woocommerce-blocks/discussions/8166

**Comment by asafm7** [comment]
Thanks @lkraav.

Actually, the checkout script is the least of the problems.

The first 2 files are much bigger and are from the WP core.

The only JS-related block I have on this page is WooCommerce Filter by Attributes block.

Dequeuing either one of these files breaks the Filter by Attributes block, although "blocks-checkout", for example, isn't semantically related.

They are probably bound as dependencies.

Loading 0.5 MB of JS just to have a simple filter functionality (which isn't even an Ajax filter) feels redundant.

I assume WooCommerce loads the entire `components.js` because it doesn't have a way to cherry-pick the components it actually needs, and it's Core's responsibility to provide such an option?

**Comment by swissspidy** [comment]
> I assume WooCommerce loads the entire components.js because it doesn't have a way to cherry-pick the components it actually needs, and it's Core's responsibility to provide such an option?

This is probably better proposed in the Gutenberg repo.

I don't think a good solution for this exists though.

**Comment by mukeshpanchal27** [comment]
It was discussed in today's bug scrub. Per https://github.com/WordPress/performance/issues/740#issuecomment-2135055351 you need to open an issue in the Gutenberg repo.
