### ISSUE TITLE
WordPress 6.3 performance highlights

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#742]
In response to https://wordpress.slack.com/archives/C02KGN5K076/p1686613248183619: This issue aims to define/discuss performance highlights to point out for the upcoming WordPress 6.3 release.

Here is the most relevant list of tickets to consider: [High-priority tickets in the 6.3 milestone with performance focus](https://core.trac.wordpress.org/query?priority=high&focuses=~performance&milestone=6.3&group=milestone)

I believe in terms of features, the most important ones are (still pending merge as of today):
* API to enhance script loading performance with `defer` or `async` (https://core.trac.wordpress.org/ticket/12009 / https://make.wordpress.org/core/2022/12/09/enhancing-the-scripts-api-with-a-loading-strategy/)
* Out of the box image loading performance enhancement with `fetchpriority="high"` (https://core.trac.wordpress.org/ticket/58235 / https://make.wordpress.org/core/2023/05/02/proposal-for-enhancing-lcp-image-performance-with-fetchpriority/)

For raw performance enhancements, I believe the two most important tickets are:
* https://core.trac.wordpress.org/ticket/58472 (~15% LCP improvement, still pending merge)
* https://core.trac.wordpress.org/ticket/57756 (~15% server response time improvement, already merged)

Other suggestions welcome! Keep in mind that we're asked to highlight the "top 3 or so most important things/features", so we really should focus on the most important priorities in 6.3.

cc @meherbala @eclarke1

**Comment by meherbala** [comment]
Thanks, @felixarntz and @eclarke1. We have covered most of these tickets in our Beta 1 post.
