### ISSUE TITLE
Improve loading translations

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#745]
The translation process has a large performance impact when in use. Given that many websites are using translations, performance improvements to the translations system should have a large horizontal impact as well.

**Comment by joemcgill** [comment]
This effort is taking place as a feature plugin called Performant Translations. See this [Call for Testing post](https://make.wordpress.org/core/2023/09/05/call-for-testing-performant-translations/) for details.

**Comment by westonruter** [comment]
Since this has landed in WP 6.5, I think this can be closed.
