### ISSUE TITLE
Improve resolving block templates

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#747]
this is a heavy operation for block themes that is unlikely to change often unless the site templates are edited or the theme is updated. The addition of some caching mechanisms could really improve TTFB (note that some improvements to this system have already been implemented during the 6.3 release cycle).

**Comment by joemcgill** [comment]
A few initial tickets related to this effort include:

- [ ] [58196 – Improve performance of `_get_block_templates_paths`](https://core.trac.wordpress.org/ticket/58196)
- [ ] [58319 – Improve performance of `get_block_theme_folders`](https://core.trac.wordpress.org/ticket/58319)

**Comment by joemcgill** [comment]
Consolidating this ticket into the main overview ticket for template loading, #746.
