### ISSUE TITLE
locate_template does not check to see site has parent theme

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#748]
The work scheduled here should please be completed via the following Trac ticket https://core.trac.wordpress.org/ticket/58576

**Comment by joemcgill** [comment]
@kt-12 found a related issue that effects our ability to write good tests around this functionality and opened a new Trac ticket that needs to be reviewed:

https://core.trac.wordpress.org/ticket/58866#ticket

**Comment by mukeshpanchal27** [comment]
I have left a comment on the Trac ticket. The patch is ready for commit. As Jonny is currently on vacation, I kindly request either @felixarntz or @joemcgill to handle the commit process for this ticket.

**Comment by joemcgill** [comment]
We've determined that [58866](https://core.trac.wordpress.org/ticket/58866) was a duplicate of an existing ticket: [18298](https://core.trac.wordpress.org/ticket/18298). I've closed the former and moved the latter into the 6.4 milestone.

**Comment by mukeshpanchal27** [comment]
Core-58576 is committed in https://core.trac.wordpress.org/changeset/56357

Open tracking issue #810 for Core-18298
