### ISSUE TITLE
Improve performance and simplify usage of `block_has_support()` by supporting a string feature and avoiding `_wp_array_get()` for them

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#749]
The work scheduled here should please be completed via the following Trac ticket https://core.trac.wordpress.org/ticket/58532

**Comment by mukeshpanchal27** [comment]
@eclarke1 @felixarntz could we please add an "In Review" column to the project board? It seems to be missing at the moment, and having this column would help us better track the progress of items that are under review. Thank you!

**Comment by eclarke1** [comment]
@mukeshpanchal27 sure thing, that's been done now for all the project boards.

**Comment by mukeshpanchal27** [comment]
Thank you 🎉

**Comment by mukeshpanchal27** [comment]
@kt-12, could you please assess the feedback on the PR and update its status accordingly once it's ready for review? Thank you!

**Comment by mukeshpanchal27** [comment]
Committed in https://core.trac.wordpress.org/changeset/56382
