### ISSUE TITLE
Adding fetchpriority=”high” to the LCP image in WordPress core

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#758]
This [Type] Overview issue is to act as a single entry point to the Adding fetchpriority=”high” to the LCP image in WordPress core work

Feature proposal: https://make.wordpress.org/core/2023/05/02/proposal-for-enhancing-lcp-image-performance-with-fetchpriority/

Trac tickets where the work is taking place: 

Adding fetchpriority to the most important image https://core.trac.wordpress.org/ticket/58235 
PR: https://github.com/WordPress/wordpress-develop/pull/4495

**Comment by mukeshpanchal27** [comment]
@felixarntz @eclarke1, since the work has been completed and merged in version 6.3, could we proceed to close this issue? If there are no further pending tasks. Thank you!
