### ISSUE TITLE
Avoiding to lazy-load LCP / hero images in WordPress core

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#759]
Originally [introduced in WordPress 5.9](https://make.wordpress.org/core/2021/12/29/enhanced-lazy-loading-performance-in-5-9/), there are still outstanding problems with LCP images being lazy-loaded
While one [critical related block theme problem](https://core.trac.wordpress.org/ticket/56930) was recently fixed, other problems remain in the field which need to be assessed

This [Type] Overview issue is designed to provide an entry point to the work ongoing for **Avoiding to lazy-load LCP / hero images in WordPress core**

Here are all the commits and tickets:

https://core.trac.wordpress.org/changeset/55816 (see #[58213](https://core.trac.wordpress.org/ticket/58213))

https://core.trac.wordpress.org/changeset/55821 (see [#58212](https://core.trac.wordpress.org/ticket/58212))

https://core.trac.wordpress.org/changeset/55825 (see [#58089](https://core.trac.wordpress.org/ticket/58089))

https://core.trac.wordpress.org/changeset/55847 (see [#58211](https://core.trac.wordpress.org/ticket/58211))

https://core.trac.wordpress.org/changeset/55850 (see [#56588](https://core.trac.wordpress.org/ticket/56588))

**Comment by mukeshpanchal27** [comment]
@felixarntz @eclarke1, since the work has been completed and merged in version 6.3, could we proceed to close this issue? If there are no further pending tasks. Thank you!
