### ISSUE TITLE
Allow global and non-persistent groups to be filtered

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#76]
See https://core.trac.wordpress.org/ticket/54303 and https://core.trac.wordpress.org/ticket/47884

This is a rarely requested feature, but given the complete lack of flexibility should be addressed.

Core calls `wp_cache_add_global_groups()` very early and using `apply_filters()` is unlikely an option.

Adding and removing groups mid-request could be catastrophic, so having an ignore-list may be the best approach:

```php
define( 'WP_OBJECT_CACHE_NON_GLOBAL_GROUPS' => [ 'users', 'usermeta' ] );
define( 'WP_OBJECT_CACHE_NON_GLOBAL_GROUPS' => 'users, usermeta' ); // support strings as well?
```

We should do the exact same for the `wp_cache_add_non_persistent_groups()` call.

**Comment by tillkruss** [comment]
@janthiel is taking a go at this.

**Comment by tillkruss** [comment]
See https://github.com/pantheon-systems/wp-redis/pull/331 and https://github.com/pantheon-systems/wp-redis/pull/333

**Comment by JanThiel** [comment]
Trac Ticket ref: https://core.trac.wordpress.org/ticket/54303

**Comment by JanThiel** [comment]
WordPress PR (currently still without tests): https://github.com/WordPress/wordpress-develop/pull/2149

**Comment by peterwilsoncc** [comment]
Just some notes of a discussion Till and I had on the PR.

It occurred to me that it might be possible to use a filter for the global groups & require site owners wishing to make use of it to `require_once wp-includes/plugin.php`, this is similar to how `enable_loading_object_cache_dropin` works. https://github.com/WordPress/wordpress-develop/pull/2149#issuecomment-1149502210

@tillkruss asked some follow up questions, see the following few comments in the thread.

**Comment by joemcgill** [comment]
This is not something we're currently focused on, so I'm going to close this so the any related discussion about this issue can remain in the related Trac ticket: https://core.trac.wordpress.org/ticket/54303
