### ISSUE TITLE
Optimizing the autoloaded options database query in WordPress core

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#766]
This issue acts as an overview to a larger project for Optimizing the autoloaded options database query in WordPress core. 
See [module proposal](https://github.com/WordPress/performance/issues/526) for the [Performance Lab plugin](https://wordpress.org/plugins/performance-lab/)

List of associated Trac tickets (subject to change, please add more as they come up):

## WP 6.4 Milestone
- [x] https://core.trac.wordpress.org/ticket/58962
- [x] https://core.trac.wordpress.org/ticket/58963
- [x] https://core.trac.wordpress.org/ticket/58964
- [x] https://core.trac.wordpress.org/ticket/58277 

## WP 6.5 Milestone
- [x] https://core.trac.wordpress.org/ticket/39537
- [x] https://core.trac.wordpress.org/ticket/56912
- [x] https://core.trac.wordpress.org/ticket/59975

## WP 6.6 Milesone
- [x] https://core.trac.wordpress.org/ticket/42441

~https://core.trac.wordpress.org/ticket/42743~ not currently planned

## Performance Lab
- [x] https://github.com/WordPress/performance/issues/889

**Comment by felixarntz** [comment]
I have updated the issue description to include a few related Trac tickets here that belong to this greater piece of work, most of which I just opened based on previous conversations.

cc @spacedmonkey @joemcgill

**Comment by mukeshpanchal27** [comment]
@felixarntz @joemcgill I have raise [PR 4970](https://github.com/WordPress/wordpress-develop/pull/4970) for the issue [#58962](https://core.trac.wordpress.org/ticket/58962).

**Comment by mukeshpanchal27** [comment]
https://core.trac.wordpress.org/ticket/58963 is committed.

**Comment by mukeshpanchal27** [comment]
https://core.trac.wordpress.org/ticket/58962 get committed.

**Comment by mukeshpanchal27** [comment]
Core-58964 get committed last week.

**Comment by mukeshpanchal27** [comment]
Core-58277 get committed https://core.trac.wordpress.org/changeset/56595

**Comment by mukeshpanchal27** [comment]
@eclarke1 https://core.trac.wordpress.org/ticket/42743 is not part of 6.4 milestone. Do we need to remove it from the list? cc. @joemcgill @felixarntz

**Comment by joemcgill** [comment]
Following up on the above—I don't think this overview ticket should be limited to things in the WP 6.4 milestone. Let's keep all the issues related to this epic listed here so we don't forget about pieces that we weren't able to get to during the 6.4 release. I've updated the description accordingly.

**Comment by mukeshpanchal27** [comment]
@eclarke1 @joemcgill @spacedmonkey, Core-42441 has been punted to `6.5`. Do we need to open a separate issue for `6.5` tickets and close this one?

**Comment by felixarntz** [comment]
@mukeshpanchal27 I think we should keep this open - IMO the overview tickets shouldn't be tied to a specific WP release, only the individual tickets within.

**Comment by joemcgill** [comment]
> IMO the overview tickets shouldn't be tied to a specific WP release, only the individual tickets within.

Agreed. I've updated the overview description

**Comment by joemcgill** [comment]
@pbearne shared [this gist](https://gist.github.com/pbearne/ce21417bf5ecfa10b84afc758092cd9f) of an idea to experimentally cache needed options per page.

**Comment by tillkruss** [comment]
> nk we should keep this open - IMO the overview tickets shouldn't be tied to a specific WP release, only the individual tickets within.

This was discussed in #526 and there are some significant downsides to this approach.

**Comment by pbearne** [comment]
> > nk we should keep this open - IMO the overview tickets shouldn't be tied to a specific WP release, only the individual tickets within.
> 
> This was discussed in #526 and there are some significant downsides to this approach.

Love to feedback as to the downsides of this. 
One extra row in DB per URL ( we might able to reduce this by fetching all the possible caches for each part of the URL path and using the highest so if the URL uses the same set of options as the home page we don't create a cache for the URL)
We do an "in" SQL call veers a = 'yes"
and a little bit of extra logic on shutdown

**Comment by mukeshpanchal27** [comment]
Added new ticket https://core.trac.wordpress.org/ticket/59975 in list.

**Comment by joemcgill** [comment]
Added https://github.com/WordPress/performance/issues/889 as a related issue to the overview.

**Comment by mukeshpanchal27** [comment]
**Committed tickets**
https://core.trac.wordpress.org/ticket/39537
https://core.trac.wordpress.org/ticket/59975

**Marked as duplicate and closed**
https://core.trac.wordpress.org/ticket/56912

**Comment by mukeshpanchal27** [comment]
Committed last week. cc. @eclarke1

**Comment by felixarntz** [comment]
@eclarke1 @joemcgill @mukeshpanchal27 I believe other than documentation, e.g. dev note for 6.6, this is done now. We could leave it open in case any follow up work arises in the WordPress 6.6 cycle, but generally from an implementation perspective, it's good to close.

**Comment by joemcgill** [comment]
I've spun up a draft issue on our project board to track the dev note, which I'll replace with a link to the dev note tracker once the 6.6 release squad has one organized. Closing this now as complete.
