### ISSUE TITLE
Add `wp_cache_*_multiple` functions

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#77]
See https://core.trac.wordpress.org/ticket/54574

Alongside `wp_cache_get_multiple()`, add these helpers:

- `wp_cache_add_multiple()`
- `wp_cache_delete_multiple()`
- `wp_cache_update_multiple()`

**Comment by tillkruss** [comment]
PR opened: https://github.com/WordPress/wordpress-develop/pull/2018

**Comment by pbearne** [comment]
@Jonny Harris has this

**Comment by tillkruss** [comment]
I can't assign this to @spacedmonkey, unless he response here I believe.

**Comment by spacedmonkey** [comment]
I can't seem to assign myself on this one.

**Comment by spacedmonkey** [comment]
Related: https://github.com/WordPress/wordpress-develop/pull/2271
