### ISSUE TITLE
Increase PHPStan to rule level to 1 (and beyond)

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#775]
## Feature Description

https://github.com/WordPress/performance/pull/730 introduced PhpStan and started with level 0 conformance. Now we can increase the [rule level](https://phpstan.org/user-guide/rule-levels) to further improve the codebase.

Once this is resolved, another issue should be created to bump the rule level again.

- [x] https://github.com/WordPress/performance/pull/1188
- [x] https://github.com/WordPress/performance/pull/1195
- [x] https://github.com/WordPress/performance/pull/1198
- [x] https://github.com/WordPress/performance/pull/1199
- [x] https://github.com/WordPress/performance/pull/1200
- [x] https://github.com/WordPress/performance/pull/1201
- [x] https://github.com/WordPress/performance/pull/1202
- [x] https://github.com/WordPress/performance/pull/1203
- [x] #1205 
- [x] https://github.com/WordPress/performance/pull/1210
- [x] https://github.com/WordPress/performance/pull/1241
- [ ] https://github.com/WordPress/performance/pull/1211 (maybe not)
- [x] https://github.com/WordPress/performance/issues/1209

**Comment by ValeriiVasyliev** [comment]
On it

**Comment by westonruter** [comment]
Over halfway to level 6 now!

**Comment by westonruter** [comment]
I'm declaring this done! Level 8 seems to be sufficient. There is https://github.com/WordPress/performance/pull/1211 for updating to level 9, but as I mention in that PR, it seems of diminishing value.
