### ISSUE TITLE
Performance issue has_content method in WP_Widget_Media_Gallery

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#777]
Trac ticket: https://core.trac.wordpress.org/ticket/58757 any work on this ticket should be completed and documented in Trac please

**Comment by mukeshpanchal27** [comment]
We already have [PR 4819](https://github.com/WordPress/wordpress-develop/pull/4819) is ready for commit.

Assign to Jonny for commit.

**Comment by spacedmonkey** [comment]
Committed.
