### ISSUE TITLE
Remove cache time limitation in WP_Term_Query

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#78]
See https://core.trac.wordpress.org/ticket/54511

No need to limit the expiration to 24 hours.

Ping @spacedmonkey

**Comment by pbearne** [comment]
I have this one

**Comment by tillkruss** [comment]
See https://github.com/WordPress/wordpress-develop/pull/2162

**Comment by eclarke1** [comment]
@tillkruss @pbearne is it feasible to put this performance issue into 'Review' and add the 'Needs Review' label based on the status of WordPress/wordpress-develop#2162 just so the 2 are aligned? I'm happy to move this issue if you agree these steps are correct?

**Comment by pbearne** [comment]
I thick this can go into push to core

**Comment by tillkruss** [comment]
> @tillkruss @pbearne is it feasible to put this performance issue into 'Review' and add the 'Needs Review' label based on the status of [WordPress/wordpress-develop#2162](https://github.com/WordPress/wordpress-develop/pull/2162) just so the 2 are aligned? I'm happy to move this issue if you agree these steps are correct?

Let's do that 👍

**Comment by spacedmonkey** [comment]
Commited into core 
https://github.com/WordPress/wordpress-develop/commit/acfcea4cba52520b4b9f352dac83addca5aa1f1e
