### ISSUE TITLE
Skip adding `[Type] Task` PRs to changelogs

### ISSUE THREAD

**Issue by joemcgill** [WordPress/performance#782]
## Feature Description

The CI command that we use to generate changelogs for the plugin, i.e. `npm run changelog`, automatically adds an entry for any PR that was merged with the current milestone assigned. Because of this, we intentionally avoid adding milestones to certain task PRs, like prepping the branch for a release by adding the `no milestone` tag. However, it would be nice to be able to track these PRs as part of the milestone, and instead update the CLI script to skip over a PR if it is a `[Type] Task`.

**Comment by joemcgill** [comment]
@westonruter does #1224 already fix this issue?

**Comment by westonruter** [comment]
@joemcgill no, but this was fixed already in #1064 with the introduction of the `skip changelog` label.
