### ISSUE TITLE
Performance analysis using an old low-powered Android phone

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#785]

**Comment by westonruter** [comment]
Here's where I am with this: https://github.com/GoogleChromeLabs/wpp-research/pull/58

(Currently stuck)

**Comment by westonruter** [comment]
I was hoping to reuse `benchmark-web-vitals`, but worst case we can manually obtain the metrics via DevTools.

**Comment by westonruter** [comment]
I'm putting this on the back-burner because `benchmark-web-vitals` now supports CPU throttling as of https://github.com/GoogleChromeLabs/wpp-research/pull/59

**Comment by swissspidy** [comment]
This one doesn't seem actionable nor needed; closing for now.
