### ISSUE TITLE
AMP error due to invalid attribute `fetchpriority`

### ISSUE THREAD

**Issue by pereirinha** [WordPress/performance#792]
## Bug Description

The `fetchpriority`  feature is currently in [experimental](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/fetchPriority) mode, and it's currently not supported by [AMP](https://amp.dev/documentation/components/amp-img).

This will cause content pieces to be flagged with an error related to an invalid attribute, and there might be a conflict with the motto [Enhancement for most, regression for none](https://make.wordpress.org/performance/handbook/about-the-team/#enhancement-for-most-regression-for-none).

## Steps to reproduce

1. Ensure you have the Performal Lab and [AMP](https://wordpress.org/plugins/amp/) plugins installed and active;
1. Go to the AMP Settings page and make sure to use either Standard or Transitional template mode;
2. Visit a published post/page in the FE that has an image;
3. In the admin bar, client the menu AMP, and click `View AMP version`. If this menu option isn't available, it might be that you're already seeing the AMP version;
4. You should see a yellow icon next to the AMP word. Expand the menu and click `Validate URL`;
5. You should see a similar error as the attached screenshot;

## Screenshots

<img width="2033" alt="Screenshot 2023-07-28 at 10 41 36" src="https://github.com/WordPress/performance/assets/2189187/2fad7a0f-6465-4ccc-bb76-4f525a199ba3">

**Comment by swissspidy** [comment]
This should be reported at https://github.com/ampproject/amp-wp/

WordPress is adding fetchpriority correctly to `<img>` tags, but then the AMP plugin is turning those into `<amp-img>` and not removing the attribute.

FWIW you can use `add_filter( 'amp_native_img_used', '__return_true' );` to keep using the native `<img>` even when using AMP — it's totally supported and valid AMP.

**Comment by felixarntz** [comment]
Agreed, `fetchpriority` is in fact no longer experimental but part of the HTML standard. If `amp-img` does not support it, I think it needs to be resolved on that side.

Given that AMP is not associated with the WordPress core project and not a web standard either, I don't think it would be appropriate to fix this in the Performance Lab plugin.

**Comment by westonruter** [comment]
This first has to be allowed by the AMP validator before it is allowed by the AMP plugin. For that, please see https://github.com/ampproject/amphtml/issues/38715

**Comment by pereirinha** [comment]
Thanks all for taking the time to evaluate this one.
