### ISSUE TITLE
Image loading optimization improvements for 6.4

### ISSUE THREAD

**Issue by joemcgill** [WordPress/performance#793]
WordPress 6.3 included many improvements to the way resource loading is handled for images and iframes, by improving the heuristics for when to automatically add lazy-loading and adding support for setting `fetchpriortiy="high"` on the likely LCP image. See: https://make.wordpress.org/core/2023/07/13/image-performance-enhancements-in-wordpress-6-3/ for details.

This overview ticket is to further improve the functionality added in 6.3 for the 6.4 release.

## Related tickets

- [x] [Fetch priority and lazy loading attributes not applying correctly in block themes](https://core.trac.wordpress.org/ticket/58770)
- [x] [Fix shortcode output not receiving image (and other) optimizations](https://core.trac.wordpress.org/ticket/58853)
- [x] [Integrate `decoding="async"` logic into `wp_get_loading_optimization_attributes()`](https://core.trac.wordpress.org/ticket/58892)
- [x] [Introduce filter to modify/override attributes returned by `wp_get_loading_optimization_attributes()`](https://core.trac.wordpress.org/ticket/58893)
- [x] [Enhance `wp_get_loading_optimization_attributes()` to support arbitrary context values](https://core.trac.wordpress.org/ticket/58894)
- [x] [Twenty Twenty-Two: Header image missing dimension attributes](https://core.trac.wordpress.org/ticket/59256)
- [x] [Make it easier to override default loading optimizations](https://core.trac.wordpress.org/ticket/58895)

**Comment by mukeshpanchal27** [comment]
Added newly open ticket Core-59256 by @felixarntz  cc. @eclarke1

**Comment by eclarke1** [comment]
@joemcgill is this [Type] Overview issue a duplication of this one https://github.com/WordPress/performance/issues/766 ? If so, could we consolidate these perhaps?

**Comment by westonruter** [comment]
@eclarke1 I don't think so, as #766 is specifically about database autoloading, whereas this issue is about optimizing image loading.

**Comment by joemcgill** [comment]
@westonruter is correct. I've updated the title to be more clear.

**Comment by mukeshpanchal27** [comment]
Core-58894 get committed: https://core.trac.wordpress.org/changeset/56612
Core-59256 get committed: https://core.trac.wordpress.org/changeset/56613

Core-58895 is punt to `6.5` so i will remove it from the list.

**Comment by felixarntz** [comment]
@mukeshpanchal27 I don't think https://core.trac.wordpress.org/ticket/58895 should have been punted. I believe that happened without involving any of the contributors active on that ticket? cc @joemcgill who mentioned the other day (if I remember correctly) that either this won't actually require any work, or he may be able to get a PR ready very quickly. So I think this should come back to 6.4.

**Comment by joemcgill** [comment]
Thanks both, I've updated the description to note that we're still tracking that issue, but that it's currently punted. I'll take a look at it and see if it can be closed altogether, or if a quick PR can be created prior to beta1.

**Comment by mukeshpanchal27** [comment]
@joemcgill, could we consider closing this ticket, as all the tickets associated with this issue have been committed in version 6.4?

**Comment by joemcgill** [comment]
Thanks @mukeshpanchal27. Agreed that this looks to have all be completed.
