### ISSUE TITLE
There are a handful of typos in the plugin

### ISSUE THREAD

**Issue by szepeviktor** [WordPress/performance#798]
## Bug Description

There are misspellings.
Please see https://github.com/szepeviktor/typos-on-you/actions/runs/5817039716/job/15771074685#step:3:40
You can use `typos` to discover and fix them.

**Comment by mukeshpanchal27** [comment]
Thanks @szepeviktor for raising the issue. Nice catch.

@felixarntz @joemcgill Do we need to implement [spell checker GitHub action](https://github.com/crate-ci/typos) in this repo?

**Comment by szepeviktor** [comment]
> Do we need to implement

No 🙃
You need all (25) my CI jobs in these workflows: https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows

**Comment by joemcgill** [comment]
Thanks all. There are two things we should do as next steps here:

1. Open a PR to fix the typos that have been reported, being extra careful about handling changes to any public function or variable names that could cause a backwards compatibility break.
2. Open a PR to consider adding CI tooling to flag typos in PRs before they're merged. @mukeshpanchal27 the [GH action](https://github.com/crate-ci/typos) you proposed looks right to me. @szepeviktor I'm not sure that all of the CI jobs you have in your workflow are applicable to this project and/or are not already duplicative of the tools we're already using. If there are specific benefits to adding additional workflows that you linked to, could you propose them separately from this issue so we can consider the use cases?

**Comment by szepeviktor** [comment]
> If there are specific benefits to adding additional workflows that you linked to

That was a joke. I cannot expect other people to do byte-level care.
