### ISSUE TITLE
Add caching to comment feed in `WP_Query`

### ISSUE THREAD

**Issue by tillkruss** [WordPress/performance#80]
See https://core.trac.wordpress.org/ticket/36904

Ping @spacedmonkey

**Comment by tillkruss** [comment]
PR: https://github.com/WordPress/wordpress-develop/pull/2181

**Comment by tillkruss** [comment]
New PR: https://github.com/WordPress/wordpress-develop/pull/2194

**Comment by peterwilsoncc** [comment]
Merged in https://github.com/wordPress/wordpress-develop/commit/5ac4ec32085d09871ec253f78f4d40bfaaa71403 and https://github.com/wordPress/wordpress-develop/commit/d613ac555571e8d5fe3ba2ad93bc9447440d2de9
