### ISSUE TITLE
Prepare 2.6.0 Release

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#804]
This issue is to track preparation of the upcoming `2.6.0` release up until publishing, which is due **August 21, 2023**.

* [x] Create `release/2.6.0` branch closer to the release date
* [x] Finalize scope and punt unfinished pull requests to following release
* [x] Prepare the release (**Monday, August 21, 2023**)

**Comment by felixarntz** [comment]
Release branch created: https://github.com/WordPress/performance/tree/release/2.6.0

There's one PR that would be great to complete for this release in the milestone (#801) as it fits the scope of this release with the new Server-Timing admin screen. If we can merge that today, I think including it is reasonable.
