### ISSUE TITLE
Trac 18298: deprecate `TEMPLATEPATH` and `STYLESHEETPATH`

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#810]
The work scheduled here should please be completed via the following Trac ticket https://core.trac.wordpress.org/ticket/18298

**Comment by mukeshpanchal27** [comment]
Assign this to Felix also as he opened PR https://github.com/WordPress/wordpress-develop/pull/5160 that address the issue.

**Comment by felixarntz** [comment]
Committed in https://core.trac.wordpress.org/changeset/56635 🎉
