### ISSUE TITLE
Trac 55595: Consider only registering widgets on themes that supports widgets

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#811]
Any work against this ticket should please be actioned against https://core.trac.wordpress.org/ticket/55595

**Comment by mukeshpanchal27** [comment]
As per the update in https://core.trac.wordpress.org/ticket/55595#comment:13, we've closed this issue as `maybelater`. Therefore, I'll proceed to close this tracking issue as well. Thank you! cc. @eclarke1 @joemcgill
