### ISSUE TITLE
Experimenting with scheduler.yield

### ISSUE THREAD

**Issue by asafm7** [WordPress/performance#812]
## Feature Description

Is this something worth experimenting with?

https://developer.chrome.com/blog/introducing-scheduler-yield-origin-trial/

**Comment by westonruter** [comment]
Yes it is!

**Comment by asafm7** [comment]
@westonruter @mukeshpanchal27 

Maybe this can help with the new INP Core Web Vital?

https://nitropack.io/blog/post/introducing-scheduler-yield

**Comment by westonruter** [comment]
@asafm7 Yes, it's something that is marked as a TODO for implementing in the Interactivity API. Currently it is implementing `setTimeout()` but `scheduler.yield()` can be used once it is available: https://github.com/WordPress/gutenberg/pull/58227

**Comment by swissspidy** [comment]
I don't think anything else is needed here, closing.
