### ISSUE TITLE
Trac 22192: update_option() strict checks can cause false negatives

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#814]
https://core.trac.wordpress.org/ticket/22192

**Comment by mukeshpanchal27** [comment]
@eclarke1 assigning it to myself.

**Comment by mukeshpanchal27** [comment]
Raise PR https://github.com/WordPress/wordpress-develop/pull/5139 ready for review. cc. @joemcgill @felixarntz

**Comment by mukeshpanchal27** [comment]
Today, I am addressing the first round of feedback, and the PR is once again ready for review.

**Comment by mukeshpanchal27** [comment]
This was committed yesterday: r56681.

Someone comment about the BC that needs to check so i'm going to spend some time to check it. Thanks!

**Comment by felixarntz** [comment]
@mukeshpanchal27 Looking into the problem as well.

**Comment by mukeshpanchal27** [comment]
The latest follow-up pull request was committed at r56788. It has finally been closed, marking the resolution of an issue that had been open for 11 years. Congratulations to the team!
