### ISSUE TITLE
Trac 58682: wp_trim_excerpt parses and renders blocks twice

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#817]
Any work for this issue should be completed against https://core.trac.wordpress.org/ticket/58682

**Comment by kt-12** [comment]
@spacedmonkey  This is ready for review.

**Comment by spacedmonkey** [comment]
Committed https://github.com/WordPress/wordpress-develop/commit/15f5a952a1b804020d0e2677058f38450a874e53
