### ISSUE TITLE
Trac 58675: Theme: use the_header_image_tag in core themes

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#818]
Any work to be completed for this issue should be done against https://core.trac.wordpress.org/ticket/58675 please

**Comment by felixarntz** [comment]
@spacedmonkey You've removed yourself as the owner on the Trac ticket, but there's a PR from you. Does that mean you'd be happy for someone else to continue the work on that PR?

**Comment by spacedmonkey** [comment]
@felixarntz That is the idea. That is the same of all my tickets. I have handed them off to @kt-12 / @mukeshpanchal27 

That being said, I think that the PR is basically there, is just needs testing and merging.

**Comment by spacedmonkey** [comment]
Committed https://github.com/WordPress/wordpress-develop/commit/a5bcf199a768c8efd19fcd5fffc5f4f1b660c808
