### ISSUE TITLE
Update styfle/cancel-workflow-action version in GH workflows

### ISSUE THREAD

**Issue by joemcgill** [WordPress/performance#839]
## Bug Description

Many of our GH workflows use the https://github.com/styfle/cancel-workflow-action action as part of the workflow. During the 2.6.1 release, we notice that [this is causing a warning](https://github.com/WordPress/performance/actions/runs/6225072352), due to the version we use relying on node 12, which is deprecated.

## Steps to reproduce

1. See the warning here: https://github.com/WordPress/performance/actions/runs/6225072352

## Screenshots

<img width="918" alt="warning message" src="https://github.com/WordPress/performance/assets/801097/ffa6f65e-2fb2-4238-91b5-a69170684c7e">

## Additional Context

[Version 0.11.0](https://github.com/styfle/cancel-workflow-action/releases/tag/0.11.0) of the cancel workflow action updates the action to run on node 16, which should resolve the issue.

**Applies to:**
- [ ] `.github/workflows/js-lint.yml`
- [ ] `.github/workflows/php-lint.yml`
- [ ] `.github/workflows/php-test-standalone-plugins.yml`
- [ ] `.github/workflows/php-test.yml`

**Comment by mukeshpanchal27** [comment]
@joemcgill, this type of issue can be merged directly into the trunk without the need to add a milestone for this ticket. What are your thoughts on this, @felixarntz?

**Comment by felixarntz** [comment]
@mukeshpanchal27 Agreed, since it doesn't make a difference for the end user we don't have to use a concrete milestone.
