### ISSUE TITLE
Dev notes for WordPress 6.4

### ISSUE THREAD

**Issue by eclarke1** [WordPress/performance#840]
This ticket is used to capture the Trac tickets for WordPress 6.4 that require Dev Notes. [See the full list on Trac.](https://core.trac.wordpress.org/query?keywords=~needs-dev-note&focuses=~performance&milestone=6.4&order=priority)

### Individual ticket dev notes
- [x] [REST API index does not respect fields](https://core.trac.wordpress.org/ticket/18298) @spacedmonkey  <- Call out in field guide.
- [x] [Double sanitization in get_term function](https://core.trac.wordpress.org/ticket/58329)  @spacedmonkey  <- Call out in field guide.
- [x] [Remove usage of outputting styles tags](https://core.trac.wordpress.org/ticket/58775) (**[dev note](https://docs.google.com/document/d/1U3oupjW_UpZnBwut2Cyja6ElKHaiYzOEVc4Ynd0580c/edit)**)  @spacedmonkey 
- [x] [Theme: use the_header_image_tag in core themes](https://core.trac.wordpress.org/ticket/58675)  (does not require a dev note)

### Dev notes encompassing multiple tickets
- **[Object caching dev note](https://docs.google.com/document/d/1dtrWzGHlzpcfaQG4wSHYtHkkzAbUScQiXeL968UKBTc/edit)**
    - [x] [WP_Posts_List_Table causes post, postmeta, and term caches to be primed for all pages in the DB on load](https://core.trac.wordpress.org/ticket/59188) @spacedmonkey 
    - [x] [WP_Query->get_posts: cache updated also when query is set to be not cacheable](      https://core.trac.wordpress.org/ticket/58599) @spacedmonkey 
    - [x] [Force split queries in WP_Query in object caching is enabled](https://core.trac.wordpress.org/ticket/57296) @spacedmonkey 
    - [x] [Change the position of notoptions lookup in get_option](https://core.trac.wordpress.org/ticket/58277) @spacedmonkey 
    - [x] [Taxonomy: Make it possible to bypass automatic caching of results in `get_terms()`](          https://core.trac.wordpress.org/ticket/52710) @spacedmonkey 
    - [x] [rest_{$this->taxonomy}_query Cache Problem](https://core.trac.wordpress.org/ticket/58116) @spacedmonkey 
- **[Template dev note ](https://docs.google.com/document/d/1avt7Yh_PArpD2NcUVKYxd4yUkTwDCGNCVhp6LmR1VUM/edit)**
    - [ ] [Deprecate TEMPLATEPATH and STYLESHEETPATH](https://core.trac.wordpress.org/ticket/18298)
    - [x] [Performance issues in _register_theme_block_patterns](https://core.trac.wordpress.org/ticket/59490) @spacedmonkey 
    - [x] [locate_template does not check to see site has parent theme.](https://core.trac.wordpress.org/ticket/58576) @spacedmonkey 
    - [x] [Unnecessarily check to see site is using a child theme in the theme functions.](https://core.trac.wordpress.org/ticket/59279) @spacedmonkey 
    - [x] [Improve performance of get_block_theme_folders](https://core.trac.wordpress.org/ticket/58319) @spacedmonkey 
- **[Image optimization logic dev note](https://docs.google.com/document/d/1ZM-BhPC5XnUw_6yEG-sMY4_3FMawiWJE9AaCniz7V9g/edit)**
    - [x] https://core.trac.wordpress.org/ticket/58891 @felixarntz 
    - [x] https://core.trac.wordpress.org/ticket/58892 @felixarntz 
    - [x] https://core.trac.wordpress.org/ticket/58893 @felixarntz 
    - [x] https://core.trac.wordpress.org/ticket/58894 @felixarntz 
    - [x] https://core.trac.wordpress.org/ticket/58853 @felixarntz 
- **[Optimizing autoloaded options dev note](https://docs.google.com/document/d/18ADBnA115cjmFb60yyKAYWdYxSHojqbZF-vNUT1teV4/edit)**
    - [x] https://core.trac.wordpress.org/ticket/58962 @felixarntz 
    - [x] https://core.trac.wordpress.org/ticket/58964 @felixarntz 
    - [x] https://core.trac.wordpress.org/ticket/51352 @felixarntz 
- **[Script loading dev note](https://make.wordpress.org/core/?p=108934&preview=1&_ppp=f8ab32089f)**
   - [x] [Use defer loading strategy for block view scripts](https://core.trac.wordpress.org/ticket/59115)  @westonruter 
   - [x] [Delay loading comment-reply script with async loading strategy](https://core.trac.wordpress.org/ticket/58870)  @westonruter 
   - [x] [Incorporate script loading strategies in bundled themes](https://core.trac.wordpress.org/ticket/59316)  @westonruter 
   - [x] [Eliminate manual construction of script tags](https://core.trac.wordpress.org/ticket/58664)  @westonruter

**Comment by felixarntz** [comment]
I have updated the issue description with a few more Trac tickets after adding `needs-dev-note` to them, including grouping relevant tickets that should get one dev note together. I also added a Trac query link.

I am happy to pick up writing the two group dev notes, since I was heavily involved in both of these efforts.

cc @eclarke1 @joemcgill @spacedmonkey @mukeshpanchal27

**Comment by eclarke1** [comment]
@spacedmonkey are you ok to pick up the dev notes for:
https://core.trac.wordpress.org/ticket/52710
https://core.trac.wordpress.org/ticket/57296
https://core.trac.wordpress.org/ticket/57902

Then we just need to understand the right person to do the dev note for https://core.trac.wordpress.org/ticket/18298 - any suggestions on this one @felixarntz ?

**Comment by felixarntz** [comment]
@eclarke1 I'm not sure 18298 needs a full dev note. There's also the Field Guide post, which is suitable for shorter notes and explanations on notable changes that can be quickly explained in 1-2 sentences or at most a full paragraph.

Maybe we should change the ticket to use `add-to-field-guide` instead of `needs-dev-note`?

**Comment by felixarntz** [comment]
@spacedmonkey Could you update the issue description with the other 6.4 performance dev notes when you get a chance?

**Comment by spacedmonkey** [comment]
@eclarke1 @felixarntz @joemcgill I have updated the description with a list ticket and dev notes I think should be written. 

Let me know if you agree and assign yourself to anything on the list that you feel you want to write about.

**Comment by felixarntz** [comment]
Thanks @spacedmonkey! Added myself to the image and optimized autoloaded options dev notes.

**Comment by spacedmonkey** [comment]
I made start on the object caching dev notes, if anyone wants to review. 

https://docs.google.com/document/d/1dtrWzGHlzpcfaQG4wSHYtHkkzAbUScQiXeL968UKBTc/edit?usp=sharing

**Comment by spacedmonkey** [comment]
> [Remove usage of outputting styles tags](https://core.trac.wordpress.org/ticket/58775) @spacedmonkey

Dev note ready for review. 
https://docs.google.com/document/d/1U3oupjW_UpZnBwut2Cyja6ElKHaiYzOEVc4Ynd0580c/edit?usp=sharing

**Comment by spacedmonkey** [comment]
>[Performance issues in _register_theme_block_patterns](https://core.trac.wordpress.org/ticket/59490) @spacedmonkey
 [locate_template does not check to see site has parent theme.](https://core.trac.wordpress.org/ticket/58576) @spacedmonkey
 [Unnecessarily check to see site is using a child theme in the theme functions.](https://core.trac.wordpress.org/ticket/59279) @spacedmonkey
 [Improve performance of get_block_theme_folders](https://core.trac.wordpress.org/ticket/58319) @spacedmonkey 

Dev note ready for review.
https://docs.google.com/document/d/1avt7Yh_PArpD2NcUVKYxd4yUkTwDCGNCVhp6LmR1VUM/edit?usp=sharing

**Comment by westonruter** [comment]
> Script loading dev note
> * [ ]  [Use defer loading strategy for block view scripts](https://core.trac.wordpress.org/ticket/59115)  @westonruter
> * [ ]  [Delay loading comment-reply script with async loading strategy](https://core.trac.wordpress.org/ticket/58870)  @westonruter
> * [ ]  [Incorporate script loading strategies in bundled themes](https://core.trac.wordpress.org/ticket/59316)  @westonruter
> * [ ]  [Eliminate manual construction of script tags](https://core.trac.wordpress.org/ticket/58664)  @westonruter

I haven't written the Dev Note yet, but it's on the top of my list for Monday (October 16).

**Comment by westonruter** [comment]
> Script loading dev note
> * [ ]  [Use defer loading strategy for block view scripts](https://core.trac.wordpress.org/ticket/59115)  @westonruter
> * [ ]  [Delay loading comment-reply script with async loading strategy](https://core.trac.wordpress.org/ticket/58870)  @westonruter
> * [ ]  [Incorporate script loading strategies in bundled themes](https://core.trac.wordpress.org/ticket/59316)  @westonruter
> * [ ]  [Eliminate manual construction of script tags](https://core.trac.wordpress.org/ticket/58664)  @westonruter

Ready for review: ~https://docs.google.com/document/d/1mOzcwLbCaQNbWOMGFj4H4MJPtIMz7Fs90uBwOQZbDS8/edit?usp=sharing~

Public preview link: https://make.wordpress.org/core/?p=108934&preview=1&_ppp=f8ab32089f

**Comment by felixarntz** [comment]
I have completed drafts for the following dev notes:
* [Image optimization logic dev note](https://docs.google.com/document/d/1ZM-BhPC5XnUw_6yEG-sMY4_3FMawiWJE9AaCniz7V9g/edit)
* [Optimizing autoloaded options dev note](https://docs.google.com/document/d/18ADBnA115cjmFb60yyKAYWdYxSHojqbZF-vNUT1teV4/edit)

I have also updated the issue description with the latest replies above, including links to the relevant dev note drafts.

@spacedmonkey I have also reviewed your dev notes for Object caching, and for Replacing hard coded style tags, those look good to me.

@westonruter Leaving feedback on your draft here since WP doesn't have inline commenting :)
* I would drop the "Summary:" from the very beginning. IMO unnecessary.
* Maybe add a paragraph / blank line after the first sentence?
* You link to the original script loading strategy dev note at the end, which is good, though I think it would be great to also include it inline somewhere earlier in the article (e.g. where you link to #12009, which is helpful but not _as_ helpful, so I would somehow link to both the ticket and dev note there).

Otherwise looks great!

**Comment by westonruter** [comment]
@felixarntz Thanks! I actioned the first and third points. For the second point, the paragraph is intended to be a summary of the entire post, so I want to keep it concise in a single paragraph. I added a "The full details follow" text to the end of the paragraph to make that clear.

**Comment by eclarke1** [comment]
This is now complete, closing this issue out unless anyone has any other concerns?
