### ISSUE TITLE
Remove Fetchpriority module and plugin

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#853]
See https://github.com/WordPress/performance/pull/851#discussion_r1352417111 and #606: Now that Performance Lab requires WordPress 6.3+, the Fetchpriority module is completely pointless. The plugin doesn't require any more updates either, so we should completely remove it from PL.

The PR for this should also bump the patch version of WebP Uploads, given the latest changes.

**Comment by mukeshpanchal27** [comment]
@felixarntz The PR https://github.com/WordPress/performance/pull/855 bump the WebP Module version.

**Comment by westonruter** [comment]
I've also closed the plugin on WordPress.org since it won't be getting updates and has only 40+ active installs.
