### ISSUE TITLE
Update Node / NPM versions for development following WP core change

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#861]
In WordPress 6.5, there is an upcoming update for the Node version. Please refer: https://core.trac.wordpress.org/ticket/59663.

As a result, we should also align our Performance Lab plugin with this update and recommend Node and NPM versions of 18.x and 9.x, respectively.

**Comment by thelovekesh** [comment]
@mukeshpanchal27 Since NodeJS has been bumped to v20, I think this issue can be closed.
see: https://github.com/WordPress/performance/pull/916

**Comment by mukeshpanchal27** [comment]
In #916 we updated node to v20.
