### ISSUE TITLE
Ai module requires (confirm) to actually 'post' the prompt

### ISSUE THREAD

**Issue by wezlol** [WordPress/performance#873]
## Bug Description

When using the /ai tool you have to confirm the ai prompt otherwise you publish an empty page with just the title.

Upside: you can still edit & confirm

## Steps to reproduce

1. Go to new post
3. Click on /ai + 'prompt'
4. Press publish
5. See post without ai prompt

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

**Comment by westonruter** [comment]
I think you submitted this issue to the wrong repo. There is no AI module in the Performance Lab plugin.

**Comment by mukeshpanchal27** [comment]
I concur with @westonruter that we don't have AI modules. @wezlol, I'm going to close this issue as it appears you may have opened it in the wrong repository. Please feel free to reopen this issue if you believe there was an issue with this repo.
