### ISSUE TITLE
Enhance experience when installing _and_ activating a standalone plugin

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#880]
This is an enhancement for the experience of installing a standalone plugin via _Settings > Performance_ and then immediately activating it, i.e. without refreshing the current screen. See https://github.com/WordPress/performance/pull/864#pullrequestreview-1690280731:

> When installing one of the plugins and then activating (without reloading the page), it will end up on the regular Plugins screen rather than redirecting back to the Performance Lab screen. This is happening because the WordPress updates JS code doesn't set the Performance Lab specific activation URL on the button, but the regular WordPress one. This is not a dealbreaker, but if we can fix it somehow that would be great (e.g. is there some event listener we could use in JS to replace the URL with our own?).

This is not a major problem, and if we cannot resolve it without rewriting/copying a lot of WordPress core's `update.js` logic, we should probably not go above and beyond to fix it. But if there's a reasonable path to implement it (e.g. maybe an event listener where we dynamically replace the activation `href` attribute to use the `perflab_activate_plugin` action), it's worth improving the user experience.

**Comment by felixarntz** [comment]
Note that this is currently only relevant for the `feature/creating-standalone-plugins` branch. It is however okay to not couple it to the overall effort tracked by #656, as it could also be fixed later.

cc @10upsimon

**Comment by mukeshpanchal27** [comment]
Fixed by #900 (in `feature/creating-standalone-plugins` branch).
