### ISSUE TITLE
Add settings and UI to control Speculation Rules prerender vs prefetch and eagerness

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#906]
See #897:
* UI controls should be provided in WP Admin to change the behavior to prefetch URLs instead of prerendering, and another one to change the behavior from prefetching/prerendering on hover to only do it on click.
    * Both alternatives are less beneficial from a performance perspective, but potentially preferable for other reasons: For example, prerendering can be problematic with dynamic content, and relying on hover can result in wastefully loaded pages, if the user doesn't actually end up navigating there.
    * As this is a Performance Lab module, it makes sense with the more performant setting by default. For a potential future WordPress core proposal, the default would have to be determined based on user feedback, and UI controls would most likely not be part of the WordPress core implementation. For early feedback, they are crucial though to make it easy to experiment with different configurations.

**Comment by westonruter** [comment]
Done in https://github.com/WordPress/performance/pull/939
