### ISSUE TITLE
Deleting the image (webp) doesn't delete corresponding JPG

### ISSUE THREAD

**Issue by ajaydsouza** [WordPress/performance#918]
## Bug Description

WebP Uploads is enabled in the Settings > Performance page. When you upload a JPG, a WebP of the same name is created. However, deleting the WebP doesn't delete the JPG. If you upload a JPG of the same name again, a duplicate JPG is created (-2.jpg) and a WebP with the same name is created.

## Steps to reproduce

1. Goto Settings > Performance and turn on WebP Uploads
2. Goto Media Library and upload a JPG file e.g. apple.jpg. Corresponding WebP is created called apple-jpg.webp
3. "Bin" the file
4. Upload the same JPG again i.e. apple.jpg. The WebP file now created is called apple-2-jpg.webp

## Additional Context

 - PHP Version: 8.3
 - OS: [e.g. iOS]: Linux server / MacOS
 - Browser: Firefox
 - Plugin Version: 2.7.0
 - Device: Macbook Air M2

**Comment by mukeshpanchal27** [comment]
Thanks, @ajaydsouza, for raising the issue.

I'm unable to replicate the same problem when I delete the updated image in the media. Could you kindly provide the precise steps you take to delete the image, along with a screenshot of the directory? This will help us investigate further. Thank you!

**Comment by ajaydsouza** [comment]
@mukeshpanchal27 

Just retested this as I had the plugin disabled and it seems to me I have a bigger issue on my site as the media library deletes the image from WP but not WordPress.

I'm going to close this issue as I think it's my install related rather than the plugin.

**Comment by ajaydsouza** [comment]
To confirm - this was an issue with the server. I used WordOps to create the site and it automatically enables the Media Trash feature.

Apologies for the confusion - didn't expect this at all!

**Comment by mukeshpanchal27** [comment]
Great it sorted now.
