### ISSUE TITLE
Plugin Check: Report `WordPress.DB.DirectDatabaseQuery.DirectQuery` warning for Autoloaded Options Health Check

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/performance#919]
## Bug Description

The [Plugin Check](https://github.com/WordPress/plugin-check) tool now shows warning for use of direct database call in Autoloaded Options Health Check.

## Steps to reproduce

1. Install Plugin Checker tool from https://github.com/WordPress/plugin-check repo
2. Go to `Tools > Plugin Check`
3. Select `Performance Lab` in Check the Plugin and click on `Check it!` button

## Screenshots

<img width="1555" alt="Screenshot 2024-01-04 at 1 58 38 PM" src="https://github.com/WordPress/performance/assets/10103365/3c2d85cd-44d2-468f-bf42-9b9705169653">

**Comment by Ellusu** [comment]
I'll handle that!

**Comment by mukeshpanchal27** [comment]
Thanks @Ellusu Let me know if you need any support.

**Comment by Ellusu** [comment]
i have created this: https://github.com/WordPress/performance/pull/1179
