### ISSUE TITLE
Weird user experience with module to plugin migration where filesystem changes are disabled

### ISSUE THREAD

**Issue by felixarntz** [WordPress/performance#943]
When testing the new module to standalone plugin migration in the 2.8.0 release on a site where any filesystem changes (most importantly for this, installing plugins) are disabled, a weird user experience can be observed.

To test, use a site where you set the `DISALLOW_FILE_MODS` constant to `true`.

First of all, the good thing is all permissions are respected, which is the most critical bit. There aren't any security flaws in the implementation as far as I can tell. 👍 

However, here's what happens on such a site:
* The admin pointer isn't shown. (This may be expected because installing plugins isn't possible anyway.)
* The admin notice however is shown. But when clicking the CTA button to migrate, it (rightfully) fails with an error regarding the missing capabilities.

I would suggest the following to improve this strange experience:
* In case the user is missing one of the `install_plugins` or `activate_plugins` capabilities, don't show the CTA button.
* Instead, adjust the text slightly to keep it purely informative. For example, the last line could be simply changed from:
> Please click the following button to install and activate the relevant plugin/s in favor of the modules. This will not impact any of the underlying functionality.

to

> Please install and activate the relevant plugin/s in favor of the modules. This will not impact any of the underlying functionality.

I think that would be good enough for a solution.

We could be more granular and still allow migration if all plugins are already installed, but I think that would be too much effort for a problem that only affects a very small niche of sites (if the plugins are already installed, the user is probably already aware and will manually migrate anyway). So I don't think we should do that.

**Comment by felixarntz** [comment]
Open question: Should we also still show the admin pointer in that case to still put awareness to the problem? In other words, show the admin pointer to any user that can access the screen (i.e. `manage_options`), regardless of the more specific capabilities needed.

I don't feel strongly about it, but if we show the notice for informational purposes, it may make sense to also show the pointer.

cc @westonruter @mukeshpanchal27 @joemcgill

**Comment by westonruter** [comment]
Yes, the admin pointer should still be shown. For example, consider the case on Pantheon where the dev environment is writable but the live (production) environment is not. If plugin updates were done automatically on dev and pushed out to live, then when a user logs in to the admin on the live environment it is critical that they still see the pointer: they'll need to manually log-in to the dev environment to do the migration since it can't be done on live.

**Comment by joemcgill** [comment]
I agree with Weston. For any of these screens we need to ensure that the migration/upgrade notices are still visible to admins even when the file system is not writeable so they can take action another way. Disabling or removing buttons that will trigger actions known to fail should be the main goal here.

**Comment by felixarntz** [comment]
SG. In other words, a PR for this should (when the user can access the screen but lacks install or activation capabilities):
* Remove the CTA button and adjust the wording in the admin notice accordingly.
* Fix the admin pointer so that it shows up for those users too.
