### ISSUE TITLE
Auto sizes causes images in galleries to display skewed

### ISSUE THREAD

**Issue by joemcgill** [WordPress/performance#947]
## Bug Description

While testing the auto-sizes plugin (#904), I discovered that images in WP core galleries set to "crop" get skewed when using auto sizes. After initial investigation, this seems to be related to the fact that the gallery block sets the images to `object-fit: cover` via CSS. I'm not sure if this is a known limitation of auto sizes, or a bug with the initial implementation in Chrome, but it would need to be resolved prior to being added to WP Core.

I've created a reduced test case for demonstration at https://codepen.io/joemcgill-the-sasster/full/ZEPemOM. To see the issue will need to use a web browser that has support for auto sizes (e.g., Chrome beta as of today).

## Steps to reproduce

1. Activate the auto-sizes plugin or module on a site
2. Create a new post with a gallery block set to crop images that includes at least 4 images
3. View the gallery on the front end to see that any lazy loaded images include "auto" in the `sizes` attribute
4. Compare the gallery in a browser that supports auto-sizes with a browser without support to see the issue

## Screenshots

**Chrome 120**
<img width="629" alt="image" src="https://github.com/WordPress/performance/assets/801097/1f62c723-7612-4a28-82f3-d03dd8170cac">

**Chrome 121**
<img width="628" alt="image" src="https://github.com/WordPress/performance/assets/801097/c0ae14af-89fb-41d9-a8a0-33d2b390084b">

## Additional Context

 
 - OS: MacOS
 - Browser: Chrome 121
 - Plugin Version: 1.0.0

**Comment by joemcgill** [comment]
Filed an HTML issue at https://github.com/whatwg/html/issues/10079 to see if this is indeed a bug, or a known limitation of the current spec.

**Comment by joemcgill** [comment]
This seems to be related to a [Chromium bug](https://chromium-review.googlesource.com/c/chromium/src/+/5241231) that has resulted in AutoSizeLazyLoadedImages being switched back to experimental mode. The issue is that the default UA stylesheet is being applied to any image that includes `sizes="auto"`, which sets `contain-intrinsic-size` to 300px by 150px due to [this rule](https://html.spec.whatwg.org/#img-contain-size).

Adding this style via CSS seems to fix the issue:

```CSS
img:is([sizes="auto" i], [sizes^="auto," i]) {
    contain-intrinsic-size: auto none;
}
```

**Comment by fvwanja** [comment]
@joemcgill that does make it better but it does not fix the problem:

![Screenshot 2024-01-31 at 16 34 35](https://github.com/WordPress/performance/assets/90781427/9d9e10d9-77c3-4002-9924-d9c3278aea53)

(image from https://unsplash.com/de/fotos/frau-im-weissen-rundhalshemd-lachelnd-IF9TK5Uy-KI)

```html
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      img:is([sizes="auto" i], [sizes^="auto," i]) {
        contain-intrinsic-size: auto none;
      }

      .box {
        position: relative;
        width: 300px;
        height: 300px;
      }

      .box img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
    </style>
  </head>
  <body>
    <div class="box">
      <img src="image.jpg" sizes="auto">
    </div>
  </body>
</html>
```

**Comment by jclarkdev** [comment]
This can be addressed by either:
- Removing sizes="auto" altogether
- Explicitly defining the sizes instead of relying on the "auto" value
-- For example: `sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw"`

The second option obviously being the preferred one

**Comment by joemcgill** [comment]
@fvwanja and @jclarkdev, thanks for the feedback.

@jclarkdev just so it's clear, the purpose of this feature is to implement `sizes="auto"` in WordPress, we've not shipped it yet, we're just experimenting with the intent to add it once we've worked through these types of issues.

**Comment by jclarkdev** [comment]
@joemcgill Apologies, as I had not dove into the full scope and context of this ticket, I had quickly stumbled upon it while trying address that mentioned Chromium bug in my own development efforts!

**Comment by joemcgill** [comment]
@jclarkdev no worries, I assumed as much and appreciate you trying to help us out!

**Comment by fvwanja** [comment]
The problem no longer occurs in Chrome 122.0.6261.57

**Comment by joemcgill** [comment]
Auto-sizes has landed in Chromium in https://issues.chromium.org/issues/40862170. After testing in Chrome Canary, it seems like this issue has been fixed.
