### ISSUE TITLE
Speculation rules: URL patterns need escaping to work correctly when special characters are present

### ISSUE THREAD

**Issue by jeremyroman** [WordPress/performance#950]
## Bug Description

If WordPress is deployed with an unusual path prefix (notably WordPress Playground uses something like /scope:0.123456/), this isn't properly escaped and the resulting patterns fail to parse.

## Steps to reproduce

1. Go to https://playground.wordpress.net/?plugin=speculation-rules.
2. Open one of the pages at the top level.
3. Observe that there are errors in the developer console resulting pages.

## Screenshots

n/a

## Additional Context

 - PHP Version: 7.4
 - OS: Linux
 - Browser: Chrome (121 beta)
 - Plugin Version: trunk
 - Device: Linux desktop

**Comment by jeremyroman** [comment]
This probably needs the following labels, though I don't think I have permission to apply them:
* [Focus] JS & CSS
* [Module] Speculation Rules
* Performance Lab Plugin

**Comment by westonruter** [comment]
Done in https://github.com/WordPress/performance/pull/951
