### ISSUE TITLE
Server-Timing: Slashes in metric name not working

### ISSUE THREAD

**Issue by asafm7** [WordPress/performance#955]
Hello.

Currently, when using a hook name such as `render_block_core/site-logo` only callbacks attached to the `render_block_core` are measured.

**Comment by swissspidy** [comment]
Can you perhaps share the code you're using and the exact problem you're facing?

`render_block` and `render_block_$name` are two entirely different hooks, so you would need to hook into both if you want to measure callbacks attached to both.

**Comment by asafm7** [comment]
Thanks for your reply, @swissspidy.

I'm not using code, but the UI under Tools -> Server-Timing.

I added only `render_block_core/site-logo` to the list of filters.

Only `render_block_core` showed up on the browser's Timing tab.

I hope it is clearer. Please let me know if you need more information.

**Comment by swissspidy** [comment]
Ah, got it! 💡 

Unfortunately I cannot reproduce this right now.

I added `render_block_core/image` to the list of filters, turned on output buffering, and got the following headers as expected:

```
Server-Timing:
wp-load-alloptions-query;dur=0.98, wp-before-template;dur=42.98, wp-template;dur=36.83, wp-filter-render_block_core/image;dur=0.02, wp-total;dur=79.83
```

Of course that requires an image block being present in the content.

**Comment by asafm7** [comment]
@swissspidy that's intresting.

While I can see the header as you can, in the "Timing" tab, it only shows `wp-filter-render-block-core`, without any measurement data:
![image](https://github.com/WordPress/performance/assets/14274769/c35e71b3-471c-4a17-8c4b-024f69efaf1b)

(the name is truncated with ..., but when hovering you can see `wp-filter-render-block-core`).

The Timing tab feels more convenient for viewing this data, so if it can be utilized it cloud be nice.

**Comment by swissspidy** [comment]
I see! Well, it seems like browsers don't like slashes in the `Server-Timing` header, even though [it doesn't appear to be disallowed in the spec](https://www.w3.org/TR/server-timing/#the-server-timing-header-field).

(EDIT: it is disallowed, see https://httpwg.org/specs/rfc7230.html#rfc.section.3.2.6)

I just tried a header like this: `Server-Timing: foo;dur=2.25, foo/bar;dur=1.2, foo/baz;dur=3.3, bar;dur=4.5`. This is the result:

Chrome:

<img width="581" alt="Screenshot 2024-01-29 at 16 41 28" src="https://github.com/WordPress/performance/assets/841956/1e3e74e6-11ce-41b9-8ced-694d6cfe5f11">

Firefox:

<img width="786" alt="Screenshot 2024-01-29 at 16 41 45" src="https://github.com/WordPress/performance/assets/841956/3a399210-4a50-4cef-b51d-22eca2caedf0">

Safari:

<img width="594" alt="Screenshot 2024-01-29 at 16 42 05" src="https://github.com/WordPress/performance/assets/841956/7e01e499-6fd7-4b50-bdf1-05f2901aa5d7">

The easiest solution here is for us to simply replace slashes with dashes, so `wp-filter-render_block_core/image` would simply become `wp-filter-render_block_core-image`.

We can do this either in `\Perflab_Server_Timing::register_metric()` or in `\Perflab_Server_Timing::format_metric_header_value()`. I think the former should be fine.

**Comment by asafm7** [comment]
Thanks, @swissspidy for looking into it, and for the explanation.

Looking forward to a fix :)
