### ISSUE TITLE
Add a performance tab under Site Health

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#97]
Each module or specific modules from the performance plugin can take advantage of the site Helth from WordPress to indicate whether a module was not installed due to specific dependency does not exist and is recommended to enable at the server level, the site health can be used as well in order to provide a piece of more detail information or run reports for specific metrics.

![2021-12-22_15-35](https://user-images.githubusercontent.com/3921289/147157996-dae1fbc5-523f-4983-8a7b-0e9296e52448.png)

### Comments

We could use the new `site_health_navigation_tabs` filter added in 5.8:

https://make.wordpress.org/core/2021/06/22/extending-the-site-health-interface-in-wordpress-5-8/

_Originally posted by @tillkruss in https://github.com/WordPress/performance/discussions/84#discussioncomment-1941511_

### Links

- #66 
-  #84

**Comment by spacedmonkey** [comment]
Related https://github.com/WordPress/performance/issues/92 ?

**Comment by mitogh** [comment]
Looks like this one is mostly an `Infrastructure` type of ticket to setup the section inside of Site Health and 

- #92 

Is mostly about adding a new section inside of the performance section @spacedmonkey 

cc @eclarke1

**Comment by JustinyAhin** [comment]
@mitogh I'm definitely interested in working on this.

I think it would make sense to start with a basic set of things to include in the tab. I can see some things mentioned here https://github.com/WordPress/performance/issues/63 included.

Like: 

- Number and size of enqueued styles
- Number and size of enqueued scripts.

to start with.

**Comment by JustinyAhin** [comment]
Also, @mitogh to be sure, do we want to extend the current "Info" tab, with the performance metrics, or add a brand-new tab like on this picture https://make.wordpress.org/core/files/2021/06/4-menu-items.png.

**Comment by eclarke1** [comment]
Are you happy to have this issue assigned to yourself @JustinyAhin and once work commences, please move over to 'In Progress'? We will keep the 'Needs Discussion' label on this issue until an approach has been agreed together. :)

**Comment by mitogh** [comment]
I would say a tab for performance as we are going to have specific metrics let's say for first paint cache and such so this makes more sense https://make.wordpress.org/core/files/2021/06/4-menu-items.png @JustinyAhin

**Comment by felixarntz** [comment]
Hmm, personally I'm questioning whether a "Performance" tab makes sense in Site Health. There's currently a clear differentiation between "Status" and "Info", but what would be the criteria for what goes under "Performance"? Several of the existing checks under "Status" are performance-related, at least in parts.

Basically the "Status" tab is for administrators to do a status check on how things are going on their site. And if their site performance is terrible, shouldn't they be informed about that there as well? IMO moving performance-related checks into its own tab will make it less prominent and also a bit confusing for where to look. Also, does that mean we later also will get a "Security" tab or an "Accessibility" tab?

While I can see how it can feel nice to have a performance-focused tab there, I'm not sure this makes sense for end users. IMO the only thing that would make sense under a separate "Performance" tab would be general performance metrics, i.e. if we eventually were able to provide lab metrics and potentially field metrics on e.g. CWV for WordPress sites. But in terms of performance problems, I prefer having them as regular status checks.

**Comment by mukeshpanchal27** [comment]
> Basically the "Status" tab is for administrators to do a status check on how things are going on their site. And if their site performance is terrible, shouldn't they be informed about that there as well? IMO moving performance-related checks into its own tab will make it less prominent and also a bit confusing for where to look. Also, does that mean we later also will get a "Security" tab or an "Accessibility" tab?

Valid point. If we add a new tab for "Performance" then other folks propose adding a new tab for other modules so it's good to add all information under current tabs.

**Comment by felixarntz** [comment]
Closing this due to a lack of activity here, plus it looks like there's no path forward.

The "Status" tab already uses labels for different focuses, one of which is "Performance". Additionally, if we were to reorganize Site Health (e.g. so that these focuses are individual tabs), it should rather be a Core Trac ticket, as it would go beyond the scope of the Performance Lab plugin.
