### ISSUE TITLE
API for Resource hints

### ISSUE THREAD

**Issue by mitogh** [WordPress/performance#99]
Having an API that can be used for Theme Developers to easily incorporate resource hints would be fantastic. This would help to provide control in the theme side of things to indicate the right order for specific resources like fonts, featured images, or other critical resources that can be used to download resources or give a better idea to the browser of the "correct" order for downloading specific resources.

The API should support the following type of hints:

- ` dns-prefetch`
- `preconnect`
- `prefetch`
- `prerender`

The API could look something like: 

```php
function dns_prefetch( $domain ) {
    // hook into wp_head to output the link.
}
```

We can can output the values from those hints via an HTTP Header `Link`  or via a `link` tag

### Links:

Quote from the [Performance Mozilla docs.](https://developer.mozilla.org/en-US/docs/Web/Performance)

> Browsers often know better than we do when it comes to resource prioritization and delivery however they're far from clairyovant. Native browser features enable us to hint to the browser when it should connect to another server, or preload a resource before the browser knows it ever needs it. When used judiciously, this can make fast experience seem even faster. In this article, we cover native browser features like rel=preconnect, rel=dns-prefetch, rel=prefetch, and rel=preload, and how to use them to your advantage.

- https://www.w3.org/TR/resource-hints/#resource-hints
- https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preconnect
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/prerender
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/prefetch
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ

**Comment by swissspidy** [comment]
WordPress has had an API for this since version 4.6

https://make.wordpress.org/core/2016/07/06/resource-hints-in-4-6/

Next up is preload, see #31

**Comment by mitogh** [comment]
Oh! I wasn't aware that one looks like that one would do it, I guess we can work on improving the docs for the function with some examples for fonts and images.

Closing this ticket then as there's no real point in having it open if this one already exists in core.

**Comment by westonruter** [comment]
Fonts and images I believe are only relevant in the context of `preload`. As such they'd be part of #31.
