### ISSUE TITLE
Fallback script obsolete - remove it

### ISSUE THREAD

**Issue by westonruter** [WordPress/performance#996]
See discussion below where we decided we should drop the fallback script, especially since the plugin now supports the `<picture>` element which provides smoother fallback experience, and because WebP is so widely supported.

<details><summary>Old description for "Script handling in WebP Uploads can be improved"</summary>

Currently an inline script is printed to the page which conditionally loads a `fallback.js` script:

https://github.com/WordPress/performance/blob/11be3253d7c40baa2a08b32eb93520b93c22665f/modules/images/webp-uploads/hooks.php#L699-L705

Note how it adds a `data-rest-api` data attribute here. This is then read in `fallback.js` via:

https://github.com/WordPress/performance/blob/11be3253d7c40baa2a08b32eb93520b93c22665f/modules/images/webp-uploads/fallback.js#L91-L93

This value is then used to construct the `script` URL to load:

https://github.com/WordPress/performance/blob/11be3253d7c40baa2a08b32eb93520b93c22665f/modules/images/webp-uploads/fallback.js#L129-L137

A couple things here:

1. Wouldn't it be better to rely on `fetch()` than to use JSONP?
2. Instead of exporting the URL in an HTML attribute, why not expose it via a global variable in the same inline script that is being printed to begin with?
3. The query args for `restPath` would be better constructed with `URLSearchParams`, or if IE11 compat is really desired, fall back to using `document.createElement('a').href`.

Also, in that inline script it would be slightly safer if this line used `wp_json_encode()`:

https://github.com/WordPress/performance/blob/11be3253d7c40baa2a08b32eb93520b93c22665f/modules/images/webp-uploads/hooks.php#L683

Like:

```js
s.src = <?php echo wp_json_encode( esc_url_raw( plugins_url( '/fallback.js', __FILE__ ) ) ); ?>; 
```

Lastly, instead of relying on data attributes on the script tag, the necessary data may make more sense to export into JS via `wp_add_inline_script_tag()` or else a JSON `script`. The reason is that the `script` tag for JS may end up getting concatenated with other scripts, resulting in those attributes getting lost.

</details>

**Comment by adamsilverstein** [comment]
I wonder if we should consider adding `picture` element support to replace this approach? Support is [solid](https://caniuse.com/picture) and using `picture` would provide a superior user experience across the board. Since we have the `sources` data, outputting a picture element should be straightforward. See https://github.com/WordPress/performance/issues/21 for previous discussion.

**Comment by westonruter** [comment]
I just checked and Gutenberg is [explicitly selecting](https://github.com/WordPress/gutenberg/blob/8dc36f6d30cc163671bdaa33f0656fdfe91f1447/packages/block-library/src/image/style.scss#L1-L7) the `img` tag in the Image block:

```scss
.wp-block-image {
	img {
		height: auto;
		max-width: 100%;
		vertical-align: bottom;
		box-sizing: border-box;
	}
```

This is done commonly in Gutenberg:
https://github.com/search?q=repo%3AWordPress%2Fgutenberg+%2Fimg+%7B%2F+language%3ASCSS&type=code
https://github.com/search?q=repo%3AWordPress%2Fgutenberg+%2Fimg%2C%2F+language%3ASCSS&type=code

This is also super common in themes generally: https://wpdirectory.net/search/01HX83JEWYSX880A2CN2W8G5GA

This was a big headache for the AMP plugin when we converted `img` to `amp-img`, as we had to rewrite all of the selectors mentioning `img` to use `amp-img`. It is possible, but only if you are processing all the CSS.

**Comment by westonruter** [comment]
As we chatted about today, it turns out explicitly targeting an `img` tag does not necessarily break CSS selectors when a `picture` element is used. If using a descendant selector like `figure img`, the styles will continue to apply to the `picture` element. Fortunately it seems Gutenberg almost exclusively uses the descendant selector. What _doesn't_ work is a child selector like `figure > img`. I put together a test page that demonstrates the behavior: https://codepen.io/westonruter/pen/ExzjQLZ

**Comment by Anuj-Rathore24** [comment]
@thelovekesh Hey Lovekesh I can pick this up!!

**Comment by westonruter** [comment]
@Anuj-Rathore24 I recommend waiting to work on this until after @adamsilverstein has finished work in #1176.

**Comment by adamsilverstein** [comment]
Hey @Anuj-Rathore24 - thanks for offering to work on this! We have added both AVIF and picture element support so this should be good to consider again.

One improvement I think we skipped when adding picture element is that the fallback script should only load when `picture` element support is disabled.

Thinking further - since we have picture element support now, I feel this fallback script is less useful now and maybe we should just consider deprecating/removing it - what do you think @westonruter? Is this still needed? when would it be useful?

Some comments if we do go ahead with updates here:

> Wouldn't it be better to rely on fetch() than to use JSONP?

Doesn't seem worth the effort to change this!

> Instead of exporting the URL in an HTML attribute, why not expose it via a global variable in the same inline script that is being printed to begin with?

That makes sense to me

>The query args for restPath would be better constructed with URLSearchParams, or if IE11 compat is really desired, fall back to using document.createElement('a').href.
we don't need ie11 support, but it does support picture element so 🤷🏼 just use that?

> Also, in that inline script it would be slightly safer if this line used wp_json_encode():

sure
 
> Lastly, instead of relying on data attributes on the script tag, the necessary data may make more sense to export into JS via wp_add_inline_script_tag() or else a JSON script. The reason is that the script tag for JS may end up getting concatenated with other scripts, resulting in those attributes getting lost.

+1 no idea why this was added as query args in te first place.

**Comment by westonruter** [comment]
@adamsilverstein I agree that the fallback script is obsolete now, given the support for the picture element, but also because WebP is in Baseline being [supported](https://caniuse.com/webp) by 96%+ of users' browsers, and AVIF being in 2024 Baseline being [supported](https://caniuse.com/avif) by 93%+ of users' browsers. I think we should go ahead and just remove it.

**Comment by adamsilverstein** [comment]
> I think we should go ahead and just remove it.

I will adjust this ticket make that its intent.

**Comment by adamsilverstein** [comment]
Hey @Anuj-Rathore24 - quick update - this Issue is now about removing the use of the fallback script from the plugin, do you want to work on that?

**Comment by Anuj-Rathore24** [comment]
Hey @adamsilverstein, I would love to work on this. Give me some time to go through everything!

**Comment by Anuj-Rathore24** [comment]
Hey @adamsilverstein @westonruter, I can remove the whole function for adding fallback script by removing this action called before checking if the mime type is equal or not. 

So Should I remove this foreach loop altogether.
https://github.com/WordPress/performance/blob/29361ec888f4fff924aedf6ba8201c1a17235ba9/plugins/webp-uploads/hooks.php#L672-L690

**Comment by Anuj-Rathore24** [comment]
Hey @adamsilverstein @westonruter, 


I should also remove heredoc string, right? because this is not being used anywhere!
https://github.com/WordPress/performance/blob/29361ec888f4fff924aedf6ba8201c1a17235ba9/plugins/webp-uploads/hooks.php#L736-L769

**Comment by westonruter** [comment]
@Anuj-Rathore24 that's correct!

**Comment by Anuj-Rathore24** [comment]
Hey @westonruter,

I think I made a mistake while analysing the code, can you please correct me if I am wrong.

What we want to achieve is to remove fallback.js script from our header which would be added using wp_print_inline_script_tag function. So what I could do is just remove one line, i.e. L-761, and its format specifier from line L-758 while keeping the rest of the function same as it is!

https://github.com/WordPress/performance/blob/29361ec888f4fff924aedf6ba8201c1a17235ba9/plugins/webp-uploads/hooks.php#L736-L769

I think so, We don't need to remove the heredoc string, as it was modified by Adam in the previous PR.

**Comment by westonruter** [comment]
@Anuj-Rathore24 I believe you can actually remove that entire [`webp_uploads_webp_fallback()` function](https://github.com/WordPress/performance/blob/29361ec888f4fff924aedf6ba8201c1a17235ba9/plugins/webp-uploads/hooks.php#L708-L769) as well as the [`fallback.js` file](https://github.com/WordPress/performance/blob/29361ec888f4fff924aedf6ba8201c1a17235ba9/plugins/webp-uploads/fallback.js).

**Comment by Anuj-Rathore24** [comment]
@westonruter, The function is attached to an action in foreach loop, if I am removing the function I should also remove the whole foreach loop.

https://github.com/WordPress/performance/blob/29361ec888f4fff924aedf6ba8201c1a17235ba9/plugins/webp-uploads/hooks.php#L672-L687

**Comment by westonruter** [comment]
@Anuj-Rathore24 good point, yes!
